export type PartnerFormError={field:string;message:string};
type VehicleInput={key:string;make?:unknown;model?:unknown;modelYear?:unknown;registrationNumber?:unknown;category?:unknown;uploadedKinds?:string[]};
type DriverInput={key:string;name?:unknown;mobile?:unknown;whatsapp?:unknown;zoneIds?:string[];cnicNumber?:unknown;licenceNumber?:unknown;licenceExpiryDate?:unknown;uploadedKinds?:string[]};
type Input={applicationType:"driver"|"ownerDriver"|"vendor";drivingSetup?:""|"self"|"vendor_driver";values:Record<string,unknown>;zoneIds:string[];uploadedKinds:string[];includeVehicle:boolean;vehicles?:VehicleInput[];drivers?:DriverInput[]};
const present=(value:unknown)=>typeof value==="string"?Boolean(value.trim()):value!==undefined&&value!==null;
export function collectPartnerFormErrors(input:Input){
 const errors:PartnerFormError[]=[],missing=(field:string,message:string,condition:boolean)=>{if(condition)errors.push({field,message})},drivingSetup=input.applicationType==="ownerDriver"?"self":input.applicationType==="vendor"?input.drivingSetup:undefined,driver=input.applicationType!=="vendor"||drivingSetup==="self";
 if(input.applicationType==="vendor")missing("businessName","Business / vendor name is required",!present(input.values.businessName));
 missing("name",input.applicationType==="vendor"?"Contact person is required":"Full name is required",!present(input.values.name));missing("mobile","Mobile number is required",!present(input.values.mobile));missing("whatsapp","WhatsApp number is required",!present(input.values.whatsapp));missing("zoneIds","Select at least one city / operational zone",input.zoneIds.length===0);
 if(driver){missing("cnic_front","CNIC front is required",!input.uploadedKinds.includes("cnic_front"));missing("cnic_back","CNIC back is required",!input.uploadedKinds.includes("cnic_back"));missing("cnicNumber","CNIC number is required",!present(input.values.cnicNumber));missing("licence_front","Driving Licence Front is required",!input.uploadedKinds.includes("licence_front"));missing("licence_back","Driving Licence Back is required",!input.uploadedKinds.includes("licence_back"));missing("licenceNumber","Driving licence number is required",!present(input.values.licenceNumber));missing("licenceExpiryDate","Licence expiry date is required",!present(input.values.licenceExpiryDate))}
  if(input.applicationType==="vendor"){
   missing("drivingSetup","Choose who will drive the vehicle",!drivingSetup);
  }
  if(input.applicationType==="vendor"){
   if(drivingSetup==="vendor_driver"){const drivers=input.drivers??[];if(input.drivers!==undefined)missing("drivers","Add at least one driver to RentKA",drivers.length===0);const seenPhones=new Map<string,number>();drivers.forEach((driver,index)=>{const prefix=`driver-${driver.key}-`,label=`Driver ${index+1}`;missing(prefix+"name",`${label} name is required`,!present(driver.name));missing(prefix+"mobile",`${label} mobile number is required`,!present(driver.mobile));missing(prefix+"whatsapp",`${label} WhatsApp number is required`,!present(driver.whatsapp));missing(prefix+"zoneIds",`${label} operational zone is required`,!driver.zoneIds?.length);missing(prefix+"cnicNumber",`${label} CNIC number is required`,!present(driver.cnicNumber));missing(prefix+"licenceNumber",`${label} licence number is required`,!present(driver.licenceNumber));missing(prefix+"licenceExpiryDate",`${label} licence expiry date is required`,!present(driver.licenceExpiryDate));for(const kind of ["cnic_front","cnic_back","licence_front","licence_back"])missing(prefix+kind,`${label} ${kind.replaceAll("_"," ")} is required`,!driver.uploadedKinds?.includes(kind));const normalized=String(driver.mobile??"").replace(/\D/g,"").replace(/^0/,"92");if(normalized){const prior=seenPhones.get(normalized);if(prior!==undefined)errors.push({field:prefix+"mobile",message:`Mobile number duplicates Driver ${prior+1}. Each driver must be unique.`});else seenPhones.set(normalized,index)}})}
   const vehicles=input.vehicles??[];missing("vehicles","Add at least one vehicle to RentKA",vehicles.length===0);const seen=new Map<string,number>();
  vehicles.forEach((vehicle,index)=>{const prefix=`vehicle-${vehicle.key}-`,label=`Vehicle ${index+1}`;missing(prefix+"make",`${label} make is required`,!present(vehicle.make));missing(prefix+"model",`${label} model is required`,!present(vehicle.model));missing(prefix+"modelYear",`${label} model year is required`,!present(vehicle.modelYear));missing(prefix+"registrationNumber",`${label} registration number is required`,!present(vehicle.registrationNumber));missing(prefix+"category",`${label} category is required`,!present(vehicle.category));missing(prefix+"vehicle_registration",`${label} registration document is required`,!vehicle.uploadedKinds?.includes("vehicle_registration"));missing(prefix+"vehicle_photo",`${label} photo is required`,!vehicle.uploadedKinds?.includes("vehicle_photo"));const normalized=String(vehicle.registrationNumber??"").replace(/[^a-zA-Z0-9]/g,"").toUpperCase();if(normalized){const prior=seen.get(normalized);if(prior!==undefined)errors.push({field:prefix+"registrationNumber",message:`Registration duplicates Vehicle ${prior+1}. Each vehicle must be unique.`});else seen.set(normalized,index)}});
 }else if(input.includeVehicle){missing("vehicleMake","Vehicle make is required",!present(input.values.vehicleMake));missing("vehicleModel","Vehicle model is required",!present(input.values.vehicleModel));missing("registrationNumber","Registration number is required",!present(input.values.registrationNumber));if(input.applicationType==="ownerDriver")missing("vehicle_registration","Registration Document is required",!input.uploadedKinds.includes("vehicle_registration"))}
 if(driver)missing("availability","Confirm that you are available for bookings after approval",input.values.availability!=="available_after_approval");missing("extractionReviewed","Confirm that you reviewed the document suggestions",input.values.extractionReviewed!==true);missing("consent","Consent is required before submission",input.values.consent!==true);return errors;
}
export const firstPartnerFormError=(errors:PartnerFormError[])=>errors[0];
