export type PartnerFormError={field:string;message:string};
type VehicleInput={key:string;make?:unknown;model?:unknown;modelYear?:unknown;registrationNumber?:unknown;category?:unknown;uploadedKinds?:string[]};
type Input={applicationType:"driver"|"ownerDriver"|"vendor";values:Record<string,unknown>;zoneIds:string[];uploadedKinds:string[];includeVehicle:boolean;vehicles?:VehicleInput[]};
const present=(value:unknown)=>typeof value==="string"?Boolean(value.trim()):value!==undefined&&value!==null;
export function collectPartnerFormErrors(input:Input){
 const errors:PartnerFormError[]=[],missing=(field:string,message:string,condition:boolean)=>{if(condition)errors.push({field,message})},driver=input.applicationType!=="vendor";
 if(input.applicationType==="vendor")missing("businessName","Business / vendor name is required",!present(input.values.businessName));
 missing("name",input.applicationType==="vendor"?"Contact person is required":"Full name is required",!present(input.values.name));missing("mobile","Mobile number is required",!present(input.values.mobile));missing("whatsapp","WhatsApp number is required",!present(input.values.whatsapp));missing("zoneIds","Select at least one city / operational zone",input.zoneIds.length===0);
 if(driver){missing("cnic_front","CNIC front is required",!input.uploadedKinds.includes("cnic_front"));missing("cnic_back","CNIC back is required",!input.uploadedKinds.includes("cnic_back"));missing("cnicNumber","CNIC number is required",!present(input.values.cnicNumber));missing("licence_front","Driving Licence Front is required",!input.uploadedKinds.includes("licence_front"));missing("licence_back","Driving Licence Back is required",!input.uploadedKinds.includes("licence_back"));missing("licenceNumber","Driving licence number is required",!present(input.values.licenceNumber));missing("licenceExpiryDate","Licence expiry date is required",!present(input.values.licenceExpiryDate))}
 if(input.applicationType==="vendor"){
  const vehicles=input.vehicles??[];missing("vehicles","Add at least one vehicle to RentKA",vehicles.length===0);const seen=new Map<string,number>();
  vehicles.forEach((vehicle,index)=>{const prefix=`vehicle-${vehicle.key}-`,label=`Vehicle ${index+1}`;missing(prefix+"make",`${label} make is required`,!present(vehicle.make));missing(prefix+"model",`${label} model is required`,!present(vehicle.model));missing(prefix+"modelYear",`${label} model year is required`,!present(vehicle.modelYear));missing(prefix+"registrationNumber",`${label} registration number is required`,!present(vehicle.registrationNumber));missing(prefix+"category",`${label} category is required`,!present(vehicle.category));missing(prefix+"vehicle_registration",`${label} registration document is required`,!vehicle.uploadedKinds?.includes("vehicle_registration"));missing(prefix+"vehicle_photo",`${label} photo is required`,!vehicle.uploadedKinds?.includes("vehicle_photo"));const normalized=String(vehicle.registrationNumber??"").replace(/[^a-zA-Z0-9]/g,"").toUpperCase();if(normalized){const prior=seen.get(normalized);if(prior!==undefined)errors.push({field:prefix+"registrationNumber",message:`Registration duplicates Vehicle ${prior+1}. Each vehicle must be unique.`});else seen.set(normalized,index)}});
 }else if(input.includeVehicle){missing("vehicleMake","Vehicle make is required",!present(input.values.vehicleMake));missing("vehicleModel","Vehicle model is required",!present(input.values.vehicleModel));missing("registrationNumber","Registration number is required",!present(input.values.registrationNumber));if(input.applicationType==="ownerDriver")missing("vehicle_registration","Registration Document is required",!input.uploadedKinds.includes("vehicle_registration"))}
 missing("extractionReviewed","Confirm that you reviewed the document suggestions",input.values.extractionReviewed!==true);missing("consent","Consent is required before submission",input.values.consent!==true);return errors;
}
export const firstPartnerFormError=(errors:PartnerFormError[])=>errors[0];
