import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  DUALHOOK_WHATSAPP_BASE_URL,
  WhatsAppProviderError,
  createDualhookWhatsAppOutboundProvider,
  dualhookMessagesUrl,
  dualhookTemplatePayload,
  dualhookTextPayload,
  requireDualhookOutboundConfig,
} from "../src/lib/messaging/dualhook-whatsapp-outbound-core.ts";

const config={apiKey:"test-key-never-log",phoneNumberId:"995770263630038"};

test("Dualhook configuration is server-only and reads the API key only from environment",()=>{const source=readFileSync(new URL("../src/lib/messaging/dualhook-whatsapp-config.ts",import.meta.url),"utf8"),wrapper=readFileSync(new URL("../src/lib/messaging/dualhook-whatsapp-outbound.ts",import.meta.url),"utf8");assert.match(source,/process\.env\.DUALHOOK_WHATSAPP_API_KEY/);assert.match(source,/process\.env\.META_WHATSAPP_PHONE_NUMBER_ID/);assert.match(source,/import "server-only"/);assert.match(wrapper,/getDualhookWhatsAppOutboundConfig/);assert.doesNotMatch(source,/dh_live_/)});
test("missing Dualhook API key fails without exposing credentials",()=>{assert.throws(()=>requireDualhookOutboundConfig({phoneNumberId:config.phoneNumberId}),error=>error instanceof WhatsAppProviderError&&error.code==="CONFIGURATION"&&!error.message.includes(config.apiKey))});
test("base URL and versioned Phone Number ID path are exact",()=>{assert.equal(DUALHOOK_WHATSAPP_BASE_URL,"https://api.dualhook.com");assert.equal(dualhookMessagesUrl(config.phoneNumberId),"https://api.dualhook.com/v25.0/995770263630038/messages")});
test("plain-text payload matches WhatsApp messages shape",()=>{assert.deepEqual(dualhookTextPayload({to:"recipient-test-id",body:"Test message"}),{messaging_product:"whatsapp",recipient_type:"individual",to:"recipient-test-id",type:"text",text:{preview_url:false,body:"Test message"}})});
test("template payload matches WhatsApp messages shape",()=>{assert.deepEqual(dualhookTemplatePayload({to:"recipient-test-id",name:"driver_offer",languageCode:"en",components:[{type:"body",parameters:[{type:"text",text:"RK-TEST"}]}]}),{messaging_product:"whatsapp",recipient_type:"individual",to:"recipient-test-id",type:"template",template:{name:"driver_offer",language:{code:"en"},components:[{type:"body",parameters:[{type:"text",text:"RK-TEST"}]}]}})});
test("provider sends Bearer authorization and accepts a valid 2xx response",async()=>{let request;const provider=createDualhookWhatsAppOutboundProvider(config,async(url,init)=>{request={url,init};return new Response(JSON.stringify({messages:[{id:"wamid.OUTBOUND"}]}),{status:200,headers:{"Content-Type":"application/json"}})}),result=await provider.sendText({to:"recipient-test-id",body:"Test message"});assert.equal(result.messageId,"wamid.OUTBOUND");assert.equal(request.url,dualhookMessagesUrl(config.phoneNumberId));assert.equal(request.init.method,"POST");assert.equal(request.init.headers.Authorization,`Bearer ${config.apiKey}`);assert.equal(request.init.headers["Content-Type"],"application/json")});
test("provider rejects non-2xx without exposing response or request data",async()=>{const provider=createDualhookWhatsAppOutboundProvider(config,async()=>new Response(JSON.stringify({error:{message:"sensitive provider detail"}}),{status:400}));await assert.rejects(provider.sendText({to:"recipient-test-id",body:"private body"}),error=>error instanceof WhatsAppProviderError&&error.status===400&&!error.message.includes(config.apiKey)&&!error.message.includes("recipient-test-id")&&!error.message.includes("private body")&&!error.message.includes("sensitive provider detail"))});
test("provider rejects malformed success responses without leaking secrets",async()=>{for(const response of [new Response("not-json",{status:200}),new Response(JSON.stringify({messages:[]}),{status:200,headers:{"Content-Type":"application/json"}})]){const provider=createDualhookWhatsAppOutboundProvider(config,async()=>response);await assert.rejects(provider.sendTemplate({to:"recipient-test-id",name:"driver_offer",languageCode:"en"}),error=>error instanceof WhatsAppProviderError&&error.code==="INVALID_RESPONSE"&&!JSON.stringify(error).includes(config.apiKey))}});
test("existing inbound routes and status handling remain unchanged",()=>{const dualhookRoute=readFileSync(new URL("../app/api/webhooks/dualhook/whatsapp/[secret]/route.ts",import.meta.url),"utf8"),metaRoute=readFileSync(new URL("../app/api/webhooks/meta/whatsapp/route.ts",import.meta.url),"utf8"),inbound=readFileSync(new URL("../src/lib/messaging/dualhook-whatsapp-webhook.ts",import.meta.url),"utf8");assert.match(dualhookRoute,/authorizedPath/);assert.doesNotMatch(dualhookRoute,/dualhook-whatsapp-outbound/);assert.match(metaRoute,/verifyMetaWebhookSignature/);assert.match(metaRoute,/x-hub-signature-256/);assert.match(inbound,/message_status/);for(const field of ["smb_message_echoes","smb_app_state_sync","history"])assert.ok(inbound.includes(field))});
test("outbound provider has no runtime logging and no production invocation",()=>{const core=readFileSync(new URL("../src/lib/messaging/dualhook-whatsapp-outbound-core.ts",import.meta.url),"utf8"),wrapper=readFileSync(new URL("../src/lib/messaging/dualhook-whatsapp-outbound.ts",import.meta.url),"utf8");assert.doesNotMatch(core,/console\.|dh_live_|raw payload|authorization header/i);assert.doesNotMatch(wrapper,/sendText\(|sendTemplate\(/)});
