import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createDriverInstructionsProjection } from "../src/lib/dispatch/driver-instructions-core.ts";

const actor={type:"shared_admin_session",label:"Shared Admin Session"};
const assignment=(patch={})=>({id:"assignment-a",status:"assigned",assignedDriverId:"driver-a",assignedVehicleId:"vehicle-a",vendorId:"vendor-test",driverSnapshot:{name:"TEST Driver A",mobileNumber:"03001111111",whatsappNumber:"03001111111",vendorId:"vendor-test"},vehicleSnapshot:{make:"Toyota",model:"Corolla",modelYear:2022,registrationNumber:"TEST-A",vendorId:"vendor-test"},approvedVendorPayoutMinor:550000,assignedAt:"now",assignedBy:actor,...patch});
const booking=(patch={})=>({id:"booking-d8",bookingId:"RK-TEST-D8",source:{type:"manual",collection:"manualBookings",documentId:"source-d8",key:"manual:source-d8"},sourceSnapshot:{durationHours:12},zoneId:"twin_cities",serviceType:"with_driver",customer:{name:"TEST Customer",phone:"03009999999",whatsapp:"03009999999"},itinerary:{travelDate:"2027-08-30",pickupTime:"11:00",pickup:"House 1, F-7, Islamabad",destinationOrUsage:"Blue Area, Islamabad",pickupLocation:{address:"House 1, F-7, Islamabad",mapLink:"https://maps.google.com/pickup"},destinationLocation:{address:"Blue Area, Islamabad",mapLink:"https://maps.google.com/destination"},notes:"Call RentKA on arrival."},requestedVehicle:{categoryOrModel:"Toyota Corolla"},customerFinancials:{customerTotalMinor:1000000,originalCustomerTotalMinor:1000000,customerDiscountTotalMinor:0,finalCustomerTotalMinor:1000000,requiredAdvanceMinor:200000,receivedAmountMinor:250000,balanceMinor:750000,refundCreditDueMinor:0,paymentStatus:"sufficient"},internalFinancials:{vendorPayoutMinor:550000,payoutStatus:"reviewed"},responsibilities:{fuel:"customer",toll:"rentka",parking:"included",driverFoodAccommodation:{mode:"allowance",amountMinor:200000},extraHour:{mode:"rate",amountMinor:150000}},lifecycle:"active",readinessStatus:"ready_for_dispatch",assignment:assignment(),createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch});

test("D8 is unavailable before a final assignment",()=>{const value=booking();delete value.assignment;assert.equal(createDriverInstructionsProjection(value),null)});
test("full private customer and operational details appear only after assignment",()=>{const value=booking(),projection=createDriverInstructionsProjection(value);assert.ok(projection);for(const expected of ["RK-TEST-D8","TEST Customer","03009999999","House 1, F-7, Islamabad","https://maps.google.com/pickup","Blue Area, Islamabad","https://maps.google.com/destination","30 Aug 2027","11:00 AM"])assert.match(projection.message,new RegExp(expected.replace(/[.*+?^$\\{}()|[\]\\]/g,"\\$&")))});
test("D8 targets only the finally assigned Driver",()=>{const projection=createDriverInstructionsProjection(booking());assert.equal(projection.driverId,"driver-a");assert.equal(projection.driverWhatsappNumber,"923001111111");assert.match(projection.whatsappUrl,/^https:\/\/wa\.me\/923001111111\?text=/)});
test("payout, collection amount and saved responsibility snapshot are rendered",()=>{const message=createDriverInstructionsProjection(booking()).message;for(const expected of ["Confirmed Driver/Vendor Payout: Rs. 5,500","Amount to Collect from Customer: Rs. 7,500","Fuel: Customer responsibility / not included","Toll: RentKA/vendor responsibility","Parking: Included","Driver Food / Accommodation: Rs. 2,000/day allowance","Extra-Hour Terms: Rs. 1,500/hour","Call RentKA on arrival."])assert.ok(message.includes(expected),expected)});
test("reassignment replaces both active Driver and physical Vehicle target",()=>{const current=assignment({id:"assignment-b",assignedDriverId:"driver-b",assignedVehicleId:"vehicle-b",previousAssignmentId:"assignment-a",driverSnapshot:{name:"TEST Driver B",mobileNumber:"03002222222",whatsappNumber:"03002222222",vendorId:"vendor-test"},vehicleSnapshot:{make:"Honda",model:"City",modelYear:2023,registrationNumber:"TEST-B",vendorId:"vendor-test"}}),projection=createDriverInstructionsProjection(booking({assignment:current}));assert.equal(projection.assignmentId,"assignment-b");assert.equal(projection.driverId,"driver-b");assert.equal(projection.vehicleId,"vehicle-b");assert.equal(projection.driverWhatsappNumber,"923002222222");assert.match(projection.message,/TEST Driver B/);assert.match(projection.message,/Honda City - 2023 - TEST-B/);assert.equal(projection.message.includes("TEST Driver A"),false);assert.equal(projection.message.includes("TEST-A"),false);assert.equal(projection.whatsappUrl.includes("923001111111"),false)});
test("cancelled or invalid assignments cannot behave like active assigned trips",()=>{assert.equal(createDriverInstructionsProjection(booking({lifecycle:"cancelled"})),null);assert.equal(createDriverInstructionsProjection(booking({assignment:assignment({status:"cancelled"})})),null)});
test("missing required data is warned about and never invented",()=>{const projection=createDriverInstructionsProjection(booking({customer:{name:"",phone:""},itinerary:{travelDate:"",pickupTime:"",pickup:"",destinationOrUsage:""},assignment:assignment({driverSnapshot:{name:"TEST Driver A",mobileNumber:"",whatsappNumber:"",vendorId:"vendor-test"}})}));assert.deepEqual(projection.missingFields,["customer name","customer phone","pickup address","destination / itinerary","travel date","pickup time","assigned driver WhatsApp"]);assert.equal(projection.whatsappUrl,undefined);assert.match(projection.message,/MISSING CUSTOMER NAME/)});
test("D7 assignment performs no automatic D8 message or customer notification",()=>{const files=["../src/lib/dispatch/assignment-core.ts","../src/lib/dispatch/assignment-repository.ts","../app/admin/dispatch/AssignmentPanel.tsx"].map(file=>readFileSync(new URL(file,import.meta.url),"utf8")).join("\n").toLowerCase();for(const forbidden of ["driver-instructions","driver_instructions","wa.me/","graph.facebook.com","customer notification"])assert.equal(files.includes(forbidden),false,forbidden)});
test("D8 actions are deliberate and audit open separately from confirmed sharing",()=>{const repository=readFileSync(new URL("../src/lib/dispatch/driver-instructions-repository.ts",import.meta.url),"utf8"),ui=readFileSync(new URL("../app/admin/dispatch/DriverInstructions.tsx",import.meta.url),"utf8");for(const marker of ["driver_instructions_copied","driver_instructions_whatsapp_opened","opened_not_confirmed_sent","driver_instructions_marked_shared","admin_confirmed_manual_share","Copy Instructions","Open WhatsApp","Mark Instructions Shared","not a delivery or read receipt"])assert.equal((repository+ui).includes(marker),true,marker);assert.equal(ui.includes("useEffect"),false)});
test("manual mutations revalidate the authoritative active assignment",()=>{const source=readFileSync(new URL("../src/lib/dispatch/driver-instructions-repository.ts",import.meta.url),"utf8");for(const marker of ["createDriverInstructionsProjection(booking)","projection.assignmentId!==assignmentId","The assignment changed","projection.driverId","projection.vehicleId"])assert.equal(source.includes(marker),true,marker)});
test("mark shared is idempotent and does not create a second shared audit",()=>{const source=readFileSync(new URL("../src/lib/dispatch/driver-instructions-repository.ts",import.meta.url),"utf8");assert.match(source,/action==="marked_shared"&&!existing\?\.sharedAt/)});
test("D8 uses manual wa.me composition and no WhatsApp API",()=>{const files=["../src/lib/dispatch/driver-instructions-core.ts","../src/lib/dispatch/driver-instructions-repository.ts","../app/admin/dispatch/DriverInstructions.tsx"].map(file=>readFileSync(new URL(file,import.meta.url),"utf8")).join("\n").toLowerCase();assert.ok(files.includes("https://wa.me/"));for(const forbidden of ["graph.facebook.com","whatsapp_business","messages endpoint","delivery receipt","read receipt received"])assert.equal(files.includes(forbidden),false,forbidden)});

