import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { candidateId, computeMatches, driverOfferSafeProjection, driverVehicleEligibility, matchingWindow, resolveVehicleCompatibility } from "../src/lib/dispatch/matching-core.ts";

const actor={type:"shared_admin_session"};
const booking=(patch={})=>({id:"booking-1",bookingId:"RK-TEST-D3",source:{type:"manual",collection:"manualBookings",documentId:"source-1",key:"manual:source-1"},sourceSnapshot:{},zoneId:"twin_cities",serviceType:"with_driver",customer:{name:"Private Customer",phone:"03000000000",email:"private@example.com"},itinerary:{travelDate:"2027-08-25",pickupTime:"09:00",pickup:"F-7",destinationOrUsage:"Blue Area",notes:"private note"},requestedVehicle:{categoryOrModel:"Toyota Corolla",passengers:3},customerFinancials:{customerTotalMinor:1000000,originalCustomerTotalMinor:1000000,customerDiscountTotalMinor:0,finalCustomerTotalMinor:1000000,requiredAdvanceMinor:200000,receivedAmountMinor:200000,balanceMinor:800000,refundCreditDueMinor:0,paymentStatus:"sufficient"},internalFinancials:{vendorPayoutMinor:800000,payoutStatus:"reviewed"},lifecycle:"active",readinessStatus:"ready_for_dispatch",createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch});
const vendor=(id="v1",patch={})=>({id,name:`Vendor ${id}`,primaryPhone:"1",primaryPhoneNormalized:"1",whatsappNumber:"1",whatsappNumberNormalized:"1",zoneIds:["twin_cities"],priority:"normal",active:true,createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch});
const vehicle=(id="car1",patch={})=>({id,vendorId:"v1",zoneIds:["twin_cities"],category:"Sedan",make:"Toyota",model:"Corolla",modelYear:2020,registrationNumber:`REG-${id}`,status:"available",active:true,documentation:{overallState:"verified",registrationState:"verified",tokenChallanState:"verified",permitState:"verified",fitnessState:"verified",insuranceState:"verified"},createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch});
const driver=(id="d1",patch={})=>({id,name:`Driver ${id}`,mobileNumber:"1",mobileNumberNormalized:"1",whatsappNumber:"1",whatsappNumberNormalized:"1",vendorId:"v1",zoneIds:["twin_cities"],priority:"normal",status:"available",active:true,documentation:{cnicVerificationState:"verified",licenceState:"verified"},createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch});
const run=(patch={})=>computeMatches({booking:booking(),vendors:[vendor()],vehicles:[vehicle()],drivers:[driver()],now:new Date("2027-01-01T00:00:00Z"),...patch});

test("non-Ready and cancelled bookings cannot match",()=>{for(const b of [booking({readinessStatus:"awaiting_advance"}),booking({lifecycle:"cancelled",readinessStatus:"cancelled"})]){const result=run({booking:b});assert.equal(result.ready,false);assert.equal(result.eligible.length,0)}});
test("Ready booking produces an eligible exact model combination",()=>{const result=run();assert.equal(result.ready,true);assert.equal(result.eligible.length,1);assert.equal(result.top[0].compatibility,"exact_model");assert.ok(result.top[0].reasons.includes("Exact requested model"))});
test("wrong-zone and inactive vendors are excluded",()=>{for(const v of [vendor("v1",{zoneIds:["lahore"]}),vendor("v1",{active:false})]){const result=run({vendors:[v]});assert.equal(result.eligible.length,0);assert.equal(result.excluded.some(x=>x.kind==="vendor"),true)}});
test("vehicle hard filters cover zone, active, unavailable and expired documentation",()=>{const cases=[vehicle("a",{zoneIds:["lahore"]}),vehicle("b",{active:false}),vehicle("c",{status:"unavailable"}),vehicle("d",{documentation:{...vehicle().documentation,overallState:"expired"}}),vehicle("e",{documentation:{...vehicle().documentation,insuranceExpiry:"2026-12-31"}})];for(const car of cases){const result=run({vehicles:[car]});assert.equal(result.eligible.length,0);assert.equal(result.excluded.some(x=>x.kind==="vehicle"),true)}});
test("vehicle compatibility centralizes exact model/category and excludes different classes",()=>{assert.equal(resolveVehicleCompatibility("Corolla",vehicle()).kind,"exact_model");assert.equal(resolveVehicleCompatibility("Sedan",vehicle()).kind,"exact_category");assert.equal(resolveVehicleCompatibility("Honda Civic",vehicle()).kind,"compatible_category");assert.equal(resolveVehicleCompatibility("Coaster",vehicle()).kind,"incompatible")});
test("driver hard filters cover zone, inactive, blocked, offline and expired licence",()=>{const cases=[driver("a",{zoneIds:["lahore"]}),driver("b",{active:false}),driver("c",{status:"blocked"}),driver("d",{status:"offline"}),driver("e",{documentation:{...driver().documentation,licenceExpiry:"2026-12-31"}})];for(const d of cases){const result=run({drivers:[d]});assert.equal(result.eligible.length,0);assert.equal(result.excluded.some(x=>x.kind==="driver"),true)}});
test("overlapping reservations exclude vehicle and driver without creating assignment state",()=>{const window=matchingWindow(booking());const reservations=[{id:"r1",bookingId:"other",vehicleId:"car1",startsAt:window.start,endsAt:window.end,active:true}];let result=run({reservations});assert.equal(result.eligible.length,0);assert.match(result.excluded.find(x=>x.kind==="vehicle").reason,/Time conflict/);result=run({reservations:[{...reservations[0],vehicleId:undefined,driverId:"d1"}]});assert.match(result.excluded.find(x=>x.kind==="driver").reason,/Time conflict/)});
test("preferred vendor and driver rank above equivalent normal resources",()=>{const vendors=[vendor("v1"),vendor("v2",{priority:"preferred"})],vehicles=[vehicle("c1"),vehicle("c2",{vendorId:"v2"})],drivers=[driver("d1"),driver("d2",{vendorId:"v2",priority:"preferred"})];const result=run({vendors,vehicles,drivers});assert.equal(result.top[0].vendor.id,"v2");assert.equal(result.top[0].driver.id,"d2")});
test("exact match outranks fallback and model-year benefit remains modest",()=>{const exact=vehicle("exact",{modelYear:2016}),fallback=vehicle("fallback",{model:"Civic",modelYear:2027}),result=run({vehicles:[fallback,exact]});assert.equal(result.top[0].vehicle.id,"exact");assert.ok(result.eligible.find(x=>x.vehicle.id==="fallback").score<result.top[0].score)});
test("ordering and Top 3 are deterministic for equal scores",()=>{const vehicles=[vehicle("c4"),vehicle("c2"),vehicle("c3"),vehicle("c1")],first=run({vehicles}),second=run({vehicles:[...vehicles].reverse()});assert.deepEqual(first.eligible.map(x=>x.id),second.eligible.map(x=>x.id));assert.equal(first.top.length,3);assert.deepEqual(first.top,first.eligible.slice(0,3))});
test("warning and unknown documentation are eligible but rank below verified with truthful reasons",()=>{const cars=[vehicle("verified"),vehicle("warning",{documentation:{...vehicle().documentation,overallState:"warning"}}),vehicle("unknown",{documentation:{...vehicle().documentation,overallState:"unknown"}})],result=run({vehicles:cars});assert.equal(result.eligible.length,3);assert.equal(result.top[0].vehicle.id,"verified");assert.ok(result.eligible.find(x=>x.vehicle.id==="warning").reasons.includes("Vehicle documentation warning"))});
test("Admin exclusion removes candidate and valid inclusion prioritizes it",()=>{const vehicles=[vehicle("a"),vehicle("b",{model:"Civic"})],base=run({vehicles}),target=base.eligible.find(x=>x.vehicle.id==="b"),excluded=run({vehicles,overrides:[{candidateId:target.id,mode:"exclude"}]});assert.equal(excluded.eligible.some(x=>x.id===target.id),false);const included=run({vehicles,overrides:[{candidateId:target.id,mode:"include"}]});assert.equal(included.top[0].id,target.id);assert.equal(included.top[0].manuallyIncluded,true)});
test("critical blocks cannot be bypassed by a forged candidate override",()=>{const id=candidateId("v1","car1","d1"),result=run({drivers:[driver("d1",{status:"blocked"})],overrides:[{candidateId:id,mode:"include"}]});assert.equal(result.eligible.length,0);assert.equal(result.excluded.some(x=>x.critical),true)});
test("match and future driver-offer projections omit private and financial data",()=>{const result=run(),projection=driverOfferSafeProjection(result.top[0],booking()),serialized=JSON.stringify(projection);for(const privateValue of ["Private Customer","03000000000","private@example.com","customerFinancials","internalFinancials","vendorPayoutMinor"])assert.equal(serialized.includes(privateValue),false);assert.equal(JSON.stringify(result).includes("Private Customer"),false)});
test("server integration authenticates mutations, uses normalized collections and creates only meaningful override audit",()=>{const actions=readFileSync(new URL("../app/admin/dispatch/actions.ts",import.meta.url),"utf8"),repository=readFileSync(new URL("../src/lib/dispatch/matching-repository.ts",import.meta.url),"utf8"),page=readFileSync(new URL("../app/admin/dispatch/page.tsx",import.meta.url),"utf8");assert.match(actions,/setMatchOverrideAction[\s\S]*mutateThenRedirect/);for(const marker of ["listDispatchVendors","listDispatchVehicles","listDispatchDrivers","getOperationalBooking","matchingOverrides","match_override_included","match_override_excluded"])assert.equal(repository.includes(marker),true,marker);for(const marker of ["Find Matches","Refresh matches","Recommended Top","Excluded / Not Eligible","no contact or assignment"])assert.equal((page+readFileSync(new URL("../app/admin/dispatch/MatchPanel.tsx",import.meta.url),"utf8")).includes(marker),true,marker)});
