import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { computeMatches, driverVehicleEligibility } from "../src/lib/dispatch/matching-core.ts";
import { parseDriverForm } from "../src/lib/dispatch/validation.ts";

const actor={type:"shared_admin_session"},docs={overallState:"verified",registrationState:"verified",tokenChallanState:"verified",permitState:"verified",fitnessState:"verified",insuranceState:"verified"};
const vendor=(id="v1")=>({id,name:id,primaryPhone:"1",primaryPhoneNormalized:"1",whatsappNumber:"1",whatsappNumberNormalized:"1",zoneIds:["twin_cities"],priority:"normal",active:true,createdAt:"x",updatedAt:"x",createdBy:actor,updatedBy:actor});
const car=(id,model,category="Sedan",vendorId="v1")=>({id,vendorId,zoneIds:["twin_cities"],category,make:model==="Alto"?"Suzuki":model==="Revo"?"Toyota":"Toyota",model,registrationNumber:`REG-${id}`,status:"available",active:true,documentation:docs,createdAt:"x",updatedAt:"x",createdBy:actor,updatedBy:actor});
const driver=(eligibility,vendorId="v1")=>({id:"d1",name:"Driver",mobileNumber:"1",mobileNumberNormalized:"1",whatsappNumber:"1",whatsappNumberNormalized:"1",vendorId,zoneIds:["twin_cities"],priority:"normal",status:"available",active:true,...(eligibility?{vehicleEligibility:eligibility}:{}),documentation:{cnicVerificationState:"verified",licenceState:"verified"},createdAt:"x",updatedAt:"x",createdBy:actor,updatedBy:actor});
const booking=request=>({id:"b1",bookingId:"RK-D3-ELIG",source:{type:"manual",collection:"manualBookings",documentId:"s",key:"manual:s"},sourceSnapshot:{},zoneId:"twin_cities",serviceType:"with_driver",customer:{name:"x",phone:"x"},itinerary:{travelDate:"2028-01-01",pickupTime:"09:00",pickup:"x"},requestedVehicle:{categoryOrModel:request},customerFinancials:{customerTotalMinor:1,originalCustomerTotalMinor:1,customerDiscountTotalMinor:0,finalCustomerTotalMinor:1,requiredAdvanceMinor:1,receivedAmountMinor:1,balanceMinor:0,refundCreditDueMinor:0,paymentStatus:"sufficient"},internalFinancials:{payoutStatus:"reviewed",vendorPayoutMinor:1},lifecycle:"active",readinessStatus:"ready_for_dispatch",createdAt:"x",updatedAt:"x",createdBy:actor,updatedBy:actor});
const match=(request,vehicles,d)=>computeMatches({booking:booking(request),vendors:[vendor()],vehicles,drivers:[d],now:new Date("2027-01-01")});

test("missing eligibility remains any vendor vehicle",()=>{assert.equal(driverVehicleEligibility(driver(),car("corolla","Corolla")).eligible,true);assert.equal(match("Corolla",[car("corolla","Corolla")],driver()).eligible.length,1)});
test("Corolla-only driver matches Corolla but not Revo",()=>{const d=driver({mode:"models_or_categories",allowedModelsOrCategories:["model:toyota corolla"]});assert.equal(match("Corolla",[car("corolla","Corolla")],d).eligible.length,1);const result=match("Revo",[car("revo","Revo","Pickup")],d);assert.equal(result.eligible.length,0);assert.match(result.excluded.find(x=>x.kind==="candidate").reason,/restricted to toyota corolla/i)});
test("Alto-only driver does not match Corolla",()=>{const d=driver({mode:"models_or_categories",allowedModelsOrCategories:["model:suzuki alto"]});assert.equal(match("Corolla",[car("corolla","Corolla")],d).eligible.length,0)});
test("specific vehicle restriction supports one or multiple same-vendor vehicles",()=>{const a=car("a","Corolla"),b=car("b","Corolla"),single=driver({mode:"specific_vehicles",vehicleIds:["a"]}),multiple=driver({mode:"specific_vehicles",vehicleIds:["a","b"]});assert.equal(driverVehicleEligibility(single,a).eligible,true);assert.equal(driverVehicleEligibility(single,b).eligible,false);assert.equal(match("Corolla",[a,b],single).eligible.length,1);assert.equal(match("Corolla",[a,b],multiple).eligible.length,2)});
test("multiple model/category restrictions work",()=>{const d=driver({mode:"models_or_categories",allowedModelsOrCategories:["model:suzuki alto","category:sedan"]});assert.equal(driverVehicleEligibility(d,car("alto","Alto","Hatchback")).eligible,true);assert.equal(driverVehicleEligibility(d,car("corolla","Corolla")).eligible,true);assert.equal(driverVehicleEligibility(d,car("revo","Revo","Pickup")).eligible,false)});
test("Revo request never produces Corolla fallback candidate",()=>{const result=match("Toyota Revo",[car("corolla","Corolla")],driver());assert.equal(result.eligible.length,0);assert.match(result.excluded[0].reason,/Different vehicle class/)});
test("eligible-driver scoring is unchanged by default eligibility",()=>{const unrestricted=match("Corolla",[car("corolla","Corolla")],driver()),explicit=match("Corolla",[car("corolla","Corolla")],driver({mode:"models_or_categories",allowedModelsOrCategories:["model:toyota corolla"]}));assert.equal(unrestricted.top[0].score,explicit.top[0].score)});
test("driver form parses optional modes and omits default eligibility",()=>{const base=new FormData();for(const[k,v]of Object.entries({name:"Driver",mobileNumber:"03020589999",whatsappNumber:"923020589999",vendorId:"v1",priority:"normal",status:"available",active:"on",cnicVerificationState:"verified",licenceState:"verified"}))base.set(k,v);base.append("zoneIds","twin_cities");assert.equal("vehicleEligibility" in parseDriverForm(base),false);base.set("vehicleEligibilityMode","specific_vehicles");base.append("eligibleVehicleIds","car-a");base.append("eligibleVehicleIds","car-b");assert.deepEqual(parseDriverForm(base).vehicleEligibility,{mode:"specific_vehicles",vehicleIds:["car-a","car-b"]})});
test("server rejects foreign vehicle IDs and UI clears stale selections on vendor change",()=>{const repository=readFileSync(new URL("../src/lib/dispatch/repository.ts",import.meta.url),"utf8"),ui=readFileSync(new URL("../app/admin/drivers/DriverVehicleEligibility.tsx",import.meta.url),"utf8");assert.match(repository,/doc\.data\(\)\?\.vendorId!==input\.vendorId/);assert.match(repository,/Every permitted vehicle must belong to the selected vendor/);assert.match(ui,/setVehicleIds\(\[\]\);setAllowed\(\[\]\)/);assert.match(ui,/vehicles\.filter\(vehicle=>vehicle\.vendorId===vendorId\)/)});
test("D4 remains protected by current D3 eligible candidate revalidation",()=>{const source=readFileSync(new URL("../src/lib/dispatch/offer-repository.ts",import.meta.url),"utf8");assert.match(source,/matches\.eligible\.find\(item=>item\.id===candidateId\)/);assert.match(source,/Candidate is no longer eligible/)});
