import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  aggregateBroadcastStatus,
  assertDriverOfferSendable,
  classifyProviderFailure,
  driverOfferTemplateComponents,
  invokeDriverOfferProvider,
} from "../src/lib/messaging/driver-offer-delivery-core.ts";
import { nextDeliveryStatus } from "../src/lib/messaging/whatsapp-delivery-core.ts";
import { requireDriverOfferDeliveryConfig } from "../src/lib/messaging/driver-offer-delivery-config-core.ts";
import { dualhookTemplatePayload } from "../src/lib/messaging/dualhook-whatsapp-outbound-core.ts";

const now = new Date("2026-09-01T00:00:00.000Z");
const booking = (patch = {}) => ({ id:"book", bookingId:"RK-T-1", lifecycle:"active", readinessStatus:"ready_for_dispatch", assignment:undefined, internalFinancials:{ payoutStatus:"reviewed", vendorPayoutMinor:700000 }, itinerary:{ pickup:"House 1, Blue Area, Islamabad", destinationOrUsage:"Office 2, F-8, Islamabad", travelDate:"2026-09-03", pickupTime:"10:00" }, requestedVehicle:{ categoryOrModel:"Sedan" }, sourceSnapshot:{ durationHours:8 }, serviceType:"within_city", ...patch });
const broadcast = (patch = {}) => ({ id:"b1", broadcastId:"b1", bookingOperationalId:"book", bookingId:"RK-T-1", revision:1, offerRevision:1, status:"approved", candidateIds:["c1"], offerIds:["o1"], driverIds:["d1"], approvedPayoutMinor:700000, offerExpiresAt:"2026-09-02T00:00:00.000Z", ...patch });
const offer = (patch = {}) => ({ id:"o1", bookingOperationalId:"book", bookingId:"RK-T-1", broadcastId:"b1", offerRevision:1, candidateId:"c1", driverId:"d1", vendorId:"v1", vehicleId:"car1", approvedPayoutMinor:700000, currentOfferedPayoutMinor:700000, offerExpiresAt:"2026-09-02T00:00:00.000Z", ...patch });
const job = (patch = {}) => ({ id:"j1", purpose:"driver_offer", bookingOperationalId:"book", bookingId:"RK-T-1", broadcastId:"b1", offerId:"o1", recipientType:"driver", recipientReferenceId:"d1", provider:"dualhook", messageKind:"template", status:"queued", attemptCount:0, idempotencyKey:"j1", createdAt:"2026-09-01", ...patch });
const sendable = (patch = {}) => ({ job:job(patch.job), booking:booking(patch.booking), broadcast:broadcast(patch.broadcast), offer:offer(patch.offer), activeBroadcastId:patch.activeBroadcastId ?? "b1", now });
const worker = readFileSync(new URL("../src/lib/messaging/driver-offer-delivery-repository.ts", import.meta.url), "utf8");
const ui = readFileSync(new URL("../app/admin/dispatch/SecureOfferControls.tsx", import.meta.url), "utf8");
const webhooks = ["../src/lib/messaging/meta-whatsapp-webhook-repository.ts", "../src/lib/messaging/dualhook-whatsapp-webhook-repository.ts"].map(path => readFileSync(new URL(path, import.meta.url), "utf8")).join("\n");

test("queued approved current Driver offer is sendable",()=>assert.doesNotThrow(()=>assertDriverOfferSendable(sendable())));
test("non-approved or non-current broadcast does not send",()=>{assert.throws(()=>assertDriverOfferSendable(sendable({broadcast:{status:"closed"}})));assert.throws(()=>assertDriverOfferSendable(sendable({activeBroadcastId:"b2"})))});
test("stale offer revision does not send",()=>assert.throws(()=>assertDriverOfferSendable(sendable({offer:{offerRevision:2}})),/stale/));
test("expired offer does not send",()=>assert.throws(()=>assertDriverOfferSendable(sendable({offer:{offerExpiresAt:"2026-08-01T00:00:00.000Z"}})),/expired/));
test("cancelled and assigned bookings do not send",()=>{assert.throws(()=>assertDriverOfferSendable(sendable({booking:{lifecycle:"cancelled"}})));assert.throws(()=>assertDriverOfferSendable(sendable({booking:{assignment:{status:"assigned"}}})))});
test("payout-stale offer does not send",()=>assert.throws(()=>assertDriverOfferSendable(sendable({booking:{internalFinancials:{payoutStatus:"reviewed",vendorPayoutMinor:800000}}})),/payout/));
test("only queued or retryable failed jobs can be claimed",()=>{assert.throws(()=>assertDriverOfferSendable(sendable({job:{status:"sending"}})));assert.doesNotThrow(()=>assertDriverOfferSendable(sendable({job:{status:"failed",failureRetryable:true}})));assert.throws(()=>assertDriverOfferSendable(sendable({job:{status:"outcome_unknown"}})))});
test("claim transaction prevents concurrent duplicate provider invocation",()=>{for(const marker of ['status: "sending"', 'currentJob.data()?.status !== "sending"', "invokeDriverOfferProvider", "invoked: false"])assert.ok(worker.includes(marker),marker);assert.equal((worker.match(/invokeDriverOfferProvider\(provider/g)||[]).length,1)});
test("claimed send invokes the selected provider exactly once",async()=>{let calls=0;const provider={sendText:async()=>{throw new Error("not used")},sendTemplate:async()=>{calls++;return{provider:"dualhook",messageId:"wamid.test"}}};const result=await invokeDriverOfferProvider(provider,{to:"923001111111",name:"rentka_driver_trip_offer_v1",languageCode:"en"});assert.equal(calls,1);assert.equal(result.status,"provider_accepted");assert.equal(result.providerMessageId,"wamid.test")});
test("provider acceptance stores message ID without marking delivered",()=>{for(const marker of ["providerMessageId", "providerAcceptedAt", 'status: "provider_accepted"'])assert.ok(worker.includes(marker),marker);assert.equal(worker.includes('status: "delivered"'),false)});
test("webhook sent delivered read and failed progress the same logical job",()=>{assert.equal(nextDeliveryStatus("provider_accepted","sent"),"sent");assert.equal(nextDeliveryStatus("sent","delivered"),"delivered");assert.equal(nextDeliveryStatus("delivered","read"),"read");assert.equal(nextDeliveryStatus("provider_accepted","failed"),"failed");assert.ok(webhooks.includes("reconcileWhatsAppDeliveryStatus"))});
test("duplicate and out-of-order webhooks are idempotent",()=>{assert.equal(nextDeliveryStatus("read","read"),"read");assert.equal(nextDeliveryStatus("delivered","sent"),"delivered");assert.equal(nextDeliveryStatus("read","failed"),"read")});
test("known retryable failures can retry and increment attempt count",()=>{assert.deepEqual(classifyProviderFailure({code:"REQUEST_FAILED",status:503}),{status:"failed",failureCode:"provider_retryable",retryable:true});assert.ok(worker.includes("job.attemptCount + 1"));assert.ok(ui.includes("Retry Automated Delivery"))});
test("ambiguous provider result becomes outcome_unknown and is not retried",()=>{assert.deepEqual(classifyProviderFailure({code:"INVALID_RESPONSE"}),{status:"outcome_unknown",failureCode:"provider_outcome_unknown",retryable:false});assert.ok(ui.includes("do not retry automatically"))});
test("partial broadcast failures are aggregated without resending success",()=>{assert.equal(aggregateBroadcastStatus(["delivered","provider_accepted","failed"]),"partially_failed");assert.equal(aggregateBroadcastStatus(["failed","cancelled"]),"failed");assert.equal(aggregateBroadcastStatus(["sent","delivered"]),"sent")});
test("driver response remains separate from delivery reconciliation",()=>{assert.equal(worker.includes("responseStatus:"),false);assert.equal(webhooks.includes("responseStatus"),false);assert.ok(ui.includes("Delivery:"))});
test("production template policy blocks missing or wrong template configuration",()=>{assert.throws(()=>requireDriverOfferDeliveryConfig({}));assert.throws(()=>requireDriverOfferDeliveryConfig({templateName:"wrong",templateLanguage:"en",publicBaseUrl:"https://www.rentka.co"}));assert.deepEqual(requireDriverOfferDeliveryConfig({templateName:"rentka_driver_trip_offer_v1",templateLanguage:"en",publicBaseUrl:"https://www.rentka.co/path"}),{templateName:"rentka_driver_trip_offer_v1",templateLanguage:"en",publicBaseUrl:"https://www.rentka.co"})});
test("approved template uses nine ordered body parameters and a separate URL-button suffix",()=>{const components=driverOfferTemplateComponents(booking(),offer(),"https://www.rentka.co/driver/offer/opaque-token");assert.equal(components.length,2);assert.equal(components[0].type,"body");assert.equal(components[0].parameters.length,9);assert.deepEqual(components[0].parameters.map(parameter=>parameter.text),["RK-T-1","Blue Area, Islamabad","F-8, Islamabad","2026-09-03","10:00","Sedan","within_city · 8 hours","PKR 7,000","2026-09-02T00:00:00.000Z"]);assert.deepEqual(components[1],{type:"button",sub_type:"url",index:"0",parameters:[{type:"text",text:"opaque-token"}]});assert.equal(JSON.stringify(components).includes("https://www.rentka.co/driver/offer/opaque-token"),false)});
test("template parameters preserve privacy and reject an invalid secure-offer path",()=>{const components=driverOfferTemplateComponents(booking(),offer(),"https://www.rentka.co/driver/offer/opaque-token");const serialized=JSON.stringify(components);for(const forbidden of ["customerPhone","House 1","Office 2","registration","customerFinancials"])assert.equal(serialized.includes(forbidden),false,forbidden);assert.throws(()=>driverOfferTemplateComponents(booking(),offer(),"https://www.rentka.co/not-an-offer/token"),/invalid/)});
test("Dualhook provider payload matches the approved template structure",()=>{const components=driverOfferTemplateComponents(booking(),offer(),"https://www.rentka.co/driver/offer/opaque-token");const payload=dualhookTemplatePayload({to:"923001111111",name:"rentka_driver_trip_offer_v1",languageCode:"en",components});assert.equal(payload.type,"template");assert.equal(payload.template.name,"rentka_driver_trip_offer_v1");assert.equal(payload.template.language.code,"en");assert.equal(payload.template.components[0].parameters.length,9);assert.deepEqual(payload.template.components[1],{type:"button",sub_type:"url",index:"0",parameters:[{type:"text",text:"opaque-token"}]})});
test("manual fallback remains and automated send requires confirmation",()=>{for(const marker of ["Open WhatsApp with Link","Manual WhatsApp only","window.confirm","Send Approved Offer"])assert.ok(ui.includes(marker),marker)});
test("worker audits sanitized lifecycle without logging private payloads",()=>{for(const marker of ["driver_offer_send_started","driver_offer_provider_accepted","driver_offer_delivery_failed","driver_offer_delivery_unknown","driver_offer_delivery_retry","driver_offer_send_prevented"])assert.ok(worker.includes(marker),marker);for(const forbidden of ["console.log","console.error","Authorization","apiKey"])assert.equal(worker.includes(forbidden),false,forbidden)});
