import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { applyOfferResponseState, createDriverOfferProjection, dispatchOfferId, generalArea } from "../src/lib/dispatch/offer-core.ts";

const actor={type:"shared_admin_session"};
const candidate={id:"candidate-1",vendor:{id:"vendor-1",name:"Test Vendor"},vehicle:{id:"vehicle-1",label:"Toyota Corolla 2020",registrationNumber:"TEST-101"},driver:{id:"driver-1",name:"Test Driver"},score:90,compatibility:"exact_model",reasons:[],manuallyIncluded:false};
const driver=(patch={})=>({id:"driver-1",name:"Test Driver",mobileNumber:"03000000000",mobileNumberNormalized:"923000000000",whatsappNumber:"03000000000",whatsappNumberNormalized:"923000000000",vendorId:"vendor-1",zoneIds:["twin_cities"],priority:"preferred",status:"available",active:true,documentation:{cnicVerificationState:"verified",licenceState:"verified"},createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch});
const booking=(patch={})=>({id:"booking-1",bookingId:"RK-TEST-D4",source:{type:"manual",collection:"manualBookings",documentId:"source-1",key:"manual:source-1"},sourceSnapshot:{},zoneId:"twin_cities",serviceType:"with_driver",customer:{name:"Secret Customer",phone:"03021111111",email:"secret@example.com"},itinerary:{travelDate:"2027-08-30",pickupTime:"11:00",pickup:"House 22, Street 4, Gulberg, Lahore, Pakistan",destinationOrUsage:"Private House, DHA, Lahore, Pakistan"},requestedVehicle:{categoryOrModel:"Toyota Corolla"},customerFinancials:{customerTotalMinor:1000000,originalCustomerTotalMinor:1100000,customerDiscountTotalMinor:100000,finalCustomerTotalMinor:1000000,requiredAdvanceMinor:200000,receivedAmountMinor:200000,balanceMinor:800000,refundCreditDueMinor:0,paymentStatus:"sufficient"},internalFinancials:{vendorPayoutMinor:400000,payoutStatus:"reviewed"},responsibilities:{fuel:"customer",toll:"rentka",parking:"included",driverFoodAccommodation:"unspecified",extraHourRateMinor:50000},lifecycle:"active",readinessStatus:"ready_for_dispatch",createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch});
const project=(b=booking(),d=driver())=>createDriverOfferProjection({booking:b,candidate,driver:d});

test("non-ready, cancelled and missing-payout bookings cannot generate offers",()=>{for(const b of [booking({readinessStatus:"awaiting_advance"}),booking({lifecycle:"cancelled",readinessStatus:"cancelled"}),booking({internalFinancials:{payoutStatus:"reviewed"}})])assert.throws(()=>project(b),/Ready for Dispatch/)});
test("ready booking projection contains only operational offer essentials",()=>{const p=project();assert.equal(p.bookingId,"RK-TEST-D4");assert.equal(p.vehicleRegistration,"TEST-101");assert.match(p.message,/30 Aug 2027/);assert.match(p.message,/11:00 AM/);assert.match(p.message,/Toyota Corolla/);assert.match(p.message,/Rs\. 4,000/)});
test("offer uses approved vendor payout and structured responsibilities without guessing",()=>{const message=project().message;for(const marker of ["Fuel: Customer","Toll: RentKA","Parking: Included","Food/Accommodation: As agreed / Confirm with RentKA","Extra hour: Rs. 500"])assert.match(message,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))});
test("general-area projection removes detailed address prefix and map data",()=>{assert.equal(generalArea("House 22, Street 4, Gulberg, Lahore, Pakistan"),"Gulberg, Lahore");const message=project().message;assert.equal(message.includes("House 22"),false);assert.equal(message.includes("Street 4"),false);assert.equal(message.includes("google.com/maps"),false)});
test("projection and message exclude customer identity and all customer financials",()=>{const serialized=JSON.stringify(project());for(const forbidden of ["Secret Customer","03021111111","secret@example.com","1,000,000","1,100,000","customerTotalMinor","originalCustomerTotalMinor","customerDiscountTotalMinor","finalCustomerTotalMinor","requiredAdvanceMinor","receivedAmountMinor","balanceMinor","refundCreditDueMinor","margin"])assert.equal(serialized.includes(forbidden),false,forbidden)});
test("WhatsApp URLs support normalized Pakistani and international driver numbers",()=>{const local=project(),international=project(booking(),driver({whatsappNumber:"+44 20 7946 0958",whatsappNumberNormalized:"442079460958"}));assert.match(local.whatsappUrl,/^https:\/\/wa\.me\/923000000000\?text=/);assert.match(international.whatsappUrl,/^https:\/\/wa\.me\/442079460958\?text=/);assert.equal(decodeURIComponent(local.whatsappUrl.split("?text=")[1]),local.message)});
test("invalid driver WhatsApp numbers are rejected",()=>assert.throws(()=>project(booking(),driver({whatsappNumber:"bad",whatsappNumberNormalized:""})),/invalid or missing/));
test("offer identity is stable and candidate-specific",()=>{assert.equal(dispatchOfferId("booking-1","candidate-1"),dispatchOfferId("booking-1","candidate-1"));assert.notEqual(dispatchOfferId("booking-1","candidate-1"),dispatchOfferId("booking-1","candidate-2"))});
test("Available, Declined and No Response transitions remain per-offer state",()=>{assert.deepEqual(applyOfferResponseState("available","now"),{responseStatus:"available",responseAt:"now"});assert.deepEqual(applyOfferResponseState("declined","later","correction"),{responseStatus:"declined",responseAt:"later",responseNote:"correction"});assert.equal(applyOfferResponseState("no_response","last").responseStatus,"no_response")});
test("repository uses deterministic offer document and audits corrections without creating assignment/global driver mutation",()=>{const source=readFileSync(new URL("../src/lib/dispatch/offer-repository.ts",import.meta.url),"utf8");for(const marker of ['collection(OFFERS).doc(projection.offerId)','driver_offer_prepared','driver_offer_whatsapp_opened','driver_offer_marked_sent','driver_offer_response_changed','from:previous?.responseStatus','to:mutation.response','assignment?.status===\"assigned\"'])assert.equal(source.includes(marker),true,marker);for(const forbidden of ["tx.create(assignment","assignedVehicle","driver.status","dispatchDrivers).doc"])assert.equal(source.includes(forbidden),false,forbidden)});
test("every D4 mutation revalidates readiness and current D3 candidate eligibility",()=>{const source=readFileSync(new URL("../src/lib/dispatch/offer-repository.ts",import.meta.url),"utf8"),actions=readFileSync(new URL("../app/admin/dispatch/actions.ts",import.meta.url),"utf8");for(const marker of ["findOperationalMatches","matches.eligible.find","ready_for_dispatch","payoutStatus!==\"reviewed\""])assert.equal(source.includes(marker),true,marker);assert.match(actions,/mutateDriverOfferAction[\s\S]*await auth\(\)/)});
test("Copy/Open UI preserves exact preview and requires manual send confirmation",()=>{const source=readFileSync(new URL("../app/admin/dispatch/OfferControls.tsx",import.meta.url),"utf8");for(const marker of ["navigator.clipboard.writeText(projection.message)","result.whatsappUrl","Mark Offer Sent","Mark Available","Mark Declined","No Response","booking is not assigned yet"])assert.equal(source.includes(marker),true,marker);assert.equal(source.includes("fetch(\"https://graph.facebook.com"),false)});
test("D4 creates no WhatsApp API, webhook, broadcast or assignment implementation",()=>{const files=["../src/lib/dispatch/offer-core.ts","../src/lib/dispatch/offer-repository.ts","../app/admin/dispatch/OfferControls.tsx"].map(file=>readFileSync(new URL(file,import.meta.url),"utf8")).join("\n").toLowerCase();for(const forbidden of ["graph.facebook.com","access_token","webhook","broadcast","assign driver","assignmentstatus"])assert.equal(files.includes(forbidden),false,forbidden)});
