import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { parseBookingResponsibilities, responsibilityDefaults } from "../src/lib/dispatch/booking-responsibilities.ts";
import { createDriverOfferProjection } from "../src/lib/dispatch/offer-core.ts";

const form=values=>{const result=new FormData();for(const[key,value]of Object.entries(values))result.set(key,String(value));return result};
const actor={type:"shared_admin_session"},candidate={id:"c1",vendor:{id:"v1",name:"Vendor"},vehicle:{id:"car1",label:"Toyota Corolla",registrationNumber:"TEST-1"},driver:{id:"d1",name:"Driver"},score:1,compatibility:"exact_model",reasons:[],manuallyIncluded:false},driver={id:"d1",name:"Driver",mobileNumber:"1",mobileNumberNormalized:"923000000000",whatsappNumber:"923000000000",whatsappNumberNormalized:"923000000000",vendorId:"v1",zoneIds:["twin_cities"],priority:"normal",status:"available",active:true,documentation:{cnicVerificationState:"verified",licenceState:"verified"},createdAt:"x",updatedAt:"x",createdBy:actor,updatedBy:actor};
const booking=(serviceType,responsibilities)=>({id:"b1",bookingId:"RK-D41",source:{type:"manual",collection:"manualBookings",documentId:"s",key:"manual:s"},sourceSnapshot:{},zoneId:"twin_cities",serviceType,customer:{name:"Private",phone:"03000000000",email:"private@example.com"},itinerary:{travelDate:"2028-01-01",pickupTime:"09:00",pickup:"F-7, Islamabad",destinationOrUsage:"Blue Area, Islamabad"},requestedVehicle:{categoryOrModel:"Corolla"},customerFinancials:{customerTotalMinor:1000000,originalCustomerTotalMinor:1000000,customerDiscountTotalMinor:0,finalCustomerTotalMinor:1000000,requiredAdvanceMinor:200000,receivedAmountMinor:200000,balanceMinor:800000,refundCreditDueMinor:0,paymentStatus:"sufficient"},internalFinancials:{payoutStatus:"reviewed",vendorPayoutMinor:800000},responsibilities,lifecycle:"active",readinessStatus:"ready_for_dispatch",createdAt:"x",updatedAt:"x",createdBy:actor,updatedBy:actor});

test("within-city Bachat defaults fuel, toll, parking and food to customer",()=>assert.deepEqual(responsibilityDefaults("with_driver"),{fuel:"customer",toll:"customer",parking:"customer",driverFoodAccommodation:{mode:"customer"},extraHour:{mode:"unspecified"}}));
test("outstation Bachat defaults fuel, toll, parking and TA/DA to customer",()=>assert.deepEqual(responsibilityDefaults("outstation"),{fuel:"customer",toll:"customer",parking:"customer",driverFoodAccommodation:{mode:"customer"},extraHour:{mode:"unspecified"}}));
test("unrelated services remain unknown rather than inheriting Bachat rules",()=>assert.equal(responsibilityDefaults("airport_transfer").fuel,"unspecified"));
test("blank new-booking form data uses the same customer-paid defaults for within-city and outstation",()=>{for(const service of ["with_driver","outstation"])assert.deepEqual(parseBookingResponsibilities(new FormData(),service),{fuel:"customer",toll:"customer",parking:"customer",driverFoodAccommodation:{mode:"customer"},extraHour:{mode:"unspecified"}})});
test("within-city Rs 1,000/day and outstation Rs 2,000/day allowances persist",()=>{assert.deepEqual(parseBookingResponsibilities(form({driverFoodMode:"allowance",driverFoodAmount:"1000"}),"with_driver").driverFoodAccommodation,{mode:"allowance",amountMinor:100000,unit:"per_day"});assert.deepEqual(parseBookingResponsibilities(form({driverFoodMode:"allowance",driverFoodAmount:"2000"}),"outstation").driverFoodAccommodation,{mode:"allowance",amountMinor:200000,unit:"per_day"})});
test("custom responsibility and explicit fuel override beat defaults",()=>{const value=parseBookingResponsibilities(form({fuel:"included",driverFoodMode:"custom",driverFoodAmount:"1500",driverFoodNote:"Vendor arranges lodging"}),"outstation");assert.equal(value.fuel,"included");assert.deepEqual(value.driverFoodAccommodation,{mode:"custom",amountMinor:150000,unit:"per_day",note:"Vendor arranges lodging"})});
test("new-booking UI keeps Rs 1,000 and Rs 2,000 allowances opt-in",()=>{const source=readFileSync(new URL("../app/admin/dispatch/OperationalResponsibilities.tsx",import.meta.url),"utf8");assert.equal(source.includes('service==="outstation"?"2000":"1000"'),true);assert.equal(source.includes('<option value="allowance">'),true);assert.equal(source.includes('if(value==="allowance")setFoodAmount(allowance)'),true);assert.equal(source.includes('initialFood?.amountMinor!==undefined?String(initialFood.amountMinor/100):""'),true)});
test("explicit extra-hour rate is structured and appears in D4 offer",()=>{const responsibilities=parseBookingResponsibilities(form({driverFoodMode:"customer",extraHourRate:"500"}),"with_driver"),message=createDriverOfferProjection({booking:booking("with_driver",responsibilities),candidate,driver}).message;assert.match(message,/Extra hour: Rs\. 500\/hour/)});
test("D4 offer renders within-city and outstation allowances clearly",()=>{const city=parseBookingResponsibilities(form({driverFoodMode:"allowance",driverFoodAmount:"1000"}),"with_driver"),out=parseBookingResponsibilities(form({driverFoodMode:"allowance",driverFoodAmount:"2000"}),"outstation");assert.match(createDriverOfferProjection({booking:booking("with_driver",city),candidate,driver}).message,/Driver Food\/Accommodation: Rs\. 1,000\/day allowance/);assert.match(createDriverOfferProjection({booking:booking("outstation",out),candidate,driver}).message,/Driver TA\/DA: Rs\. 2,000\/day allowance/)});
test("unknown legacy responsibilities retain safe fallback",()=>{const message=createDriverOfferProjection({booking:booking("with_driver",{fuel:"unspecified",toll:"unspecified",parking:"unspecified",driverFoodAccommodation:"unspecified"}),candidate,driver}).message;assert.match(message,/Fuel: As agreed \/ Confirm with RentKA/);assert.match(message,/Extra hour: Confirm with RentKA/)});
test("responsibility persistence does not update financial, payout, readiness or D3 fields",()=>{const source=readFileSync(new URL("../src/lib/dispatch/booking-repository.ts",import.meta.url),"utf8"),operation=source.slice(source.indexOf("export async function updateOperationalResponsibilities"));assert.match(operation,/responsibilities:firestoreSafePayload/);for(const forbidden of ["customerFinancials","internalFinancials","vendorPayoutMinor","readinessStatus","paymentStatus","matching","vehicleEligibility"])assert.equal(operation.includes(forbidden),false,forbidden)});
test("D4.1 projection remains privacy safe",()=>{const message=JSON.stringify(createDriverOfferProjection({booking:booking("with_driver",responsibilityDefaults("with_driver")),candidate,driver}));for(const privateValue of ["Private","03000000000","private@example.com","customerFinancials","customerTotalMinor","requiredAdvanceMinor","balanceMinor","margin"])assert.equal(message.includes(privateValue),false,privateValue)});
