import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createCustomerDriverDetailsProjection, resolveCustomerDriverDetailsState, resolveScheduleAt } from "../src/lib/dispatch/customer-driver-details-core.ts";

const actor={type:"shared_admin_session",label:"Shared Admin Session"};
const assignment=(patch={})=>({id:"assignment-a",status:"assigned",assignedDriverId:"driver-a",assignedVehicleId:"vehicle-a",dispatchVendorId:"vendor-secret",vendorName:"Internal Vendor",driverSnapshot:{name:"TEST Driver A",mobileNumber:"03001111111",whatsappNumber:"03001111111",vendorId:"vendor-secret"},vehicleSnapshot:{make:"Toyota",model:"Corolla",modelYear:2022,registrationNumber:"TEST-A",vendorId:"vendor-secret"},approvedVendorPayoutMinor:550000,offerId:"offer-secret",offerCandidateId:"candidate-secret",assignedAt:"now",assignedBy:actor,window:{start:"2027-08-30T06:00:00Z",end:"2027-08-30T18:00:00Z",basis:"test"},...patch});
const booking=(patch={})=>({id:"booking-d9",bookingId:"RK-TEST-D9",source:{type:"manual",collection:"manualBookings",documentId:"source-d9",key:"manual:source-d9"},sourceSnapshot:{durationHours:12},zoneId:"twin_cities",serviceType:"with_driver",customer:{name:"TEST Customer",phone:"03009999999"},itinerary:{travelDate:"2027-08-30",pickupTime:"11:00",pickup:"Private pickup",destinationOrUsage:"Private destination",notes:"Internal dispatch note"},requestedVehicle:{categoryOrModel:"Toyota Corolla"},customerFinancials:{customerTotalMinor:1000000,originalCustomerTotalMinor:1000000,customerDiscountTotalMinor:0,finalCustomerTotalMinor:1000000,requiredAdvanceMinor:200000,receivedAmountMinor:250000,balanceMinor:750000,refundCreditDueMinor:0,paymentStatus:"sufficient"},internalFinancials:{vendorPayoutMinor:550000,payoutStatus:"reviewed",payoutNotes:"SECRET MARGIN NOTE"},responsibilities:{fuel:"customer"},lifecycle:"active",readinessStatus:"ready_for_dispatch",assignment:assignment(),createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch});
const record=(patch={})=>({id:"assignment-a",bookingOperationalId:"booking-d9",bookingId:"RK-TEST-D9",assignmentId:"assignment-a",driverId:"driver-a",vehicleId:"vehicle-a",createdAt:"2027-08-01T00:00:00.000Z",updatedAt:"2027-08-01T00:00:00.000Z",createdBy:actor,updatedBy:actor,...patch});

test("D9 is unavailable before a final assignment",()=>{const value=booking();delete value.assignment;assert.equal(createCustomerDriverDetailsProjection(value),null)});
test("customer message contains only current public Driver, Vehicle and pickup fields",()=>{const projection=createCustomerDriverDetailsProjection(booking());for(const value of ["RK-TEST-D9","TEST Driver A","03001111111","Toyota Corolla 2022 - TEST-A","30 Aug 2027","11:00 AM","0302 058 9999"])assert.ok(projection.message.includes(value),value);for(const forbidden of ["Internal Vendor","550000","5,500","SECRET MARGIN NOTE","offer-secret","candidate-secret","Private pickup","Private destination","Internal dispatch note"])assert.equal(projection.message.includes(forbidden),false,forbidden)});
test("WhatsApp targets the customer and no one else",()=>{const projection=createCustomerDriverDetailsProjection(booking());assert.equal(projection.customerWhatsappNumber,"923009999999");assert.match(projection.whatsappUrl,/^https:\/\/wa\.me\/923009999999\?text=/);assert.equal(projection.whatsappUrl.startsWith("https://wa.me/923001111111"),false)});
test("schedule presets are calculated before Pakistan pickup time",()=>{assert.equal(resolveScheduleAt(booking(),"1",undefined),"2027-08-30T05:00:00.000Z");assert.equal(resolveScheduleAt(booking(),"3",undefined),"2027-08-30T03:00:00.000Z");assert.equal(resolveScheduleAt(booking(),"custom","2027-08-30T09:30"),"2027-08-30T04:30:00.000Z");assert.throws(()=>resolveScheduleAt(booking(),"custom","2027-02-31T09:30"),/valid custom/);assert.throws(()=>resolveScheduleAt(booking(),"custom","2027-08-30T12:00"),/after pickup/)});
test("scheduled, due and overdue operational reminder states never imply Sent",()=>{const scheduled=record({scheduledAt:"2027-08-30T05:00:00.000Z"});assert.equal(resolveCustomerDriverDetailsState(scheduled,false,new Date("2027-08-30T04:00:00Z")),"scheduled");assert.equal(resolveCustomerDriverDetailsState(scheduled,false,new Date("2027-08-30T05:05:00Z")),"ready_to_share");assert.equal(resolveCustomerDriverDetailsState(scheduled,false,new Date("2027-08-30T06:00:00Z")),"overdue")});
test("reassignment before sharing updates preview without an update-required flag",()=>{const current=assignment({id:"assignment-b",assignedDriverId:"driver-b",assignedVehicleId:"vehicle-b",previousAssignmentId:"assignment-a",driverSnapshot:{name:"TEST Driver B",mobileNumber:"03002222222",whatsappNumber:"03002222222",vendorId:"vendor-secret"},vehicleSnapshot:{make:"Honda",model:"City",modelYear:2024,registrationNumber:"TEST-B",vendorId:"vendor-secret"}}),projection=createCustomerDriverDetailsProjection(booking({assignment:current}),[record({scheduledAt:"2027-08-30T05:00:00.000Z"})]);assert.equal(projection.driverId,"driver-b");assert.equal(projection.vehicleId,"vehicle-b");assert.match(projection.message,/TEST Driver B/);assert.match(projection.message,/Honda City 2024 - TEST-B/);assert.equal(projection.updatedDetailsRequired,false);assert.equal(projection.message.includes("TEST Driver A"),false)});
test("reassignment after sharing flags updated details required",()=>{const current=assignment({id:"assignment-b",assignedDriverId:"driver-b",assignedVehicleId:"vehicle-b",previousAssignmentId:"assignment-a",driverSnapshot:{name:"TEST Driver B",mobileNumber:"03002222222",whatsappNumber:"03002222222",vendorId:"vendor-secret"},vehicleSnapshot:{make:"Honda",model:"City",registrationNumber:"TEST-B",vendorId:"vendor-secret"}}),projection=createCustomerDriverDetailsProjection(booking({assignment:current}),[record({sharedAt:"2027-08-29T00:00:00.000Z"})]);assert.equal(projection.updatedDetailsRequired,true);assert.equal(projection.previousSharedAssignmentId,"assignment-a");assert.equal(projection.state,"updated_details_required")});
test("cancelled bookings block new D9 sharing and scheduling projections",()=>{assert.equal(createCustomerDriverDetailsProjection(booking({lifecycle:"cancelled"})),null);assert.equal(createCustomerDriverDetailsProjection(booking({assignment:assignment({status:"cancelled"})})),null)});
test("manual share, scheduling changes, cancellation and update-required are distinctly audited",()=>{const source=readFileSync(new URL("../src/lib/dispatch/customer-driver-details-repository.ts",import.meta.url),"utf8");for(const marker of ["customer_driver_details_copied","customer_driver_details_whatsapp_opened","opened_not_confirmed_sent","customer_driver_details_marked_shared","admin_confirmed_manual_share","customer_driver_details_scheduled","customer_driver_details_schedule_changed","customer_driver_details_schedule_cancelled","customer_driver_details_update_required","manual_reminder_only"])assert.ok(source.includes(marker),marker)});
test("manual sharing and unchanged scheduling are idempotent",()=>{const source=readFileSync(new URL("../src/lib/dispatch/customer-driver-details-repository.ts",import.meta.url),"utf8");assert.match(source,/mutation\.action==="marked_shared"&&!existing\?\.sharedAt/);assert.match(source,/const scheduledAt=.*unchanged=.*iso\(existing\.scheduledAt\)===scheduledAt/);assert.match(source,/if\(!unchanged\)/)});
test("assignment never automatically starts D9 or sends customer communication",()=>{const files=["../src/lib/dispatch/assignment-core.ts","../src/lib/dispatch/assignment-repository.ts","../app/admin/dispatch/AssignmentPanel.tsx"].map(file=>readFileSync(new URL(file,import.meta.url),"utf8")).join("\n").toLowerCase();for(const forbidden of ["customer-driver-details","customer_driver_details","customerdrivernotifications","wa.me/","graph.facebook.com"])assert.equal(files.includes(forbidden),false,forbidden)});
test("D9 UI exposes deliberate manual controls and no automatic effect",()=>{const ui=readFileSync(new URL("../app/admin/dispatch/CustomerDriverDetails.tsx",import.meta.url),"utf8");for(const marker of ["Share Now","Schedule for Later","1 hour before pickup","2 hours before pickup","3 hours before pickup","Custom date/time","Copy Message","Open WhatsApp","not a delivery or read receipt","window.confirm"])assert.ok(ui.includes(marker),marker);assert.equal(ui.includes("useEffect"),false)});
test("D8 remains separate and unaffected by D9",()=>{const core=readFileSync(new URL("../src/lib/dispatch/driver-instructions-core.ts",import.meta.url),"utf8"),repository=readFileSync(new URL("../src/lib/dispatch/driver-instructions-repository.ts",import.meta.url),"utf8");assert.equal((core+repository).includes("customerDriverNotifications"),false);assert.equal((core+repository).includes("customer_driver_details"),false)});
test("no WhatsApp API, customer auto-send, D10 or D11 implementation exists in D9",()=>{const files=["../src/lib/dispatch/customer-driver-details-core.ts","../src/lib/dispatch/customer-driver-details-repository.ts","../app/admin/dispatch/CustomerDriverDetails.tsx"].map(file=>readFileSync(new URL(file,import.meta.url),"utf8")).join("\n").toLowerCase();assert.ok(files.includes("https://wa.me/"));for(const forbidden of ["graph.facebook.com","whatsapp_business","sendmessage","delivery receipt received","en route","onboard","trip completed"])assert.equal(files.includes(forbidden),false,forbidden)});

