import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { assertTripAllowsReassignment, createDriverTripProjection, createTripOperationsProjection, nextTripStatus, validateTripTransition } from "../src/lib/dispatch/trip-operations-core.ts";

const actor={type:"shared_admin_session"};
const assignment=(patch={})=>({id:"assignment-a",status:"assigned",bookingOperationalId:"booking-d10",bookingId:"RK-TEST-D10",dispatchVendorId:"vendor-secret",vendorName:"Internal Vendor",assignedDriverId:"driver-a",driverSnapshot:{id:"driver-a",name:"TEST Driver",mobileNumber:"03001111111",whatsappNumber:"03001111111",vendorId:"vendor-secret",priority:"normal",zoneIds:["twin_cities"]},assignedVehicleId:"vehicle-a",vehicleSnapshot:{id:"vehicle-a",vendorId:"vendor-secret",zoneIds:["twin_cities"],category:"Sedan",make:"Toyota",model:"Corolla",modelYear:2022,registrationNumber:"TEST-A",documentationState:"verified"},approvedVendorPayoutMinor:550000,offerId:"offer-secret",offerCandidateId:"candidate-secret",assignedAt:"now",assignedBy:actor,window:{start:"2027-08-30T06:00:00Z",end:"2027-08-30T18:00:00Z",basis:"test"},...patch});
const booking=(patch={})=>({id:"booking-d10",bookingId:"RK-TEST-D10",source:{type:"manual",collection:"manualBookings",documentId:"source-d10",key:"manual:source-d10"},sourceSnapshot:{durationHours:12},zoneId:"twin_cities",serviceType:"with_driver",customer:{name:"TEST Customer",phone:"03009999999"},itinerary:{travelDate:"2027-08-30",pickupTime:"11:00",pickup:"House 1, F-7, Islamabad",destinationOrUsage:"Blue Area",pickupLocation:{mapLink:"https://maps.google.com/pickup"},destinationLocation:{mapLink:"https://maps.google.com/destination"},notes:"ADMIN SECRET"},requestedVehicle:{categoryOrModel:"Toyota Corolla"},customerFinancials:{customerTotalMinor:1000000,requiredAdvanceMinor:200000,receivedAmountMinor:200000,balanceMinor:800000,paymentStatus:"sufficient"},internalFinancials:{vendorPayoutMinor:550000,payoutStatus:"reviewed",payoutNotes:"SECRET MARGIN"},responsibilities:{fuel:"customer",toll:"customer",parking:"customer",driverFoodAccommodation:{mode:"customer"}},lifecycle:"active",readinessStatus:"ready_for_dispatch",assignment:assignment(),createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch});
const operation=(status="assigned")=>({id:"assignment-a",bookingOperationalId:"booking-d10",bookingId:"RK-TEST-D10",assignmentId:"assignment-a",assignedDriverId:"driver-a",assignedVehicleId:"vehicle-a",driverSnapshot:assignment().driverSnapshot,vehicleSnapshot:assignment().vehicleSnapshot,currentStatus:status,statusTimestamps:{assigned:"now"},createdAt:"now",updatedAt:"now"});

test("normal D10 state progression is exact",()=>{assert.equal(nextTripStatus("assigned"),"en_route");assert.equal(nextTripStatus("en_route"),"arrived");assert.equal(nextTripStatus("arrived"),"customer_onboard");assert.equal(nextTripStatus("customer_onboard"),"completed");assert.equal(nextTripStatus("completed"),undefined)});
test("each valid transition is accepted",()=>{for(const[from,to]of [["assigned","en_route"],["en_route","arrived"],["arrived","customer_onboard"],["customer_onboard","completed"]])assert.equal(validateTripTransition(from,to).duplicate,false)});
test("invalid skips and completed regression are blocked",()=>{assert.throws(()=>validateTripTransition("assigned","arrived"),/Invalid trip transition/);assert.throws(()=>validateTripTransition("en_route","customer_onboard"),/Invalid trip transition/);assert.throws(()=>validateTripTransition("completed","arrived"),/Invalid trip transition/)});
test("repeated identical transition is idempotent",()=>assert.equal(validateTripTransition("en_route","en_route").duplicate,true));
test("Admin and Driver projection uses authoritative assignment and physical Vehicle",()=>{const projection=createTripOperationsProjection(booking(),operation("arrived"));assert.equal(projection.assignmentId,"assignment-a");assert.equal(projection.driverId,"driver-a");assert.equal(projection.vehicleId,"vehicle-a");assert.equal(projection.vehicleLabel,"Toyota Corolla 2022 - TEST-A");assert.equal(projection.nextStatus,"customer_onboard")});
test("secure Driver projection contains operational data but no internal financials",()=>{const projection=createDriverTripProjection(booking(),operation("assigned"));for(const expected of ["TEST Customer","03009999999","House 1, F-7, Islamabad","Blue Area","https://maps.google.com/pickup","Toyota Corolla 2022 - TEST-A","Fuel: Customer responsibility / not included"])assert.ok(JSON.stringify(projection).includes(expected),expected);for(const forbidden of ["Internal Vendor","550000","SECRET MARGIN","offer-secret","candidate-secret","ADMIN SECRET"])assert.equal(JSON.stringify(projection).includes(forbidden),false,forbidden)});
test("reassignment is allowed before activity and blocked after start",()=>{assert.doesNotThrow(()=>assertTripAllowsReassignment(undefined));assert.doesNotThrow(()=>assertTripAllowsReassignment("assigned"));for(const status of ["en_route","arrived","customer_onboard","completed"])assert.throws(()=>assertTripAllowsReassignment(status),/already started/)});
test("token model stores only a hash and validates booking, assignment and Driver authority",()=>{const source=readFileSync(new URL("../src/lib/dispatch/trip-operations-repository.ts",import.meta.url),"utf8");for(const marker of ["randomBytes(32)","createHash(\"sha256\")","doc(tokenHash)","tokenLooksValid","data.assignmentId","data.assignedDriverId","booking.assignment.id!==data.assignmentId","booking.assignment.assignedDriverId!==data.assignedDriverId","active:false","revokedAt"])assert.ok(source.includes(marker),marker);assert.equal(source.includes("doc(token)"),false)});
test("invalid, expired, revoked, stale and cross-booking tokens are rejected server-side",()=>{const source=readFileSync(new URL("../src/lib/dispatch/trip-operations-repository.ts",import.meta.url),"utf8");for(const marker of ["Invalid or expired Driver trip link","!data.active","expiresAt","stale after an assignment change","does not authorize this trip","authorization is stale or revoked"])assert.ok(source.includes(marker),marker)});
test("transitions persist immutable history, timestamps, actor and source",()=>{const source=readFileSync(new URL("../src/lib/dispatch/trip-operations-repository.ts",import.meta.url),"utf8");for(const marker of ["collection(TRANSITIONS).doc()","tx.create(transitionRef","previousStatus","newStatus","statusTimestamps","driver_secure_page","admin_fallback","assigned_driver","trip_status_changed"])assert.ok(source.includes(marker),marker);assert.equal(source.includes("tx.delete(transitionRef"),false)});
test("cancelled bookings cannot authorize or continue while history is never deleted",()=>{const source=readFileSync(new URL("../src/lib/dispatch/trip-operations-repository.ts",import.meta.url),"utf8");assert.ok(source.includes('booking.lifecycle!=="active"'));assert.ok(source.includes("A cancelled booking cannot begin or continue a trip."));assert.equal(source.includes("delete(operationRef"),false);assert.equal(source.includes("delete(transition"),false)});
test("Admin fallback authenticates and uses the same transition function without impersonation",()=>{const actions=readFileSync(new URL("../app/admin/dispatch/actions.ts",import.meta.url),"utf8"),ui=readFileSync(new URL("../app/admin/dispatch/TripOperations.tsx",import.meta.url),"utf8");assert.match(actions,/transitionTripAdminAction[\s\S]*await auth\(\)/);assert.match(actions,/transitionTrip\(\{bookingOperationalId,assignmentId,requestedStatus,source:"admin_fallback"\}\)/);for(const marker of ["window.confirm","Shared Admin Session, not Driver","never impersonates the Driver"])assert.ok(ui.includes(marker),marker)});
test("secure mobile page has one state-dependent primary action and completion confirmation",()=>{const page=readFileSync(new URL("../app/driver/trip/[token]/page.tsx",import.meta.url),"utf8"),action=readFileSync(new URL("../app/driver/trip/[token]/TripAction.tsx",import.meta.url),"utf8");for(const marker of ["max-w-lg","trip.nextStatus","trip.nextAction","w-full","py-5","window.confirm","cannot be reversed","Trip Completed"])assert.ok((page+action).includes(marker),marker)});
test("D7 reassignment guard reads current trip state without changing normal assignment architecture",()=>{const source=readFileSync(new URL("../src/lib/dispatch/assignment-repository.ts",import.meta.url),"utf8");for(const marker of ["tripOperations","assertTripAllowsReassignment","currentStatus","previousAssignmentId","booking_reassigned"])assert.ok(source.includes(marker),marker)});
test("D8 and D9 remain separate from D10",()=>{for(const file of ["../src/lib/dispatch/driver-instructions-repository.ts","../src/lib/dispatch/customer-driver-details-repository.ts"]){const source=readFileSync(new URL(file,import.meta.url),"utf8");assert.equal(source.includes("tripOperations"),false);assert.equal(source.includes("driverTripTokens"),false)}});
test("D10 performs no automatic WhatsApp or customer notification",()=>{const files=["../src/lib/dispatch/trip-operations-core.ts","../src/lib/dispatch/trip-operations-repository.ts","../app/admin/dispatch/TripOperations.tsx","../app/driver/trip/[token]/page.tsx"].map(file=>readFileSync(new URL(file,import.meta.url),"utf8")).join("\n").toLowerCase();for(const forbidden of ["wa.me/","graph.facebook.com","whatsapp_business","customer_driver_details_marked_shared","delivery receipt"])assert.equal(files.includes(forbidden),false,forbidden)});

