import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { assertBroadcastBookingCurrent,broadcastRecipients,createBroadcastSafePreview,resolveOfferExpiry,selectBroadcastRecipients } from "../src/lib/dispatch/broadcast-approval-core.ts";
import { buildApprovedBroadcast,dispatchBroadcastIdentity } from "../src/lib/dispatch/dispatch-orchestration-core.ts";

const actor={type:"shared_admin_session"};
const candidate=(id,driverId,patch={})=>({id,vendor:{id:`vendor-${driverId}`,name:`Vendor ${driverId}`},vehicle:{id:`vehicle-${id}`,label:"Physical vehicle",registrationNumber:"PRIVATE-REG"},driver:{id:driverId,name:`Driver ${driverId}`},score:80,compatibility:"exact_category",reasons:["Correct zone","No conflict"],manuallyIncluded:false,...patch});
const candidates=[candidate("candidate-a","driver-a"),candidate("candidate-b","driver-b"),candidate("candidate-c","driver-a")];
const booking=(patch={})=>({id:"booking-a",bookingId:"RK-TEST-D62",sourceSnapshot:{durationHours:10},zoneId:"twin_cities",serviceType:"outstation",customer:{name:"PRIVATE CUSTOMER",phone:"03001234567"},itinerary:{travelDate:"2027-10-02",pickupTime:"09:00",pickup:"House 99, F-7, Islamabad, Pakistan",pickupLocation:{mapLink:"PRIVATE-MAP"},destinationOrUsage:"Murree"},requestedVehicle:{categoryOrModel:"Toyota Corolla"},customerFinancials:{customerTotalMinor:1000000},internalFinancials:{payoutStatus:"reviewed",vendorPayoutMinor:700000},lifecycle:"active",readinessStatus:"ready_for_dispatch",createdBy:actor,...patch});
const broadcastInput={bookingOperationalId:"booking-a",bookingId:"RK-TEST-D62",revision:1,offerRevision:1,candidateIds:["candidate-a"],offerIds:["offer-a"],driverIds:["driver-a"],approvedPayoutMinor:700000,offerExpiresAt:"2027-10-01T12:00:00.000Z",approvedAt:"2027-10-01T10:00:00.000Z",approvedBy:actor};

test("zero recipients and ineligible candidates are rejected",()=>{assert.throws(()=>selectBroadcastRecipients([],candidates),/at least one Driver/);assert.throws(()=>selectBroadcastRecipients(["missing"],candidates),/no longer eligible/);assert.throws(()=>selectBroadcastRecipients(["candidate-a","candidate-c"],candidates),/each Driver only once/)});
test("only exact selected recipients are returned",()=>{const selected=selectBroadcastRecipients(["candidate-b"],candidates);assert.deepEqual(selected.map(item=>item.id),["candidate-b"]);assert.deepEqual(selected.map(item=>item.driver.id),["driver-b"])});
test("recommended and other eligible Drivers are distinct and deduplicated",()=>{const rows=broadcastRecipients(candidates,[candidates[0]]);assert.equal(rows.length,2);assert.equal(rows.find(item=>item.driverId==="driver-a")?.recommended,true);assert.equal(rows.find(item=>item.driverId==="driver-b")?.recommended,false)});
test("privacy-safe preview contains operations only",()=>{const preview=createBroadcastSafePreview(booking()),serialized=JSON.stringify(preview);for(const privateValue of ["PRIVATE CUSTOMER","03001234567","House 99","PRIVATE-MAP","PRIVATE-REG","1000000"])assert.equal(serialized.includes(privateValue),false,privateValue);assert.equal(preview.vehicleRequirement,"Toyota Corolla");assert.equal(preview.approvedPayoutMinor,700000)});
test("expiry presets default safely and reject past/custom invalid values",()=>{const now=new Date("2027-10-01T10:00:00.000Z");assert.equal(resolveOfferExpiry("",undefined,now),"2027-10-01T10:30:00.000Z");assert.equal(resolveOfferExpiry("15",undefined,now),"2027-10-01T10:15:00.000Z");assert.throws(()=>resolveOfferExpiry("custom","2027-10-01T09:00",now),/future/);assert.throws(()=>resolveOfferExpiry("custom","bad",now),/valid custom/)});
test("booking and payout snapshots are revalidated",()=>{assert.equal(assertBroadcastBookingCurrent(booking(),700000).bookingId,"RK-TEST-D62");assert.throws(()=>assertBroadcastBookingCurrent(booking(),710000),/payout changed/);assert.throws(()=>assertBroadcastBookingCurrent(booking({readinessStatus:"awaiting_advance"}),700000),/Booking changed/);assert.throws(()=>assertBroadcastBookingCurrent(booking({lifecycle:"cancelled"}),700000),/Booking changed/)});
test("recipient, payout and expiry changes alter deterministic approval identity",()=>{const first=dispatchBroadcastIdentity(broadcastInput);assert.notEqual(first,dispatchBroadcastIdentity({...broadcastInput,candidateIds:["candidate-b"],offerIds:["offer-b"],driverIds:["driver-b"]}));assert.notEqual(first,dispatchBroadcastIdentity({...broadcastInput,approvedPayoutMinor:710000}));assert.notEqual(first,dispatchBroadcastIdentity({...broadcastInput,offerExpiresAt:"2027-10-01T13:00:00.000Z"}));assert.equal(buildApprovedBroadcast(broadcastInput).approvedPayoutMinor,700000)});
test("Admin UX starts empty, defaults to 30 minutes and requires explicit approval",()=>{const source=readFileSync(new URL("../app/admin/dispatch/BroadcastApproval.tsx",import.meta.url),"utf8");assert.match(source,/useState<string\[]>\(\[\]\)/);assert.match(source,/useState\("30"\)/);assert.match(source,/Approve Broadcast/);assert.match(source,/window\.confirm/);assert.match(source,/disabled=\{busy\|\|!selected\.length\|\|!validExpiry/);assert.match(source,/No messages sent yet/)});
test("server approval revalidates matching, stale revision and exact selected jobs",()=>{const source=readFileSync(new URL("../src/lib/dispatch/broadcast-approval-repository.ts",import.meta.url),"utf8");for(const marker of ["assertBroadcastBookingCurrent","computeMatches","selectBroadcastRecipients","currentRevision!==request.expectedCurrentRevision","selected.map","purpose:\"driver_offer\"","notificationStatus:\"queued\"","status:\"queued\"","driver_broadcast_approved","selectedRecipientCount"])assert.ok(source.includes(marker),marker);assert.match(source,/if\(existingBroadcast\.exists\)return/)});
test("approval preserves response state and queues delivery independently",()=>{const source=readFileSync(new URL("../src/lib/dispatch/broadcast-approval-repository.ts",import.meta.url),"utf8");assert.match(source,/responseStatus:existing\?\.responseStatus\?\?"not_recorded"/);assert.match(source,/notificationStatus:"queued"/);assert.doesNotMatch(source,/responseStatus:"available"|responseStatus:"accepted"|responseStatus:"declined"|responseStatus:"countered"/)});
test("D6.2 is provider-inert and manual fallback remains",()=>{const repository=readFileSync(new URL("../src/lib/dispatch/broadcast-approval-repository.ts",import.meta.url),"utf8"),manual=readFileSync(new URL("../app/admin/dispatch/OfferControls.tsx",import.meta.url),"utf8");for(const forbidden of ["getWhatsAppOutboundProvider","sendText(","sendTemplate(","fetch(","api.dualhook.com"])assert.equal(repository.includes(forbidden),false,forbidden);for(const marker of ["Copy Driver Offer","Open WhatsApp","Mark Offer Sent"])assert.ok(manual.includes(marker),marker)});
test("approval audit contains no recipient phone or private payload",()=>{const source=readFileSync(new URL("../src/lib/dispatch/broadcast-approval-repository.ts",import.meta.url),"utf8"),audit=source.slice(source.indexOf("driver_broadcast_approved"));assert.match(audit,/candidateIds/);assert.match(audit,/offerIds/);assert.match(audit,/approvedPayoutMinor/);assert.match(audit,/offerExpiresAt/);assert.doesNotMatch(audit,/driverWhatsappNumber|customer|phone|message/)});
