import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { assertBroadcastTransition,assertCurrentRevision,assertNotificationTransition,assertOfferOpen,buildApprovedBroadcast,buildOutboundMessageJob,dispatchBroadcastIdentity,isOfferExpired,offerNotificationStatus,outboundMessageIdentity,reuseOrCreateBroadcast,reuseOrCreateOutboundJob } from "../src/lib/dispatch/dispatch-orchestration-core.ts";

const actor={type:"shared_admin_session"};
const broadcastInput={bookingOperationalId:"booking-a",bookingId:"RK-TEST-1",revision:1,offerRevision:2,candidateIds:["candidate-b","candidate-a"],offerIds:["offer-b","offer-a"],driverIds:["driver-b","driver-a"],approvedPayoutMinor:500000,offerExpiresAt:"2027-10-01T12:00:00.000Z",approvedAt:"2027-10-01T10:00:00.000Z",approvedBy:actor};

test("broadcast validation snapshots only selected candidates and offers",()=>{const value=buildApprovedBroadcast(broadcastInput);assert.equal(value.status,"approved");assert.deepEqual(value.candidateIds,["candidate-a","candidate-b"]);assert.deepEqual(value.offerIds,["offer-a","offer-b"]);assert.equal(value.approvedPayoutMinor,500000);assert.throws(()=>buildApprovedBroadcast({...broadcastInput,candidateIds:[]}));assert.throws(()=>buildApprovedBroadcast({...broadcastInput,offerIds:["offer-a"]}))});
test("broadcast identity is deterministic and revision-sensitive",()=>{const first=dispatchBroadcastIdentity(broadcastInput);assert.equal(first,dispatchBroadcastIdentity({...broadcastInput,candidateIds:[...broadcastInput.candidateIds].reverse(),offerIds:[...broadcastInput.offerIds].reverse(),driverIds:[...broadcastInput.driverIds].reverse()}));assert.notEqual(first,dispatchBroadcastIdentity({...broadcastInput,revision:2}))});
test("duplicate broadcast creation reuses existing record",()=>{const proposed=buildApprovedBroadcast(broadcastInput),existing={...proposed,status:"queued"};const result=reuseOrCreateBroadcast(existing,proposed);assert.equal(result.duplicate,true);assert.equal(result.broadcast,existing)});
test("broadcast transition and stale revision guards reject invalid state",()=>{assert.equal(assertBroadcastTransition("approved","queued"),"queued");assert.throws(()=>assertBroadcastTransition("sent","sending"));assert.equal(assertCurrentRevision(3,3),3);assert.throws(()=>assertCurrentRevision(2,3))});
test("outbound identities cover driver offers and assignment notifications",()=>{const base={purpose:"driver_offer",bookingOperationalId:"booking-a",bookingId:"RK-TEST-1",broadcastId:"broadcast-a",offerId:"offer-a",recipientType:"driver",recipientReferenceId:"driver-a",provider:"dualhook",messageKind:"template",createdAt:"2027-10-01T10:00:00.000Z"};const first=outboundMessageIdentity(base);assert.equal(first,outboundMessageIdentity({...base}));assert.notEqual(first,outboundMessageIdentity({...base,recipientReferenceId:"driver-b"}));assert.throws(()=>outboundMessageIdentity({...base,broadcastId:undefined}));assert.doesNotThrow(()=>outboundMessageIdentity({...base,purpose:"driver_final_instructions",broadcastId:undefined,offerId:undefined,assignmentId:"assignment-a"}))});
test("duplicate outbound creation reuses existing job",()=>{const proposed=buildOutboundMessageJob({purpose:"driver_offer",bookingOperationalId:"booking-a",bookingId:"RK-TEST-1",broadcastId:"broadcast-a",offerId:"offer-a",recipientType:"driver",recipientReferenceId:"driver-a",provider:"dualhook",messageKind:"template",createdAt:"2027-10-01T10:00:00.000Z"}),existing={...proposed,status:"queued",attemptCount:0};const result=reuseOrCreateOutboundJob(existing,proposed);assert.equal(result.duplicate,true);assert.equal(result.job,existing)});
test("notification transitions support provider progression and outcome unknown",()=>{for(const [from,to] of [["not_queued","queued"],["queued","sending"],["sending","provider_accepted"],["provider_accepted","sent"],["sent","delivered"],["delivered","read"],["sending","outcome_unknown"],["outcome_unknown","delivered"]])assert.equal(assertNotificationTransition(from,to),to);assert.throws(()=>assertNotificationTransition("read","queued"));assert.throws(()=>assertNotificationTransition("cancelled","sent"))});
test("response and delivery state remain independent and old offers default safely",()=>{const old={responseStatus:"accepted"};assert.equal(offerNotificationStatus(old),"not_queued");const extended={...old,notificationStatus:"delivered"};assert.equal(extended.responseStatus,"accepted");assert.equal(offerNotificationStatus(extended),"delivered")});
test("explicit offer expiry closes responses while old offers remain compatible",()=>{assert.equal(isOfferExpired(undefined,new Date("2027-01-01")),false);assert.equal(isOfferExpired("2027-01-01T00:00:00Z",new Date("2027-01-02")),true);assert.doesNotThrow(()=>assertOfferOpen({responseStatus:"not_recorded"},new Date("2027-01-01")));assert.throws(()=>assertOfferOpen({responseStatus:"not_recorded",offerExpiresAt:"2027-01-01T00:00:00Z"},new Date("2027-01-02")))});
test("pre-assignment offer message excludes private and physical vehicle data",async()=>{const {createDriverOfferProjection}=await import("../src/lib/dispatch/offer-core.ts"),booking={id:"booking-a",bookingId:"RK-TEST-1",sourceSnapshot:{durationHours:12},zoneId:"twin_cities",serviceType:"with_driver",customer:{name:"PRIVATE PERSON",phone:"03001234567"},itinerary:{travelDate:"2027-10-01",pickupTime:"10:00",pickup:"House 99, F-7, Islamabad, Pakistan",destinationOrUsage:"Lahore"},requestedVehicle:{categoryOrModel:"Sedan"},customerFinancials:{customerTotalMinor:1000000},internalFinancials:{payoutStatus:"reviewed",vendorPayoutMinor:500000},responsibilities:{},lifecycle:"active",readinessStatus:"ready_for_dispatch"},candidate={id:"candidate-a",vendor:{id:"vendor-a",name:"Vendor"},vehicle:{id:"vehicle-a",label:"Toyota Corolla 2024",registrationNumber:"SECRET-REG"},driver:{id:"driver-a",name:"Driver"},score:100,compatibility:"exact_category",reasons:[],manuallyIncluded:false},driver={id:"driver-a",whatsappNumber:"03001111111",whatsappNumberNormalized:"923001111111"};const projection=createDriverOfferProjection({booking,candidate,driver});for(const privateValue of ["PRIVATE PERSON","03001234567","House 99","SECRET-REG","Toyota Corolla 2024","1000000"])assert.equal(projection.message.includes(privateValue),false,privateValue);assert.match(projection.message,/Vehicle Requirement: Sedan/);assert.match(projection.message,/Pickup Area: F-7, Islamabad/)});
test("D6.1 repositories are provider-inert and existing webhook security is untouched",()=>{const files=["../src/lib/dispatch/dispatch-broadcast-repository.ts","../src/lib/messaging/whatsapp-outbox-repository.ts"].map(value=>readFileSync(new URL(value,import.meta.url),"utf8")).join("\n"),meta=readFileSync(new URL("../app/api/webhooks/meta/whatsapp/route.ts",import.meta.url),"utf8");for(const forbidden of ["getWhatsAppOutboundProvider","sendText(","sendTemplate(","api.dualhook.com","fetch("])assert.equal(files.includes(forbidden),false,forbidden);assert.match(meta,/verifyMetaWebhookSignature/);assert.match(meta,/x-hub-signature-256/)});
test("broadcast repository keeps one authoritative revision and closes its predecessor",()=>{const source=readFileSync(new URL("../src/lib/dispatch/dispatch-broadcast-repository.ts",import.meta.url),"utf8");for(const marker of ["activeBroadcastId","assertCurrentRevision","previousId","superseded","status:\"closed\""])assert.ok(source.includes(marker),marker)});
