import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  aggregateBroadcastStatus,
  assertBookingOfferSendable,
  bookingOfferTemplateComponents,
  classifyProviderFailure,
  invokeDriverOfferProvider,
} from "../src/lib/messaging/driver-offer-delivery-core.ts";
import { requireBookingOfferDeliveryConfig } from "../src/lib/messaging/driver-offer-delivery-config-core.ts";
import { nextDeliveryStatus } from "../src/lib/messaging/whatsapp-delivery-core.ts";
import { directDriverOfferIdentity,serializeDispatchOfferRecord } from "../src/lib/dispatch/offer-types.ts";
import { projectSupplyRecipients } from "../src/lib/dispatch/supply-recipient-projection.ts";

const source = path => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const now = new Date("2026-09-14T00:00:00.000Z");
const actor = { type:"shared_admin_session" };
const booking = (patch={}) => ({ id:"book", bookingId:"RK-VF8", lifecycle:"active", readinessStatus:"ready_for_dispatch", serviceType:"within_city", assignment:undefined, customer:{name:"Private Customer",phone:"03009999999"}, internalFinancials:{payoutStatus:"reviewed",vendorPayoutMinor:700000}, itinerary:{pickup:"House 1, Blue Area, Islamabad",destinationOrUsage:"Office 2, F-8, Islamabad",travelDate:"2026-09-16",pickupTime:"10:00"}, requestedVehicle:{categoryOrModel:"Sedan"}, sourceSnapshot:{durationHours:8}, ...patch });
const vendor = (patch={}) => ({ id:"v1", name:"Vendor One", primaryPhone:"03001111111", primaryPhoneNormalized:"923001111111", whatsappNumber:"03001111111", whatsappNumberNormalized:"923001111111", supplyClassification:"vendor_managed", independentOwnerDriverId:undefined, active:true, zoneIds:["twin_cities"], createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch });
const driver = (patch={}) => ({ id:"d1", name:"Driver One", vendorId:"v1", mobileNumber:"03002222222",mobileNumberNormalized:"923002222222",whatsappNumber:"03002222222",whatsappNumberNormalized:"923002222222",supplyRelationship:"vendor_managed",active:true,status:"available",zoneIds:["twin_cities"],createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch });
const vehicle = (id="car1",patch={}) => ({ id,vendorId:"v1",controlRelationship:"vendor_managed",label:`Toyota Corolla ${id}`,active:true,status:"available",zoneIds:["twin_cities"],createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch });
const offer = (patch={}) => ({ id:"o1",bookingOperationalId:"book",bookingId:"RK-VF8",broadcastId:"b1",offerRevision:1,candidateId:"s1",vendorId:"v1",recipientType:"vendor",recipientId:"v1",supplyAccountId:"v1",recipientWhatsappNumber:"923001111111",approvedPayoutMinor:700000,currentOfferedPayoutMinor:700000,offerExpiresAt:"2026-09-15T00:00:00.000Z",offerStage:"prepared",responseStatus:"not_recorded",createdAt:"now",updatedAt:"now",createdBy:actor,updatedBy:actor,...patch });
const broadcast = (patch={}) => ({ id:"b1",broadcastId:"b1",bookingOperationalId:"book",bookingId:"RK-VF8",revision:1,offerRevision:1,status:"approved",candidateIds:["s1"],offerIds:["o1"],driverIds:[],approvedPayoutMinor:700000,offerExpiresAt:"2026-09-15T00:00:00.000Z",recipients:[{candidateId:"s1",offerId:"o1",recipientType:"vendor",recipientId:"v1",supplyAccountId:"v1",recipientDisplayName:"Vendor One",recipientWhatsappNumber:"923001111111"}],...patch });
const job = (patch={}) => ({ id:"j1",purpose:"booking_offer",bookingOperationalId:"book",bookingId:"RK-VF8",broadcastId:"b1",offerId:"o1",recipientType:"vendor",recipientReferenceId:"v1",recipientWhatsappNumber:"923001111111",provider:"dualhook",messageKind:"template",status:"queued",attemptCount:0,idempotencyKey:"j1",createdAt:"now",...patch });
const sendable = (patch={}) => ({job:job(patch.job),booking:booking(patch.booking),broadcast:broadcast(patch.broadcast),offer:offer(patch.offer),activeBroadcastId:patch.activeBroadcastId??"b1",vendor:vendor(patch.vendor),driver:patch.driver?driver(patch.driver):undefined,now});
const independent = (patch={}) => sendable({
  vendor:{supplyClassification:"independent_owner_driver",independentOwnerDriverId:"d1",...patch.vendor},
  driver:{supplyRelationship:"independent_owner_driver",...patch.driver},
  offer:{recipientType:"independent_driver",recipientId:"d1",driverId:"d1",recipientWhatsappNumber:"923002222222",...patch.offer},
  job:{recipientType:"independent_driver",recipientReferenceId:"d1",recipientWhatsappNumber:"923002222222",...patch.job},
  broadcast:{recipients:[{candidateId:"s1",offerId:"o1",recipientType:"independent_driver",recipientId:"d1",supplyAccountId:"v1",recipientDisplayName:"Driver One",recipientWhatsappNumber:"923002222222"}],driverIds:["d1"],...patch.broadcast},
  booking:patch.booking,activeBroadcastId:patch.activeBroadcastId,
});
const pair = (d,car,score=90) => ({id:`pair-${d.id}-${car.id}`,driver:d,vehicle:{...car,label:car.label},vendor:vendor(),score,compatibility:"exact_model",reasons:[]});
const worker = source("src/lib/messaging/driver-offer-delivery-repository.ts");
const approvalRepo = source("src/lib/dispatch/broadcast-approval-repository.ts");
const actions = source("app/admin/dispatch/actions.ts");
const approvalUi = source("app/admin/dispatch/BroadcastApproval.tsx");
const vendorUi = source("app/admin/dispatch/VendorSecureOfferControls.tsx");
const vendorRepo = source("src/lib/dispatch/vendor-offer-portal-repository.ts");
const assignmentUi = source("app/admin/dispatch/AssignmentPanel.tsx");

test("vendor-managed booking offer is sendable",()=>assert.equal(assertBookingOfferSendable(sendable()).target,"923001111111"));
test("vendor-managed target is the Vendor operational WhatsApp",()=>assert.equal(assertBookingOfferSendable(sendable({offer:{recipientWhatsappNumber:"923001111111"}})).recipientType,"vendor"));
test("vendor-managed offer cannot target a child Driver",()=>assert.throws(()=>assertBookingOfferSendable(sendable({offer:{recipientId:"d1"},job:{recipientReferenceId:"d1"},broadcast:{recipients:[{candidateId:"s1",offerId:"o1",recipientType:"vendor",recipientId:"d1",supplyAccountId:"v1",recipientDisplayName:"Driver One",recipientWhatsappNumber:"923002222222"}]}})),/classification/));
test("vendor-managed delivery rejects contradictory supply classification",()=>assert.throws(()=>assertBookingOfferSendable(sendable({vendor:{supplyClassification:"independent_owner_driver"}})),/classification/));
test("inactive or unknown-needs-review Vendor supply is blocked",()=>{assert.throws(()=>assertBookingOfferSendable(sendable({vendor:{active:false}})),/active/);assert.throws(()=>assertBookingOfferSendable(sendable({vendor:{supplyClassification:"unknown_needs_review"}})),/classification/);const d=driver(),car=vehicle(),projection=projectSupplyRecipients({pairCandidates:[pair(d,car)],vendors:[vendor({supplyClassification:"unknown_needs_review"})],drivers:[d],vehicles:[car],zoneId:"twin_cities"});assert.equal(projection.eligible.length,0);assert.equal(projection.excluded.length,1)});
test("independent owner-driver booking offer is sendable",()=>assert.equal(assertBookingOfferSendable(independent()).target,"923002222222"));
test("independent owner-driver uses the Driver operational WhatsApp",()=>assert.equal(assertBookingOfferSendable(independent()).recipientType,"independent_driver"));
test("independent relationship contradiction is blocked",()=>assert.throws(()=>assertBookingOfferSendable(independent({driver:{supplyRelationship:"vendor_managed"}})),/identity/));
test("foreign independent Driver is blocked",()=>assert.throws(()=>assertBookingOfferSendable(independent({driver:{vendorId:"v2"}})),/identity/));
test("missing or changed Vendor operational WhatsApp is blocked",()=>{assert.throws(()=>assertBookingOfferSendable(sendable({vendor:{whatsappNumber:"",whatsappNumberNormalized:""}})),/WhatsApp changed/);assert.throws(()=>assertBookingOfferSendable(sendable({vendor:{whatsappNumber:"03003333333",whatsappNumberNormalized:"923003333333"}})),/WhatsApp changed/)});
test("stale broadcast identity or revision is blocked",()=>{assert.throws(()=>assertBookingOfferSendable(sendable({activeBroadcastId:"b2"})),/current/);assert.throws(()=>assertBookingOfferSendable(sendable({offer:{offerRevision:2}})),/stale/)});
test("expired Supplier offer is blocked",()=>assert.throws(()=>assertBookingOfferSendable(sendable({offer:{offerExpiresAt:"2026-09-13T00:00:00.000Z"}})),/expired/));
test("stale payout is blocked",()=>assert.throws(()=>assertBookingOfferSendable(sendable({booking:{internalFinancials:{payoutStatus:"reviewed",vendorPayoutMinor:800000}}})),/payout/));
test("cancelled or assigned booking is blocked",()=>{assert.throws(()=>assertBookingOfferSendable(sendable({booking:{lifecycle:"cancelled"}})),/dispatch-valid/);assert.throws(()=>assertBookingOfferSendable(sendable({booking:{assignment:{status:"assigned"}}})),/dispatch-valid/)});
test("double-submit and progressed jobs cannot resend",()=>{assert.doesNotThrow(()=>assertBookingOfferSendable(sendable({job:{status:"failed",failureRetryable:true}})));for(const status of ["sending","provider_accepted","sent","delivered","read","outcome_unknown"])assert.throws(()=>assertBookingOfferSendable(sendable({job:{status}})),/not sendable/);assert.ok(worker.includes("invoked: false"));assert.equal((worker.match(/invokeDriverOfferProvider\(provider/g)||[]).length,1)});
test("missing Vendor template configuration fails before claim",()=>{assert.throws(()=>requireBookingOfferDeliveryConfig({templateName:"rentka_driver_trip_offer_v1",templateLanguage:"en",publicBaseUrl:"https://www.rentka.co"},"vendor"),/Vendor offer/);assert.ok(worker.indexOf("requireBookingOfferDeliveryConfig(rawConfig,preflight.recipientType)")<worker.indexOf("runTransaction"))});
test("dedicated Vendor template configuration is accepted",()=>assert.deepEqual(requireBookingOfferDeliveryConfig({vendorTemplateName:"rentka_vendor_trip_offer_v1",vendorTemplateLanguage:"en",publicBaseUrl:"https://www.rentka.co/path"},"vendor"),{templateName:"rentka_vendor_trip_offer_v1",templateLanguage:"en",publicBaseUrl:"https://www.rentka.co"}));
test("independent owner-driver retains the approved Driver template",()=>assert.equal(requireBookingOfferDeliveryConfig({templateName:"rentka_driver_trip_offer_v1",templateLanguage:"en",publicBaseUrl:"https://www.rentka.co"},"independent_driver").templateName,"rentka_driver_trip_offer_v1"));
test("Vendor template has nine ordered privacy-safe body parameters",()=>{const components=bookingOfferTemplateComponents(booking(),offer(),"https://www.rentka.co/vendor/offer/opaque-token");assert.deepEqual(components[0].parameters.map(item=>item.text),["RK-VF8","Blue Area, Islamabad","F-8, Islamabad","2026-09-16","10:00","Sedan","within_city · 8 hours","PKR 7,000","2026-09-15T00:00:00.000Z"])});
test("Vendor template sends only the opaque URL-button suffix",()=>assert.deepEqual(bookingOfferTemplateComponents(booking(),offer(),"https://www.rentka.co/vendor/offer/opaque-token")[1],{type:"button",sub_type:"url",index:"0",parameters:[{type:"text",text:"opaque-token"}]}));
test("Supplier template excludes private customer and child-resource details",()=>{const serialized=JSON.stringify(bookingOfferTemplateComponents(booking(),offer({vehicleRegistration:"ADMIN-REG-8"}),"https://www.rentka.co/vendor/offer/opaque-token"));for(const forbidden of ["Private Customer","03009999999","House 1","Office 2","Driver One","car1","ADMIN-REG-8"])assert.equal(serialized.includes(forbidden),false,forbidden)});
test("Supplier template rejects wrong secure portal path",()=>assert.throws(()=>bookingOfferTemplateComponents(booking(),offer(),"https://www.rentka.co/driver/offer/token"),/invalid/));
test("provider abstraction is invoked exactly once",async()=>{let calls=0;const provider={sendText:async()=>{throw new Error("unused")},sendTemplate:async()=>{calls++;return{provider:"dualhook",messageId:"wamid.vf8"}}};const result=await invokeDriverOfferProvider(provider,{to:"923001111111",name:"rentka_vendor_trip_offer_v1",languageCode:"en",components:[]});assert.equal(calls,1);assert.equal(result.status,"provider_accepted")});
test("provider acceptance remains separate from confirmed delivery",()=>{assert.equal(nextDeliveryStatus("provider_accepted","delivered"),"delivered");assert.equal(worker.includes('status: "delivered"'),false);assert.ok(worker.includes("supplier_offer_provider_accepted"));assert.ok(vendorUi.includes("Delivery:"));const timestamp={toDate:()=>new Date("2026-09-14T12:20:35.987Z")},record=serializeDispatchOfferRecord({...offer(),createdAt:timestamp,updatedAt:timestamp,providerAcceptedAt:timestamp,fulfillmentProposal:{proposedAt:timestamp}},"o1");assert.equal(record.providerAcceptedAt,"2026-09-14T12:20:35.987Z");assert.equal(record.fulfillmentProposal.proposedAt,"2026-09-14T12:20:35.987Z");assert.doesNotThrow(()=>JSON.stringify(record))});
test("vendor fulfillment proposal timestamps become fully plain Client Component data",()=>{const timestamp={toDate:()=>new Date("2026-09-14T12:24:30.185Z")},proposal={proposalId:"proposal-vf8",status:"provided",vendorId:"v1",driverId:"d1",driverName:"Driver One",vehicleId:"car1",vehicleLabel:"Toyota Corolla",offerRevision:2,responseRevision:2,proposedAt:timestamp,timestamp,updatedAt:timestamp,history:[{timestamp,updatedAt:timestamp}],actor:{type:"vendor_offer",vendorId:"v1",offerId:"o1"}},record=serializeDispatchOfferRecord({...offer({responseStatus:"accepted",proposalStatus:"provided"}),createdAt:timestamp,updatedAt:timestamp,fulfillmentProposal:proposal},"o1"),normalized=record.fulfillmentProposal,assertPlain=value=>{if(value===null||typeof value!=="object")return;assert.equal(typeof value.toDate,"undefined");if(Array.isArray(value)){for(const item of value)assertPlain(item);return}assert.equal(Object.getPrototypeOf(value),Object.prototype);for(const nested of Object.values(value))assertPlain(nested)};assert.equal(normalized.proposedAt,"2026-09-14T12:24:30.185Z");assert.equal(normalized.timestamp,"2026-09-14T12:24:30.185Z");assert.equal(normalized.updatedAt,"2026-09-14T12:24:30.185Z");assert.equal(normalized.history[0].timestamp,"2026-09-14T12:24:30.185Z");assert.equal(normalized.proposalId,"proposal-vf8");assert.equal(normalized.vendorId,"v1");assert.equal(normalized.driverId,"d1");assert.equal(normalized.vehicleId,"car1");assert.equal(normalized.status,"provided");assert.equal(record.responseStatus,"accepted");assert.equal(record.proposalStatus,"provided");assertPlain(normalized);assert.doesNotThrow(()=>JSON.stringify(record))});
test("retryable and ambiguous provider failures remain distinct",()=>{assert.deepEqual(classifyProviderFailure({code:"REQUEST_FAILED",status:503}),{status:"failed",failureCode:"provider_retryable",retryable:true});assert.deepEqual(classifyProviderFailure({code:"INVALID_RESPONSE"}),{status:"outcome_unknown",failureCode:"provider_outcome_unknown",retryable:false});assert.ok(vendorUi.includes("Retry Supplier Delivery"));assert.ok(vendorUi.includes("Do not retry until provider reconciliation"))});
test("webhook delivery states advance idempotently",()=>{assert.equal(nextDeliveryStatus("provider_accepted","sent"),"sent");assert.equal(nextDeliveryStatus("sent","delivered"),"delivered");assert.equal(nextDeliveryStatus("delivered","read"),"read");assert.equal(nextDeliveryStatus("read","sent"),"read")});
test("delivery response proposal and final assignment remain independent",()=>{assert.equal(aggregateBroadcastStatus(["delivered","failed"]),"partially_failed");assert.equal(worker.includes("responseStatus:"),false);const accept=vendorRepo.slice(vendorRepo.indexOf("submitSecureVendorOfferResponse"),vendorRepo.indexOf("export type VendorCounterReviewRequest")),proposal=vendorRepo.slice(vendorRepo.indexOf("submitVendorFulfillmentProposal"));assert.equal(accept.includes("reservationRef"),false);assert.equal(proposal.includes("tx.create(reservation"),false);assert.ok(vendorUi.includes("Assignment:"));assert.ok(assignmentUi.includes("Confirm Vendor Fulfillment Assignment"))});
test("Admin action completes approval before dispatching deterministic jobs",()=>{const approved=actions.indexOf("await approveDispatchBroadcast"),delivered=actions.indexOf("await deliverApprovedBookingOfferJobs",approved);assert.ok(approved>=0&&delivered>approved);assert.match(approvalUi,/Approve & Send Offers/);assert.match(approvalUi,/approval transaction completes first/i)});
test("Approve and Send creates one deterministic Vendor outbox job per selected recipient",()=>{for(const forbidden of ["getWhatsAppOutboundProvider","sendTemplate(","sendText("])assert.equal(approvalRepo.includes(forbidden),false,forbidden);for(const marker of ["buildOutboundMessageJob","tx.create(jobRefs[index]","status:\"queued\""])assert.ok(approvalRepo.includes(marker),marker);assert.equal((approvalRepo.match(/tx\.create\(jobRefs\[index\]/g)||[]).length,1)});
test("one Vendor one Vehicle one Driver yields one Vendor-first recipient",()=>{const d=driver(),car=vehicle(),projection=projectSupplyRecipients({pairCandidates:[pair(d,car)],vendors:[vendor()],drivers:[d],vehicles:[car],zoneId:"twin_cities"});assert.equal(projection.eligible.length,1);assert.equal(projection.eligible[0].recipientTypeIntent,"vendor");assert.equal(projection.eligible[0].recipientReferenceId,"v1");assert.equal(projection.eligible[0].eligibleDriverCount,1);assert.equal(projection.eligible[0].eligibleVehicleCount,1)});
test("one Vendor five Vehicles eight Drivers still yields one Vendor-first recipient",()=>{const drivers=Array.from({length:8},(_,i)=>driver({id:`d${i+1}`,name:`Driver ${i+1}`})),vehicles=Array.from({length:5},(_,i)=>vehicle(`car${i+1}`)),pairs=drivers.flatMap((d,di)=>vehicles.map((car,ci)=>pair(d,car,100-di-ci)));const projection=projectSupplyRecipients({pairCandidates:pairs,vendors:[vendor()],drivers,vehicles,zoneId:"twin_cities"});assert.equal(projection.eligible.length,1);assert.equal(projection.eligible[0].recipientTypeIntent,"vendor");assert.equal(projection.eligible[0].eligibleDriverCount,8);assert.equal(projection.eligible[0].eligibleVehicleCount,5);assert.notEqual(projection.eligible[0].recipientReferenceId,"d1")});
test("historical D6.4 and independent Driver portals remain compatible while Vendor is rejected",()=>{assert.deepEqual(directDriverOfferIdentity({driverId:"d1",vendorId:"v1"}),{driverId:"d1",vendorId:"v1",recipientType:"driver"});assert.deepEqual(directDriverOfferIdentity({recipientType:"independent_driver",recipientId:"d1",supplyAccountId:"v1",driverId:"d1",vendorId:"v1"}),{driverId:"d1",vendorId:"v1",recipientType:"independent_driver"});assert.throws(()=>directDriverOfferIdentity({recipientType:"vendor",recipientId:"v1",supplyAccountId:"v1"}),/direct Driver/);for(const marker of ["driver_offer_send_started","driver_offer_provider_accepted","issueSecureDriverOfferLink"])assert.ok(worker.includes(marker),marker)});
