import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { verifyDualhookWebhookChallenge,parseDualhookWebhookPayload } from "../src/lib/messaging/dualhook-whatsapp-webhook.ts";

const expected={wabaId:"1669817960844204",phoneNumberId:"995770263630038"};
const payload=(field="messages",value={statuses:[{id:"wamid.TEST",status:"delivered",timestamp:"1750000000"}],metadata:{phone_number_id:expected.phoneNumberId}})=>({object:"whatsapp_business_account",entry:[{id:expected.wabaId,changes:[{field,value}]}]});
test("Dualhook GET challenge validates dedicated token",()=>{assert.equal(verifyDualhookWebhookChallenge({mode:"subscribe",token:"dual",challenge:"abc",expectedToken:"dual"}),true);assert.equal(verifyDualhookWebhookChallenge({mode:"subscribe",token:"wrong",challenge:"abc",expectedToken:"dual"}),false);assert.equal(verifyDualhookWebhookChallenge({mode:null,token:null,challenge:null,expectedToken:"dual"}),false)});
for(const field of ["messages","smb_message_echoes","smb_app_state_sync","history"])test(`${field} is accepted with strict tenant validation`,()=>{const events=parseDualhookWebhookPayload(payload(field,field==="messages"?{statuses:[{id:"wamid.TEST",status:"sent",timestamp:"1750000000"}],metadata:{phone_number_id:expected.phoneNumberId}}:{metadata:{phone_number_id:expected.phoneNumberId}}),expected,"raw");assert.equal(events.length,1);assert.equal(events[0].field,field)});
test("wrong tenant identifiers and malformed envelopes reject",()=>{assert.deepEqual(parseDualhookWebhookPayload(payload("messages",{metadata:{phone_number_id:"wrong"}}),expected,"raw"),[]);assert.deepEqual(parseDualhookWebhookPayload({...payload(),entry:[{...payload().entry[0],id:"wrong"}]},expected,"raw"),[]);assert.deepEqual(parseDualhookWebhookPayload({object:"bad"},expected,"raw"),[]);assert.deepEqual(parseDualhookWebhookPayload(null,expected,"raw"),[])});
test("duplicate delivery is deterministic and unverifiable X-Hub signature is not consulted",()=>{const body=JSON.stringify(payload()),a=parseDualhookWebhookPayload(JSON.parse(body),expected,body),b=parseDualhookWebhookPayload(JSON.parse(body),expected,body);assert.equal(a[0].eventId,b[0].eventId);const route=readFileSync(new URL("../app/api/webhooks/dualhook/whatsapp/[secret]/route.ts",import.meta.url),"utf8");assert.equal(route.includes("x-hub-signature"),false)});
test("existing Meta endpoint retains cryptographic verification",()=>{const route=readFileSync(new URL("../app/api/webhooks/meta/whatsapp/route.ts",import.meta.url),"utf8");assert.match(route,/verifyMetaWebhookSignature/);assert.match(route,/x-hub-signature-256/) });
