"use client";
import { useEffect,useRef,useState } from "react";
import { Autocomplete } from "@react-google-maps/api";
import { GooglePlacesProvider,useGooglePlacesLoader } from "../../../app/admin/pricing-calculator/_components/GooglePlacesProvider";
import { ISLAMABAD_AIRPORT } from "@/lib/airport/constants";
import type { AirportPlace,AirportTripType,LuggageLevel } from "@/lib/airport/types";
import { trackDataLayer } from "@/lib/tracking";

type Quote={quoteId:string;tripType:AirportTripType;pickup:AirportPlace;destination:AirportPlace;distanceKm:number;durationMinutes:number;vehicle:{id:string;name:string;passengers:number;luggage:string};price:number;includedItems:string[];excludedItems:string[];expiresAt:string};
type DateOption={value:string;label:string;disabled:boolean};
type BookingSuccess={bookingId:string;quoteId:string;status:string;tripType:AirportTripType;date:string;time:string;pickup:AirportPlace;destination:AirportPlace;vehicle:{name:string};quotedTotal:number;advancePercentage:number;expectedAdvanceAmount:number;passengers:number;luggage:string;customer:{name:string;phone:string;email:string};flightNumber:string;airline:string;notes:string};
const whatsapp="https://wa.me/923020589999?text=Hi%20RentKA%2C%20I%20need%20help%20with%20an%20Islamabad%20Airport%20Transfer.";
const localDateValue=(value:Date)=>`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;
const TIME_OPTIONS=Array.from({length:96},(_,index)=>{const minutes=index*15;const hour=Math.floor(minutes/60);const minute=minutes%60;const value=`${String(hour).padStart(2,"0")}:${String(minute).padStart(2,"0")}`;const label=`${hour%12||12}:${String(minute).padStart(2,"0")} ${hour<12?"AM":"PM"}`;return {value,label,minutes}});
const whatsappUrlForBooking=(booking:BookingSuccess)=>{const [year,month,day]=booking.date.split("-").map(Number);const dateLabel=new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(year,month-1,day));const [hour,minute]=booking.time.split(":").map(Number);const timeLabel=`${hour%12||12}:${String(minute).padStart(2,"0")} ${hour<12?"AM":"PM"}`;const lines=["🚘 *RentKA Airport Booking*","",`🆔 *Booking ID:* ${booking.bookingId}`,"",`✈️ *Service:* ${booking.tripType==="airportPickup"?"Airport Pickup":"Airport Drop-off"}`,`🚗 *Vehicle:* ${booking.vehicle.name}`,"",`📍 *From:* ${booking.pickup.formattedAddress}`,`📍 *To:* ${booking.destination.formattedAddress}`,"",`📅 *Date:* ${dateLabel}`,`🕐 *Pickup Time:* ${timeLabel}`,`👥 *Passengers:* ${booking.passengers}`,`🧳 *Luggage:* ${booking.luggage.charAt(0).toUpperCase()+booking.luggage.slice(1)}`,"",`💰 *Total Fare:* Rs ${booking.quotedTotal.toLocaleString("en-PK")}`,"",`👤 *Passenger:* ${booking.customer.name}`,`📞 *Phone:* ${booking.customer.phone}`];if(booking.flightNumber)lines.push("",`✈️ *Flight:* ${booking.flightNumber}`);if(booking.airline)lines.push(`🏢 *Airline:* ${booking.airline}`);if(booking.notes)lines.push(`📝 *Notes:* ${booking.notes}`);lines.push("","✅ *Booking request submitted through RentKA website.*");return `https://wa.me/923020589999?text=${encodeURIComponent(lines.join("\n"))}`};
function LocationInput({value,setValue,setPlace}:{value:string;setValue:(v:string)=>void;setPlace:(v:AirportPlace|undefined)=>void}){const {status}=useGooglePlacesLoader();const ref=useRef<google.maps.places.Autocomplete|null>(null);const input=<input className="w-full rounded-xl border border-slate-300 px-4 py-3 text-base text-slate-900 outline-none focus:border-[#5BAE4A]" value={value} placeholder="Search your home, hotel or office" onChange={e=>{setValue(e.target.value);setPlace(undefined)}}/>;return <div>{status==="ready"?<Autocomplete onLoad={v=>{ref.current=v}} onPlaceChanged={()=>{const p=ref.current?.getPlace();const l=p?.geometry?.location;if(!p?.place_id||!l)return;const formattedAddress=p.formatted_address??p.name??"";setValue(formattedAddress);setPlace({placeId:p.place_id,displayName:p.name??formattedAddress,formattedAddress,lat:l.lat(),lng:l.lng()});trackDataLayer("airport_location_selected")}} options={{componentRestrictions:{country:"pk"},fields:["formatted_address","name","place_id","geometry"]}}>{input}</Autocomplete>:input}{status==="loading"&&<p className="mt-1 text-xs text-slate-500">Loading location search…</p>}{(status==="missing"||status==="error")&&<p className="mt-1 text-xs text-amber-700">Location search is temporarily unavailable. Please use WhatsApp.</p>}</div>}
function Engine(){const [tripType,setTripType]=useState<AirportTripType>("airportPickup");const [location,setLocation]=useState("");const [place,setPlace]=useState<AirportPlace>();const [date,setDate]=useState("");const [time,setTime]=useState("");const [dateOptions,setDateOptions]=useState<DateOption[]>([]);const [todayDate,setTodayDate]=useState("");const [earliestTodayMinutes,setEarliestTodayMinutes]=useState(0);const [passengers,setPassengers]=useState(1);const [luggage,setLuggage]=useState<LuggageLevel>("standard");const [quotes,setQuotes]=useState<Quote[]>([]);const [selected,setSelected]=useState<Quote>();const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState<BookingSuccess>();const quoteInProgress=useRef(false);const bookingInProgress=useRef(false);
 useEffect(()=>{const now=new Date();const today=localDateValue(now);const roundedMinutes=Math.ceil((now.getHours()*60+now.getMinutes())/15)*15;const options=Array.from({length:31},(_,index)=>{const optionDate=new Date(now.getFullYear(),now.getMonth(),now.getDate()+index);const prefix=index===0?"Today — ":index===1?"Tomorrow — ":"";return {value:localDateValue(optionDate),label:`${prefix}${optionDate.toLocaleDateString("en-GB",{weekday:"short",day:"numeric",month:"short"})}`,disabled:index===0&&roundedMinutes>=24*60}});const defaultDate=roundedMinutes>=24*60?options[1].value:today;const defaultMinutes=roundedMinutes%(24*60);setTodayDate(today);setEarliestTodayMinutes(roundedMinutes);setDateOptions(options);setDate(defaultDate);setTime(TIME_OPTIONS[defaultMinutes/15].value)},[]);
 const availableTimeOptions=date===todayDate?TIME_OPTIONS.filter(option=>option.minutes>=earliestTodayMinutes):TIME_OPTIONS;
 const changeDate=(nextDate:string)=>{setDate(nextDate);const nextOptions=nextDate===todayDate?TIME_OPTIONS.filter(option=>option.minutes>=earliestTodayMinutes):TIME_OPTIONS;if(!nextOptions.some(option=>option.value===time))setTime(nextOptions[0]?.value??"")};
 const calculate=async()=>{if(quoteInProgress.current)return;if(!place){setError("Please choose a location from the Google suggestions.");return}quoteInProgress.current=true;setLoading(true);setError("");setQuotes([]);try{const r=await fetch("/api/quotes/airport",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tripType,place,date,time,passengers,luggage})});const data=await r.json();if(!r.ok)throw new Error(data.error);setQuotes(data.quotes);trackDataLayer("airport_quote_generated",{trip_type:tripType,vehicle_count:data.quotes.length});}catch(e){setError(e instanceof Error?e.message:"Unable to calculate the price.")}finally{quoteInProgress.current=false;setLoading(false)}};
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected||bookingInProgress.current)return;bookingInProgress.current=true;const whatsappWindow=window.open("","_blank");setLoading(true);setError("");const form=new FormData(e.currentTarget);try{const r=await fetch("/api/bookings/airport",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({quoteId:selected.quoteId,vehicleId:selected.vehicle.id,...Object.fromEntries(form)})});const data=await r.json();if(!r.ok)throw new Error(data.error);const booking=data as BookingSuccess;const whatsappUrl=whatsappUrlForBooking(booking);setSuccess(booking);trackDataLayer("airport_booking_submitted",{booking_id:booking.bookingId,vehicle_id:selected.vehicle.id});if(whatsappWindow&&!whatsappWindow.closed){try{whatsappWindow.location.href=whatsappUrl}catch{}}}catch(e){if(whatsappWindow&&!whatsappWindow.closed)whatsappWindow.close();setError(e instanceof Error?e.message:"We could not create your booking request. Please try again or contact us on WhatsApp.")}finally{bookingInProgress.current=false;setLoading(false)}};
 const successWhatsApp=success?whatsappUrlForBooking(success):"";
 const locked=<div className="rounded-xl border border-slate-200 bg-slate-100 px-4 py-3 font-semibold text-[#0F2B46]">{ISLAMABAD_AIRPORT.displayName} <span className="block text-xs font-normal text-slate-500">Fixed airport location</span></div>;
 return <section id="airport-booking" className="bg-slate-50 px-4 py-10"><div className="mx-auto max-w-5xl rounded-3xl bg-white p-5 shadow-xl md:p-8"><div className="mb-6"><p className="font-bold uppercase tracking-widest text-[#5BAE4A]">Instant airport quote</p><h2 className="mt-2 text-3xl font-black text-[#0F2B46]">Calculate your transfer price</h2><p className="mt-2 text-slate-600">Fuel-inclusive pricing. Booking remains pending until availability is confirmed.</p></div>
 <div className="grid grid-cols-2 gap-2 rounded-xl bg-slate-100 p-1">{(["airportPickup","airportDropoff"] as const).map(t=><button key={t} type="button" onClick={()=>{setTripType(t);setQuotes([]);trackDataLayer("airport_trip_type_selected",{trip_type:t})}} className={`rounded-lg px-3 py-3 text-sm font-bold ${tripType===t?"bg-[#0F2B46] text-white":"text-slate-600"}`}>{t==="airportPickup"?"AIRPORT PICKUP":"AIRPORT DROP-OFF"}</button>)}</div>
 <div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold text-slate-700">FROM{tripType==="airportPickup"?locked:<LocationInput value={location} setValue={setLocation} setPlace={setPlace}/>}</label><label className="text-sm font-semibold text-slate-700">TO{tripType==="airportDropoff"?locked:<LocationInput value={location} setValue={setLocation} setPlace={setPlace}/>}</label><div><label htmlFor="airport-pickup-date" className="text-sm font-semibold text-slate-700">DATE</label><select id="airport-pickup-date" required value={date} onChange={e=>changeDate(e.currentTarget.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3"><option value="" disabled>Select a date</option>{dateOptions.map(option=><option key={option.value} value={option.value} disabled={option.disabled}>{option.label}</option>)}</select></div><div><label htmlFor="airport-pickup-time" className="text-sm font-semibold text-slate-700">PICKUP TIME</label><select id="airport-pickup-time" required value={time} onChange={e=>setTime(e.currentTarget.value)} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3"><option value="" disabled>Select a time</option>{availableTimeOptions.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></div><label className="text-sm font-semibold text-slate-700">PASSENGERS<select value={passengers} onChange={e=>setPassengers(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3">{[1,2,3,4,5,6,7,8].map(n=><option key={n}>{n}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">LUGGAGE<select value={luggage} onChange={e=>setLuggage(e.target.value as LuggageLevel)} className="mt-1 w-full rounded-xl border border-slate-300 px-4 py-3"><option value="light">Light</option><option value="standard">Standard</option><option value="heavy">Heavy</option></select></label></div>
 <button type="button" disabled={loading||!date||!time} onClick={calculate} className="mt-6 w-full rounded-xl bg-[#5BAE4A] px-5 py-4 font-bold text-white disabled:opacity-50">{loading?"Calculating route…":error&&quotes.length===0?"Try Again":"See vehicles & prices"}</button>{error&&<div role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error} <a className="font-bold underline" href={whatsapp} target="_blank">Get help on WhatsApp</a></div>}
 {quotes.length>0&&<div className="mt-8 grid gap-4 md:grid-cols-2">{quotes.map(q=><article key={`${q.quoteId}-${q.vehicle.id}`} className="rounded-2xl border border-slate-200 p-5"><h3 className="text-xl font-black text-[#0F2B46]">{q.vehicle.name}</h3><p className="mt-2 text-sm text-slate-600">{q.pickup.displayName} → {q.destination.displayName}</p><p className="mt-2 font-semibold">{q.distanceKm} km · Approx. {q.durationMinutes} min</p><p className="my-3 text-3xl font-black text-[#5BAE4A]">Rs {q.price.toLocaleString("en-PK")}</p><p className="text-sm text-slate-600">Up to {q.vehicle.passengers} passengers · {q.vehicle.luggage} luggage</p><p className="mt-2 text-sm text-slate-700">✓ {q.includedItems.join(" · ✓ ")}</p>{q.excludedItems.length>0&&<p className="mt-1 text-xs text-slate-500">Excluded: {q.excludedItems.join(", ")}</p>}<button onClick={()=>{setSelected(q);trackDataLayer("airport_vehicle_selected",{vehicle_id:q.vehicle.id})}} className="mt-4 w-full rounded-xl bg-[#0F2B46] py-3 font-bold text-white">Select {q.vehicle.name.replace("Toyota ","").replace("Honda ","")}</button></article>)}</div>}
 {selected&&!success&&<form onSubmit={submit} className="mt-8 rounded-2xl bg-slate-50 p-5"><h3 className="text-2xl font-black text-[#0F2B46]">Booking details</h3><p className="mb-4 text-sm text-slate-600">{selected.vehicle.name} · Rs {selected.price.toLocaleString("en-PK")} · price calculated</p><div className="grid gap-3 md:grid-cols-2"><input required name="name" placeholder="Full name" className="rounded-xl border p-3"/><input required name="phone" inputMode="tel" placeholder="Pakistani phone / WhatsApp" className="rounded-xl border p-3"/><input name="email" type="email" placeholder="Email (optional)" className="rounded-xl border p-3"/><input name="flightNumber" placeholder="Flight number (recommended)" className="rounded-xl border p-3"/><input name="airline" placeholder="Airline (optional)" className="rounded-xl border p-3"/><textarea name="notes" placeholder="Notes or special request" className="rounded-xl border p-3 md:col-span-2"/></div><button disabled={loading} className="mt-4 w-full rounded-xl bg-[#5BAE4A] py-4 font-bold text-white">{loading?"Creating request…":"Create booking request"}</button></form>}{success&&<div className="mt-8 rounded-2xl border border-green-200 bg-green-50 p-6 text-green-900"><p className="text-sm font-bold uppercase tracking-wider text-green-700">Booking request received</p><h3 className="mt-2 text-2xl font-black">Booking ID: {success.bookingId}</h3><p className="mt-2">Your vehicle availability will be confirmed by RentKA. Advance payment instructions will follow after availability is checked.</p><a href={successWhatsApp} target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-xl bg-[#25D366] px-5 py-3 font-bold text-white">Open WhatsApp</a></div>}
 <p className="mt-5 text-center text-sm text-slate-500">Need help? <a href={whatsapp} target="_blank" className="font-bold text-[#5BAE4A] underline">Book via WhatsApp</a></p></div></section>}
export default function AirportBookingEngine(){return <GooglePlacesProvider><Engine/></GooglePlacesProvider>}
