import { cloneElement, isValidElement, useId } from "react";
import type { ReactElement, ReactNode } from "react";
import styles from "./Controls.module.css";
export const input="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-[#5BAE4A] focus:ring-2 focus:ring-[#5BAE4A]/20";
export const primary="rounded-lg bg-[#0F2B46] px-3 py-2 text-sm font-semibold text-white hover:bg-[#173f64] disabled:opacity-40";
export const secondary="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-[#0F2B46] hover:bg-slate-50 disabled:opacity-40";
export function Card({title,children,action}:{title:string;children:ReactNode;action?:ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:p-6"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-bold text-[#0F2B46]">{title}</h2>{action}</div>{children}</section>}
export function Field({label,children,id}:{label:string;children:ReactElement<{id?:string}>;id?:string}){const generatedId=useId();const fieldId=id??generatedId;const displayLabel=label==="Target profit margin %"?"Target profit on cost %":label==="Minimum acceptable margin %"?"Minimum acceptable profit on cost %":label;return <div className="block text-sm font-medium text-slate-700"><label htmlFor={fieldId}>{displayLabel}</label>{isValidElement(children)?cloneElement(children,{id:fieldId}):children}</div>}
export function Text({value,onChange,type="text",placeholder="",id}:{value:string;onChange:(v:string)=>void;type?:string;placeholder?:string;id?:string}){const pickerClass=type==="date"||type==="time"?` ${styles.nativePickerBounds}`:"";return <input id={id} className={`${input}${pickerClass}`} type={type} value={value} placeholder={placeholder} onChange={(e)=>onChange(e.target.value)}/>}
export function Num({value,onChange,step=1,allowNegative=false,id}:{value:number;onChange:(v:number)=>void;step?:number;allowNegative?:boolean;id?:string}){return <input id={id} className={input} type="number" min={allowNegative?undefined:0} step={step} value={Number.isFinite(value)?value:0} onChange={(e)=>{const n=Number(e.target.value)||0;onChange(allowNegative?n:Math.max(0,n))}}/>}
export function Metric({label,value,tone="plain"}:{label:string;value:string;tone?:"plain"|"green"|"yellow"|"red"}){const colors={plain:"bg-slate-50",green:"bg-green-100 text-green-900",yellow:"bg-amber-100 text-amber-900",red:"bg-red-100 text-red-900"};return <div className={`rounded-xl p-3 ${colors[tone]}`}><div className="text-xs font-semibold uppercase tracking-wide opacity-70">{label}</div><div className="mt-1 text-lg font-bold">{value}</div></div>}
