"use client";
import { useEffect,useMemo,useState } from "react";
import { createState,newStop,STOP_TYPES,WAITING_DEFAULTS } from "../_lib/defaults";
import { calculatePricing,duration,money,percent } from "../_lib/pricing";
import { customerQuotation } from "../_lib/quotation";
import { persist,readSaved,removeSaved } from "../_lib/storage";
import type { CalculatorState,DistanceKey,PricingMode,SavedQuotation,TripPackage,TripType,VehicleCategory,VehiclePreset } from "../_lib/types";
import { Card,Field,input,Metric,Num,primary,secondary,Text } from "./Controls";
import { PlaceInput,googleAutocompleteConfigured } from "./PlaceInput";
import { stableRouteHash } from "../_lib/automatic-route";
import type { AutomaticRouteRequest,AutomaticRouteResponse } from "../_lib/automatic-route";
const distanceLabels:Record<DistanceKey,string>={pickupOperational:"Origin to customer pickup KM",customerTrip:"Customer trip KM",outstation:"Outstation KM",driverReturn:"Driver return KM",buffer:"Buffer KM"};
const expenseLabels={toll:"Toll",parking:"Parking",driverFood:"Driver food",driverAccommodation:"Driver accommodation",outstationSurcharge:"Outstation vehicle surcharge",miscellaneous:"Miscellaneous",operationalContingency:"Operational contingency",discount:"Discount"} as const;
const routeShape=(item:TripPackage)=>JSON.stringify({stops:item.stops.map((stop)=>({id:stop.id,name:stop.name,enabled:stop.enabled,place:stop.place})),distances:item.distances,drivingMinutes:item.drivingMinutes});
const outdate=(item:TripPackage):TripPackage=>item.automaticRoute?{...item,routeStatus:"outdated"}:item;
export default function PricingCalculator({serverRoutesConfigured}:{serverRoutesConfigured:boolean}){
 const [state,setState]=useState<CalculatorState>(()=>createState());const [saved,setSaved]=useState<SavedQuotation[]>([]);const [saveName,setSaveName]=useState("");
 useEffect(()=>{const timer=window.setTimeout(()=>setSaved(readSaved()),0);return()=>clearTimeout(timer)},[]);
 const pkg=state.packages.find((p)=>p.id===state.activePackageId)??state.packages[0];const vehicle=state.vehiclePresets.find((v)=>v.id===state.trip.vehiclePresetId)??state.vehiclePresets[0];
 const result=useMemo(()=>calculatePricing(state,pkg,vehicle),[state,pkg,vehicle]);const quote=useMemo(()=>customerQuotation(state,pkg,result),[state,pkg,result]);
 const setTrip=<K extends keyof CalculatorState["trip"]>(key:K,value:CalculatorState["trip"][K])=>setState((s)=>({...s,trip:{...s.trip,[key]:value}}));
 const setPkg=(next:TripPackage)=>setState((s)=>({...s,packages:s.packages.map((p)=>p.id===next.id?(routeShape(p)!==routeShape(next)&&next.routeStatus===p.routeStatus?outdate(next):next):p)}));
 const setVehicle=(next:VehiclePreset)=>setState((s)=>({...s,vehiclePresets:s.vehiclePresets.map((v)=>v.id===next.id?next:v)}));
 const selectVehicle=(id:string)=>{const next=state.vehiclePresets.find((v)=>v.id===id);if(next)setState((s)=>({...s,trip:{...s.trip,vehiclePresetId:id,vehicleName:next.name},packages:s.packages.map((item)=>item.id===pkg.id?{...item,expenses:{...item.expenses,driverFood:next.defaultDriverFood,driverAccommodation:next.defaultDriverAccommodation}}:item)}))};
 const copy=(text:string)=>navigator.clipboard.writeText(text);
 const setRouteTrip=<K extends keyof CalculatorState["trip"]>(key:K,value:CalculatorState["trip"][K])=>setState((s)=>({...s,trip:{...s.trip,[key]:value},packages:s.packages.map(outdate)}));
 const calculateRoute=async()=>{const enabledStops=pkg.stops.filter((stop)=>stop.enabled);if(!state.trip.originPlace||!state.trip.pickupPlace||!state.trip.finalDropPlace||enabledStops.some((stop)=>!stop.place)||(state.trip.includeDriverReturn&&!state.trip.driverReturnPlace)){setPkg({...pkg,routeStatus:"failed",routeError:"Resolve the origin, pickup, every enabled stop, final drop, and return destination before calculating."});return}const request:AutomaticRouteRequest={origin:state.trip.originPlace,pickup:state.trip.pickupPlace,stops:enabledStops.map((stop)=>stop.place!),finalDrop:state.trip.finalDropPlace,returnDestination:state.trip.driverReturnPlace,includeReturn:state.trip.includeDriverReturn,tripType:state.trip.tripType};const hash=stableRouteHash(request);if(pkg.automaticRoute?.requestHash===hash&&pkg.routeStatus==="calculated")return;setPkg({...pkg,routeStatus:"calculating",routeError:undefined});try{const response=await fetch("/api/admin/trip-route",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(request)});const data=await response.json() as {success:boolean;route?:AutomaticRouteResponse;error?:string};if(!response.ok||!data.success||!data.route)throw new Error(data.error||"Route calculation failed.");const route=data.route;setPkg({...pkg,distances:{...pkg.distances,...route.distances},drivingMinutes:Math.ceil(route.durationSeconds/60),routeStatus:"calculated",routeError:undefined,automaticRoute:{requestHash:route.requestHash,calculatedAt:new Date().toISOString(),distanceMeters:route.distanceMeters,durationSeconds:route.durationSeconds,legCount:route.legCount}})}catch(error){setPkg({...pkg,routeStatus:"failed",routeError:error instanceof Error?error.message:"Route calculation failed."})}};
 const internalText=`${pkg.name}\n${result.internalLines.map((l)=>`${l.label}: ${money(l.amount)}`).join("\n")}\nTotal internal cost: ${money(result.internalCost)}\nSuggested: ${money(result.suggestedPrice)}\nFinal: ${money(result.finalPrice)}\nProfit: ${money(result.grossProfit)} | Margin ${percent(result.margin)} | Markup ${percent(result.markup)}`;
 return <div className="min-h-screen bg-slate-100 py-8"><div className="mx-auto max-w-7xl space-y-5 px-4">
  <header className="rounded-2xl bg-[#0F2B46] p-6 text-white"><p className="text-sm font-bold uppercase tracking-widest text-[#8ed17e]">RentKA Internal</p><h1 className="mt-2 text-3xl font-bold">Central Trip Pricing Calculator</h1><p className="mt-2 text-slate-200">Manual route inputs · Stage 1</p></header>
  <Card title="1–6. Trip workflow"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
   <Field id="trip-type" label="Trip type"><select className={input} value={state.trip.tripType} onChange={(e)=>setRouteTrip("tripType",e.target.value as TripType)}>{["Within city","Outstation","One-way customer drop","Round trip","Custom multi-stop trip"].map((type)=><option key={type}>{type}</option>)}</select></Field>
   <Field id="trip-vehicle" label="Vehicle"><select className={input} value={vehicle.id} onChange={(e)=>selectVehicle(e.target.value)}>{state.vehiclePresets.map((v)=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field>
   <Field id="trip-office-vendor" label="Office / vendor"><select className={input} value={state.trip.originPresetId} onChange={(e)=>{const o=state.originPresets.find((x)=>x.id===e.target.value);if(o)setState((s)=>({...s,trip:{...s.trip,originPresetId:o.id,origin:o.name,originPlace:undefined},packages:s.packages.map(outdate)}))}}>{state.originPresets.map((o)=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field>
   <Field id="trip-origin" label="Origin (editable)"><PlaceInput value={state.trip.origin} place={state.trip.originPlace} onTextChange={(origin)=>setState((s)=>({...s,trip:{...s.trip,origin,originPlace:undefined},packages:s.packages.map(outdate)}))} onSelect={(originPlace)=>setState((s)=>({...s,trip:{...s.trip,origin:originPlace.formattedAddress,originPlace},packages:s.packages.map(outdate)}))}/></Field><Field id="trip-customer-pickup" label="Customer pickup"><PlaceInput value={state.trip.pickup} place={state.trip.pickupPlace} onTextChange={(pickup)=>setState((s)=>({...s,trip:{...s.trip,pickup,pickupPlace:undefined},packages:s.packages.map(outdate)}))} onSelect={(pickupPlace)=>setState((s)=>({...s,trip:{...s.trip,pickup:pickupPlace.formattedAddress,pickupPlace},packages:s.packages.map(outdate)}))} placeholder="e.g. G-13 Islamabad"/></Field>
   <Field id="trip-final-drop" label="Final customer drop"><PlaceInput value={state.trip.finalDrop} place={state.trip.finalDropPlace} onTextChange={(finalDrop)=>setState((s)=>({...s,trip:{...s.trip,finalDrop,finalDropPlace:undefined},packages:s.packages.map(outdate)}))} onSelect={(finalDropPlace)=>setState((s)=>({...s,trip:{...s.trip,finalDrop:finalDropPlace.formattedAddress,finalDropPlace},packages:s.packages.map(outdate)}))} placeholder="City or outstation destination"/></Field><Field id="trip-driver-return" label="Return destination"><PlaceInput value={state.trip.driverReturn} place={state.trip.driverReturnPlace} onTextChange={(driverReturn)=>setState((s)=>({...s,trip:{...s.trip,driverReturn,driverReturnPlace:undefined},packages:s.packages.map(outdate)}))} onSelect={(driverReturnPlace)=>setState((s)=>({...s,trip:{...s.trip,driverReturn:driverReturnPlace.formattedAddress,driverReturnPlace},packages:s.packages.map(outdate)}))}/></Field>
   <Field id="trip-date" label="Date"><Text type="date" value={state.trip.date} onChange={(v)=>setTrip("date",v)}/></Field><Field id="trip-pickup-time" label="Pickup time"><Text type="time" value={state.trip.pickupTime} onChange={(v)=>setTrip("pickupTime",v)}/></Field>
   <label className="flex items-center gap-2 pt-6 text-sm"><input id="trip-include-return" type="checkbox" checked={state.trip.includeDriverReturn} onChange={(e)=>setRouteTrip("includeDriverReturn",e.target.checked)}/> Include driver return journey</label>
  </div></Card>
  <Card title="Trip packages"><div className="flex flex-wrap gap-2">{state.packages.map((p)=><button key={p.id} className={p.id===pkg.id?primary:secondary} onClick={()=>setState({...state,activePackageId:p.id})}>{p.name}</button>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Package name"><Text value={pkg.name} onChange={(name)=>setPkg({...pkg,name})}/></Field><label className="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" checked={pkg.enabled} onChange={(e)=>setPkg({...pkg,enabled:e.target.checked})}/> Enable package</label></div></Card>
  <Card title="3. Trip locations and waiting time" action={<button className={primary} onClick={()=>setPkg({...pkg,stops:[...pkg.stops,newStop()]})}>Add location</button>}>
   <div className="space-y-3">{pkg.stops.map((stop,index)=><div key={stop.id} className="grid gap-2 rounded-xl border p-3 md:grid-cols-[auto_1fr_140px_130px_1fr_auto]">
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={stop.enabled} onChange={(e)=>setPkg({...pkg,stops:pkg.stops.map((s)=>s.id===stop.id?{...s,enabled:e.target.checked}:s)})}/>Use</label>
    <Field label={`Location ${index+1}`}><PlaceInput value={stop.name} place={stop.place} onTextChange={(name)=>setPkg({...pkg,stops:pkg.stops.map((s)=>s.id===stop.id?{...s,name,place:undefined}:s)})} onSelect={(place)=>setPkg({...pkg,stops:pkg.stops.map((s)=>s.id===stop.id?{...s,name:place.formattedAddress,place}:s)})}/></Field>
    <Field label="Stop type"><select className={input} value={stop.type} onChange={(e)=>setPkg({...pkg,stops:pkg.stops.map((s)=>s.id===stop.id?{...s,type:e.target.value as typeof stop.type,waitingMinutes:WAITING_DEFAULTS[e.target.value as typeof stop.type]}:s)})}>{STOP_TYPES.map((type)=><option key={type}>{type}</option>)}</select></Field>
    <Field label="Waiting minutes"><Num value={stop.waitingMinutes} onChange={(waitingMinutes)=>setPkg({...pkg,stops:pkg.stops.map((s)=>s.id===stop.id?{...s,waitingMinutes}:s)})}/></Field>
    <Field label="Notes"><Text value={stop.notes} onChange={(notes)=>setPkg({...pkg,stops:pkg.stops.map((s)=>s.id===stop.id?{...s,notes}:s)})}/></Field>
    <div className="flex items-end gap-1"><button className={secondary} disabled={index===0} onClick={()=>{const stops=[...pkg.stops];[stops[index-1],stops[index]]=[stops[index],stops[index-1]];setPkg({...pkg,stops})}}>↑</button><button className={secondary} disabled={index===pkg.stops.length-1} onClick={()=>{const stops=[...pkg.stops];[stops[index],stops[index+1]]=[stops[index+1],stops[index]];setPkg({...pkg,stops})}}>↓</button><button className="rounded-lg border border-red-200 px-3 py-2 text-sm text-red-700" onClick={()=>setPkg({...pkg,stops:pkg.stops.filter((s)=>s.id!==stop.id)})}>Remove</button></div>
   </div>)}</div>
  </Card>
  <Card title="4. Route distance" action={<button type="button" className={primary} disabled={!serverRoutesConfigured||pkg.routeStatus==="calculating"} onClick={()=>void calculateRoute()}>{pkg.routeStatus==="calculating"?"Calculating…":"Calculate Route"}</button>}><div className="mb-4 flex flex-wrap items-center gap-3 text-sm"><span className={`rounded-full px-3 py-1 font-semibold ${pkg.routeStatus==="calculated"?"bg-green-100 text-green-800":pkg.routeStatus==="failed"?"bg-red-100 text-red-800":pkg.routeStatus==="outdated"?"bg-amber-100 text-amber-800":"bg-slate-200 text-slate-700"}`}>{pkg.routeStatus.replaceAll("-"," ")}</span><span>{googleAutocompleteConfigured?"Places autocomplete ready.":"Browser key missing: autocomplete unavailable; manual locations remain enabled."}</span>{!serverRoutesConfigured&&<span className="text-amber-700">Server key missing: automatic route calculation is disabled.</span>}</div>{pkg.routeError&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{pkg.routeError}</div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{(Object.keys(distanceLabels) as DistanceKey[]).map((key)=><Field key={key} label={distanceLabels[key]}><Num step={0.1} value={pkg.distances[key]} onChange={(v)=>setPkg({...pkg,routeStatus:"manual",automaticRoute:undefined,routeError:undefined,distances:{...pkg.distances,[key]:v}})}/></Field>)}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Driving time (minutes)"><Num value={pkg.drivingMinutes} onChange={(drivingMinutes)=>setPkg({...pkg,routeStatus:"manual",automaticRoute:undefined,routeError:undefined,drivingMinutes})}/></Field><Field label="Time buffer (minutes)"><Num value={pkg.timeBufferMinutes} onChange={(timeBufferMinutes)=>setPkg({...pkg,timeBufferMinutes})}/></Field></div>{pkg.automaticRoute&&<p className="mt-3 text-xs text-slate-500">Automatic route: {(pkg.automaticRoute.distanceMeters/1000).toFixed(1)} km across {pkg.automaticRoute.legCount} legs, calculated {new Date(pkg.automaticRoute.calculatedAt).toLocaleString("en-PK")}.</p>}</Card>
  <Card title="7. Vehicle rent and extra hours"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Vehicle name"><Text value={vehicle.name} onChange={(name)=>{setVehicle({...vehicle,name});setTrip("vehicleName",name)}}/></Field><Field label="Vehicle category"><select className={input} value={vehicle.category} onChange={(e)=>setVehicle({...vehicle,category:e.target.value as VehicleCategory})}>{["Hatchback","Sedan","SUV","Van","Coaster or bus"].map((category)=><option key={category}>{category}</option>)}</select></Field>{(["includedHours","vendorRent","customerReferenceRent","fuelAverage","vendorExtraHour","customerExtraHour","defaultDriverFood","defaultDriverAccommodation"] as const).map((key)=><Field key={key} label={key.replace(/([A-Z])/g," $1")}><Num step={key==="fuelAverage"?0.1:1} value={vehicle[key]} onChange={(v)=>setVehicle({...vehicle,[key]:v})}/></Field>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Metric label="Vendor extra-hour cost" value={money(result.vendorExtraHourCost)}/><Metric label="Customer extra-hour reference" value={money(result.customerExtraHourReference)}/></div></Card>
  <Card title="6 and 8. Fuel, toll and other expenses"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Petrol price"><Num step={0.01} value={state.fuelPrice} onChange={(fuelPrice)=>setState({...state,fuelPrice})}/></Field><Field label="Fuel buffer %"><Num step={0.1} value={state.fuelBufferPercent} onChange={(fuelBufferPercent)=>setState({...state,fuelBufferPercent})}/></Field>{(Object.keys(expenseLabels) as Array<keyof typeof expenseLabels>).map((key)=><Field key={key} label={expenseLabels[key]}><Num value={pkg.expenses[key]} onChange={(v)=>setPkg({...pkg,expenses:{...pkg.expenses,[key]:v}})}/></Field>)}</div></Card>
  <Card title="5. Driving and booking time"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-7"><Metric label="Estimated driving time" value={duration(result.route.drivingMinutes)}/><Metric label="Total waiting time" value={duration(result.route.waitingMinutes)}/><Metric label="Time buffer" value={duration(result.route.bufferMinutes)}/><Metric label="Total booking time" value={duration(result.route.bookingMinutes)}/><Metric label="Included booking time" value={`${vehicle.includedHours}h`}/><Metric label="Extra time" value={duration(result.route.extraMinutes)}/><Metric label="Billable extra hours" value={`${result.route.extraHours}`}/></div></Card>
  <Card title="9. Internal cost"><div className="overflow-x-auto"><table className="w-full min-w-[500px] text-sm"><tbody>{result.internalLines.map((line)=><tr className="border-b" key={line.label}><td className="px-3 py-2">{line.label}</td><td className="px-3 py-2 text-right">{money(line.amount)}</td></tr>)}</tbody><tfoot><tr className="font-bold"><td className="px-3 py-3">Total internal cost</td><td className="px-3 py-3 text-right">{money(result.internalCost)}</td></tr></tfoot></table></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead><tr className="bg-slate-100"><th className="px-3 py-2 text-left">Fuel category</th><th className="px-3 py-2 text-right">KM</th><th className="px-3 py-2 text-right">Litres</th><th className="px-3 py-2 text-right">Raw cost</th></tr></thead><tbody>{result.fuelLines.map((line)=><tr className="border-b" key={line.key}><td className="px-3 py-2">{line.label}</td><td className="px-3 py-2 text-right">{line.kilometres.toFixed(1)}</td><td className="px-3 py-2 text-right">{line.litres.toFixed(2)}</td><td className="px-3 py-2 text-right">{money(line.cost)}</td></tr>)}</tbody></table></div><div className="mt-4 grid gap-3 sm:grid-cols-4"><Metric label="Total KM" value={`${result.route.totalKm.toFixed(1)} km`}/><Metric label="Total fuel litres" value={`${result.fuelLitres.toFixed(2)} L`}/><Metric label="Fuel buffer" value={money(result.fuelBufferAmount)}/><Metric label="Final fuel cost" value={money(result.fuelCost)}/></div>{result.warnings.length>0&&<div className="mt-4 space-y-2">{result.warnings.map((warning)=><div key={warning} className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-900">⚠ {warning}</div>)}</div>}</Card>
  <Card title="10. Pricing strategy"><div className="grid gap-4 md:grid-cols-3"><Field label="Pricing mode"><select className={input} value={pkg.pricing.mode} onChange={(e)=>setPkg({...pkg,pricing:{...pkg.pricing,mode:e.target.value as PricingMode}})}><option value="target">Target profit on cost</option><option value="fixed">Fixed profit</option><option value="manual">Manual quotation</option></select></Field><Field label="Target profit on cost %"><Num step={0.1} value={pkg.pricing.targetProfitPercent} onChange={(v)=>setPkg({...pkg,pricing:{...pkg.pricing,targetProfitPercent:v}})}/></Field><Field label="Minimum acceptable profit on cost %"><Num step={0.1} value={pkg.pricing.minimumProfitPercent} onChange={(v)=>setPkg({...pkg,pricing:{...pkg.pricing,minimumProfitPercent:v}})}/></Field><Field label="Fixed profit"><Num value={pkg.pricing.fixedProfit} onChange={(v)=>setPkg({...pkg,pricing:{...pkg.pricing,fixedProfit:v}})}/></Field><Field label="Manual quotation"><Num value={pkg.pricing.manualPrice} onChange={(v)=>setPkg({...pkg,pricing:{...pkg.pricing,manualPrice:v}})}/></Field><Field label="Market adjustment (+ / −)"><Num allowNegative value={pkg.pricing.marketAdjustment} onChange={(v)=>setPkg({...pkg,pricing:{...pkg.pricing,marketAdjustment:v}})}/></Field></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="Minimum price" value={money(result.minimumPrice)}/><Metric label="Suggested price" value={money(result.baseSuggestedPrice)}/><Metric label="Final price" value={money(result.finalPrice)} tone={result.indicator==="excellent"?"green":result.indicator==="acceptable"?"yellow":"red"}/><Metric label="Adjustment impact" value={money(result.adjustmentImpact)}/><Metric label="Gross profit" value={money(result.grossProfit)}/><Metric label="Gross margin / markup" value={`${percent(result.margin)} / ${percent(result.markup)}`}/></div><div className={`mt-4 rounded-xl p-3 font-bold ${result.indicator==="excellent"?"bg-green-100 text-green-900":result.indicator==="acceptable"?"bg-amber-100 text-amber-900":"bg-red-100 text-red-900"}`}>{result.indicator==="excellent"?"Excellent — at or above target":result.indicator==="acceptable"?"Acceptable — above minimum":"Below minimum acceptable profit"}</div></Card>
  <Card title="14. Customer quotation" action={<button className={primary} onClick={()=>copy(quote)}>Copy quotation</button>}><pre className="whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-6">{quote}</pre><button className={`${secondary} mt-3`} onClick={()=>copy(internalText)}>Copy internal costing</button></Card>
  <Card title="Save quotations"><div className="flex flex-col gap-2 sm:flex-row"><input className={input} value={saveName} onChange={(e)=>setSaveName(e.target.value)} placeholder="Quotation name"/><button className={primary} onClick={()=>{setSaved(persist(saveName,state));setSaveName("")}}>Save quotation</button><button className={secondary} onClick={()=>setState(createState())}>Reset</button></div><div className="mt-4 space-y-2">{saved.map((item)=><div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border p-3"><div><b>{item.name}</b><div className="text-xs text-slate-500">{new Date(item.savedAt).toLocaleString("en-PK")}</div></div><div className="flex gap-2"><button className={secondary} onClick={()=>setState(item.state)}>Load</button><button className={secondary} onClick={()=>{const duplicate={...item.state};setState(duplicate)}}>Duplicate</button><button className="rounded-lg border border-red-200 px-3 py-2 text-sm text-red-700" onClick={()=>setSaved(removeSaved(item.id))}>Delete</button></div></div>)}</div></Card>
 </div></div>
}
