"use client";
import { useEffect,useRef,useState } from "react";
import type { Dispatch,SetStateAction } from "react";
import { duration,money,percent } from "../_lib/pricing";
import { newStop } from "../_lib/defaults";
import type { CalculatorState,PricingResult,ResolvedPlace,TripPackage,TripType,VehiclePreset } from "../_lib/types";
import { Card,Field,Metric,Num,primary,secondary,Text } from "./Controls";
import { PlaceInput } from "./PlaceInput";

type Props={state:CalculatorState;setState:Dispatch<SetStateAction<CalculatorState>>;pkg:TripPackage;setPkg:(pkg:TripPackage)=>void;vehicle:VehiclePreset;setVehicle:(vehicle:VehiclePreset)=>void;selectVehicle:(id:string)=>void;result:PricingResult;recommendedPrice:number;quote:string;copied:boolean;copy:()=>void;calculateRoute:()=>void;serverRoutesConfigured:boolean};
const services:Array<{label:string,type:TripType}>=[{label:"Within City",type:"Within city"},{label:"Outstation",type:"Outstation"},{label:"One-Way Drop",type:"One-way customer drop"},{label:"Airport",type:"Within city"},{label:"Custom Trip",type:"Custom multi-stop trip"}];
export default function QuickQuote({state,setState,pkg,setPkg,vehicle,setVehicle,selectVehicle,result,recommendedPrice,quote,copied,copy,calculateRoute,serverRoutesConfigured}:Props){
 const [advanced,setAdvanced]=useState(false);const [service,setService]=useState("Within City");const [selectedDuration,setSelectedDuration]=useState("point");
 const lastAutomaticRoute=useRef("");const automaticRouteKey=[state.trip.originPlace?.placeId,state.trip.pickupPlace?.placeId,...pkg.stops.map(stop=>stop.place?.placeId),state.trip.destinationPlace?.placeId,state.trip.finalDropPlace?.placeId].join("|");
 useEffect(()=>{if(serverRoutesConfigured&&state.trip.originPlace&&state.trip.pickupPlace&&state.trip.destinationPlace&&state.trip.finalDropPlace&&pkg.stops.every(stop=>!stop.enabled||Boolean(stop.place))&&automaticRouteKey!==lastAutomaticRoute.current){lastAutomaticRoute.current=automaticRouteKey;calculateRoute()}},[automaticRouteKey,calculateRoute,pkg.stops,serverRoutesConfigured,state.trip.destinationPlace,state.trip.finalDropPlace,state.trip.originPlace,state.trip.pickupPlace]);
 const setTrip=<K extends keyof CalculatorState["trip"]>(key:K,value:CalculatorState["trip"][K])=>setState((current)=>({...current,trip:{...current.trip,[key]:value}}));
 const setPlace=(kind:"pickup"|"destination",place:ResolvedPlace)=>setState((current)=>{const round=current.trip.tripType==="Round trip";return{...current,trip:{...current.trip,[kind]:place.formattedAddress,[`${kind}Place`]:place,...(kind==="pickup"&&round?{finalDrop:place.formattedAddress,finalDropPlace:place}:{}),...(kind==="destination"&&!round?{finalDrop:place.formattedAddress,finalDropPlace:place}:{})}}});
 const route=[state.trip.pickup,...pkg.stops.filter(s=>s.enabled).map(s=>s.name),state.trip.destination,state.trip.finalDrop!==state.trip.destination?state.trip.finalDrop:""].filter(Boolean).join(" → ");
 const number=(state.trip.customerMobile??"").replace(/\D/g,"").replace(/^0/,"92");const whatsapp=`https://wa.me/${number}?text=${encodeURIComponent(quote)}`;
 const chooseDuration=(value:string)=>{setSelectedDuration(value);const minutes=value==="point"?0:value==="full"?720:Number(value)||0;if(minutes)setPkg({...pkg,timeBufferMinutes:Math.max(0,minutes-pkg.drivingMinutes-result.route.waitingMinutes)})};
 return <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1.15fr)_minmax(380px,.85fr)]"><div className="space-y-5">
  <Card title="Trip details"><div className="grid gap-4 sm:grid-cols-2"><Field label="Pickup"><PlaceInput value={state.trip.pickup} place={state.trip.pickupPlace} onTextChange={(pickup)=>setState(s=>({...s,trip:{...s.trip,pickup,pickupPlace:undefined}}))} onSelect={(place)=>setPlace("pickup",place)} placeholder="Search pickup"/></Field><Field label="Destination"><PlaceInput value={state.trip.destination??""} place={state.trip.destinationPlace} onTextChange={(destination)=>setState(s=>({...s,trip:{...s.trip,destination,destinationPlace:undefined,finalDrop:s.trip.tripType==="Round trip"?s.trip.finalDrop:destination,finalDropPlace:s.trip.tripType==="Round trip"?s.trip.finalDropPlace:undefined}}))} onSelect={(place)=>setPlace("destination",place)} placeholder="Search destination"/></Field></div><button className={`${secondary} mt-4`} onClick={()=>setPkg({...pkg,stops:[...pkg.stops,newStop()]})}>+ Add Stop</button>{pkg.stops.map((stop,index)=><div key={stop.id} className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><Field label={`Stop ${index+1}`}><PlaceInput value={stop.name} place={stop.place} onTextChange={(name)=>setPkg({...pkg,stops:pkg.stops.map(s=>s.id===stop.id?{...s,name,place:undefined}:s)})} onSelect={(place)=>setPkg({...pkg,stops:pkg.stops.map(s=>s.id===stop.id?{...s,name:place.formattedAddress,place}:s)})}/></Field><button className="self-end rounded-lg border border-red-200 px-3 py-2 text-sm text-red-700" onClick={()=>setPkg({...pkg,stops:pkg.stops.filter(s=>s.id!==stop.id)})}>Remove</button></div>)}<button className={`mt-4 w-full rounded-xl border-2 px-4 py-3 font-bold ${state.trip.tripType==="Round trip"?"border-[#5BAE4A] bg-green-50 text-green-900":"border-slate-300 text-[#0F2B46]"}`} onClick={()=>setState(s=>{const returning=s.trip.tripType!=="Round trip";return{...s,trip:{...s.trip,tripType:returning?"Round trip":"Outstation",finalDrop:returning?s.trip.pickup:(s.trip.destination??""),finalDropPlace:returning?s.trip.pickupPlace:s.trip.destinationPlace}}})}>↩ {state.trip.tripType==="Round trip"?"Returning to Pickup":"Return to Pickup"}</button></Card>
  <Card title="Vehicle"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{state.vehiclePresets.map(item=><button key={item.id} className={`rounded-xl border-2 px-3 py-3 text-left font-bold ${vehicle.id===item.id?"border-[#5BAE4A] bg-green-50 text-green-900":"border-slate-200 text-[#0F2B46]"}`} onClick={()=>selectVehicle(item.id)}>{item.name}</button>)}</div></Card>
  <Card title="Service & duration"><div className="flex flex-wrap gap-2">{services.map(item=><button key={item.label} className={service===item.label?primary:secondary} onClick={()=>{setService(item.label);setTrip("tripType",item.type)}}>{item.label}</button>)}</div><div className="mt-5 flex flex-wrap gap-2">{[{l:"Point-to-Point",v:"point"},{l:"5 Hours",v:"300"},{l:"10 Hours",v:"600"},{l:"12 Hours",v:"720"},{l:"Full Day",v:"full"},{l:"Custom",v:"custom"}].map(item=><button key={item.v} className={selectedDuration===item.v?primary:secondary} onClick={()=>chooseDuration(item.v)}>{item.l}</button>)}</div>{selectedDuration==="custom"&&<div className="mt-3"><Field label="Custom total minutes"><Num value={result.route.bookingMinutes} onChange={(minutes)=>setPkg({...pkg,timeBufferMinutes:Math.max(0,minutes-pkg.drivingMinutes-result.route.waitingMinutes)})}/></Field></div>}<div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Date"><Text type="date" value={state.trip.date} onChange={v=>setTrip("date",v)}/></Field><Field label="Time"><Text type="time" value={state.trip.pickupTime} onChange={v=>setTrip("pickupTime",v)}/></Field></div></Card>
  <Card title="Optional customer details"><div className="grid gap-4 sm:grid-cols-2"><Field label="Customer Name"><Text value={state.trip.customerName??""} onChange={v=>setTrip("customerName",v)}/></Field><Field label="Mobile Number"><Text value={state.trip.customerMobile??""} onChange={v=>setTrip("customerMobile",v)} placeholder="03xx xxxxxxx"/></Field></div></Card>
  <Card title="Advanced Options" action={<button className={secondary} onClick={()=>setAdvanced(!advanced)}>{advanced?"Hide":"Show"}</button>}>{advanced?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Office / operational origin"><PlaceInput value={state.trip.origin} place={state.trip.originPlace} onTextChange={origin=>setState(s=>({...s,trip:{...s.trip,origin,originPlace:undefined}}))} onSelect={originPlace=>setState(s=>({...s,trip:{...s.trip,origin:originPlace.formattedAddress,originPlace}}))}/></Field><Field label="Vendor Rent"><Num value={vehicle.vendorRent} onChange={vendorRent=>setVehicle({...vehicle,vendorRent})}/></Field><Field label="Fuel efficiency (km/L)"><Num step={0.1} value={vehicle.fuelAverage} onChange={fuelAverage=>setVehicle({...vehicle,fuelAverage})}/></Field><Field label="Fuel price"><Num step={0.01} value={state.fuelPrice} onChange={fuelPrice=>setState({...state,fuelPrice})}/></Field><Field label="Estimated Toll"><Num value={pkg.expenses.toll} onChange={toll=>setPkg({...pkg,expenses:{...pkg.expenses,toll}})}/></Field><Field label="Driver TA/DA"><Num value={pkg.expenses.driverFood+pkg.expenses.driverAccommodation} onChange={driverFood=>setPkg({...pkg,expenses:{...pkg.expenses,driverFood,driverAccommodation:0}})}/></Field><Field label="Other operational cost"><Num value={pkg.expenses.miscellaneous} onChange={miscellaneous=>setPkg({...pkg,expenses:{...pkg.expenses,miscellaneous}})}/></Field><Field label="Profit target %"><Num step={0.1} value={pkg.pricing.targetProfitPercent} onChange={targetProfitPercent=>setPkg({...pkg,pricing:{...pkg.pricing,targetProfitPercent}})}/></Field><Field label="Operational KM adjustment"><Num step={0.1} value={pkg.distances.buffer} onChange={buffer=>setPkg({...pkg,distances:{...pkg.distances,buffer}})}/></Field></div>:<p className="text-sm text-slate-500">Vendor rent, fuel, toll, waiting, TA/DA, operating costs, profit target and route settings.</p>}</Card>
 </div><div className="sticky top-4 space-y-5"><Card title="RECOMMENDED CUSTOMER PRICE"><div className="rounded-2xl bg-[#0F2B46] p-5 text-center text-white"><p className="text-sm font-bold uppercase tracking-widest text-green-300">Live quotation</p><p className="mt-2 text-4xl font-black">{money(recommendedPrice)}</p></div><div className="mt-4"><Field label={`Customer Quote (recommended ${money(recommendedPrice)})`}><Num value={result.finalPrice} onChange={manualPrice=>setPkg({...pkg,pricing:{...pkg.pricing,mode:"manual",manualPrice,marketAdjustment:0}})}/></Field></div><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Profit" value={money(result.grossProfit)} tone={result.grossProfit>=0?"green":"red"}/><Metric label="Margin" value={percent(result.margin)} tone={result.margin>=0?"green":"red"}/></div></Card>
  <Card title="Customer sees"><div className="space-y-2 text-sm"><p><b>Vehicle:</b> {state.trip.vehicleName}</p><p><b>Route:</b> {route||"Select pickup and destination"}</p><p><b>Duration:</b> {duration(result.route.bookingMinutes)}</p><p><b>Fuel:</b> Included</p><p><b>Toll:</b> Included</p><p className="text-lg"><b>Final Price:</b> {money(result.finalPrice)}</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><button className={primary} onClick={copy}>{copied?"Copied ✓":"Copy Customer Quote"}</button><a className={`${secondary} text-center`} href={whatsapp} target="_blank" rel="noreferrer">Send on WhatsApp</a></div></Card>
  <Card title="Internal Breakdown"><div className="grid grid-cols-2 gap-3"><Metric label="Vendor Rent" value={money(vehicle.vendorRent)}/><Metric label="Customer KM" value={`${(pkg.distances.customerTrip+pkg.distances.outstation).toFixed(1)} km`}/><Metric label="Operational KM" value={`${(pkg.distances.pickupOperational+pkg.distances.driverReturn+pkg.distances.buffer).toFixed(1)} km`}/><Metric label="Total KM" value={`${result.route.totalKm.toFixed(1)} km`}/><Metric label="Fuel Cost" value={money(result.fuelCost)}/><Metric label="Tolls" value={money(pkg.expenses.toll)}/><Metric label="TA/DA" value={money(pkg.expenses.driverFood+pkg.expenses.driverAccommodation)}/><Metric label="Overtime" value={money(result.vendorExtraHourCost)}/><Metric label="Other Cost" value={money(pkg.expenses.miscellaneous+pkg.expenses.operationalContingency)}/><Metric label="Profit" value={money(result.grossProfit)}/></div>{pkg.routeError&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{pkg.routeError}</p>}<button className={`${primary} mt-4 w-full`} disabled={!serverRoutesConfigured} onClick={calculateRoute}>{pkg.routeStatus==="calculating"?"Calculating route…":"Calculate / Refresh Route"}</button></Card></div></div>
}
