import "server-only";
import { FieldValue, type DocumentReference } from "firebase-admin/firestore";
import { getAdminDb } from "../firebaseAdmin";
import { DISPATCH_COLLECTIONS } from "../dispatch/collections";
import { SHARED_ADMIN_ACTOR } from "../dispatch/repository";
import { APPLICATION_COLLECTION, getPartnerApplication } from "./repository";
import { normalizeRegistration, normalizeVendorName } from "./normalization";
import { deterministicDriverId,deterministicVehicleId,deterministicVendorId,newDriverPayload,newVehiclePayload,newVendorPayload,resolveCandidate,resolveDispatchCategory } from "./onboarding-core";

export type DuplicateCandidates={vendors:string[];drivers:string[];vehicles:string[];vehicleMatches:Record<string,string[]>};
export type OnboardingDecisions={vendorId?:string;driverId?:string;vehicleIds?:Record<string,string>;vehicleCategories?:Record<string,string>};

export async function findDuplicateCandidates(applicationId:string):Promise<DuplicateCandidates>{
 const application=await getPartnerApplication(applicationId);if(!application)throw new Error("Application not found.");const db=getAdminDb();
 const[vendorPhones,driverPhones,vehicles,allVendors]=await Promise.all([db.collection(DISPATCH_COLLECTIONS.vendors).where("primaryPhoneNormalized","==",application.mobileNormalized).get(),db.collection(DISPATCH_COLLECTIONS.drivers).where("mobileNumberNormalized","==",application.mobileNormalized).get(),db.collection(DISPATCH_COLLECTIONS.vehicles).get(),db.collection(DISPATCH_COLLECTIONS.vendors).get()]);
 const applicationVendorName=normalizeVendorName(application.businessName||application.name),vendorNames=applicationVendorName?allVendors.docs.filter(d=>normalizeVendorName(d.data().name)===applicationVendorName):[],vehicleMatches=Object.fromEntries(application.vehicles.map(vehicle=>[vehicle.registrationNormalized,vehicles.docs.filter(d=>normalizeRegistration(d.data().registrationNumber)===vehicle.registrationNormalized).map(d=>d.id)]));
 return{vendors:[...new Set([...vendorPhones.docs,...vendorNames].map(d=>d.id))],drivers:driverPhones.docs.map(d=>d.id),vehicles:[...new Set(Object.values(vehicleMatches).flat())],vehicleMatches};
}

export async function approveAndOnboard(applicationId:string,decisions:OnboardingDecisions={}){
 const db=getAdminDb(),applicationRef=db.collection(APPLICATION_COLLECTION).doc(applicationId),application=await getPartnerApplication(applicationId);if(!application)throw new Error("Application not found.");if(application.onboarding)return application.onboarding;
 const duplicates=await findDuplicateCandidates(applicationId),selectedVendor=resolveCandidate("vendor",duplicates.vendors,decisions.vendorId);if(application.applicationType==="driver"&&!selectedVendor)throw new Error("Select the existing Dispatch vendor this driver belongs to before approval.");
 const vendorRef=db.collection(DISPATCH_COLLECTIONS.vendors).doc(selectedVendor||deterministicVendorId(application.mobileNormalized)),selectedDriver=application.applicationType!=="vendor"?resolveCandidate("driver",duplicates.drivers,decisions.driverId):undefined,driverRef=application.applicationType!=="vendor"?db.collection(DISPATCH_COLLECTIONS.drivers).doc(selectedDriver||deterministicDriverId(vendorRef.id,application.mobileNormalized)):null;
 const registrations=application.vehicles.map(v=>v.registrationNormalized);if(new Set(registrations).size!==registrations.length)throw new Error("The application contains duplicate vehicle registrations.");
 const vehicleRefs:DocumentReference[]=application.vehicles.map(v=>db.collection(DISPATCH_COLLECTIONS.vehicles).doc(resolveCandidate(`vehicle ${v.registrationNumber}`,duplicates.vehicleMatches[v.registrationNormalized]??[],decisions.vehicleIds?.[v.registrationNormalized])||deterministicVehicleId(v.registrationNormalized))),categories=application.vehicles.map(v=>resolveDispatchCategory(v.category,decisions.vehicleCategories?.[v.registrationNormalized]));
 return db.runTransaction(async tx=>{const snap=await tx.get(applicationRef);if(!snap.exists)throw new Error("Application not found.");const app=snap.data()!;if(app.onboarding)return app.onboarding;if(app.status==="rejected")throw new Error("A rejected application cannot be onboarded.");
  const refs:DocumentReference[]=[vendorRef,...(driverRef?[driverRef]:[]),...vehicleRefs],existing=await Promise.all(refs.map(ref=>tx.get(ref))),vendorExists=existing[0].exists,driverExists=driverRef?existing[1].exists:false,vehicleOffset=driverRef?2:1,now=FieldValue.serverTimestamp();
  if(selectedVendor&&!vendorExists)throw new Error("The selected Dispatch vendor no longer exists.");if(selectedDriver&&!duplicates.drivers.includes(selectedDriver))throw new Error("The selected Dispatch driver is not a valid duplicate candidate.");if(selectedDriver&&!driverExists)throw new Error("The selected Dispatch driver no longer exists.");
  if(driverExists&&existing[1].data()?.vendorId!==vendorRef.id)throw new Error("The selected existing driver belongs to a different vendor.");for(let i=0;i<vehicleRefs.length;i++){const vehicle=existing[vehicleOffset+i];if(decisions.vehicleIds?.[registrations[i]]&&!duplicates.vehicleMatches[registrations[i]]?.includes(decisions.vehicleIds[registrations[i]]))throw new Error(`The selected vehicle ${application.vehicles[i].registrationNumber} is not a valid registration match.`);if(decisions.vehicleIds?.[registrations[i]]&&!vehicle.exists)throw new Error(`The selected vehicle ${application.vehicles[i].registrationNumber} no longer exists.`);if(vehicle.exists&&normalizeRegistration(vehicle.data()?.registrationNumber)!==registrations[i])throw new Error(`The selected vehicle does not match registration ${application.vehicles[i].registrationNumber}.`);if(vehicle.exists&&vehicle.data()?.vendorId!==vendorRef.id)throw new Error(`The matching vehicle ${application.vehicles[i].registrationNumber} belongs to a different vendor.`)}
  if(vendorExists)tx.update(vendorRef,{active:true,updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR});else tx.create(vendorRef,newVendorPayload(application,now,SHARED_ADMIN_ACTOR));
  if(driverRef){if(driverExists)tx.update(driverRef,{active:true,status:"available",updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR});else tx.create(driverRef,newDriverPayload(application,vendorRef.id,now,SHARED_ADMIN_ACTOR))}
  vehicleRefs.forEach((ref,i)=>{if(existing[vehicleOffset+i].exists)tx.update(ref,{active:true,status:"available",updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR});else tx.create(ref,newVehiclePayload(application,application.vehicles[i],vendorRef.id,categories[i],now,SHARED_ADMIN_ACTOR))});
  const onboarding={vendorId:vendorRef.id,driverIds:driverRef?[driverRef.id]:[],vehicleIds:vehicleRefs.map(r=>r.id),onboardedAt:now,onboardedBy:SHARED_ADMIN_ACTOR};tx.update(applicationRef,{status:"approved",approvedAt:now,approvedBy:SHARED_ADMIN_ACTOR,duplicateCandidates:duplicates,onboarding,updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR});tx.create(applicationRef.collection("events").doc(),{type:"approved_and_onboarded",timestamp:now,actor:SHARED_ADMIN_ACTOR,metadata:{duplicates,vendor:{id:vendorRef.id,action:vendorExists?"linked_and_activated":"created_active"},driver:driverRef?{id:driverRef.id,action:driverExists?"linked_and_activated":"created_available"}:null,vehicles:vehicleRefs.map((r,i)=>({id:r.id,action:existing[vehicleOffset+i].exists?"linked_and_activated":"created_available"})),activation:"active_available_d3_rules_apply"}});return onboarding;
 });
}
