import { createHash } from "node:crypto";
import type { AuditActor } from "../dispatch/types.ts";
import type { PartnerApplication } from "./types.ts";

export const SAFE_DISPATCH_CATEGORIES=["Sedan","Hatchback","SUV","Mid SUV","Luxury","Van","Coaster"] as const;
const stableId=(kind:string,identity:string)=>`partner-${kind}-${createHash("sha256").update(identity).digest("hex").slice(0,24)}`;
export const deterministicVendorId=(phone:string)=>stableId("vendor",phone);
export const deterministicDriverId=(vendorId:string,phone:string)=>stableId("driver",`${vendorId}:${phone}`);
export const deterministicVehicleId=(registration:string)=>stableId("vehicle",registration);

export function resolveCandidate(label:string,candidates:string[],selected?:string){const unique=[...new Set(candidates)];if(unique.length>1&&!selected)throw new Error(`Multiple possible ${label} records exist. Select the correct record before approval.`);return selected||(unique.length===1?unique[0]:undefined)}
export function resolveDispatchCategory(category:string,selected?:string){if(category!=="Other")return category;if(!selected||!(SAFE_DISPATCH_CATEGORIES as readonly string[]).includes(selected))throw new Error("Vehicle category Other requires an explicit Dispatch category mapping before approval.");return selected}
export function newVendorPayload(app:PartnerApplication,now:unknown,actor:AuditActor){return{name:app.businessName||`${app.name} Partner`,primaryPhone:app.mobile,primaryPhoneNormalized:app.mobileNormalized,whatsappNumber:app.whatsapp,whatsappNumberNormalized:app.whatsappNormalized,zoneIds:app.zoneIds,priority:"normal" as const,active:true,notes:`Created from partner application ${app.applicationId}.`,createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor}}
export function newDriverPayload(app:PartnerApplication,vendorId:string,now:unknown,actor:AuditActor){return{name:app.name,mobileNumber:app.mobile,mobileNumberNormalized:app.mobileNormalized,whatsappNumber:app.whatsapp,whatsappNumberNormalized:app.whatsappNormalized,vendorId,zoneIds:app.zoneIds,priority:"normal" as const,status:"available" as const,active:true,notes:`Created from partner application ${app.applicationId}; CNIC/licence identifiers remain in onboarding only.`,documentation:{cnicVerificationState:"unknown" as const,licenceState:"unknown" as const,...(app.licenceExpiryDate?{licenceExpiry:app.licenceExpiryDate}:{})},createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor}}
export function newVehiclePayload(app:PartnerApplication,vehicle:PartnerApplication["vehicles"][number],vendorId:string,category:string,now:unknown,actor:AuditActor){return{vendorId,zoneIds:app.zoneIds,category,make:vehicle.make,model:vehicle.model,...(vehicle.modelYear?{modelYear:vehicle.modelYear}:{}),registrationNumber:vehicle.registrationNumber,status:"available" as const,active:true,notes:`Created from partner application ${app.applicationId}; documentation remains unverified until separately reviewed.`,documentation:{overallState:"unknown" as const,registrationState:"unknown" as const,tokenChallanState:"unknown" as const,permitState:"unknown" as const,fitnessState:"unknown" as const,insuranceState:"unknown" as const},createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor}}
