import { createHash } from "node:crypto";
import type { AuditActor } from "../dispatch/types.ts";
import type { PartnerApplication } from "./types.ts";
import type { DriverSupplyRelationship, SupplyClassification, VehicleControlRelationship } from "../dispatch/supply-classification.ts";

export const SAFE_DISPATCH_CATEGORIES=["Sedan","Hatchback","SUV","Mid SUV","Luxury","Van","Coaster"] as const;
export const SAFE_PARTNER_APPROVAL_DEFAULTS={supplyClassification:"unknown_needs_review",supplyRelationship:"unknown_needs_review",controlRelationship:"unknown_needs_review"} as const;
const stableId=(kind:string,identity:string)=>`partner-${kind}-${createHash("sha256").update(identity).digest("hex").slice(0,24)}`;
export const deterministicVendorId=(phone:string)=>stableId("vendor",phone);
export const deterministicDriverId=(vendorId:string,phone:string)=>stableId("driver",`${vendorId}:${phone}`);
export const deterministicVehicleId=(registration:string)=>stableId("vehicle",registration);

export function resolveCandidate(label:string,candidates:string[],selected?:string){const unique=[...new Set(candidates)];if(unique.length>1&&!selected)throw new Error(`Multiple possible ${label} records exist. Select the correct record before approval.`);return selected||(unique.length===1?unique[0]:undefined)}
export function resolveDispatchCategory(category:string,selected?:string){if(category!=="Other")return category;if(!selected||!(SAFE_DISPATCH_CATEGORIES as readonly string[]).includes(selected))throw new Error("Vehicle category Other requires an explicit Dispatch category mapping before approval.");return selected}
export function resolveApprovalClassification(applicationType:"driver"|"ownerDriver"|"vendor",selected?:SupplyClassification):SupplyClassification{const classification=selected||"unknown_needs_review";if(!(["vendor_managed","independent_owner_driver","unknown_needs_review"] as const).includes(classification as never))throw new Error("Choose a valid partner supply classification.");if(applicationType==="vendor"&&classification==="independent_owner_driver")throw new Error("A vendor / fleet application cannot be confirmed as an independent owner-driver.");if(applicationType==="ownerDriver"&&classification==="vendor_managed")throw new Error("An owner-driver application cannot be confirmed as vendor-managed.");if(applicationType==="driver"&&classification!=="unknown_needs_review")throw new Error("A legacy driver-only application must remain Needs Review.");return classification}
export function relationshipsForClassification(classification:SupplyClassification){const supplyRelationship:DriverSupplyRelationship=classification==="vendor_managed"?"vendor_managed":classification==="independent_owner_driver"?"independent_owner_driver":"unknown_needs_review",controlRelationship:VehicleControlRelationship=classification==="vendor_managed"?"vendor_managed":classification==="independent_owner_driver"?"independent_controlled":"unknown_needs_review";return{supplyRelationship,controlRelationship}}
export function newVendorPayload(app:PartnerApplication,now:unknown,actor:AuditActor,supplyClassification:SupplyClassification=SAFE_PARTNER_APPROVAL_DEFAULTS.supplyClassification){return{name:app.businessName||`${app.name} Partner`,primaryPhone:app.mobile,primaryPhoneNormalized:app.mobileNormalized,whatsappNumber:app.whatsapp,whatsappNumberNormalized:app.whatsappNormalized,zoneIds:app.zoneIds,priority:"normal" as const,supplyClassification,onboardingApplicationId:app.applicationId,active:true,notes:`Created from partner application ${app.applicationId}.`,createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor}}
export function newDriverPayload(app:PartnerApplication,vendorId:string,now:unknown,actor:AuditActor,supplyRelationship:DriverSupplyRelationship=SAFE_PARTNER_APPROVAL_DEFAULTS.supplyRelationship,driver:PartnerApplication["drivers"][number]|undefined=undefined){const source=driver||app;return{name:source.name,mobileNumber:source.mobile,mobileNumberNormalized:source.mobileNormalized,whatsappNumber:source.whatsapp,whatsappNumberNormalized:source.whatsappNormalized,vendorId,supplyRelationship,zoneIds:source.zoneIds,priority:"normal" as const,status:"available" as const,active:true,notes:`Created from partner application ${app.applicationId}; CNIC/licence identifiers remain in onboarding only.`,documentation:{cnicVerificationState:"unknown" as const,licenceState:"unknown" as const,...(source.licenceExpiryDate?{licenceExpiry:source.licenceExpiryDate}:{})},createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor}}
export function newVehiclePayload(app:PartnerApplication,vehicle:PartnerApplication["vehicles"][number],vendorId:string,category:string,now:unknown,actor:AuditActor,controlRelationship:VehicleControlRelationship=SAFE_PARTNER_APPROVAL_DEFAULTS.controlRelationship){return{vendorId,controlRelationship,zoneIds:app.zoneIds,category,make:vehicle.make,model:vehicle.model,...(vehicle.modelYear?{modelYear:vehicle.modelYear}:{}),registrationNumber:vehicle.registrationNumber,status:"available" as const,active:true,notes:`Created from partner application ${app.applicationId}; documentation remains unverified until separately reviewed.`,documentation:{overallState:"unknown" as const,registrationState:"unknown" as const,tokenChallanState:"unknown" as const,permitState:"unknown" as const,fitnessState:"unknown" as const,insuranceState:"unknown" as const},createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor}}
