import "server-only";
import { FieldValue, type DocumentReference } from "firebase-admin/firestore";
import { getAdminDb } from "../firebaseAdmin";
import { DISPATCH_COLLECTIONS } from "../dispatch/collections";
import { SHARED_ADMIN_ACTOR } from "../dispatch/repository";
import { LEGACY_DRIVER_RELATIONSHIP,LEGACY_SUPPLY_CLASSIFICATION,LEGACY_VEHICLE_CONTROL,assertDriverSupplyRelationship,assertVehicleControlRelationship,type SupplyClassification } from "../dispatch/supply-classification";
import { APPLICATION_COLLECTION, getPartnerApplication } from "./repository";
import { normalizeRegistration, normalizeVendorName } from "./normalization";
import { deterministicDriverId,deterministicVehicleId,deterministicVendorId,newDriverPayload,newVehiclePayload,newVendorPayload,relationshipsForClassification,resolveApprovalClassification,resolveCandidate,resolveDispatchCategory } from "./onboarding-core";

export type DuplicateCandidates={vendors:string[];drivers:string[];vehicles:string[];driverMatches:Record<string,string[]>;vehicleMatches:Record<string,string[]>};
export type OnboardingDecisions={supplyClassification?:SupplyClassification;vendorId?:string;driverId?:string;driverIds?:Record<string,string>;vehicleIds?:Record<string,string>;vehicleCategories?:Record<string,string>};

export async function findDuplicateCandidates(applicationId:string):Promise<DuplicateCandidates>{
 const application=await getPartnerApplication(applicationId);if(!application)throw new Error("Application not found.");const db=getAdminDb();
 const[vendorPhones,allDrivers,vehicles,allVendors]=await Promise.all([db.collection(DISPATCH_COLLECTIONS.vendors).where("primaryPhoneNormalized","==",application.mobileNormalized).get(),db.collection(DISPATCH_COLLECTIONS.drivers).get(),db.collection(DISPATCH_COLLECTIONS.vehicles).get(),db.collection(DISPATCH_COLLECTIONS.vendors).get()]);
 const applicationVendorName=normalizeVendorName(application.businessName||application.name),vendorNames=applicationVendorName?allVendors.docs.filter(d=>normalizeVendorName(d.data().name)===applicationVendorName):[],driverPhones=[application.mobileNormalized,...application.drivers.map(d=>d.mobileNormalized)],driverMatches=Object.fromEntries(driverPhones.map(phone=>[phone,allDrivers.docs.filter(d=>d.data().mobileNumberNormalized===phone).map(d=>d.id)])),vehicleMatches=Object.fromEntries(application.vehicles.map(vehicle=>[vehicle.registrationNormalized,vehicles.docs.filter(d=>normalizeRegistration(d.data().registrationNumber)===vehicle.registrationNormalized).map(d=>d.id)]));
 return{vendors:[...new Set([...vendorPhones.docs,...vendorNames].map(d=>d.id))],drivers:[...new Set(Object.values(driverMatches).flat())],vehicles:[...new Set(Object.values(vehicleMatches).flat())],driverMatches,vehicleMatches};
}

export async function approveAndOnboard(applicationId:string,decisions:OnboardingDecisions={}){
 const db=getAdminDb(),applicationRef=db.collection(APPLICATION_COLLECTION).doc(applicationId),application=await getPartnerApplication(applicationId);if(!application)throw new Error("Application not found.");if(application.onboarding)return application.onboarding;
 const classification=resolveApprovalClassification(application.applicationType,decisions.supplyClassification,application.drivingSetup),relationships=relationshipsForClassification(classification),duplicates=await findDuplicateCandidates(applicationId),selectedVendor=resolveCandidate("vendor",duplicates.vendors,decisions.vendorId);if(application.applicationType==="driver"&&!selectedVendor)throw new Error("Select the existing Dispatch vendor this driver belongs to before approval.");
 const vendorRef=db.collection(DISPATCH_COLLECTIONS.vendors).doc(selectedVendor||deterministicVendorId(application.mobileNormalized)),driverSources=application.applicationType==="vendor"&&application.drivingSetup!=="self"?application.drivers:[undefined],driverPhones=driverSources.map(driver=>driver?.mobileNormalized||application.mobileNormalized),selectedDrivers=driverSources.map((driver,index)=>resolveCandidate(`driver ${driver?.name||application.name}`,duplicates.driverMatches[driverPhones[index]]??[],driver?decisions.driverIds?.[driver.mobileNormalized]:decisions.driverId)),driverRefs=driverSources.map((driver,index)=>db.collection(DISPATCH_COLLECTIONS.drivers).doc(selectedDrivers[index]||deterministicDriverId(vendorRef.id,driverPhones[index])));
 const registrations=application.vehicles.map(v=>v.registrationNormalized);if(new Set(registrations).size!==registrations.length)throw new Error("The application contains duplicate vehicle registrations.");if(new Set(driverPhones).size!==driverPhones.length)throw new Error("The application contains duplicate driver mobile numbers.");
 const vehicleRefs:DocumentReference[]=application.vehicles.map(v=>db.collection(DISPATCH_COLLECTIONS.vehicles).doc(resolveCandidate(`vehicle ${v.registrationNumber}`,duplicates.vehicleMatches[v.registrationNormalized]??[],decisions.vehicleIds?.[v.registrationNormalized])||deterministicVehicleId(v.registrationNormalized))),categories=application.vehicles.map(v=>resolveDispatchCategory(v.category,decisions.vehicleCategories?.[v.registrationNormalized]));
 return db.runTransaction(async tx=>{const snap=await tx.get(applicationRef);if(!snap.exists)throw new Error("Application not found.");const app=snap.data()!;if(app.onboarding)return app.onboarding;if(app.status==="rejected")throw new Error("A rejected application cannot be onboarded.");
  const refs:DocumentReference[]=[vendorRef,...driverRefs,...vehicleRefs],existing=await Promise.all(refs.map(ref=>tx.get(ref))),vendorExists=existing[0].exists,driverOffset=1,vehicleOffset=1+driverRefs.length,now=FieldValue.serverTimestamp(),existingClassification=(existing[0].data()?.supplyClassification||LEGACY_SUPPLY_CLASSIFICATION) as SupplyClassification;
  if(selectedVendor&&!vendorExists)throw new Error("The selected Dispatch vendor no longer exists.");if(vendorExists&&classification!=="unknown_needs_review"&&existingClassification!==classification)throw new Error(`The selected vendor is classified ${existingClassification}; it cannot be onboarded as ${classification}.`);
  driverRefs.forEach((_,i)=>{const selected=selectedDrivers[i],driver=existing[driverOffset+i];if(selected&&!duplicates.driverMatches[driverPhones[i]]?.includes(selected))throw new Error(`The selected driver ${driverSources[i]?.name||application.name} is not a valid duplicate candidate.`);if(selected&&!driver.exists)throw new Error(`The selected driver ${driverSources[i]?.name||application.name} no longer exists.`);if(driver.exists&&driver.data()?.vendorId!==vendorRef.id)throw new Error(`The selected driver ${driverSources[i]?.name||application.name} belongs to a different vendor.`);if(driver.exists)assertDriverSupplyRelationship(existingClassification,(driver.data()?.supplyRelationship||LEGACY_DRIVER_RELATIONSHIP) as never)});
  for(let i=0;i<vehicleRefs.length;i++){const vehicle=existing[vehicleOffset+i];if(decisions.vehicleIds?.[registrations[i]]&&!duplicates.vehicleMatches[registrations[i]]?.includes(decisions.vehicleIds[registrations[i]]))throw new Error(`The selected vehicle ${application.vehicles[i].registrationNumber} is not a valid registration match.`);if(decisions.vehicleIds?.[registrations[i]]&&!vehicle.exists)throw new Error(`The selected vehicle ${application.vehicles[i].registrationNumber} no longer exists.`);if(vehicle.exists&&normalizeRegistration(vehicle.data()?.registrationNumber)!==registrations[i])throw new Error(`The selected vehicle does not match registration ${application.vehicles[i].registrationNumber}.`);if(vehicle.exists&&vehicle.data()?.vendorId!==vendorRef.id)throw new Error(`The matching vehicle ${application.vehicles[i].registrationNumber} belongs to a different vendor.`);if(vehicle.exists)assertVehicleControlRelationship(existingClassification,(vehicle.data()?.controlRelationship||LEGACY_VEHICLE_CONTROL) as never)}
  const designation=classification==="independent_owner_driver"&&driverRefs[0]?{independentOwnerDriverId:driverRefs[0].id}:{};if(vendorExists)tx.update(vendorRef,{active:true,...designation,updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR});else tx.create(vendorRef,{...newVendorPayload(application,now,SHARED_ADMIN_ACTOR,classification),...designation});
  driverRefs.forEach((ref,i)=>{if(existing[driverOffset+i].exists)tx.update(ref,{active:true,status:"available",supplyRelationship:relationships.supplyRelationship,updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR});else tx.create(ref,newDriverPayload(application,vendorRef.id,now,SHARED_ADMIN_ACTOR,relationships.supplyRelationship,driverSources[i]))});
  vehicleRefs.forEach((ref,i)=>{if(existing[vehicleOffset+i].exists)tx.update(ref,{active:true,status:"available",controlRelationship:relationships.controlRelationship,updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR});else tx.create(ref,newVehiclePayload(application,application.vehicles[i],vendorRef.id,categories[i],now,SHARED_ADMIN_ACTOR,relationships.controlRelationship))});
  const onboarding={vendorId:vendorRef.id,driverIds:driverRefs.map(r=>r.id),vehicleIds:vehicleRefs.map(r=>r.id),onboardedAt:now,onboardedBy:SHARED_ADMIN_ACTOR};tx.update(applicationRef,{status:"approved",approvedAt:now,approvedBy:SHARED_ADMIN_ACTOR,confirmedSupplyClassification:classification,duplicateCandidates:duplicates,onboarding,updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR});tx.create(applicationRef.collection("events").doc(),{type:"approved_and_onboarded",timestamp:now,actor:SHARED_ADMIN_ACTOR,metadata:{duplicates,supplyClassification:classification,vendor:{id:vendorRef.id,action:vendorExists?"linked_and_activated":"created_active"},drivers:driverRefs.map((r,i)=>({id:r.id,action:existing[driverOffset+i].exists?"linked_and_activated":"created_available"})),vehicles:vehicleRefs.map((r,i)=>({id:r.id,action:existing[vehicleOffset+i].exists?"linked_and_activated":"created_available"})),activation:"active_available_d3_rules_apply"}});return onboarding;
 });
}
