import "server-only";
import { randomUUID } from "node:crypto";
import { FieldValue } from "firebase-admin/firestore";
import { getAdminDb } from "../firebaseAdmin";
import { firestoreSafePayload } from "../dispatch/firestore-payload";
import { SHARED_ADMIN_ACTOR } from "../dispatch/repository";
import type { ApplicationStatus, DocumentReviewState, PartnerApplication } from "./types";
import { claimStagedDocuments } from "./documents";
import { writeAdminReplacementDocument } from "./documents";
import { applyDocumentReviewChanges,replacePartnerDocument,type DocumentOwnerExpectation,type DocumentReviewChange } from "./document-review-core";
import { resolveCurrentPartnerApplicationDocument } from "./document-retrieval-core";

export const APPLICATION_COLLECTION="partnerApplications";
const iso=(v:unknown)=>v&&typeof v==="object"&&"toDate" in v?(v as{toDate():Date}).toDate().toISOString():String(v??"");
const hydrateApplication=(data:FirebaseFirestore.DocumentData,id:string):PartnerApplication=>({...data,id,drivers:Array.isArray(data.drivers)?data.drivers:[],vehicles:Array.isArray(data.vehicles)?data.vehicles:[],documents:Array.isArray(data.documents)?data.documents:[],documentHistory:Array.isArray(data.documentHistory)?data.documentHistory:[],createdAt:iso(data.createdAt),updatedAt:iso(data.updatedAt)}) as PartnerApplication;
export async function createPartnerApplication(input:ReturnType<typeof import("./validation").validateSubmission>){const db=getAdminDb(),ref=db.collection(APPLICATION_COLLECTION).doc(randomUUID()),counter=db.collection("meta").doc("counters");return db.runTransaction(async tx=>{const count=await tx.get(counter);const seq=Number(count.data()?.partnerApplicationCounter??0)+1;if(!Number.isSafeInteger(seq))throw new Error("Application number is unavailable.");const applicationId=`RK-PA-${String(seq).padStart(4,"0")}`,allTokens=[...input.uploadTokens,...input.drivers.flatMap(d=>d.uploadTokens),...input.vehicles.flatMap(v=>v.uploadTokens)],documents=await claimStagedDocuments(tx,allTokens,ref.id),kinds=new Set(documents.map(d=>d.kind)),applicantDrives=input.applicationType!=="vendor"||input.drivingSetup==="self";if(applicantDrives&&!(["cnic_front","cnic_back","licence_front","licence_back"] as const).every(k=>kinds.has(k)))throw new Error("Upload both sides of your CNIC and driving licence.");const now=FieldValue.serverTimestamp(),publicActor={type:"public_applicant" as const};const drivers=input.drivers.map((d,index)=>{const ids=new Set(d.uploadTokens.map(t=>t.split(".")[0])),driverDocuments=documents.filter(doc=>ids.has(doc.id)),driverKinds=new Set(driverDocuments.map(doc=>doc.kind));if(!(["cnic_front","cnic_back","licence_front","licence_back"] as const).every(kind=>driverKinds.has(kind)))throw new Error(`Driver ${index+1} requires both sides of the CNIC and driving licence.`);return{...d,documents:driverDocuments,uploadTokens:undefined}});const vehicles=input.vehicles.map((v,index)=>{const ids=new Set(v.uploadTokens.map(t=>t.split(".")[0])),vehicleDocuments=documents.filter(d=>ids.has(d.id)),vehicleKinds=new Set(vehicleDocuments.map(d=>d.kind));if(!vehicleKinds.has("vehicle_registration"))throw new Error(`Vehicle ${index+1} requires its registration document.`);if(input.applicationType==="vendor"&&!vehicleKinds.has("vehicle_photo"))throw new Error(`Vehicle ${index+1} requires its vehicle photo.`);return{...v,documents:vehicleDocuments,uploadTokens:undefined}});const rootTokens=new Set(input.uploadTokens.map(t=>t.split(".")[0]));const application=firestoreSafePayload({...input,uploadTokens:undefined,drivers,vehicles,documents:documents.filter(d=>rootTokens.has(d.id)),applicationId,applicationType:input.applicationType,status:"new",consent:{accepted:true,textVersion:"2026-08-26",acceptedAt:new Date().toISOString()},createdAt:now,updatedAt:now,createdBy:publicActor,updatedBy:publicActor});tx.set(counter,{partnerApplicationCounter:seq,updatedAt:now},{merge:true});tx.create(ref,application);tx.create(ref.collection("events").doc(),{type:"application_submitted",timestamp:now,actor:publicActor,metadata:{submittedDriverCount:drivers.length,submittedVehicleCount:vehicles.length}});return{applicationId,id:ref.id}})}
export async function listPartnerApplications(){const snap=await getAdminDb().collection(APPLICATION_COLLECTION).orderBy("createdAt","desc").limit(300).get();return snap.docs.map(d=>hydrateApplication(d.data(),d.id))}
export async function getPartnerApplication(id:string){const doc=await getAdminDb().collection(APPLICATION_COLLECTION).doc(id).get();return doc.exists?hydrateApplication(doc.data()!,doc.id):null}
export async function listApplicationEvents(id:string){const snap=await getAdminDb().collection(APPLICATION_COLLECTION).doc(id).collection("events").orderBy("timestamp","desc").get();return snap.docs.map(d=>({...d.data(),id:d.id,timestamp:iso(d.data().timestamp)}) as {id:string;type:string;timestamp:string;metadata?:Record<string,unknown>})}
export async function changeApplicationStatus(id:string,status:ApplicationStatus,note?:string){const db=getAdminDb(),ref=db.collection(APPLICATION_COLLECTION).doc(id);await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new Error("Application not found.");const from=snap.data()?.status;if(from==="approved")throw new Error("An onboarded application cannot change status.");const now=FieldValue.serverTimestamp();tx.update(ref,firestoreSafePayload({status,statusNote:note,updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR}));tx.create(ref.collection("events").doc(),firestoreSafePayload({type:status==="rejected"?"application_rejected":"status_changed",timestamp:now,actor:SHARED_ADMIN_ACTOR,metadata:{from,to:status,note}}))})}
export async function reviewApplicationDocuments(id:string,changes:DocumentReviewChange[]){if(!changes.length)throw new Error("No document review changes.");const db=getAdminDb(),ref=db.collection(APPLICATION_COLLECTION).doc(id);await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new Error("Application not found.");const reviewedAt=new Date().toISOString(),updated=applyDocumentReviewChanges(snap.data() as PartnerApplication,changes,reviewedAt),now=FieldValue.serverTimestamp();tx.update(ref,firestoreSafePayload({...updated,updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR}));tx.create(ref.collection("events").doc(),firestoreSafePayload({type:changes.length===1?"document_reviewed":"document_reviews_saved",timestamp:now,actor:SHARED_ADMIN_ACTOR,metadata:{changes:changes.map(change=>({documentId:change.documentId,state:change.state,note:change.note}))}}))})}
export async function reviewApplicationDocument(id:string,documentId:string,state:DocumentReviewState,note?:string){return reviewApplicationDocuments(id,[{documentId,state,note}])}
export async function replaceApplicationDocument(id:string,documentId:string,file:File,reason:string|undefined,owner:DocumentOwnerExpectation){const db=getAdminDb(),ref=db.collection(APPLICATION_COLLECTION).doc(id),before=await ref.get();if(!before.exists)throw new Error("Application not found.");const initial=resolveCurrentPartnerApplicationDocument(before.data() as PartnerApplication,documentId);if(!initial)throw new Error("Document not found.");if(initial.ownerType!==owner.ownerType||initial.ownerIndex!==owner.ownerIndex)throw new Error("Document owner does not match.");const replacement=await writeAdminReplacementDocument(file,initial.document.kind);await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new Error("Application not found.");const application=snap.data() as PartnerApplication,replacedAt=new Date().toISOString(),updated=replacePartnerDocument(application,documentId,replacement.document,owner,{replacedAt,replacedBy:SHARED_ADMIN_ACTOR,reason}),now=FieldValue.serverTimestamp();tx.update(ref,firestoreSafePayload({...updated,updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR}));tx.create(ref.collection("events").doc(),firestoreSafePayload({type:"document_replaced",timestamp:now,actor:SHARED_ADMIN_ACTOR,metadata:{documentKind:replacement.document.kind,ownerType:owner.ownerType,ownerIndex:owner.ownerIndex,previousDocumentId:documentId,newDocumentId:replacement.document.id,reason}}))});return replacement.document.id}
