import "server-only";
import { randomUUID } from "node:crypto";
import { FieldValue } from "firebase-admin/firestore";
import { getAdminDb } from "../firebaseAdmin";
import { firestoreSafePayload } from "../dispatch/firestore-payload";
import { SHARED_ADMIN_ACTOR } from "../dispatch/repository";
import type { ApplicationStatus, DocumentReviewState, PartnerApplication } from "./types";
import { claimStagedDocuments } from "./documents";

export const APPLICATION_COLLECTION="partnerApplications";
const iso=(v:unknown)=>v&&typeof v==="object"&&"toDate" in v?(v as{toDate():Date}).toDate().toISOString():String(v??"");
const hydrateApplication=(data:FirebaseFirestore.DocumentData,id:string):PartnerApplication=>({...data,id,vehicles:Array.isArray(data.vehicles)?data.vehicles:[],documents:Array.isArray(data.documents)?data.documents:[],createdAt:iso(data.createdAt),updatedAt:iso(data.updatedAt)}) as PartnerApplication;
export async function createPartnerApplication(input:ReturnType<typeof import("./validation").validateSubmission>){const db=getAdminDb(),ref=db.collection(APPLICATION_COLLECTION).doc(randomUUID()),counter=db.collection("meta").doc("counters");return db.runTransaction(async tx=>{const count=await tx.get(counter);const seq=Number(count.data()?.partnerApplicationCounter??0)+1;if(!Number.isSafeInteger(seq))throw new Error("Application number is unavailable.");const applicationId=`RK-PA-${String(seq).padStart(4,"0")}`,allTokens=[...input.uploadTokens,...input.vehicles.flatMap(v=>v.uploadTokens)],documents=await claimStagedDocuments(tx,allTokens,ref.id),kinds=new Set(documents.map(d=>d.kind));if(input.applicationType!=="vendor"&&!(["cnic_front","cnic_back","licence_front","licence_back"] as const).every(k=>kinds.has(k)))throw new Error("Upload both sides of your CNIC and driving licence.");const now=FieldValue.serverTimestamp(),publicActor={type:"public_applicant" as const};const vehicles=input.vehicles.map((v,index)=>{const ids=new Set(v.uploadTokens.map(t=>t.split(".")[0])),vehicleDocuments=documents.filter(d=>ids.has(d.id)),vehicleKinds=new Set(vehicleDocuments.map(d=>d.kind));if(!vehicleKinds.has("vehicle_registration"))throw new Error(`Vehicle ${index+1} requires its registration document.`);if(input.applicationType==="vendor"&&!vehicleKinds.has("vehicle_photo"))throw new Error(`Vehicle ${index+1} requires its vehicle photo.`);return{...v,documents:vehicleDocuments,uploadTokens:undefined}});const rootTokens=new Set(input.uploadTokens.map(t=>t.split(".")[0]));const application=firestoreSafePayload({...input,uploadTokens:undefined,vehicles,documents:documents.filter(d=>rootTokens.has(d.id)),applicationId,applicationType:input.applicationType,status:"new",consent:{accepted:true,textVersion:"2026-08-26",acceptedAt:new Date().toISOString()},createdAt:now,updatedAt:now,createdBy:publicActor,updatedBy:publicActor});tx.set(counter,{partnerApplicationCounter:seq,updatedAt:now},{merge:true});tx.create(ref,application);tx.create(ref.collection("events").doc(),{type:"application_submitted",timestamp:now,actor:publicActor,metadata:{submittedVehicleCount:vehicles.length}});return{applicationId,id:ref.id}})}
export async function listPartnerApplications(){const snap=await getAdminDb().collection(APPLICATION_COLLECTION).orderBy("createdAt","desc").limit(300).get();return snap.docs.map(d=>hydrateApplication(d.data(),d.id))}
export async function getPartnerApplication(id:string){const doc=await getAdminDb().collection(APPLICATION_COLLECTION).doc(id).get();return doc.exists?hydrateApplication(doc.data()!,doc.id):null}
export async function listApplicationEvents(id:string){const snap=await getAdminDb().collection(APPLICATION_COLLECTION).doc(id).collection("events").orderBy("timestamp","desc").get();return snap.docs.map(d=>({...d.data(),id:d.id,timestamp:iso(d.data().timestamp)}) as {id:string;type:string;timestamp:string;metadata?:Record<string,unknown>})}
export async function changeApplicationStatus(id:string,status:ApplicationStatus,note?:string){const db=getAdminDb(),ref=db.collection(APPLICATION_COLLECTION).doc(id);await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new Error("Application not found.");const from=snap.data()?.status;if(from==="approved")throw new Error("An onboarded application cannot change status.");const now=FieldValue.serverTimestamp();tx.update(ref,firestoreSafePayload({status,statusNote:note,updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR}));tx.create(ref.collection("events").doc(),firestoreSafePayload({type:status==="rejected"?"application_rejected":"status_changed",timestamp:now,actor:SHARED_ADMIN_ACTOR,metadata:{from,to:status,note}}))})}
export async function reviewApplicationDocument(id:string,documentId:string,state:DocumentReviewState,note?:string){const db=getAdminDb(),ref=db.collection(APPLICATION_COLLECTION).doc(id);await db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw new Error("Application not found.");const data=snap.data() as PartnerApplication;let found=false;const update=(docs:PartnerApplication["documents"])=>(docs??[]).map(d=>{if(d.id!==documentId)return d;found=true;return{...d,reviewState:state,reviewedAt:new Date().toISOString(),reviewNote:note}});const documents=update(data.documents),vehicles=(data.vehicles??[]).map(v=>({...v,documents:update(v.documents)}));if(!found)throw new Error("Document not found.");const now=FieldValue.serverTimestamp();tx.update(ref,firestoreSafePayload({documents,vehicles,updatedAt:now,updatedBy:SHARED_ADMIN_ACTOR}));tx.create(ref.collection("events").doc(),firestoreSafePayload({type:"document_reviewed",timestamp:now,actor:SHARED_ADMIN_ACTOR,metadata:{documentId,state,note}}))})}
