import { normalizeDispatchPhone, parseZoneIds } from "../dispatch/validation.ts";
import { APPLICATION_TYPES, PARTNER_VEHICLE_CATEGORIES, type ApplicationType } from "./types.ts";
import { cleanText, normalizeCnic, normalizeLicence, normalizeRegistration } from "./normalization.ts";

export class PartnerValidationError extends Error { field: string; constructor(field: string, message: string) { super(message); this.field=field; } }
export const MAX_VENDOR_APPLICATION_VEHICLES=12;
export const MAX_VENDOR_APPLICATION_DRIVERS=20;
const required = (value: unknown, field: string, label: string, max=160) => { const v=cleanText(value,max); if(!v)throw new PartnerValidationError(field,`${label} is required.`); return v; };
export function parsePartnerDate(value:unknown,field="date",requiredValue=false){const entered=cleanText(value,10);if(!entered){if(requiredValue)throw new PartnerValidationError(field,"Enter a date as DD/MM/YYYY.");return undefined}const match=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(entered);if(!match)throw new PartnerValidationError(field,"Enter the date as DD/MM/YYYY, for example 25/08/2027.");const day=Number(match[1]),month=Number(match[2]),year=Number(match[3]),candidate=new Date(Date.UTC(year,month-1,day));if(year<1900||year>9999||candidate.getUTCFullYear()!==year||candidate.getUTCMonth()!==month-1||candidate.getUTCDate()!==day)throw new PartnerValidationError(field,"Enter a real calendar date in DD/MM/YYYY format.");return`${match[3]}-${match[2]}-${match[1]}`}
export function validateSubmission(body: Record<string, unknown>) {
  const applicationType=cleanText(body.applicationType) as ApplicationType;if(!APPLICATION_TYPES.includes(applicationType))throw new PartnerValidationError("applicationType","Choose a partner type.");const requestedDrivingSetup=cleanText(body.drivingSetup);if(requestedDrivingSetup&&requestedDrivingSetup!=="self"&&requestedDrivingSetup!=="vendor_driver")throw new PartnerValidationError("drivingSetup","Choose who will drive the vehicle.");const drivingSetup=applicationType==="ownerDriver"?"self":applicationType==="vendor"?(requestedDrivingSetup||"vendor_driver"):undefined;if(applicationType==="ownerDriver"&&requestedDrivingSetup&&requestedDrivingSetup!=="self")throw new PartnerValidationError("drivingSetup","Choose I will drive myself for an owner-driver application.");const applicantDrives=applicationType!=="vendor"||drivingSetup==="self";
  const name=required(body.name,"name",applicationType==="vendor"?"Contact person":"Full name");
  const mobile=required(body.mobile,"mobile","Mobile number",40),mobileNormalized=normalizeDispatchPhone(mobile);if(!mobileNormalized)throw new PartnerValidationError("mobile","Enter a valid mobile number.");
  const whatsapp=required(body.whatsapp,"whatsapp","WhatsApp number",40),whatsappNormalized=normalizeDispatchPhone(whatsapp);if(!whatsappNormalized)throw new PartnerValidationError("whatsapp","Enter a valid WhatsApp number.");
  if(body.consent!==true)throw new PartnerValidationError("consent","Consent is required before submission.");
  const rawZoneIds=Array.isArray(body.zoneIds)?body.zoneIds:[],otherZoneSelected=body.otherZoneSelected===true,otherOperationalArea=cleanText(body.otherOperationalArea,160);if(otherZoneSelected&&!otherOperationalArea)throw new PartnerValidationError("otherOperationalArea","Other city / operational area is required.");if(!rawZoneIds.length&&!otherZoneSelected)throw new PartnerValidationError("zoneIds","Select at least one valid operating zone.");const zoneIds=rawZoneIds.length?parseZoneIds(rawZoneIds):[];
  const cnicNumber=cleanText(body.cnicNumber,30),cnicNormalized=cnicNumber?normalizeCnic(cnicNumber):"";
  if(applicantDrives&&!cnicNormalized)throw new PartnerValidationError("cnicNumber","Enter a valid 13-digit CNIC number.");
  const licenceNumber=cleanText(body.licenceNumber,60),licenceNormalized=licenceNumber?normalizeLicence(licenceNumber):"";
  if(applicantDrives&&!licenceNormalized)throw new PartnerValidationError("licenceNumber","Driving licence number is required.");
  const licenceIssueDate=applicantDrives?parsePartnerDate(body.licenceIssueDate,"licenceIssueDate"):undefined,licenceExpiryDate=applicantDrives?parsePartnerDate(body.licenceExpiryDate,"licenceExpiryDate",true):undefined;if(licenceIssueDate&&licenceExpiryDate&&licenceExpiryDate<=licenceIssueDate)throw new PartnerValidationError("licenceExpiryDate","Licence expiry date must be after the issue date.");
  const availability=cleanText(body.availability,40);if(availability&&availability!=="available_after_approval")throw new PartnerValidationError("availability","Confirm when you are available for bookings.");const businessName=cleanText(body.businessName,160);if(applicationType==="vendor"&&!businessName)throw new PartnerValidationError("businessName","Business / vendor name is required.");
  const rawDrivers=Array.isArray(body.drivers)?body.drivers:[];if(applicationType==="vendor"&&drivingSetup==="vendor_driver"&&body.drivers!==undefined&&!rawDrivers.length)throw new PartnerValidationError("drivers","Add at least one driver to RentKA.");if(applicationType==="vendor"&&drivingSetup==="vendor_driver"&&rawDrivers.length>MAX_VENDOR_APPLICATION_DRIVERS)throw new PartnerValidationError("drivers",`Add no more than ${MAX_VENDOR_APPLICATION_DRIVERS} drivers in one application.`);
  const drivers=applicationType==="vendor"&&drivingSetup==="vendor_driver"?rawDrivers.map((raw,index)=>{const d=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>,prefix=`drivers.${index}.`,driverMobile=required(d.mobile,prefix+"mobile","Driver mobile number",40),driverMobileNormalized=normalizeDispatchPhone(driverMobile),driverWhatsapp=required(d.whatsapp,prefix+"whatsapp","Driver WhatsApp number",40),driverWhatsappNormalized=normalizeDispatchPhone(driverWhatsapp);if(!driverMobileNormalized)throw new PartnerValidationError(prefix+"mobile","Enter a valid driver mobile number.");if(!driverWhatsappNormalized)throw new PartnerValidationError(prefix+"whatsapp","Enter a valid driver WhatsApp number.");const driverCnic=required(d.cnicNumber,prefix+"cnicNumber","Driver CNIC number",30),driverCnicNormalized=normalizeCnic(driverCnic);if(!driverCnicNormalized)throw new PartnerValidationError(prefix+"cnicNumber","Enter a valid 13-digit driver CNIC number.");const driverLicence=required(d.licenceNumber,prefix+"licenceNumber","Driver licence number",60),driverLicenceNormalized=normalizeLicence(driverLicence),driverLicenceIssue=parsePartnerDate(d.licenceIssueDate,prefix+"licenceIssueDate"),driverLicenceExpiry=parsePartnerDate(d.licenceExpiryDate,prefix+"licenceExpiryDate",true)!;if(driverLicenceIssue&&driverLicenceExpiry<=driverLicenceIssue)throw new PartnerValidationError(prefix+"licenceExpiryDate","Driver licence expiry date must be after the issue date.");return{key:required(d.key,prefix+"key","Driver identity",80),name:required(d.name,prefix+"name","Driver name"),mobile:driverMobile,mobileNormalized:driverMobileNormalized,whatsapp:driverWhatsapp,whatsappNormalized:driverWhatsappNormalized,zoneIds:parseZoneIds(Array.isArray(d.zoneIds)?d.zoneIds:[]),cnicNumber:driverCnic,cnicNormalized:driverCnicNormalized,licenceNumber:driverLicence,licenceNormalized:driverLicenceNormalized,licenceIssueDate:driverLicenceIssue,licenceExpiryDate:driverLicenceExpiry,relationshipIntent:"vendor_managed" as const,uploadTokens:Array.isArray(d.uploadTokens)?d.uploadTokens.filter(x=>typeof x==="string"):[]}}):[];const seenDriverPhones=new Set<string>();drivers.forEach((driver,index)=>{if(seenDriverPhones.has(driver.mobileNormalized))throw new PartnerValidationError(`drivers.${index}.mobile`,"Each submitted driver must have a unique mobile number.");seenDriverPhones.add(driver.mobileNormalized)});
  const rawVehicles=Array.isArray(body.vehicles)?body.vehicles:[];if((applicationType==="ownerDriver"||applicationType==="vendor")&&!rawVehicles.length)throw new PartnerValidationError("vehicles","Add at least one vehicle to RentKA.");if(applicationType==="vendor"&&rawVehicles.length>MAX_VENDOR_APPLICATION_VEHICLES)throw new PartnerValidationError("vehicles",`Add no more than ${MAX_VENDOR_APPLICATION_VEHICLES} vehicles in one application.`);
  const vehicles=rawVehicles.map((raw,index)=>{const v=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>,category=required(v.category,`vehicles.${index}.category`,"Category",80);if(!PARTNER_VEHICLE_CATEGORIES.includes(category as typeof PARTNER_VEHICLE_CATEGORIES[number]))throw new PartnerValidationError(`vehicles.${index}.category`,"Choose a valid vehicle category.");const registrationNumber=required(v.registrationNumber,`vehicles.${index}.registrationNumber`,"Registration number",40),modelYear=v.modelYear?Number(v.modelYear):undefined;if(modelYear!==undefined&&(!Number.isInteger(modelYear)||modelYear<1950||modelYear>new Date().getFullYear()+1))throw new PartnerValidationError(`vehicles.${index}.modelYear`,"Enter a valid model year.");if(applicationType==="vendor"&&modelYear===undefined)throw new PartnerValidationError(`vehicles.${index}.modelYear`,"Model year is required.");return{make:required(v.make,`vehicles.${index}.make`,"Make",80),model:required(v.model,`vehicles.${index}.model`,"Model",100),modelYear,registrationNumber,registrationNormalized:normalizeRegistration(registrationNumber),category,ownershipRelationship:cleanText(v.ownershipRelationship,100)||undefined,uploadTokens:Array.isArray(v.uploadTokens)?v.uploadTokens.filter(x=>typeof x==="string"):[]}});const seen=new Set<string>();vehicles.forEach((vehicle,index)=>{if(seen.has(vehicle.registrationNormalized))throw new PartnerValidationError(`vehicles.${index}.registrationNumber`,"Each submitted vehicle must have a unique registration number.");seen.add(vehicle.registrationNormalized)});
  return {applicationType,drivingSetup,name,businessName:businessName||undefined,mobile,mobileNormalized,whatsapp,whatsappNormalized,zoneIds,...(otherZoneSelected?{otherOperationalArea}:{}),address:cleanText(body.address,300)||undefined,cnicNumber:cnicNumber||undefined,cnicNormalized:cnicNormalized||undefined,licenceNumber:licenceNumber||undefined,licenceNormalized:licenceNormalized||undefined,licenceIssueDate,licenceExpiryDate,availability:availability==="available_after_approval"?availability:undefined,numberOfVehicles:body.numberOfVehicles?Number(body.numberOfVehicles):undefined,approximateDrivers:body.approximateDrivers?Number(body.approximateDrivers):undefined,businessInfo:cleanText(body.businessInfo,500)||undefined,notes:cleanText(body.notes,2000)||undefined,extractionReviewed:body.extractionReviewed===true,drivers,vehicles,uploadTokens:Array.isArray(body.uploadTokens)?body.uploadTokens.filter(x=>typeof x==="string"):[]};
}
