import { normalizeDispatchPhone, parseZoneIds } from "../dispatch/validation.ts";
import { APPLICATION_TYPES, PARTNER_VEHICLE_CATEGORIES, type ApplicationType } from "./types.ts";
import { cleanText, normalizeCnic, normalizeLicence, normalizeRegistration } from "./normalization.ts";

export class PartnerValidationError extends Error { field: string; constructor(field: string, message: string) { super(message); this.field=field; } }
export const MAX_VENDOR_APPLICATION_VEHICLES=12;
const required = (value: unknown, field: string, label: string, max=160) => { const v=cleanText(value,max); if(!v)throw new PartnerValidationError(field,`${label} is required.`); return v; };
export function parsePartnerDate(value:unknown,field="date",requiredValue=false){const entered=cleanText(value,10);if(!entered){if(requiredValue)throw new PartnerValidationError(field,"Enter a date as DD/MM/YYYY.");return undefined}const match=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(entered);if(!match)throw new PartnerValidationError(field,"Enter the date as DD/MM/YYYY, for example 25/08/2027.");const day=Number(match[1]),month=Number(match[2]),year=Number(match[3]),candidate=new Date(Date.UTC(year,month-1,day));if(year<1900||year>9999||candidate.getUTCFullYear()!==year||candidate.getUTCMonth()!==month-1||candidate.getUTCDate()!==day)throw new PartnerValidationError(field,"Enter a real calendar date in DD/MM/YYYY format.");return`${match[3]}-${match[2]}-${match[1]}`}
export function validateSubmission(body: Record<string, unknown>) {
  const applicationType=cleanText(body.applicationType) as ApplicationType;if(!APPLICATION_TYPES.includes(applicationType))throw new PartnerValidationError("applicationType","Choose a partner type.");
  const name=required(body.name,"name",applicationType==="vendor"?"Contact person":"Full name");
  const mobile=required(body.mobile,"mobile","Mobile number",40),mobileNormalized=normalizeDispatchPhone(mobile);if(!mobileNormalized)throw new PartnerValidationError("mobile","Enter a valid mobile number.");
  const whatsapp=required(body.whatsapp,"whatsapp","WhatsApp number",40),whatsappNormalized=normalizeDispatchPhone(whatsapp);if(!whatsappNormalized)throw new PartnerValidationError("whatsapp","Enter a valid WhatsApp number.");
  if(body.consent!==true)throw new PartnerValidationError("consent","Consent is required before submission.");
  const zoneIds=parseZoneIds(Array.isArray(body.zoneIds)?body.zoneIds:[]);
  const cnicNumber=cleanText(body.cnicNumber,30),cnicNormalized=cnicNumber?normalizeCnic(cnicNumber):"";
  if(applicationType!=="vendor"&&!cnicNormalized)throw new PartnerValidationError("cnicNumber","Enter a valid 13-digit CNIC number.");
  const licenceNumber=cleanText(body.licenceNumber,60),licenceNormalized=licenceNumber?normalizeLicence(licenceNumber):"";
  if(applicationType!=="vendor"&&!licenceNormalized)throw new PartnerValidationError("licenceNumber","Driving licence number is required.");
  const licenceIssueDate=applicationType!=="vendor"?parsePartnerDate(body.licenceIssueDate,"licenceIssueDate"):undefined,licenceExpiryDate=applicationType!=="vendor"?parsePartnerDate(body.licenceExpiryDate,"licenceExpiryDate",true):undefined;if(licenceIssueDate&&licenceExpiryDate&&licenceExpiryDate<=licenceIssueDate)throw new PartnerValidationError("licenceExpiryDate","Licence expiry date must be after the issue date.");
  const businessName=cleanText(body.businessName,160);if(applicationType==="vendor"&&!businessName)throw new PartnerValidationError("businessName","Business / vendor name is required.");
  const rawVehicles=Array.isArray(body.vehicles)?body.vehicles:[];if((applicationType==="ownerDriver"||applicationType==="vendor")&&!rawVehicles.length)throw new PartnerValidationError("vehicles","Add at least one vehicle to RentKA.");if(applicationType==="vendor"&&rawVehicles.length>MAX_VENDOR_APPLICATION_VEHICLES)throw new PartnerValidationError("vehicles",`Add no more than ${MAX_VENDOR_APPLICATION_VEHICLES} vehicles in one application.`);
  const vehicles=rawVehicles.map((raw,index)=>{const v=(raw&&typeof raw==="object"?raw:{}) as Record<string,unknown>,category=required(v.category,`vehicles.${index}.category`,"Category",80);if(!PARTNER_VEHICLE_CATEGORIES.includes(category as typeof PARTNER_VEHICLE_CATEGORIES[number]))throw new PartnerValidationError(`vehicles.${index}.category`,"Choose a valid vehicle category.");const registrationNumber=required(v.registrationNumber,`vehicles.${index}.registrationNumber`,"Registration number",40),modelYear=v.modelYear?Number(v.modelYear):undefined;if(modelYear!==undefined&&(!Number.isInteger(modelYear)||modelYear<1950||modelYear>new Date().getFullYear()+1))throw new PartnerValidationError(`vehicles.${index}.modelYear`,"Enter a valid model year.");if(applicationType==="vendor"&&modelYear===undefined)throw new PartnerValidationError(`vehicles.${index}.modelYear`,"Model year is required.");return{make:required(v.make,`vehicles.${index}.make`,"Make",80),model:required(v.model,`vehicles.${index}.model`,"Model",100),modelYear,registrationNumber,registrationNormalized:normalizeRegistration(registrationNumber),category,ownershipRelationship:cleanText(v.ownershipRelationship,100)||undefined,uploadTokens:Array.isArray(v.uploadTokens)?v.uploadTokens.filter(x=>typeof x==="string"):[]}});const seen=new Set<string>();vehicles.forEach((vehicle,index)=>{if(seen.has(vehicle.registrationNormalized))throw new PartnerValidationError(`vehicles.${index}.registrationNumber`,"Each submitted vehicle must have a unique registration number.");seen.add(vehicle.registrationNormalized)});
  return {applicationType,name,businessName:businessName||undefined,mobile,mobileNormalized,whatsapp,whatsappNormalized,zoneIds,address:cleanText(body.address,300)||undefined,cnicNumber:cnicNumber||undefined,cnicNormalized:cnicNormalized||undefined,licenceNumber:licenceNumber||undefined,licenceNormalized:licenceNormalized||undefined,licenceIssueDate,licenceExpiryDate,numberOfVehicles:body.numberOfVehicles?Number(body.numberOfVehicles):undefined,approximateDrivers:body.approximateDrivers?Number(body.approximateDrivers):undefined,businessInfo:cleanText(body.businessInfo,500)||undefined,notes:cleanText(body.notes,2000)||undefined,extractionReviewed:body.extractionReviewed===true,vehicles,uploadTokens:Array.isArray(body.uploadTokens)?body.uploadTokens.filter(x=>typeof x==="string"):[]};
}
