import type { ManualServiceType } from "./booking-types.ts";
export type OperationalResponsibilityMode="unspecified"|"customer"|"rentka"|"included"|"not_applicable";
export type AllowanceResponsibility={mode:"customer"|"allowance"|"custom"|"unspecified";amountMinor?:number;unit?:"per_day";note?:string};
export type ExtraHourResponsibility={mode:"rate"|"custom"|"unspecified";amountMinor?:number;unit?:"per_hour";note?:string};
export type BookingResponsibilities={fuel:OperationalResponsibilityMode;toll:OperationalResponsibilityMode;parking:OperationalResponsibilityMode;driverFoodAccommodation:AllowanceResponsibility|OperationalResponsibilityMode;extraHour?:ExtraHourResponsibility;extraHourRateMinor?:number};

export const RESPONSIBILITY_MODES=["unspecified","customer","rentka","included","not_applicable"] as const;
export function responsibilityDefaults(serviceType:string):BookingResponsibilities{const bachat=serviceType==="with_driver"||serviceType==="outstation";return{fuel:bachat?"customer":"unspecified",toll:bachat?"customer":"unspecified",parking:bachat?"customer":"unspecified",driverFoodAccommodation:bachat?{mode:"customer"}:{mode:"unspecified"},extraHour:{mode:"unspecified"}}}
const clean=(value:unknown)=>typeof value==="string"?value.trim():"";
const mode=(value:unknown,label:string):OperationalResponsibilityMode=>{const entered=clean(value) as OperationalResponsibilityMode;if(!RESPONSIBILITY_MODES.includes(entered))throw new Error(`Select a valid ${label} responsibility.`);return entered};
const minor=(value:string,label:string)=>{if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error(`${label} must be a valid amount.`);const result=Math.round(Number(value)*100);if(!Number.isSafeInteger(result)||result<0)throw new Error(`${label} must be a valid amount.`);return result};
export function parseBookingResponsibilities(form:FormData,serviceType:ManualServiceType|string):BookingResponsibilities{const defaults=responsibilityDefaults(serviceType),fuel=clean(form.get("fuel"))?mode(form.get("fuel"),"fuel"):defaults.fuel,toll=clean(form.get("toll"))?mode(form.get("toll"),"toll"):defaults.toll,parking=clean(form.get("parking"))?mode(form.get("parking"),"parking"):defaults.parking,foodMode=clean(form.get("driverFoodMode"))||((defaults.driverFoodAccommodation as AllowanceResponsibility).mode),foodAmount=clean(form.get("driverFoodAmount")),foodNote=clean(form.get("driverFoodNote")),extraHourRate=clean(form.get("extraHourRate")),extraHourNote=clean(form.get("extraHourNote"));let driverFoodAccommodation:AllowanceResponsibility;if(foodMode==="customer"||foodMode==="unspecified")driverFoodAccommodation={mode:foodMode};else if(foodMode==="allowance"){if(!foodAmount)throw new Error("Enter the driver food/TA-DA allowance amount.");driverFoodAccommodation={mode:"allowance",amountMinor:minor(foodAmount,"Driver allowance"),unit:"per_day"}}else if(foodMode==="custom"){if(!foodNote)throw new Error("Enter the custom driver food/accommodation arrangement.");driverFoodAccommodation={mode:"custom",...(foodAmount?{amountMinor:minor(foodAmount,"Custom driver allowance"),unit:"per_day" as const}:{}),note:foodNote}}else throw new Error("Select a valid driver food/accommodation responsibility.");return{fuel,toll,parking,driverFoodAccommodation,extraHour:extraHourRate?{mode:"rate",amountMinor:minor(extraHourRate,"Extra-hour rate"),unit:"per_hour"}:extraHourNote?{mode:"custom",note:extraHourNote}:{mode:"unspecified"}}}
