import type { MoneySnapshot, OperationalEvent, PaymentStatus, PayoutStatus, ReadinessStatus } from "./booking-types";
import type { AuditActor } from "./types";

export const sharedActor:AuditActor={type:"shared_admin_session"};
export const manualBookingId=(bookingCode:string,sequence:number)=>`RK-${bookingCode}-${sequence}`;
export function paymentStatus(required:number,received:number,overridden=false):PaymentStatus{if(overridden)return"waived_or_credit";if(required===0)return"sufficient";if(received<=0)return"awaiting";return received>=required?"sufficient":"partial"}
export function moneySnapshot(total:number,required:number,received=0,overridden=false):MoneySnapshot{return discountedMoneySnapshot(total,0,required,received,overridden)}
export function discountedMoneySnapshot(original:number,discount:number,required:number,received=0,overridden=false):MoneySnapshot{assertMinor(original,"Original customer sale");assertMinor(discount,"Customer discount",{allowZero:true});if(discount>original)throw new Error("Customer discount cannot exceed the original customer sale.");assertMinor(required,"Required advance",{allowZero:true});assertMinor(received,"Received amount",{allowZero:true});const final=original-discount;return{customerTotalMinor:final,originalCustomerTotalMinor:original,customerDiscountTotalMinor:discount,finalCustomerTotalMinor:final,requiredAdvanceMinor:required,receivedAmountMinor:received,balanceMinor:Math.max(0,final-received),refundCreditDueMinor:Math.max(0,received-final),paymentStatus:paymentStatus(required,received,overridden)}}
export function applyCustomerDiscountSnapshot(current:MoneySnapshot,amount:number,overridden=false):MoneySnapshot{assertMinor(amount,"Customer discount");const original=current.originalCustomerTotalMinor??current.customerTotalMinor;const previousDiscount=current.customerDiscountTotalMinor??Math.max(0,original-(current.finalCustomerTotalMinor??current.customerTotalMinor));const discount=previousDiscount+amount;if(discount>original)throw new Error("Total customer discounts cannot exceed the original customer sale.");const final=original-discount;const required=current.advancePercentage!==undefined?Math.round(final*current.advancePercentage/100):current.requiredAdvanceMinor;return{...discountedMoneySnapshot(original,discount,required,current.receivedAmountMinor,overridden),...(current.advancePercentage!==undefined?{advancePercentage:current.advancePercentage}:{})}}
export function readiness(input:{lifecycle:"active"|"cancelled"|"not_proceeding";paymentStatus:PaymentStatus;payoutStatus:PayoutStatus;overrideApproved?:boolean}):ReadinessStatus{if(input.lifecycle!=="active")return"cancelled";const paid=input.paymentStatus==="sufficient";const bypass=input.overrideApproved===true;if((paid||bypass)&&input.payoutStatus==="reviewed")return"ready_for_dispatch";if(bypass)return"override_approved";if(paid)return"needs_vendor_payout";if(input.paymentStatus==="partial")return"awaiting_advance";return"awaiting_advance"}
export function auditEvent(type:OperationalEvent["type"],timestamp:unknown,metadata?:Record<string,unknown>):OperationalEvent{return{type,timestamp,actor:sharedActor,...(metadata?{metadata}:{})}}
export function assertMinor(value:number,label:string,{allowZero=false}:{allowZero?:boolean}={}){if(!Number.isSafeInteger(value)||value<0||(!allowZero&&value===0))throw new Error(`${label} must be a valid positive amount.`);return value}
