import { createHash } from "node:crypto"; import type { NormalRentalZoneId } from "../normal-rental/zones.ts"; import type { OperationalBooking,OperationalSourceType } from "./booking-types.ts"; import { moneySnapshot,readiness,sharedActor } from "./booking-core.ts";
type Data=Record<string,unknown>; const s=(v:unknown)=>typeof v==="string"?v.trim():"";const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:Number(v)||0;const obj=(v:unknown):Data=>v&&typeof v==="object"?v as Data:{};
export const sourceCollection=(type:OperationalSourceType)=>type==="airport"?"airportBookings":type==="ta_connections"?"taConnectionsBookings":type==="manual"?"manualBookings":"leads";
export const sourceKey=(type:OperationalSourceType,documentId:string)=>`${type}:${documentId}`;
export const operationalDocumentId=(key:string)=>createHash("sha256").update(key).digest("hex");
const zone=(type:OperationalSourceType,d:Data):NormalRentalZoneId=>{if(d.zoneId==="lahore")return"lahore";if(d.zoneId==="twin_cities")return"twin_cities";const location=`${s(d.city)} ${s(d.pickupCity)} ${s(d.airportCode)} ${s(obj(d.pickupLocation).address)}`.toLowerCase();return location.includes("lahore")||location.includes("lhe")?"lahore":"twin_cities"};
const canonicalDate=(v:unknown)=>{const value=s(v);return /^\d{4}-\d{2}-\d{2}/.test(value)?value.slice(0,10):value};
export function adaptSource(type:Exclude<OperationalSourceType,"manual">,documentId:string,d:Data):Omit<OperationalBooking,"id"|"createdAt"|"updatedAt">{
 const collection=sourceCollection(type),key=sourceKey(type,documentId),airport=type==="airport",ta=type==="ta_connections",one=type==="one_way_drop";const customer=airport?obj(d.customer):{};const pricing=ta?obj(d.pricing):{};const payment=ta?obj(d.payment):{};
 const totalMinor=ta?n(pricing.grossContractRateMinor):Math.round(n(airport?d.quotedTotal:one?d.quotedPrice:d.estimatedRentalAmount||d.price)*100);if(totalMinor<0||!Number.isSafeInteger(totalMinor))throw new Error("Source customer total is invalid.");
 const advancePercentage=airport?n(d.advancePercentage):20;const required=airport?Math.round(n(d.expectedAdvanceAmount)*100):ta?totalMinor:Math.round(totalMinor*advancePercentage/100);const received=ta?Math.round(n(payment.paymentAmountMinor)):0;const financials=moneySnapshot(totalMinor,required,received);
 const lifecycle="active" as const,payoutStatus="pending" as const;
 return{bookingId:s(d.bookingId)||s(d.leadId)||documentId,source:{type,collection,documentId,key},sourceSnapshot:{sourceStatus:d.status??d.bookingStatus??null,source:d.source??null},zoneId:zone(type,d),serviceType:ta?s(d.serviceType):airport?s(d.tripType)||"airportTransfer":one?s(d.tripType)||"one_way_drop":s(d.service)||s(d.pricingType)||"normal_rental",customer:{name:airport?s(customer.name):ta?s(d.passengerOrGroupName):s(d.name),phone:airport?s(customer.phone):ta?s(d.passengerContact):s(d.phone),...(airport&&s(customer.email)?{email:s(customer.email)}:!airport&&!ta&&s(d.email)?{email:s(d.email)}:{})},itinerary:{travelDate:canonicalDate(ta?d.travelDate:airport?d.date:one?d.travelDate:d.pickupDate),pickupTime:s(ta?d.pickupTime:airport?d.time:one?d.travelTime:d.preferredTime),pickup:airport?s(obj(d.pickup).formattedAddress):ta?s(obj(d.pickupLocation).address):one?s(d.pickupAddress):s(d.pickupAddress),...(airport?{destinationOrUsage:s(obj(d.destination).formattedAddress)}:ta?{destinationOrUsage:s(obj(d.dropoffLocation).address)}:one?{destinationOrUsage:s(d.dropAddress)||s(d.destinationCity)}:s(d.destinationAddress)?{destinationOrUsage:s(d.destinationAddress)}:{}),...(s(d.notes)||s(d.specialInstructions)?{notes:s(d.notes)||s(d.specialInstructions)}:{})},requestedVehicle:{categoryOrModel:airport?s(obj(d.vehicle).name):ta?s(d.vehicleCategory):one?s(d.vehicle):s(d.publicVehicleLabel)||s(d.carName),...(n(d.passengers)||n(d.passengerCount)?{passengers:n(d.passengers)||n(d.passengerCount)}:{})},customerFinancials:{...financials,...(advancePercentage?{advancePercentage}:{})},internalFinancials:{payoutStatus},lifecycle,readinessStatus:readiness({lifecycle,paymentStatus:financials.paymentStatus,payoutStatus}),createdBy:sharedActor,updatedBy:sharedActor};
}
