import { isNormalRentalZoneId } from "../normal-rental/zones.ts";
import { MANUAL_DESTINATION_REQUIRED, MANUAL_SERVICE_TYPES, MANUAL_SOURCE_TYPES, MANUAL_TIME_VALUES, OPERATIONAL_SOURCE_TYPES } from "./booking-types.ts";
import { parseBookingResponsibilities } from "./booking-responsibilities.ts";

const text=(form:FormData,key:string,max=500)=>{const v=String(form.get(key)??"").trim();if(v.length>max)throw new Error(`${key} is too long.`);return v};
const required=(form:FormData,key:string,max=500)=>{const v=text(form,key,max);if(!v)throw new Error(`${key} is required.`);return v};
export const majorToMinor=(value:string,label:string,allowZero=false)=>{if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error(`${label} must be a valid amount.`);const n=Math.round(Number(value)*100);if(!Number.isSafeInteger(n)||n<0||(!allowZero&&n===0))throw new Error(`${label} must be a valid amount.`);return n};
export const manualTravelDate=(value:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error("Select a valid travel date.");const [y,m,d]=value.split("-").map(Number);const date=new Date(Date.UTC(y,m-1,d));if(date.getUTCFullYear()!==y||date.getUTCMonth()!==m-1||date.getUTCDate()!==d)throw new Error("Select a valid travel date.");return value};
export const withManualTravelDate=(form:FormData,value:string)=>{form.set("travelDate",value);return form};
export type ManualLocation={address:string;placeId:string;lat:number;lng:number;mapLink:string};
export const parseManualLocation=(form:FormData,prefix:string,requiredLocation:boolean):ManualLocation|undefined=>{const address=text(form,`${prefix}Address`,1000),selectedAddress=text(form,`${prefix}SelectedAddress`,1000),placeId=text(form,`${prefix}PlaceId`,256),lat=Number(text(form,`${prefix}Lat`,40)),lng=Number(text(form,`${prefix}Lng`,40));if(!address&&!requiredLocation)return undefined;if(!address||address!==selectedAddress||!placeId||!Number.isFinite(lat)||lat<23||lat>38.5||!Number.isFinite(lng)||lng<60||lng>78.5)throw new Error(`${prefix==="pickup"?"Pickup":"Destination"} must be selected from Google Places.`);return{address,placeId,lat,lng,mapLink:`https://www.google.com/maps/search/?api=1&query=${lat},${lng}&query_place_id=${encodeURIComponent(placeId)}`}};

export function parseManualBooking(form:FormData){
 const zoneId=required(form,"zoneId");if(!isNormalRentalZoneId(zoneId))throw new Error("Select a valid zone.");
 const channel=required(form,"manualChannel") as typeof MANUAL_SOURCE_TYPES[number];if(!MANUAL_SOURCE_TYPES.includes(channel))throw new Error("Select a valid manual source.");
 const serviceType=required(form,"serviceType") as typeof MANUAL_SERVICE_TYPES[number];if(!MANUAL_SERVICE_TYPES.includes(serviceType))throw new Error("Select a valid service type.");
 const pickupLocation=parseManualLocation(form,"pickup",true)!;const destinationRequired=MANUAL_DESTINATION_REQUIRED.includes(serviceType as typeof MANUAL_DESTINATION_REQUIRED[number]);const destinationLocation=parseManualLocation(form,"destination",destinationRequired);const usageNote=text(form,"usageNote",500)||undefined;
 const pickupTime=required(form,"pickupTime",5);if(!MANUAL_TIME_VALUES.includes(pickupTime))throw new Error("Select a valid pickup time.");
 const vehicleSelection=required(form,"vehicleSelection",300);const customVehicle=text(form,"customVehicle",160);if(vehicleSelection==="custom"&&!customVehicle)throw new Error("Enter the custom vehicle/category.");if(vehicleSelection!=="custom"&&!vehicleSelection.startsWith("dispatch:"))throw new Error("Select a valid vehicle/category.");
 const total=majorToMinor(required(form,"customerTotal"),"Customer total");const discount=text(form,"customerDiscount")?majorToMinor(text(form,"customerDiscount"),"Customer discount"):0;if(discount>total)throw new Error("Customer discount cannot exceed the original customer sale.");const discountReason=text(form,"discountReason",500)||undefined;if(discount>0&&!discountReason)throw new Error("Customer discount reason is required.");const finalTotal=total-discount;const advanceMode=required(form,"advanceMode");const advanceValue=required(form,"advanceValue");const requiredAdvanceMinor=advanceMode==="percentage"?Math.round(finalTotal*Number(advanceValue)/100):majorToMinor(advanceValue,"Required advance",true);if(advanceMode==="percentage"&&(!Number.isFinite(Number(advanceValue))||Number(advanceValue)<0||Number(advanceValue)>100))throw new Error("Advance percentage must be between 0 and 100.");const received=text(form,"receivedAmount")?majorToMinor(text(form,"receivedAmount"),"Received amount",true):0;
 const passengersValue=text(form,"passengers");const passengers=passengersValue?Number(passengersValue):undefined;if(passengers!==undefined&&(!Number.isInteger(passengers)||passengers<1||passengers>100))throw new Error("Passengers must be a whole number between 1 and 100.");
 return{zoneId,channel,customer:{name:required(form,"customerName",160),phone:required(form,"customerPhone",40),...(text(form,"customerEmail",160)?{email:text(form,"customerEmail",160)}:{})},serviceType,travelDate:manualTravelDate(required(form,"travelDate")),pickupTime,pickupLocation,destinationLocation,usageNote,notes:text(form,"notes",2000)||undefined,vehicleSelection,customVehicle:customVehicle||undefined,passengers,total,discount,discountReason,requiredAdvanceMinor,advancePercentage:advanceMode==="percentage"?Number(advanceValue):undefined,received,paymentMethod:text(form,"paymentMethod",80)||undefined,paymentReference:text(form,"paymentReference",160)||undefined,paymentNote:text(form,"paymentNote",500)||undefined,responsibilities:parseBookingResponsibilities(form,serviceType)};
}
export function parseResponsibilityUpdate(form:FormData,serviceType:string){return{bookingDocumentId:required(form,"bookingDocumentId",300),responsibilities:parseBookingResponsibilities(form,serviceType)}}
export function parseCustomerDiscount(form:FormData){const amountMinor=majorToMinor(required(form,"discountAmount"),"Customer discount");const reason=text(form,"discountReason",500);if(!reason)throw new Error("Customer discount reason is required.");if(reason.length<3)throw new Error("Customer discount reason must be specific.");return{bookingDocumentId:required(form,"bookingDocumentId",300),amountMinor,reason}}
export function parseImport(form:FormData){const type=required(form,"sourceType") as typeof OPERATIONAL_SOURCE_TYPES[number];if(type==="manual"||!OPERATIONAL_SOURCE_TYPES.includes(type))throw new Error("Select a valid existing source type.");return{type,documentId:required(form,"sourceDocumentId",300)}}
