import "server-only";
import { FieldValue } from "firebase-admin/firestore";
import { getAdminDb } from "../firebaseAdmin";
import { auditEvent,sharedActor } from "./booking-core";
import type { OperationalBooking } from "./booking-types";
import { assertBroadcastBookingCurrent,selectSupplyBroadcastRecipients } from "./broadcast-approval-core";
import { buildApprovedSupplyBroadcast,buildOutboundMessageJob } from "./dispatch-orchestration-core";
import { createSupplyOfferProjection,dispatchOfferId } from "./offer-core";
import { computeMatches } from "./matching-core";
import { projectSupplyRecipients } from "./supply-recipient-projection";
import type { MatchOverride,ResourceReservation } from "./matching-types";
import type { DispatchOfferRecord } from "./offer-types";
import type { DispatchDriver,DispatchVehicle,DispatchVendor } from "./types";
import { DISPATCH_COLLECTIONS } from "./collections";

const BOOKINGS="operationalBookings",OFFERS="dispatchOffers",BROADCASTS="dispatchBroadcasts",CONTROL="dispatchBroadcastControl",OUTBOX="whatsappOutboundMessages";
const resource=<T>(doc:FirebaseFirestore.QueryDocumentSnapshot|FirebaseFirestore.DocumentSnapshot)=>({...doc.data(),id:doc.id}) as T;
const iso=(value:unknown)=>value&&typeof value==="object"&&"toDate" in value?(value as{toDate():Date}).toDate().toISOString():String(value??"");
const reservation=(doc:FirebaseFirestore.QueryDocumentSnapshot):ResourceReservation=>{const data=doc.data();return{id:doc.id,bookingId:String(data.bookingId??""),...(data.vehicleId?{vehicleId:String(data.vehicleId)}:{}),...(data.driverId?{driverId:String(data.driverId)}:{}),startsAt:iso(data.startsAt),endsAt:iso(data.endsAt),active:data.active===true}};
export type ApproveBroadcastRequest={bookingOperationalId:string;candidateIds:string[];offerExpiresAt:string;payoutSnapshotMinor:number;expectedCurrentRevision:number};

export async function getDispatchBroadcastPanel(bookingOperationalId:string){const db=getAdminDb(),bookingRef=db.collection(BOOKINGS).doc(bookingOperationalId),[control,broadcasts]=await Promise.all([bookingRef.collection(CONTROL).doc("current").get(),bookingRef.collection(BROADCASTS).orderBy("revision","desc").limit(5).get()]);return{currentRevision:Number(control.data()?.revision??0),activeBroadcastId:String(control.data()?.activeBroadcastId??""),defaultOfferExpiresAt:new Date(Date.now()+30*60000).toISOString(),broadcasts:broadcasts.docs.map(doc=>({...doc.data(),id:doc.id}))}}

export async function approveDispatchBroadcast(request:ApproveBroadcastRequest){
 const expiry=new Date(request.offerExpiresAt);if(Number.isNaN(expiry.getTime())||expiry.getTime()<=Date.now())throw new Error("Offer expiry must be in the future.");
 const db=getAdminDb(),bookingRef=db.collection(BOOKINGS).doc(request.bookingOperationalId),controlRef=bookingRef.collection(CONTROL).doc("current");
 return db.runTransaction(async tx=>{
  const[bookingSnap,controlSnap,vendorsSnap,driversSnap,vehiclesSnap,reservationsSnap,overridesSnap]=await Promise.all([tx.get(bookingRef),tx.get(controlRef),tx.get(db.collection(DISPATCH_COLLECTIONS.vendors)),tx.get(db.collection(DISPATCH_COLLECTIONS.drivers)),tx.get(db.collection(DISPATCH_COLLECTIONS.vehicles)),tx.get(db.collection(DISPATCH_COLLECTIONS.reservations).where("active","==",true)),tx.get(bookingRef.collection("matchingOverrides"))]);
  if(!bookingSnap.exists)throw new Error("Operational booking not found.");const booking=assertBroadcastBookingCurrent(resource<OperationalBooking>(bookingSnap),request.payoutSnapshotMinor),currentRevision=Number(controlSnap.data()?.revision??0),revision=request.expectedCurrentRevision+1;
  const vendors=vendorsSnap.docs.map(doc=>resource<DispatchVendor>(doc)),drivers=driversSnap.docs.map(doc=>resource<DispatchDriver>(doc)),vehicles=vehiclesSnap.docs.map(doc=>resource<DispatchVehicle>(doc)),matches=computeMatches({booking,vendors,drivers,vehicles,reservations:reservationsSnap.docs.map(reservation),overrides:overridesSnap.docs.map(doc=>({candidateId:doc.id,mode:doc.data().mode} as MatchOverride))});
  if(!matches.ready)throw new Error("Booking changed. Refresh Smart Matching before approving.");const grouped=projectSupplyRecipients({pairCandidates:matches.eligible,vendors,drivers,vehicles,zoneId:booking.zoneId}),selected=selectSupplyBroadcastRecipients(request.candidateIds,grouped.eligible),offerIds=selected.map(candidate=>dispatchOfferId(booking.id,candidate.id)),approvedAt=new Date().toISOString(),recipients=selected.map((candidate,index)=>({recipientType:candidate.recipientTypeIntent,recipientId:candidate.recipientReferenceId,supplyAccountId:candidate.supplyAccountId,displayName:candidate.displayName,offerId:offerIds[index]})),broadcast=buildApprovedSupplyBroadcast({bookingOperationalId:booking.id,bookingId:booking.bookingId,revision,offerRevision:revision,candidateIds:selected.map(candidate=>candidate.id),offerIds,recipients,approvedPayoutMinor:request.payoutSnapshotMinor,offerExpiresAt:request.offerExpiresAt,approvedAt,approvedBy:sharedActor}),broadcastRef=bookingRef.collection(BROADCASTS).doc(broadcast.id);
  const existingBroadcast=await tx.get(broadcastRef);if(existingBroadcast.exists)return{broadcastId:broadcast.id,revision:Number(existingBroadcast.data()?.revision??revision),queuedCount:selected.length,duplicate:true};
  if(currentRevision!==request.expectedCurrentRevision)throw new Error("Booking changed. Refresh Smart Matching before approving.");
  const vendorMap=new Map(vendors.map(item=>[item.id,item])),driverMap=new Map(drivers.map(item=>[item.id,item])),projections=selected.map(candidate=>{const vendor=vendorMap.get(candidate.supplyAccountId);if(!vendor)throw new Error("A selected supply account no longer exists.");return createSupplyOfferProjection({booking,candidate,vendor,...(candidate.recipientTypeIntent==="independent_driver"?{designatedDriver:driverMap.get(candidate.recipientReferenceId)}:{})})}),offerRefs=offerIds.map(id=>bookingRef.collection(OFFERS).doc(id)),jobs=projections.map((projection,index)=>buildOutboundMessageJob({purpose:"booking_offer",bookingOperationalId:booking.id,bookingId:booking.bookingId,broadcastId:broadcast.id,offerId:offerIds[index],recipientType:projection.recipientType,recipientReferenceId:projection.recipientId,provider:"dualhook",messageKind:"template",createdAt:approvedAt})),jobRefs=jobs.map(job=>db.collection(OUTBOX).doc(job.id)),[offerSnaps,jobSnaps]=await Promise.all([Promise.all(offerRefs.map(ref=>tx.get(ref))),Promise.all(jobRefs.map(ref=>tx.get(ref)))]);
  const previousId=String(controlSnap.data()?.activeBroadcastId??"");if(previousId){const previousRef=bookingRef.collection(BROADCASTS).doc(previousId),previous=await tx.get(previousRef);if(previous.exists&&!["closed","cancelled"].includes(String(previous.data()?.status)))tx.update(previousRef,{status:"closed",closeReason:"superseded",updatedAt:approvedAt})}
  tx.create(broadcastRef,broadcast);tx.set(controlRef,{activeBroadcastId:broadcast.id,revision,offerRevision:revision,updatedAt:approvedAt,updatedBy:sharedActor});
  selected.forEach((candidate,index)=>{const projection=projections[index],existing=offerSnaps[index].exists?offerSnaps[index].data() as DispatchOfferRecord:undefined,now=FieldValue.serverTimestamp(),base={bookingOperationalId:booking.id,bookingId:booking.bookingId,vendorId:projection.supplyAccountId,...(projection.recipientType==="independent_driver"?{driverId:projection.recipientId}:{}),candidateId:candidate.id,recipientType:projection.recipientType,recipientId:projection.recipientId,supplyAccountId:projection.supplyAccountId,recipientDisplayName:projection.recipientDisplayName,recipientWhatsappNumber:projection.recipientWhatsappNumber,approvedPayoutMinor:request.payoutSnapshotMinor,offerStage:existing?.offerStage??"prepared",responseStatus:existing?.responseStatus??"not_recorded",createdAt:existing?.createdAt??now,createdBy:existing?.createdBy??sharedActor,updatedAt:now,updatedBy:sharedActor,broadcastId:broadcast.id,offerRevision:revision,offerExpiresAt:request.offerExpiresAt,notificationStatus:"queued",outboundMessageId:jobs[index].id};tx.set(offerRefs[index],base,{merge:true});if(!jobSnaps[index].exists)tx.create(jobRefs[index],{...jobs[index],status:"queued",queuedAt:approvedAt})});
  tx.create(bookingRef.collection("events").doc(),auditEvent("driver_broadcast_approved" as never,FieldValue.serverTimestamp(),{broadcastId:broadcast.id,revision,selectedRecipientCount:selected.length,candidateIds:broadcast.candidateIds,offerIds:broadcast.offerIds,recipientTypes:recipients.map(item=>item.recipientType),approvedPayoutMinor:broadcast.approvedPayoutMinor,offerExpiresAt:broadcast.offerExpiresAt}));
  return{broadcastId:broadcast.id,revision,queuedCount:selected.length,duplicate:false};
 });
}

// Backward compatibility: historical D6 jobs retain purpose:"driver_offer" and the legacy selectBroadcastRecipients path remains readable; VF5 creates only generalized booking_offer jobs above.
