import type { OperationalBooking } from "./booking-types";
import type { DriverInstructionProjection } from "./driver-instructions-types";
import { normalizeDispatchPhone } from "./validation.ts";

const SUPPORT_PHONE="0302 058 9999",SUPPORT_WHATSAPP="923020589999";
const money=(minor:number)=>`Rs. ${(minor/100).toLocaleString("en-PK",{maximumFractionDigits:2})}`;
const dateLabel=(value:string)=>{const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);return match?new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`)):value};
const timeLabel=(value:string)=>{const match=/^(\d{2}):(\d{2})$/.exec(value);if(!match)return value;const hour=Number(match[1]);return `${hour%12||12}:${match[2]} ${hour<12?"AM":"PM"}`};
const responsibility=(value:unknown)=>value==="customer"?"Customer responsibility / not included":value==="rentka"?"RentKA/vendor responsibility":value==="included"?"Included":value==="not_applicable"||value==="not-applicable"?"Not applicable":"Missing - confirm with RentKA";
const allowance=(value:unknown)=>{if(!value||typeof value!=="object")return responsibility(value);const item=value as{mode?:string;amountMinor?:number;note?:string};if(item.mode==="customer")return"Customer provides/pays directly";if(item.mode==="allowance"&&typeof item.amountMinor==="number")return`${money(item.amountMinor)}/day allowance`;if(item.mode==="custom")return`${typeof item.amountMinor==="number"?`${money(item.amountMinor)}/day - `:""}${item.note||"Custom arrangement - confirm with RentKA"}`;return"Missing - confirm with RentKA"};
const extraHour=(responsibilities:Record<string,unknown>)=>{const value=responsibilities.extraHour;if(value&&typeof value==="object"){const item=value as{mode?:string;amountMinor?:number;note?:string};if(item.mode==="rate"&&typeof item.amountMinor==="number")return`${money(item.amountMinor)}/hour`;if(item.mode==="custom"&&item.note)return item.note}return typeof responsibilities.extraHourRateMinor==="number"&&responsibilities.extraHourRateMinor>0?`${money(responsibilities.extraHourRateMinor)}/hour`:"Not specified - confirm with RentKA"};
const required=(value:string|undefined,label:string,missing:string[])=>{const clean=value?.trim();if(clean)return clean;missing.push(label);return`MISSING ${label.toUpperCase()} - confirm with RentKA`};

export function createDriverInstructionsProjection(booking:OperationalBooking):DriverInstructionProjection|null{
 if(booking.lifecycle!=="active"||booking.assignment?.status!=="assigned")return null;
 const assignment=booking.assignment,missingFields:string[]=[],r=(booking.responsibilities??{}) as Record<string,unknown>;
 const customerName=required(booking.customer.name,"customer name",missingFields),customerPhone=required(booking.customer.phone,"customer phone",missingFields),pickup=required(booking.itinerary.pickup,"pickup address",missingFields),destination=required(booking.itinerary.destinationOrUsage,"destination / itinerary",missingFields),travelDate=required(booking.itinerary.travelDate,"travel date",missingFields),pickupTime=required(booking.itinerary.pickupTime,"pickup time",missingFields);
 const driverPhone=normalizeDispatchPhone(assignment.driverSnapshot.whatsappNumber||assignment.driverSnapshot.mobileNumber);if(!driverPhone)missingFields.push("assigned driver WhatsApp");
 const vehicleYear=assignment.vehicleSnapshot.modelYear?String(assignment.vehicleSnapshot.modelYear):"Year not recorded",collectionAmount=Math.max(0,booking.customerFinancials.balanceMinor),collectionLabel=collectionAmount>0?money(collectionAmount):"Nothing currently outstanding",paymentNote=collectionAmount>0?"Current outstanding customer balance. Confirm with RentKA before collecting because payments may change.":"No customer collection currently shown. Confirm with RentKA if instructed otherwise.";
 const lines=["RENTKA - FINAL DRIVER INSTRUCTIONS",`Trip Reference: ${booking.bookingId}`,"",`Customer: ${customerName}`,`Customer Phone / WhatsApp: ${customerPhone}`,"",`Exact Pickup: ${pickup}`,...(booking.itinerary.pickupLocation?.mapLink?[`Pickup Map: ${booking.itinerary.pickupLocation.mapLink}`]:[]),`Destination / Itinerary: ${destination}`,...(booking.itinerary.destinationLocation?.mapLink?[`Destination Map: ${booking.itinerary.destinationLocation.mapLink}`]:[]),`Travel Date: ${dateLabel(travelDate)}`,`Reporting / Pickup Time: ${timeLabel(pickupTime)}`,"",`Assigned Driver: ${assignment.driverSnapshot.name}`,`Assigned Vehicle: ${assignment.vehicleSnapshot.make} ${assignment.vehicleSnapshot.model} - ${vehicleYear} - ${assignment.vehicleSnapshot.registrationNumber}`,`Confirmed Driver/Vendor Payout: ${money(assignment.approvedVendorPayoutMinor)}`,`Amount to Collect from Customer: ${collectionLabel}`,`Payment / Collection Note: ${paymentNote}`,"",`Fuel: ${responsibility(r.fuel)}`,`Toll: ${responsibility(r.toll)}`,`Parking: ${responsibility(r.parking)}`,`Driver Food / Accommodation: ${allowance(r.driverFoodAccommodation)}`,`Extra-Hour Terms: ${extraHour(r)}`,`Operational / Special Instructions: ${booking.itinerary.notes?.trim()||"None recorded"}`,"",`RentKA Support: ${SUPPORT_PHONE} | WhatsApp +${SUPPORT_WHATSAPP}`,"","These are the final operational instructions for the assigned Driver and Vehicle. Contact RentKA before accepting changes directly from the customer."];
 const message=lines.join("\n");
 return{bookingOperationalId:booking.id,bookingId:booking.bookingId,assignmentId:assignment.id,driverId:assignment.assignedDriverId,vehicleId:assignment.assignedVehicleId,driverName:assignment.driverSnapshot.name,...(driverPhone?{driverWhatsappNumber:driverPhone,whatsappUrl:`https://wa.me/${driverPhone}?text=${encodeURIComponent(message)}`}:{}),message,missingFields};
}
