import type { OperationalBooking } from "./booking-types";
import { generalArea } from "./offer-core.ts";
import { directDriverOfferIdentity,type DispatchOfferRecord } from "./offer-types.ts";
import { isOfferExpired } from "./dispatch-orchestration-core.ts";
import type { DriverOfferResponse,SecureDriverOfferProjection } from "./driver-offer-portal-types";
const responsibility=(label:string,value:unknown)=>`${label}: ${value==="customer"?"Customer responsibility":value==="rentka"?"RentKA/vendor responsibility":value==="included"?"Included":"As agreed with RentKA"}`;
export function createSecureDriverOfferProjection(booking:OperationalBooking,offer:DispatchOfferRecord,responses:DriverOfferResponse[]=[]):SecureDriverOfferProjection{const identity=directDriverOfferIdentity(offer),r=booking.responsibilities??{},latest=responses[0],duration=typeof booking.sourceSnapshot.durationHours==="number"?`${booking.sourceSnapshot.durationHours} hours`:"Confirm package with RentKA";return{bookingOperationalId:booking.id,bookingId:booking.bookingId,offerId:offer.id,driverId:identity.driverId,vendorId:identity.vendorId,offeredPayoutMinor:offer.currentOfferedPayoutMinor??offer.approvedPayoutMinor,generalPickupArea:generalArea(booking.itinerary.pickup),generalDestination:generalArea(booking.itinerary.destinationOrUsage),travelDate:booking.itinerary.travelDate,pickupTime:booking.itinerary.pickupTime,vehicleRequirement:booking.requestedVehicle.categoryOrModel,packageInformation:duration,responsibilities:[responsibility("Fuel",r.fuel),responsibility("Toll",r.toll),responsibility("Parking",r.parking)],supportPhone:"0302 058 9999",...(offer.secureViewedAt?{viewedAt:offer.secureViewedAt}:{}),closed:offer.portalStatus==="closed"||isOfferExpired(offer.offerExpiresAt)||booking.lifecycle!=="active"||booking.assignment?.status==="assigned",...(latest?{latestResponse:latest}:{})}}
export function validateCounterPayout(amountMinor:number,offeredMinor:number){if(!Number.isSafeInteger(amountMinor)||amountMinor<=0)throw new Error("Counter payout must be a valid positive amount.");if(amountMinor>Math.max(offeredMinor*5,5000000))throw new Error("Counter payout is outside the reasonable review range.");return amountMinor}
export function assertCurrentOfferRevision(tokenRevision:number|undefined,offerRevision:number|undefined){if(tokenRevision!==undefined&&tokenRevision!==(offerRevision??0))throw new Error("This offer is no longer available.");return offerRevision??0}
export function assertCurrentBroadcast(offer:Pick<DispatchOfferRecord,"broadcastId">,activeBroadcastId:string|undefined){if(offer.broadcastId&&offer.broadcastId!==activeBroadcastId)throw new Error("This offer is no longer available.");return offer}
export function assertDriverResponseOpen(offer:Pick<DispatchOfferRecord,"responseStatus">){if(["accepted","declined","countered","expired","closed","cancelled","not_selected"].includes(offer.responseStatus))throw new Error("This offer is no longer available.");return offer}
export function assertCounterDecisionCurrent(offer:Pick<DispatchOfferRecord,"responseStatus"|"offerRevision"|"requestedPayoutMinor">,expectedRevision:number,expectedCounterMinor:number){if(offer.responseStatus!=="countered"||offer.offerRevision!==expectedRevision||offer.requestedPayoutMinor!==expectedCounterMinor)throw new Error("This counter offer changed. Refresh before deciding.");return offer}
export function validateRevisedOfferExpiry(value:string,now=new Date()){const expiry=new Date(value);if(!value||Number.isNaN(expiry.getTime())||expiry.getTime()<=now.getTime())throw new Error("Choose a future expiry for the revised offer.");return expiry.toISOString()}
