import { createHash } from "node:crypto";
import type { OperationalBooking } from "./booking-types";
import type { MatchCandidate, MatchExclusion, MatchInput, MatchProjection, ResourceReservation } from "./matching-types";
import type { CheckState, DispatchDriver, DispatchPriority, DispatchVehicle, DispatchVendor, DocumentationState } from "./types";

const normalize=(value:string)=>value.toLowerCase().replace(/\b(toyota|honda|suzuki|kia|hyundai|proton|changan)\b/g," ").replace(/[^a-z0-9]+/g," ").trim();
const tokens=(value:string)=>new Set(normalize(value).split(" ").filter(Boolean));
const aliases:Record<string,string>={saloon:"sedan",car:"sedan",corolla:"corolla",civic:"civic",city:"city",brv:"brv",br_v:"brv",suv:"suv",mpv:"mpv",van:"van",hiace:"hiace",coaster:"coaster"};
const canonical=(value:string)=>[...tokens(value)].map(x=>aliases[x]??x).join(" ");
const categoryFamilies:Record<string,string[]>={sedan:["sedan","corolla","civic","city","yaris","alsvin","saga"],suv:["suv","brv","sportage","tucson","prado","fortuner"],van:["van","hiace"],coaster:["coaster"]};
const family=(value:string)=>Object.entries(categoryFamilies).find(([,members])=>members.some(x=>canonical(value).split(" ").includes(x)))?.[0];
export function resolveVehicleCompatibility(requested:string,vehicle:Pick<DispatchVehicle,"category"|"make"|"model">){
 const request=canonical(requested),model=canonical(`${vehicle.make} ${vehicle.model}`),category=canonical(vehicle.category);
 if(request&&model&&(request===model||request.includes(model)||model.includes(request)))return{kind:"exact_model" as const,score:35,reason:"Exact requested model"};
 if(request&&category&&(request===category||request.includes(category)))return{kind:"exact_category" as const,score:28,reason:"Exact requested category"};
 const requestedFamily=family(request),vehicleFamily=family(`${category} ${model}`);
 if(requestedFamily&&requestedFamily===vehicleFamily)return{kind:"compatible_category" as const,score:18,reason:`Compatible ${requestedFamily} alternative`};
 return{kind:"incompatible" as const,score:0,reason:"Different vehicle class/model is not an approved operational substitute"};
}
export function driverVehicleEligibility(driver:DispatchDriver,vehicle:DispatchVehicle){const rule=driver.vehicleEligibility;if(!rule||rule.mode==="any_vendor_vehicle")return{eligible:true,reason:"Any vendor vehicle"};if(rule.mode==="specific_vehicles"){const eligible=(rule.vehicleIds??[]).includes(vehicle.id);return{eligible,reason:eligible?`Permitted vehicle ${vehicle.registrationNumber}`:`Driver restricted to selected vehicle(s); ${vehicle.registrationNumber} is not permitted`}}const allowed=rule.allowedModelsOrCategories??[],eligible=allowed.some(value=>{const[prefix,...rest]=value.split(":"),restriction=rest.length?rest.join(":"):value,result=resolveVehicleCompatibility(restriction,vehicle);return prefix==="model"?result.kind==="exact_model":prefix==="category"?result.kind==="exact_category":result.kind==="exact_model"||result.kind==="exact_category"});return{eligible,reason:eligible?`Driver vehicle eligibility satisfied`:`Driver restricted to ${allowed.map(value=>value.replace(/^(model|category):/,"")).join(", ")||"configured models/categories"}`}}
const priorityScore=(priority:DispatchPriority)=>priority==="preferred"?18:priority==="normal"?10:3;
const priorityLabel=(priority:DispatchPriority)=>priority[0].toUpperCase()+priority.slice(1);
const documentationScore=(state:DocumentationState)=>state==="verified"?10:state==="warning"?3:0;
const checkExpired=(state:CheckState)=>state==="expired";
const expiredDate=(date:string|undefined,now:Date)=>!!date&&date<now.toISOString().slice(0,10);
function vehicleDocumentationBlock(vehicle:DispatchVehicle,now:Date){const d=vehicle.documentation;if(d.overallState==="expired")return"Vehicle documentation expired";if([d.registrationState,d.permitState,d.fitnessState,d.insuranceState].some(checkExpired))return"Critical vehicle document expired";if([d.registrationExpiry,d.permitExpiry,d.fitnessExpiry,d.insuranceExpiry].some(x=>expiredDate(x,now)))return"Critical vehicle document expiry date passed";return""}
function driverDocumentationBlock(driver:DispatchDriver,now:Date){const d=driver.documentation;if(d.licenceState==="expired"||expiredDate(d.licenceExpiry,now))return"Driver licence expired";return""}
const parseStart=(booking:OperationalBooking)=>new Date(`${booking.itinerary.travelDate}T${/^\d{2}:\d{2}$/.test(booking.itinerary.pickupTime)?booking.itinerary.pickupTime:"00:00"}:00+05:00`);
export function matchingWindow(booking:OperationalBooking){const start=parseStart(booking);let hours=12,basis="Conservative 12-hour default; exact duration is unavailable";const service=booking.serviceType.toLowerCase();if(service.includes("monthly")){hours=24*30;basis="Monthly service window (30 days)"}else if(service.includes("outstation")){hours=24;basis="Conservative 24-hour outstation window"}const raw=booking.sourceSnapshot.durationHours;if(typeof raw==="number"&&Number.isFinite(raw)&&raw>0&&raw<=24*31){hours=raw;basis="Exact normalized duration"}return{start:start.toISOString(),end:new Date(start.getTime()+hours*3600000).toISOString(),basis}}
const overlaps=(window:{start:string;end:string},reservation:ResourceReservation)=>reservation.active&&new Date(reservation.startsAt)<new Date(window.end)&&new Date(reservation.endsAt)>new Date(window.start);
export const candidateId=(vendorId:string,vehicleId:string,driverId:string)=>createHash("sha256").update(`${vendorId}:${vehicleId}:${driverId}`).digest("hex").slice(0,24);
const exclusion=(kind:MatchExclusion["kind"],id:string,label:string,reason:string,critical:boolean):MatchExclusion=>({kind,id,label,reason,critical});
export function computeMatches(input:MatchInput):MatchProjection{
 const {booking,vendors,vehicles,drivers}=input,now=input.now??new Date(),window=matchingWindow(booking),excluded:MatchExclusion[]=[];
 if(booking.lifecycle!=="active"||booking.readinessStatus!=="ready_for_dispatch")return{bookingId:booking.bookingId,ready:false,unavailableReason:booking.lifecycle!=="active"?"Cancelled / Not Proceeding":`Booking is ${booking.readinessStatus.replaceAll("_"," ")}`,window,top:[],eligible:[],excluded:[]};
 const vendorMap=new Map<string,DispatchVendor>();for(const v of vendors){if(!v.active){excluded.push(exclusion("vendor",v.id,v.name,"Inactive vendor",true));continue}if(!v.zoneIds.includes(booking.zoneId)){excluded.push(exclusion("vendor",v.id,v.name,"Vendor does not serve booking zone",true));continue}vendorMap.set(v.id,v)}
 const vehicleMap=new Map<string,DispatchVehicle>();for(const v of vehicles){const label=`${v.make} ${v.model} — ${v.registrationNumber}`;if(!vendorMap.has(v.vendorId)){if(vendors.some(x=>x.id===v.vendorId))continue;excluded.push(exclusion("vehicle",v.id,label,"Vendor relationship is missing",true));continue}if(!v.active||v.status==="inactive"){excluded.push(exclusion("vehicle",v.id,label,"Inactive vehicle",true));continue}if(!v.zoneIds.includes(booking.zoneId)){excluded.push(exclusion("vehicle",v.id,label,"Vehicle does not serve booking zone",true));continue}if(v.status==="unavailable"){excluded.push(exclusion("vehicle",v.id,label,"Vehicle unavailable",false));continue}const block=vehicleDocumentationBlock(v,now);if(block){excluded.push(exclusion("vehicle",v.id,label,block,true));continue}if(input.reservations?.some(r=>r.vehicleId===v.id&&r.bookingId!==booking.id&&overlaps(window,r))){excluded.push(exclusion("vehicle",v.id,label,"Time conflict with operational reservation",true));continue}if(v.status==="assigned"){excluded.push(exclusion("vehicle",v.id,label,"Vehicle is currently assigned; no time-specific release is recorded",false));continue}vehicleMap.set(v.id,v)}
 const driverMap=new Map<string,DispatchDriver>();for(const d of drivers){if(!vendorMap.has(d.vendorId)){if(vendors.some(x=>x.id===d.vendorId))continue;excluded.push(exclusion("driver",d.id,d.name,"Vendor relationship is missing",true));continue}if(!d.active){excluded.push(exclusion("driver",d.id,d.name,"Inactive driver",true));continue}if(!d.zoneIds.includes(booking.zoneId)){excluded.push(exclusion("driver",d.id,d.name,"Driver does not serve booking zone",true));continue}if(d.status==="blocked"){excluded.push(exclusion("driver",d.id,d.name,"Driver blocked",true));continue}if(d.status==="offline"){excluded.push(exclusion("driver",d.id,d.name,"Driver offline",false));continue}const block=driverDocumentationBlock(d,now);if(block){excluded.push(exclusion("driver",d.id,d.name,block,true));continue}if(input.reservations?.some(r=>r.driverId===d.id&&r.bookingId!==booking.id&&overlaps(window,r))){excluded.push(exclusion("driver",d.id,d.name,"Time conflict with operational reservation",true));continue}if(d.status==="on_trip"){excluded.push(exclusion("driver",d.id,d.name,"Driver is on trip; no time-specific release is recorded",false));continue}driverMap.set(d.id,d)}
 const overrides=new Map((input.overrides??[]).map(x=>[x.candidateId,x.mode])),eligible:MatchCandidate[]=[];
 for(const vendor of vendorMap.values())for(const vehicle of vehicleMap.values()){if(vehicle.vendorId!==vendor.id)continue;for(const driver of driverMap.values()){if(driver.vendorId!==vendor.id)continue;const id=candidateId(vendor.id,vehicle.id,driver.id),compatibility=resolveVehicleCompatibility(booking.requestedVehicle.categoryOrModel,vehicle);if(compatibility.kind==="incompatible"){excluded.push(exclusion("candidate",id,`${driver.name} + ${vehicle.make} ${vehicle.model}`,compatibility.reason,true));continue}const driverEligibility=driverVehicleEligibility(driver,vehicle);if(!driverEligibility.eligible){excluded.push(exclusion("candidate",id,`${driver.name} + ${vehicle.make} ${vehicle.model}`,driverEligibility.reason,true));continue}const mode=overrides.get(id);if(mode==="exclude"){excluded.push(exclusion("candidate",id,`${driver.name} + ${vehicle.make} ${vehicle.model}`,"Excluded by Admin for this booking",false));continue}let score=priorityScore(vendor.priority)+priorityScore(driver.priority)+compatibility.score+documentationScore(vehicle.documentation.overallState)+(driver.documentation.licenceState==="verified"?6:0)+(driver.documentation.cnicVerificationState==="verified"?4:0);const reasons=[`${priorityLabel(vendor.priority)} vendor`,`${priorityLabel(driver.priority)} driver`,compatibility.reason,driverEligibility.reason,`Correct ${booking.zoneId.replaceAll("_"," ")} zone`,"Vehicle available",vehicle.documentation.overallState==="verified"?"Vehicle documentation verified":`Vehicle documentation ${vehicle.documentation.overallState}`,driver.documentation.licenceState==="verified"?"Driver licence verified":`Driver licence ${driver.documentation.licenceState}`,"No known booking conflict"];if(vehicle.modelYear){score+=Math.max(0,Math.min(5,vehicle.modelYear-2015)*0.5);reasons.push(`Model year ${vehicle.modelYear} (modest benefit)`)}if(mode==="include"){score+=100;reasons.unshift("Included by Admin for this booking")}eligible.push({id,vendor:{id:vendor.id,name:vendor.name},vehicle:{id:vehicle.id,label:`${vehicle.make} ${vehicle.model}${vehicle.modelYear?` ${vehicle.modelYear}`:""}`,registrationNumber:vehicle.registrationNumber},driver:{id:driver.id,name:driver.name},score:Math.round(score*10)/10,compatibility:compatibility.kind,reasons,manuallyIncluded:mode==="include"})}}
 eligible.sort((a,b)=>b.score-a.score||a.vendor.name.localeCompare(b.vendor.name)||a.vehicle.registrationNumber.localeCompare(b.vehicle.registrationNumber)||a.driver.name.localeCompare(b.driver.name)||a.id.localeCompare(b.id));return{bookingId:booking.bookingId,ready:true,window,top:eligible.slice(0,3),eligible,excluded:excluded.sort((a,b)=>a.kind.localeCompare(b.kind)||a.label.localeCompare(b.label)||a.reason.localeCompare(b.reason))}
}
export function driverOfferSafeProjection(candidate:MatchCandidate,booking:OperationalBooking){return{bookingId:booking.bookingId,zoneId:booking.zoneId,serviceType:booking.serviceType,travelDate:booking.itinerary.travelDate,pickupTime:booking.itinerary.pickupTime,pickup:booking.itinerary.pickup,destinationOrUsage:booking.itinerary.destinationOrUsage,requestedVehicle:booking.requestedVehicle.categoryOrModel,candidate:{vendorId:candidate.vendor.id,vehicleId:candidate.vehicle.id,driverId:candidate.driver.id}}}
