import type { AuditActor } from "./types";
import type { BookingOfferRecipientType } from "./broadcast-types";

export type DispatchOfferStage="prepared"|"whatsapp_opened"|"sent_manual";
export type DispatchResponseStatus="not_recorded"|"available"|"declined"|"no_response";
export type DispatchOfferNotificationStatus="not_queued"|"queued"|"sending"|"provider_accepted"|"sent"|"delivered"|"read"|"failed"|"cancelled"|"outcome_unknown";
export type DriverOfferProjection={offerId:string;candidateId:string;bookingOperationalId:string;bookingId:string;vendorId:string;driverId:string;vehicleId:string;vehicleRegistration:string;driverName:string;vendorName:string;driverWhatsappNumber:string;approvedPayoutMinor:number;message:string;whatsappUrl:string};
export type SupplyOfferProjection={offerId:string;candidateId:string;bookingOperationalId:string;bookingId:string;recipientType:BookingOfferRecipientType;recipientId:string;supplyAccountId:string;recipientDisplayName:string;recipientWhatsappNumber:string;approvedPayoutMinor:number};
export type VendorFulfillmentProposalSnapshot={proposalId?:string;status:"provided"|"superseded"|"rejected"|"assigned";vendorId:string;driverId:string;driverName:string;vehicleId:string;vehicleLabel:string;offerRevision:number;responseRevision?:number;proposedAt:string;actor:{type:"vendor_offer";vendorId:string;offerId:string}};
export type DispatchOfferRecord={id:string;bookingOperationalId:string;bookingId:string;vendorId?:string;driverId?:string;vehicleId?:string;candidateId:string;vehicleRegistration?:string;driverName?:string;vendorName?:string;driverWhatsappNumber?:string;recipientType?:BookingOfferRecipientType;recipientId?:string;supplyAccountId?:string;recipientDisplayName?:string;recipientWhatsappNumber?:string;approvedPayoutMinor:number;currentOfferedPayoutMinor?:number;agreedPayoutMinor?:number;requestedPayoutMinor?:number;previousCounterPayoutMinor?:number;offerStage:DispatchOfferStage;responseStatus:DispatchResponseStatus|"accepted"|"countered"|"expired"|"closed"|"cancelled"|"not_selected";responseSource?:"admin_manual"|"driver_secure_page"|"vendor_secure_page";portalStatus?:"open"|"closed";closeReason?:string;negotiationStatus?:"awaiting_driver"|"awaiting_admin_review"|"counter_agreed"|"counter_rejected";lastAdminDecision?:"accept_counter"|"reject_counter"|"revised_offer";lastAdminDecisionRevision?:number;secureViewedAt?:string;vendorSecureViewedAt?:string;fulfillmentProposal?:VendorFulfillmentProposalSnapshot;proposalStatus?:"not_provided"|"provided"|"superseded"|"rejected"|"assigned";createdAt:string;updatedAt:string;createdBy:AuditActor;updatedBy:AuditActor;openedAt?:string;sentAt?:string;responseAt?:string;responseNote?:string;declineReason?:string;broadcastId?:string;offerRevision?:number;offerExpiresAt?:string;notificationStatus?:DispatchOfferNotificationStatus;outboundMessageId?:string;providerMessageId?:string;providerAcceptedAt?:string;deliveredAt?:string;readAt?:string;failedAt?:string;failureCode?:string;failureRetryable?:boolean;messageTemplateName?:string;messageLanguage?:string};
export const offerRecipientType=(offer:Pick<DispatchOfferRecord,"recipientType">)=>offer.recipientType??"driver";
export type HistoricalDriverOfferRecord=DispatchOfferRecord&Required<Pick<DispatchOfferRecord,"vendorId"|"driverId">>;
export function assertHistoricalDriverOffer(offer:DispatchOfferRecord):asserts offer is HistoricalDriverOfferRecord{if(offer.recipientType||!offer.vendorId||!offer.driverId)throw new Error("This record is not a historical Driver offer.")}
export type DirectDriverOfferIdentity={driverId:string;vendorId:string;recipientType:"driver"|"independent_driver"};
export function directDriverOfferIdentity(offer:DispatchOfferRecord):DirectDriverOfferIdentity{
 if(!offer.recipientType){assertHistoricalDriverOffer(offer);return{driverId:offer.driverId,vendorId:offer.vendorId,recipientType:"driver"}}
 if(offer.recipientType==="independent_driver"&&offer.recipientId&&offer.supplyAccountId&&offer.vendorId===offer.supplyAccountId)return{driverId:offer.recipientId,vendorId:offer.supplyAccountId,recipientType:"independent_driver"};
 throw new Error("This record is not a direct Driver offer.");
}
