import { createHash } from "node:crypto";
import type { OperationalBooking } from "./booking-types";
import type { MatchCandidate } from "./matching-types";
import type { DispatchResponseStatus, DriverOfferProjection } from "./offer-types";
import type { DispatchDriver } from "./types";
import { normalizeDispatchPhone } from "./validation.ts";

export const dispatchOfferId=(bookingOperationalId:string,candidateId:string)=>createHash("sha256").update(`${bookingOperationalId}:${candidateId}`).digest("hex");
export function applyOfferResponseState(response:Exclude<DispatchResponseStatus,"not_recorded">,timestamp:unknown,note?:string){return{responseStatus:response,responseAt:timestamp,...(note?{responseNote:note}:{})}}
const dateLabel=(value:string)=>{const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!match)return value;return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`))};
const timeLabel=(value:string)=>{const match=/^(\d{2}):(\d{2})$/.exec(value);if(!match)return value;const hour=Number(match[1]);return `${hour%12||12}:${match[2]} ${hour<12?"AM":"PM"}`};
export function generalArea(value:string|undefined){if(!value)return"Confirm with RentKA";const parts=value.split(",").map(x=>x.trim()).filter(Boolean).filter(x=>!/^pakistan$/i.test(x));return(parts.length>2?parts.slice(-2):parts).join(", ")||"Confirm with RentKA"}
const responsibility=(value:unknown)=>value==="customer"?"Customer responsibility":value==="rentka"?"RentKA/vendor responsibility":value==="included"?"Included":value==="not_applicable"||value==="not-applicable"?"Not applicable":"As agreed / Confirm with RentKA";
const money=(minor:number)=>`Rs. ${(minor/100).toLocaleString("en-PK",{maximumFractionDigits:2})}`;
const allowance=(value:unknown)=>{if(!value||typeof value!=="object")return responsibility(value);const item=value as{mode?:string;amountMinor?:number;note?:string};if(item.mode==="customer")return"Customer responsibility";if(item.mode==="allowance"&&typeof item.amountMinor==="number")return`${money(item.amountMinor)}/day allowance`;if(item.mode==="custom")return`${typeof item.amountMinor==="number"?`${money(item.amountMinor)}/day — `:""}${item.note||"Custom arrangement — confirm with RentKA"}`;return"As agreed / Confirm with RentKA"};
const extraHour=(responsibilities:Record<string,unknown>)=>{const value=responsibilities.extraHour;if(value&&typeof value==="object"){const item=value as{mode?:string;amountMinor?:number;note?:string};if(item.mode==="rate"&&typeof item.amountMinor==="number")return`${money(item.amountMinor)}/hour`;if(item.mode==="custom"&&item.note)return item.note}return typeof responsibilities.extraHourRateMinor==="number"&&responsibilities.extraHourRateMinor>0?`${money(responsibilities.extraHourRateMinor)}/hour`:"Confirm with RentKA"};
export function createDriverOfferProjection(input:{booking:OperationalBooking;candidate:MatchCandidate;driver:DispatchDriver}):DriverOfferProjection{
 const{booking,candidate,driver}=input;if(booking.lifecycle!=="active"||booking.readinessStatus!=="ready_for_dispatch"||booking.internalFinancials.payoutStatus!=="reviewed"||booking.internalFinancials.vendorPayoutMinor===undefined)throw new Error("Booking must be Ready for Dispatch with an approved vendor payout.");const phone=normalizeDispatchPhone(driver.whatsappNumberNormalized||driver.whatsappNumber);if(!phone)throw new Error("Driver WhatsApp number is invalid or missing.");const r=(booking.responsibilities??{}) as Record<string,unknown>,duration=typeof booking.sourceSnapshot.durationHours==="number"?`${booking.sourceSnapshot.durationHours} hours`:booking.serviceType.toLowerCase().includes("monthly")?"Monthly — confirm schedule":booking.serviceType.toLowerCase().includes("outstation")?"Outstation — confirm duration":"12 hours / confirm with RentKA",foodLabel=booking.serviceType.toLowerCase().includes("outstation")?"Driver TA/DA":"Driver Food/Accommodation";
 const lines=["🚗 *RENTKA — TRIP AVAILABLE*",`Booking: *${booking.bookingId}*`,`📅 Date: ${dateLabel(booking.itinerary.travelDate)}`,`⏰ Pickup: ${timeLabel(booking.itinerary.pickupTime)}`,`🚘 Vehicle: ${candidate.vehicle.label} — ${candidate.vehicle.registrationNumber}`,`📍 Pickup Area: ${generalArea(booking.itinerary.pickup)}`,`📍 Destination / Usage: ${generalArea(booking.itinerary.destinationOrUsage)}`,`⏱ Package: ${duration}`,`💰 Your Amount: *${money(booking.internalFinancials.vendorPayoutMinor)}*`,`⛽ Fuel: ${responsibility(r.fuel)}`,`🛣 Toll: ${responsibility(r.toll)}`,`🅿 Parking: ${responsibility(r.parking)}`,`🍽 ${foodLabel}: ${allowance(r.driverFoodAccommodation)}`,`⏳ Extra hour: ${extraHour(r)}`,"","Please confirm:","AVAILABLE","or","NOT AVAILABLE","","Availability only — booking is not assigned yet."];const message=lines.join("\n"),offerId=dispatchOfferId(booking.id,candidate.id);return{offerId,candidateId:candidate.id,bookingOperationalId:booking.id,bookingId:booking.bookingId,vendorId:candidate.vendor.id,driverId:candidate.driver.id,vehicleId:candidate.vehicle.id,vehicleRegistration:candidate.vehicle.registrationNumber,driverName:candidate.driver.name,vendorName:candidate.vendor.name,driverWhatsappNumber:phone,approvedPayoutMinor:booking.internalFinancials.vendorPayoutMinor,message,whatsappUrl:`https://wa.me/${phone}?text=${encodeURIComponent(message)}`}}
