import "server-only";
import { FieldValue } from "firebase-admin/firestore";
import { getAdminDb } from "../firebaseAdmin";
import { auditEvent, sharedActor } from "./booking-core";
import { getOperationalBooking } from "./booking-repository";
import { findOperationalMatches } from "./matching-repository";
import { applyOfferResponseState, createDriverOfferProjection } from "./offer-core";
import type { DispatchOfferRecord, DispatchOfferStage, DispatchResponseStatus, DriverOfferProjection } from "./offer-types";
import { listDispatchDrivers } from "./repository";

const BOOKINGS="operationalBookings",OFFERS="dispatchOffers";
const iso=(value:unknown)=>value&&typeof value==="object"&&"toDate" in value?(value as{toDate():Date}).toDate().toISOString():String(value??"");
const offerRecord=(doc:FirebaseFirestore.QueryDocumentSnapshot|FirebaseFirestore.DocumentSnapshot)=>{const data=doc.data()!;return{...data,id:doc.id,createdAt:iso(data.createdAt),updatedAt:iso(data.updatedAt),...(data.openedAt?{openedAt:iso(data.openedAt)}:{}),...(data.sentAt?{sentAt:iso(data.sentAt)}:{}),...(data.responseAt?{responseAt:iso(data.responseAt)}:{})} as DispatchOfferRecord};
async function requireProjection(bookingOperationalId:string,candidateId:string){const[booking,matches,drivers]=await Promise.all([getOperationalBooking(bookingOperationalId),findOperationalMatches(bookingOperationalId),listDispatchDrivers()]);if(!booking)throw new Error("Operational booking not found.");if(booking.assignment?.status==="assigned")throw new Error("Booking is already assigned; its Driver response history is now closed.");if(!matches.ready)throw new Error(matches.unavailableReason??"Booking is not eligible for manual dispatch.");const candidate=matches.eligible.find(item=>item.id===candidateId);if(!candidate)throw new Error("Candidate is no longer eligible for this booking. Refresh matches.");const driver=drivers.find(item=>item.id===candidate.driver.id);if(!driver)throw new Error("Dispatch driver was not found.");return createDriverOfferProjection({booking,candidate,driver})}
export async function getDispatchOfferPanel(bookingOperationalId:string){const[booking,matches,drivers,offers]=await Promise.all([getOperationalBooking(bookingOperationalId),findOperationalMatches(bookingOperationalId),listDispatchDrivers(),getAdminDb().collection(BOOKINGS).doc(bookingOperationalId).collection(OFFERS).orderBy("updatedAt","desc").get()]);if(!booking)throw new Error("Operational booking not found.");const projections:DriverOfferProjection[]=[];if(matches.ready&&booking.assignment?.status!=="assigned")for(const candidate of matches.eligible){const driver=drivers.find(item=>item.id===candidate.driver.id);if(driver)try{projections.push(createDriverOfferProjection({booking,candidate,driver}))}catch{/* Invalid number is represented by the missing actionable projection. */}}return{matches,projections,offers:offers.docs.map(offerRecord)}}
type OfferMutation={kind:"prepare"|"opened"|"sent"}|{kind:"response";response:Exclude<DispatchResponseStatus,"not_recorded">;note?:string};
export async function mutateDispatchOffer(bookingOperationalId:string,candidateId:string,mutation:OfferMutation){const projection=await requireProjection(bookingOperationalId,candidateId),db=getAdminDb(),bookingRef=db.collection(BOOKINGS).doc(bookingOperationalId),offerRef=bookingRef.collection(OFFERS).doc(projection.offerId);await db.runTransaction(async tx=>{const[latest,existing]=await Promise.all([tx.get(bookingRef),tx.get(offerRef)]);if(!latest.exists||latest.data()?.lifecycle!=="active"||latest.data()?.readinessStatus!=="ready_for_dispatch"||latest.data()?.internalFinancials?.payoutStatus!=="reviewed"||latest.data()?.assignment?.status==="assigned")throw new Error("Booking is no longer eligible for manual dispatch or is already assigned.");const previous=existing.exists?existing.data() as DispatchOfferRecord:undefined,now=FieldValue.serverTimestamp(),base={bookingOperationalId,bookingId:projection.bookingId,vendorId:projection.vendorId,driverId:projection.driverId,vehicleId:projection.vehicleId,candidateId,vehicleRegistration:projection.vehicleRegistration,driverName:projection.driverName,vendorName:projection.vendorName,driverWhatsappNumber:projection.driverWhatsappNumber,approvedPayoutMinor:projection.approvedPayoutMinor,createdAt:previous?.createdAt??now,createdBy:previous?.createdBy??sharedActor,updatedAt:now,updatedBy:sharedActor,offerStage:previous?.offerStage??"prepared",responseStatus:previous?.responseStatus??"not_recorded"};
  if(!previous)tx.create(bookingRef.collection("events").doc(),auditEvent("driver_offer_prepared",now,{candidateId,vendorId:projection.vendorId,driverId:projection.driverId,vehicleId:projection.vehicleId,approvedPayoutMinor:projection.approvedPayoutMinor}));
  if(mutation.kind==="opened"&&previous?.offerStage!=="sent_manual"&&previous?.offerStage!=="whatsapp_opened"){base.offerStage="whatsapp_opened" as DispatchOfferStage;Object.assign(base,{openedAt:now});tx.create(bookingRef.collection("events").doc(),auditEvent("driver_offer_whatsapp_opened",now,{candidateId,driverId:projection.driverId,vehicleId:projection.vehicleId}))}
  if(mutation.kind==="sent"&&previous?.offerStage!=="sent_manual"){base.offerStage="sent_manual" as DispatchOfferStage;Object.assign(base,{sentAt:now});tx.create(bookingRef.collection("events").doc(),auditEvent("driver_offer_marked_sent",now,{candidateId,driverId:projection.driverId,vehicleId:projection.vehicleId}))}
  if(mutation.kind==="response"&&previous?.responseStatus!==mutation.response){Object.assign(base,applyOfferResponseState(mutation.response,now,mutation.note));tx.create(bookingRef.collection("events").doc(),auditEvent("driver_offer_response_changed",now,{candidateId,driverId:projection.driverId,vehicleId:projection.vehicleId,from:previous?.responseStatus??"not_recorded",to:mutation.response,...(mutation.note?{note:mutation.note}:{})}))}
  tx.set(offerRef,base,{merge:true});});return projection}
