import type { OperationalBooking } from "./booking-types";
import type { TripOperationRecord } from "./trip-operations-types";
import type { CustomerSettlementAdjustment,DriverCollectionReconciliation,PayoutSettlementAdjustment,TripSettlementProjection,TripSettlementRecord,VendorSettlementPayment } from "./settlement-types";
const sum=(values:number[])=>values.reduce((total,value)=>total+value,0);
export function createTripSettlementProjection(input:{booking:OperationalBooking;operation?:TripOperationRecord;record?:TripSettlementRecord;customerAdjustments?:CustomerSettlementAdjustment[];payoutAdjustments?:PayoutSettlementAdjustment[];driverCollection?:DriverCollectionReconciliation;vendorPayments?:VendorSettlementPayment[]}):TripSettlementProjection|null{
 const{booking,operation,record}=input,assignment=booking.assignment;if(!assignment||assignment.status!=="assigned")return null;
 const authoritative=operation?.assignmentId===assignment.id&&operation.currentStatus==="completed"&&booking.lifecycle==="active";
 const originalSale=booking.customerFinancials.originalCustomerTotalMinor??booking.customerFinancials.customerTotalMinor;
 const d2Final=booking.customerFinancials.finalCustomerTotalMinor??booking.customerFinancials.customerTotalMinor;
 const approved=assignment.approvedVendorPayoutMinor;
 const customerAdjustments=input.customerAdjustments??[],payoutAdjustments=input.payoutAdjustments??[],vendorPayments=input.vendorPayments??[];
 const postTrip=sum(customerAdjustments.map(item=>item.signedAmountMinor)),finalSale=d2Final+postTrip,driverActual=input.driverCollection?.actualAmountMinor??0,totalCollected=booking.customerFinancials.receivedAmountMinor+driverActual;
 const customerRemaining=Math.max(0,finalSale-totalCollected),refund=Math.max(0,totalCollected-finalSale),payoutDelta=sum(payoutAdjustments.map(item=>item.signedAmountMinor)),finalPayout=approved+payoutDelta,vendorPaid=sum(vendorPayments.map(item=>item.amountMinor)),vendorRemaining=Math.max(0,finalPayout-vendorPaid),vendorOverpaid=Math.max(0,vendorPaid-finalPayout);
 const expected=record?.driverCollectionExpectedMinor??0,warnings:string[]=[];if(customerRemaining)warnings.push("Customer balance remains unresolved.");if(refund)warnings.push("Customer refund / credit due requires resolution.");if(vendorRemaining)warnings.push("Vendor / Driver payable remains unresolved.");if(vendorOverpaid)warnings.push("Vendor / Driver payment exceeds final payout.");if(expected&&!input.driverCollection)warnings.push("Driver collection requires reconciliation.");if(finalPayout<0)warnings.push("Final payout cannot be negative.");
 const hasActivity=customerAdjustments.length+payoutAdjustments.length+vendorPayments.length+(input.driverCollection?1:0)>0,critical=refund>0||vendorOverpaid>0||finalPayout<0;
 const state=!authoritative?"not_ready":record?.finalizedAt?"settled":critical?"review_required":hasActivity?"partially_settled":"ready_to_settle";
 return{bookingOperationalId:booking.id,bookingId:booking.bookingId,assignmentId:assignment.id,driverId:assignment.assignedDriverId,vehicleId:assignment.assignedVehicleId,eligible:authoritative,state,originalSaleMinor:originalSale,preTripAdjustmentsMinor:d2Final-originalSale,postTripAdjustmentsMinor:postTrip,finalSaleMinor:finalSale,rentkaReceivedMinor:booking.customerFinancials.receivedAmountMinor,driverCollectionExpectedMinor:expected,driverCollectionActualMinor:driverActual,customerRemainingMinor:customerRemaining,refundCreditDueMinor:refund,approvedPayoutMinor:approved,payoutAdjustmentsMinor:payoutDelta,finalPayoutMinor:finalPayout,vendorPaidMinor:vendorPaid,vendorRemainingMinor:vendorRemaining,vendorOverpaidMinor:vendorOverpaid,grossMarginMinor:finalSale-finalPayout,warnings,customerAdjustments,payoutAdjustments,...(input.driverCollection?{driverCollection:input.driverCollection}:{}),vendorPayments,...(record?.finalizedAt?{finalizedAt:record.finalizedAt}:{})};
}
export function assertSettlementCanFinalize(projection:TripSettlementProjection){if(!projection.eligible)throw new Error("Settlement is available only after the authoritative trip is completed.");if(projection.finalizedAt)return;if(projection.warnings.length)throw new Error(`Settlement cannot be finalized: ${projection.warnings.join(" ")}`)}
