import "server-only";
import { FieldValue } from "firebase-admin/firestore";
import { getAdminDb } from "../firebaseAdmin";
import { assertMinor,auditEvent,sharedActor } from "./booking-core";
import type { OperationalBooking } from "./booking-types";
import { assertSettlementCanFinalize,createTripSettlementProjection } from "./settlement-core";
import type { CustomerSettlementAdjustment,DriverCollectionReconciliation,PayoutSettlementAdjustment,SettlementMutation,TripSettlementRecord,VendorSettlementPayment } from "./settlement-types";
import type { TripOperationRecord } from "./trip-operations-types";
const BOOKINGS="operationalBookings",SETTLEMENTS="tripSettlements";
const iso=(value:unknown)=>value&&typeof value==="object"&&"toDate" in value?(value as{toDate():Date}).toDate().toISOString():String(value??"");
const entry=<T>(doc:FirebaseFirestore.DocumentSnapshot)=>{const data=doc.data()!;return{...data,id:doc.id,createdAt:iso(data.createdAt)} as T};
async function context(bookingOperationalId:string){const db=getAdminDb(),bookingRef=db.collection(BOOKINGS).doc(bookingOperationalId),bookingSnap=await bookingRef.get();if(!bookingSnap.exists)return null;const booking={...bookingSnap.data(),id:bookingSnap.id} as OperationalBooking,assignment=booking.assignment;if(!assignment)return null;const settlementRef=bookingRef.collection(SETTLEMENTS).doc(assignment.id),[operationSnap,recordSnap,customerSnap,payoutSnap,collectionSnap,paymentsSnap]=await Promise.all([bookingRef.collection("tripOperations").doc(assignment.id).get(),settlementRef.get(),settlementRef.collection("customerAdjustments").orderBy("createdAt").get(),settlementRef.collection("payoutAdjustments").orderBy("createdAt").get(),settlementRef.collection("driverCollections").orderBy("createdAt","desc").limit(1).get(),settlementRef.collection("vendorPayments").orderBy("createdAt").get()]);return{db,bookingRef,settlementRef,booking,operation:operationSnap.exists?{...operationSnap.data(),id:operationSnap.id} as TripOperationRecord:undefined,record:recordSnap.exists?{...recordSnap.data(),id:recordSnap.id,createdAt:iso(recordSnap.data()!.createdAt),...(recordSnap.data()!.finalizedAt?{finalizedAt:iso(recordSnap.data()!.finalizedAt)}:{})} as TripSettlementRecord:undefined,customerAdjustments:customerSnap.docs.map(doc=>entry<CustomerSettlementAdjustment>(doc)),payoutAdjustments:payoutSnap.docs.map(doc=>entry<PayoutSettlementAdjustment>(doc)),driverCollection:collectionSnap.docs[0]?entry<DriverCollectionReconciliation>(collectionSnap.docs[0]):undefined,vendorPayments:paymentsSnap.docs.map(doc=>entry<VendorSettlementPayment>(doc))}}
export async function getTripSettlementPanel(bookingOperationalId:string){const value=await context(bookingOperationalId);if(!value)return null;const projection=createTripSettlementProjection(value);return projection?{projection}:null}
export async function mutateTripSettlement(bookingOperationalId:string,assignmentId:string,mutation:SettlementMutation){const value=await context(bookingOperationalId);if(!value)throw new Error("Operational booking not found.");const projection=createTripSettlementProjection(value);if(!projection||!projection.eligible)throw new Error("Trip Settlement is available only after the authoritative trip is completed.");if(projection.assignmentId!==assignmentId)throw new Error("The assignment changed. Refresh Trip Settlement.");if(value.record?.finalizedAt){if(mutation.kind==="finalize")return projection;throw new Error("This settlement is finalized. Historical finance entries cannot be rewritten.");}if(mutation.kind!=="finalize")assertMinor(mutation.kind==="driver_collection"?mutation.actualAmountMinor:mutation.amountMinor,"Amount",{allowZero:mutation.kind==="driver_collection"});if(mutation.kind==="payout_adjustment"&&mutation.reason.trim().length<3)throw new Error("Payout adjustment reason is required.");
 const now=FieldValue.serverTimestamp(),base={bookingOperationalId,bookingId:projection.bookingId,assignmentId,driverId:projection.driverId,vehicleId:projection.vehicleId,originalFinalSaleMinor:value.booking.customerFinancials.finalCustomerTotalMinor??value.booking.customerFinancials.customerTotalMinor,originalApprovedPayoutMinor:projection.approvedPayoutMinor,driverCollectionExpectedMinor:value.record?.driverCollectionExpectedMinor??value.booking.customerFinancials.balanceMinor,createdAt:value.record?.createdAt??now,createdBy:sharedActor,updatedAt:now,updatedBy:sharedActor};
 await value.db.runTransaction(async tx=>{const[bookingSnap,settlementSnap]=await Promise.all([tx.get(value.bookingRef),tx.get(value.settlementRef)]);if(!bookingSnap.exists)throw new Error("Operational booking not found.");const current={...bookingSnap.data(),id:bookingSnap.id} as OperationalBooking;if(current.lifecycle!=="active"||current.assignment?.id!==assignmentId||current.assignment.status!=="assigned")throw new Error("The authoritative assignment changed.");if(settlementSnap.data()?.finalizedAt){if(mutation.kind==="finalize")return;throw new Error("This settlement is already finalized.");}const eventRef=value.bookingRef.collection("events").doc();tx.set(value.settlementRef,base,{merge:true});let eventType:Parameters<typeof auditEvent>[0],metadata:Record<string,unknown>={assignmentId};
  if(mutation.kind==="customer_adjustment"){const signed=mutation.direction==="charge"?mutation.amountMinor:-mutation.amountMinor;tx.create(value.settlementRef.collection("customerAdjustments").doc(),{...mutation,signedAmountMinor:signed,createdAt:now,createdBy:sharedActor});eventType="trip_settlement_customer_adjustment";metadata={...metadata,direction:mutation.direction,category:mutation.category,amountMinor:mutation.amountMinor,beforeFinalSaleMinor:projection.finalSaleMinor,afterFinalSaleMinor:projection.finalSaleMinor+signed}}
  else if(mutation.kind==="payout_adjustment"){const signed=mutation.direction==="addition"?mutation.amountMinor:-mutation.amountMinor;if(projection.finalPayoutMinor+signed<0)throw new Error("Payout adjustment cannot make final payout negative.");tx.create(value.settlementRef.collection("payoutAdjustments").doc(),{...mutation,signedAmountMinor:signed,createdAt:now,createdBy:sharedActor});eventType="trip_settlement_payout_adjustment";metadata={...metadata,direction:mutation.direction,reason:mutation.reason,amountMinor:mutation.amountMinor,originalApprovedPayoutMinor:projection.approvedPayoutMinor,beforeFinalPayoutMinor:projection.finalPayoutMinor,afterFinalPayoutMinor:projection.finalPayoutMinor+signed}}
  else if(mutation.kind==="driver_collection"){if(value.driverCollection)throw new Error("Driver collection is already reconciled; history cannot be overwritten.");tx.create(value.settlementRef.collection("driverCollections").doc(),{...mutation,expectedAmountMinor:projection.driverCollectionExpectedMinor,createdAt:now,createdBy:sharedActor});eventType="trip_settlement_driver_collection_reconciled";metadata={...metadata,status:mutation.status,expectedAmountMinor:projection.driverCollectionExpectedMinor,actualAmountMinor:mutation.actualAmountMinor,rentkaReceivedMinor:projection.rentkaReceivedMinor}}
  else if(mutation.kind==="vendor_payment"){tx.create(value.settlementRef.collection("vendorPayments").doc(),{...mutation,createdAt:now,createdBy:sharedActor});eventType="trip_settlement_vendor_payment_recorded";metadata={...metadata,amountMinor:mutation.amountMinor,beforeVendorPaidMinor:projection.vendorPaidMinor,afterVendorPaidMinor:projection.vendorPaidMinor+mutation.amountMinor}}
  else{assertSettlementCanFinalize(projection);tx.update(value.settlementRef,{finalizedAt:now,finalizedBy:sharedActor,updatedAt:now,updatedBy:sharedActor});eventType="trip_settlement_finalized";metadata={...metadata,finalSaleMinor:projection.finalSaleMinor,finalPayoutMinor:projection.finalPayoutMinor,grossMarginMinor:projection.grossMarginMinor}}
  tx.create(eventRef,auditEvent(eventType,now,metadata));
 });return(await getTripSettlementPanel(bookingOperationalId))!.projection}
