import type { OperationalBooking } from "./booking-types";
import type { TripOperationRecord, TripOperationsProjection, TripStatus, TripTransition } from "./trip-operations-types";
const NEXT:Record<TripStatus,TripStatus|undefined>={assigned:"en_route",en_route:"arrived",arrived:"customer_onboard",customer_onboard:"completed",completed:undefined};
const ACTION:Partial<Record<TripStatus,string>>={assigned:"Start Trip / En Route",en_route:"Mark Arrived",arrived:"Customer Onboard",customer_onboard:"Complete Trip"};
export function nextTripStatus(status:TripStatus){return NEXT[status]}
export function validateTripTransition(current:TripStatus,requested:TripStatus){if(current===requested)return{duplicate:true};if(NEXT[current]!==requested)throw new Error(`Invalid trip transition from ${current} to ${requested}.`);return{duplicate:false}}
export function assertTripAllowsReassignment(status:TripStatus|undefined){if(status&&status!=="assigned")throw new Error("This trip has already started. Use a controlled trip recovery process before changing the assignment.")}
export function createTripOperationsProjection(booking:OperationalBooking,record?:TripOperationRecord,history:TripTransition[]=[]):TripOperationsProjection|null{if(booking.assignment?.status!=="assigned")return null;const assignment=booking.assignment;if(record&&record.assignmentId!==assignment.id)return null;const currentStatus=record?.currentStatus??"assigned",nextStatus=nextTripStatus(currentStatus);return{bookingOperationalId:booking.id,bookingId:booking.bookingId,assignmentId:assignment.id,driverId:assignment.assignedDriverId,vehicleId:assignment.assignedVehicleId,driverName:assignment.driverSnapshot.name,vehicleLabel:`${assignment.vehicleSnapshot.make} ${assignment.vehicleSnapshot.model}${assignment.vehicleSnapshot.modelYear?` ${assignment.vehicleSnapshot.modelYear}`:""} - ${assignment.vehicleSnapshot.registrationNumber}`,currentStatus,...(nextStatus?{nextStatus,nextAction:ACTION[currentStatus]}:{}),...(history[0]?.timestamp?{latestTransitionAt:history[0].timestamp}:{}),history}}
const responsibility=(value:unknown)=>value==="customer"?"Customer responsibility / not included":value==="rentka"?"RentKA/vendor responsibility":value==="included"?"Included":value==="not_applicable"||value==="not-applicable"?"Not applicable":"Confirm with RentKA";
const food=(value:unknown)=>{if(!value||typeof value!=="object")return responsibility(value);const item=value as{mode?:string;amountMinor?:number;note?:string};if(item.mode==="customer")return"Customer provides/pays directly";if(item.mode==="allowance"&&typeof item.amountMinor==="number")return`Rs. ${(item.amountMinor/100).toLocaleString("en-PK")}/day allowance`;return item.note||"Confirm with RentKA"};
export function createDriverTripProjection(booking:OperationalBooking,record?:TripOperationRecord,history:TripTransition[]=[]){const base=createTripOperationsProjection(booking,record,history);if(!base)return null;const r=(booking.responsibilities??{}) as Record<string,unknown>;return{...base,customerName:booking.customer.name,customerPhone:booking.customer.phone,pickup:booking.itinerary.pickup,...(booking.itinerary.pickupLocation?.mapLink?{pickupMapLink:booking.itinerary.pickupLocation.mapLink}:{}),destination:booking.itinerary.destinationOrUsage||"Confirm itinerary with RentKA",...(booking.itinerary.destinationLocation?.mapLink?{destinationMapLink:booking.itinerary.destinationLocation.mapLink}:{}),pickupDate:booking.itinerary.travelDate,pickupTime:booking.itinerary.pickupTime,responsibilities:[`Fuel: ${responsibility(r.fuel)}`,`Toll: ${responsibility(r.toll)}`,`Parking: ${responsibility(r.parking)}`,`Driver food/accommodation: ${food(r.driverFoodAccommodation)}`],supportPhone:"0302 058 9999"}}

