import type { OperationalBooking } from "./booking-types";
import { assertCurrentBroadcast,assertCurrentOfferRevision,validateCounterPayout } from "./driver-offer-portal-core.ts";
import { isOfferExpired } from "./dispatch-orchestration-core.ts";
import { generalArea } from "./offer-core.ts";
import type { MatchProjection } from "./matching-types";
import type { DispatchOfferRecord } from "./offer-types";
import type { DispatchDriver,DispatchVehicle,DispatchVendor } from "./types";
import { isCurrentFulfillmentQuickAdd } from "./vendor-fulfillment-quick-add-core.ts";
import type { SecureVendorOfferProjection,VendorFulfillmentProposal,VendorOfferResponse } from "./vendor-offer-portal-types";

export function assertVendorOfferIdentity(offer:DispatchOfferRecord,vendorId?:string){if(offer.recipientType!=="vendor"||!offer.recipientId||!offer.supplyAccountId||offer.recipientId!==offer.supplyAccountId||offer.vendorId!==offer.supplyAccountId||(vendorId&&offer.supplyAccountId!==vendorId))throw new Error("Vendor offer authorization does not match.");return offer}
export function assertVendorOfferCurrent(booking:OperationalBooking,offer:DispatchOfferRecord,activeBroadcastId:string|undefined,now=new Date()){assertVendorOfferIdentity(offer);if(booking.lifecycle!=="active"||booking.assignment?.status==="assigned"||offer.portalStatus==="closed"||isOfferExpired(offer.offerExpiresAt,now))throw new Error("This vendor offer is no longer available.");assertCurrentBroadcast(offer,activeBroadcastId);if(booking.internalFinancials.vendorPayoutMinor!==offer.approvedPayoutMinor)throw new Error("This vendor offer is no longer available.");return offer}
export function assertVendorResponseOpen(offer:Pick<DispatchOfferRecord,"responseStatus">){if(["accepted","declined","countered","expired","closed","cancelled","not_selected"].includes(offer.responseStatus))throw new Error("This vendor offer is no longer available.");return offer}
export function validateVendorProposal(input:{booking:OperationalBooking;offer:DispatchOfferRecord;vendor:DispatchVendor;driver:DispatchDriver;vehicle:DispatchVehicle;matches:MatchProjection}){const{booking,offer,vendor,driver,vehicle,matches}=input;assertVendorOfferIdentity(offer,vendor.id);if(booking.lifecycle!=="active"||booking.assignment?.status==="assigned")throw new Error("This booking no longer accepts fulfillment proposals.");if(offer.responseStatus!=="accepted"||offer.agreedPayoutMinor===undefined)throw new Error("Accept the current vendor offer before proposing resources.");if(vendor.supplyClassification!=="vendor_managed"||driver.vendorId!==vendor.id||driver.supplyRelationship!=="vendor_managed")throw new Error("Selected Driver does not belong to this vendor-managed supply account.");if(vehicle.vendorId!==vendor.id||!(vehicle.controlRelationship==="vendor_owned"||vehicle.controlRelationship==="vendor_managed"))throw new Error("Selected Vehicle does not belong to this vendor-managed supply account.");const context={bookingOperationalId:booking.id,offerId:offer.id,vendorId:vendor.id},driverPending=isCurrentFulfillmentQuickAdd(driver,context)&&(!driver.active||driver.status!=="available"),vehiclePending=isCurrentFulfillmentQuickAdd(vehicle,context)&&(!vehicle.active||vehicle.status!=="available"),eligible=matches.ready&&matches.eligible.some(item=>item.vendor.id===vendor.id&&item.driver.id===driver.id&&item.vehicle.id===vehicle.id);if(!eligible)throw new Error("Selected Driver and Vehicle are no longer an eligible pair.");return{vendor,driver,vehicle,driverReviewRequired:driverPending,vehicleReviewRequired:vehiclePending}}
export function createSecureVendorOfferProjection(input:{booking:OperationalBooking;offer:DispatchOfferRecord;responses?:VendorOfferResponse[];proposals?:VendorFulfillmentProposal[];matches?:MatchProjection;vendor:DispatchVendor;drivers?:DispatchDriver[];vehicles?:DispatchVehicle[]}):SecureVendorOfferProjection{const{booking,offer,vendor}=input;assertVendorOfferIdentity(offer,vendor.id);const closed=offer.portalStatus==="closed"||isOfferExpired(offer.offerExpiresAt)||booking.lifecycle!=="active"||booking.assignment?.status==="assigned",canPropose=offer.responseStatus==="accepted"&&!closed,pairs=canPropose?input.matches?.eligible.filter(item=>item.vendor.id===vendor.id)??[]:[],drivers=new Map<string,{label:string;reviewRequired?:boolean;submittedDuringFulfillment?:boolean}>(),vehicles=new Map<string,{label:string;reviewRequired?:boolean;submittedDuringFulfillment?:boolean}>();for(const pair of pairs){drivers.set(pair.driver.id,{label:pair.driver.name});vehicles.set(pair.vehicle.id,{label:pair.vehicle.label})}const context={bookingOperationalId:booking.id,offerId:offer.id,vendorId:vendor.id};if(canPropose)for(const driver of input.drivers??[])if(isCurrentFulfillmentQuickAdd(driver,context))drivers.set(driver.id,{label:driver.name,reviewRequired:!driver.active||driver.status!=="available",submittedDuringFulfillment:true});if(canPropose)for(const vehicle of input.vehicles??[])if(isCurrentFulfillmentQuickAdd(vehicle,context))vehicles.set(vehicle.id,{label:[vehicle.make,vehicle.model,vehicle.modelYear,`— ${vehicle.registrationNumber}`].filter(Boolean).join(" "),reviewRequired:!vehicle.active||vehicle.status!=="available",submittedDuringFulfillment:true});const latest=input.responses?.[0],proposal=input.proposals?.[0];return{bookingOperationalId:booking.id,bookingId:booking.bookingId,offerId:offer.id,vendorId:vendor.id,vendorName:vendor.name,offeredPayoutMinor:offer.currentOfferedPayoutMinor??offer.approvedPayoutMinor,responseStatus:offer.responseStatus,generalPickupArea:generalArea(booking.itinerary.pickup),generalDestination:generalArea(booking.itinerary.destinationOrUsage),travelDate:booking.itinerary.travelDate,pickupTime:booking.itinerary.pickupTime,vehicleRequirement:booking.requestedVehicle.categoryOrModel,packageInformation:typeof booking.sourceSnapshot.durationHours==="number"?`${booking.serviceType} · ${booking.sourceSnapshot.durationHours} hours`:booking.serviceType,offerExpiresAt:offer.offerExpiresAt??"",supportPhone:"0302 058 9999",closed,...(latest?{latestResponse:latest}:{}),proposalStatus:offer.proposalStatus??"not_provided",...(proposal?{currentProposal:proposal}:{}),eligibleDrivers:[...drivers].map(([id,item])=>({id,...item})),eligibleVehicles:[...vehicles].map(([id,item])=>({id,...item})),eligiblePairs:pairs.map(pair=>({driverId:pair.driver.id,vehicleId:pair.vehicle.id}))}}
export{assertCurrentOfferRevision,validateCounterPayout};
