import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { hasAdminSession } from "../_lib/session";
import { getAirportPricingConfig } from "@/lib/airport/config";
import { saveAirportPricing } from "./actions";
export const metadata:Metadata={title:"Airport Pricing | RentKA Admin",robots:{index:false,follow:false}};
const field=(id:string,label:string,value:number)=><label className="text-sm font-semibold text-slate-700">{label}<input name={id} type="number" min="0" step="any" defaultValue={value} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"/></label>;
const check=(id:string,label:string,value:boolean)=><label className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input name={id} value="21" type="checkbox" defaultChecked={value}/>{label}</label>;
export default async function AirportPricingPage(){if(!(await hasAdminSession()))redirect("/admin/pricing-calculator");const config=await getAirportPricingConfig();return <main className="min-h-screen bg-slate-100 p-4 md:p-8"><div className="mx-auto max-w-6xl"><div className="mb-6 flex items-center justify-between"><div><h1 className="text-3xl font-black text-[#0F2B46]">Airport pricing</h1><p className="text-slate-600">Server-side customer pricing configuration · version {config.version}</p></div><a href="/admin/pricing-calculator" className="font-semibold text-[#0F2B46] underline">Trip calculator</a></div><form action={saveAirportPricing} className="space-y-5"><div className="grid gap-4 rounded-2xl bg-white p-5 shadow md:grid-cols-2">{field("quoteValidityMinutes","Quote validity (minutes)",config.quoteValidityMinutes)}{field("advancePercentage","Future advance percentage",config.advancePercentage)}</div>{config.vehicles.map(v=><section key={v.id} className="rounded-2xl bg-white p-5 shadow"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black text-[#0F2B46]">{v.name}</h2>{check(`${v.id}.active`,"Bookable",v.active)}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{field(`${v.id}.minimumFare`,"Minimum fare",v.minimumFare)}{field(`${v.id}.includedKm`,"Included customer km",v.includedKm)}{field(`${v.id}.additionalKmRate`,"Additional / operational km rate",v.additionalKmRate)}{field(`${v.id}.operationalKm`,"Operational km",v.operationalKm)}{field(`${v.id}.operationalAllowance`,"Operational allowance (Rs)",v.operationalAllowance)}{field(`${v.id}.pickupAdjustment`,"Pickup adjustment",v.pickupAdjustment)}{field(`${v.id}.dropoffAdjustment`,"Drop-off adjustment",v.dropoffAdjustment)}{field(`${v.id}.lateNightSurcharge`,"Late-night surcharge",v.lateNightSurcharge)}{field(`${v.id}.waitingAllowanceMinutes`,"Waiting allowance (min)",v.waitingAllowanceMinutes)}{field(`${v.id}.additionalWaitingRate`,"Additional waiting rate",v.additionalWaitingRate)}</div><div className="mt-4 flex flex-wrap gap-5">{check(`${v.id}.lateNightEnabled`,"Late night enabled",v.lateNightEnabled)}{check(`${v.id}.fuelIncluded`,"Fuel included",v.fuelIncluded)}{check(`${v.id}.tollIncluded`,"Tolls included",v.tollIncluded)}{check(`${v.id}.parkingIncluded`,"Parking included",v.parkingIncluded)}</div></section>)}<button className="w-full rounded-xl bg-[#5BAE4A] py-4 font-bold text-white">Save airport pricing</button></form></div></main>}
