/* eslint-disable react-hooks/purity -- current time is checked only to disable an already-expired approval. */
"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { BroadcastRecipient,BroadcastSafePreview } from "@/lib/dispatch/broadcast-approval-core";
import { approveBroadcastAction } from "./actions";

const money=(minor:number)=>`Rs. ${(minor/100).toLocaleString("en-PK",{maximumFractionDigits:2})}`;
const expiryLabel=(value:string)=>value?new Date(value).toLocaleString("en-PK",{dateStyle:"medium",timeStyle:"short"}):"Choose an expiry";

export default function BroadcastApproval({bookingDocumentId,recipients,preview,currentRevision,activeBroadcastId,defaultOfferExpiresAt}:{bookingDocumentId:string;recipients:BroadcastRecipient[];preview:BroadcastSafePreview;currentRevision:number;activeBroadcastId:string;defaultOfferExpiresAt:string}){
 const[selected,setSelected]=useState<string[]>([]),[preset,setPreset]=useState("30"),[custom,setCustom]=useState(""),[expiresAt,setExpiresAt]=useState(defaultOfferExpiresAt),[busy,setBusy]=useState(false),[result,setResult]=useState<{ok:boolean;message:string}|null>(null),router=useRouter();
 const validExpiry=!!expiresAt&&new Date(expiresAt).getTime()>Date.now(),toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
 const submit=async()=>{if(!selected.length||!validExpiry)return;if(!window.confirm(`Approve this broadcast for ${selected.length} selected Driver${selected.length===1?"":"s"}? No WhatsApp messages will be sent yet.`))return;const form=new FormData();form.set("bookingDocumentId",bookingDocumentId);selected.forEach(id=>form.append("candidateId",id));form.set("offerExpiresAt",expiresAt);form.set("payoutSnapshotMinor",String(preview.approvedPayoutMinor));form.set("expectedCurrentRevision",String(currentRevision));setBusy(true);setResult(null);const response=await approveBroadcastAction(form);setBusy(false);setResult(response);if(response.ok)router.refresh()};
 const recommended=recipients.filter(item=>item.recommended),other=recipients.filter(item=>!item.recommended),group=(title:string,items:BroadcastRecipient[])=><div><h5 className="mb-2 text-sm font-black">{title} ({items.length})</h5><div className="grid gap-2">{items.map(item=><label key={item.candidateId} className={`cursor-pointer rounded-lg border p-3 ${selected.includes(item.candidateId)?"border-indigo-600 bg-indigo-50":"bg-white"}`}><div className="flex items-start gap-3"><input type="checkbox" checked={selected.includes(item.candidateId)} onChange={()=>toggle(item.candidateId)} className="mt-1 h-4 w-4"/><div><b>{item.driverName}</b> · {item.vendorName}<p className="text-xs">{item.compatibility.replaceAll("_"," ")} · {item.reasons.slice(0,3).join(" · ")}</p></div></div></label>)}</div></div>;
 const changePreset=(value:string)=>{setPreset(value);if(value!=="custom")setExpiresAt(new Date(Date.now()+Number(value)*60000).toISOString())},changeCustom=(value:string)=>{setCustom(value);const date=new Date(value);setExpiresAt(value&&!Number.isNaN(date.getTime())?date.toISOString():"")};
 return <section className="mt-5 rounded-xl border-2 border-indigo-700 bg-indigo-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="text-lg font-black text-indigo-950">D6 Broadcast Approval</h4><p className="text-sm">Select Drivers explicitly. Recommended Drivers are never auto-selected.</p></div><div className="text-right text-xs"><b>{selected.length} driver{selected.length===1?"":"s"} selected</b><p>Current revision: {currentRevision}{activeBroadcastId?" · Existing approved broadcast":""}</p></div></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="space-y-4">{group("Recommended",recommended)}{group("Other eligible",other)}{!recipients.length&&<p className="rounded bg-amber-50 p-3 text-sm">No eligible Driver recipient is available.</p>}</div><div className="space-y-4"><div className="rounded-xl bg-white p-4"><h5 className="font-black">Privacy-safe Driver preview</h5><pre className="mt-2 whitespace-pre-wrap text-sm">{`Trip Offer — ${preview.bookingId}\n\nRoute: ${preview.pickupArea} → ${preview.destinationArea}\nDate: ${preview.travelDate}\nPickup: ${preview.pickupTime}\nVehicle Requirement: ${preview.vehicleRequirement}\nDuty: ${preview.dutySummary}\nYour offered payout: ${money(preview.approvedPayoutMinor)}\nPlease respond before: ${expiryLabel(expiresAt)}\n\n[Secure offer link will be included]`}</pre><p className="mt-2 text-xs font-bold text-green-800">No customer identity, phone, exact address, map pin, customer price, or physical registration is included.</p></div><div className="rounded-xl bg-white p-4"><label className="text-sm font-bold">Offer expires<select value={preset} onChange={event=>changePreset(event.target.value)} className="mt-1 block w-full rounded border p-2"><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">1 hour</option><option value="120">2 hours</option><option value="240">4 hours</option><option value="custom">Custom</option></select></label>{preset==="custom"&&<label className="mt-3 block text-sm font-bold">Custom expiry<input type="datetime-local" value={custom} onChange={event=>changeCustom(event.target.value)} className="mt-1 block w-full rounded border p-2"/></label>}<button type="button" disabled={busy||!selected.length||!validExpiry||!recipients.length} onClick={submit} className="mt-4 w-full rounded-lg bg-indigo-800 px-4 py-3 font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300">{busy?"Approving…":"Approve Broadcast"}</button><p className="mt-2 text-xs">Approval creates queued records only. No messages sent yet.</p>{result&&<p role="status" className={`mt-3 rounded p-3 text-sm font-bold ${result.ok?"bg-green-100 text-green-900":"bg-red-100 text-red-900"}`}>{result.message}</p>}</div></div></div></section>;
}
