"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { DriverInstructionProjection, DriverInstructionRecord } from "@/lib/dispatch/driver-instructions-types";
import { mutateDriverInstructionsAction } from "./actions";

export default function DriverInstructions({projection,record}:{projection:DriverInstructionProjection;record:DriverInstructionRecord|null}){
 const[busy,setBusy]=useState(false),[error,setError]=useState(""),router=useRouter();
 const action=async(kind:"copied"|"whatsapp_opened"|"marked_shared")=>{const form=new FormData();form.set("bookingDocumentId",projection.bookingOperationalId);form.set("assignmentId",projection.assignmentId);form.set("kind",kind);setBusy(true);setError("");try{const result=await mutateDriverInstructionsAction(form);if(!result.ok)throw new Error(result.message);router.refresh();return result}catch(reason){setError(reason instanceof Error?reason.message:"Unable to update Driver Instructions.");return null}finally{setBusy(false)}};
 const copy=async()=>{try{await navigator.clipboard.writeText(projection.message);await action("copied")}catch(reason){setError(reason instanceof Error?reason.message:"Unable to copy Driver Instructions.")}};
 const open=async()=>{const popup=window.open("","_blank");if(popup)popup.opener=null;const result=await action("whatsapp_opened");if(result?.whatsappUrl){if(popup)popup.location.href=result.whatsappUrl;else window.location.href=result.whatsappUrl}else popup?.close()};
 return <section className="lg:col-span-2 rounded-xl border-2 border-green-700 bg-green-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-green-800">D8 - Selected Driver Only</p><h3 className="text-xl font-black text-green-950">Driver Instructions</h3><p className="text-sm text-green-900">Final assigned Driver: <b>{projection.driverName}</b>. Manual sharing only; nothing is sent automatically.</p></div><div className="text-right text-xs text-slate-600"><p>Copied: {record?.lastCopiedAt?new Date(record.lastCopiedAt).toLocaleString("en-PK"):"not yet"}</p><p>WhatsApp opened: {record?.lastWhatsappOpenedAt?new Date(record.lastWhatsappOpenedAt).toLocaleString("en-PK"):"not yet"}</p><p>Marked shared: {record?.sharedAt?new Date(record.sharedAt).toLocaleString("en-PK"):"not yet"}</p></div></div>{projection.missingFields.length>0&&<div role="alert" className="mt-3 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm font-bold text-amber-900">Missing required instruction data: {projection.missingFields.join(", ")}. Confirm it before sharing; RentKA has not invented a value.</div>}<details open className="mt-4 rounded-lg border bg-white p-3"><summary className="cursor-pointer font-bold">Preview final driver message</summary><pre className="mt-3 whitespace-pre-wrap text-sm">{projection.message}</pre></details><div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={copy} className="rounded-lg bg-slate-800 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Copy Instructions</button><button type="button" disabled={busy||!projection.whatsappUrl} onClick={open} className="rounded-lg bg-green-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Open WhatsApp</button><button type="button" disabled={busy||!!record?.sharedAt} onClick={()=>action("marked_shared")} className="rounded-lg border border-green-700 bg-white px-4 py-2 text-sm font-bold text-green-900 disabled:opacity-50">{record?.sharedAt?"Marked Shared":"Mark Instructions Shared"}</button></div><p className="mt-2 text-xs text-slate-600">Opening WhatsApp records only that the compose window was opened. It is not a delivery or read receipt.</p>{error&&<p role="alert" className="mt-3 rounded bg-red-50 p-2 text-sm font-bold text-red-800">{error}</p>}</section>;
}
