import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { hasAdminSession } from "../_lib/session";
import DispatchAdminNav from "../_components/DispatchAdminNav";
import { input, label } from "../_components/DispatchFormFields";
import { getOperationalBooking, listOperationalBookings, listOperationalEvents } from "@/lib/dispatch/booking-repository";
import { OPERATIONAL_SOURCE_TYPES, type OperationalBooking } from "@/lib/dispatch/booking-types";
import { NORMAL_RENTAL_ZONES } from "@/lib/normal-rental/zones";
import { applyCustomerDiscountAction, cancelBookingAction, createManualBookingAction, importBookingAction, overridePaymentAction, recordPaymentAction, reviewPayoutAction, updateResponsibilitiesAction } from "./actions";
import { formatDispatchAdminDate } from "@/lib/dispatch/validation";
import ManualBookingForm from "./ManualBookingForm";
import { listDispatchVehicles } from "@/lib/dispatch/vehicles";
import { getDispatchOfferPanel } from "@/lib/dispatch/offer-repository";
import MatchPanel from "./MatchPanel";
import OperationalResponsibilities from "./OperationalResponsibilities";
import { getAssignmentPanel } from "@/lib/dispatch/assignment-repository";
import AssignmentPanel from "./AssignmentPanel";

export const metadata:Metadata={title:"Dispatch Queue | RentKA Admin",robots:{index:false,follow:false,noarchive:true,nosnippet:true}};
const money=(n:number)=>`Rs ${(n/100).toLocaleString("en-PK",{maximumFractionDigits:2})}`;
const tabs=["all","awaiting_advance","advance_recorded","needs_vendor_payout","ready_for_dispatch","override_approved","cancelled"] as const;
const badge=(s:string)=>s==="ready_for_dispatch"?"bg-green-100 text-green-800":s==="cancelled"?"bg-red-100 text-red-800":s==="override_approved"?"bg-purple-100 text-purple-800":"bg-amber-50 text-amber-900";

function Financials({b}:{b:OperationalBooking}){const values=[["Original sale",b.customerFinancials.originalCustomerTotalMinor??b.customerFinancials.customerTotalMinor],["Discounts",b.customerFinancials.customerDiscountTotalMinor??0],["Final sale",b.customerFinancials.finalCustomerTotalMinor??b.customerFinancials.customerTotalMinor],["Required advance",b.customerFinancials.requiredAdvanceMinor],["Received",b.customerFinancials.receivedAmountMinor],["Balance",b.customerFinancials.balanceMinor],["Refund / credit due",b.customerFinancials.refundCreditDueMinor??0]] as const;return <><div className="mt-4 grid gap-3 rounded-xl bg-blue-50 p-4 text-sm sm:grid-cols-4 lg:grid-cols-7">{values.map(([title,value])=><div key={title}><p className="text-slate-500">{title}</p><b>{money(value)}</b></div>)}</div><div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><b>Internal vendor payout:</b> {b.internalFinancials.payoutStatus==="reviewed"?money(b.internalFinancials.vendorPayoutMinor??0):"Needs review"}</div></>}

function D2Forms({b}:{b:OperationalBooking}){return <>
 <form action={recordPaymentAction} className="rounded-xl border p-4"><input type="hidden" name="bookingDocumentId" value={b.id}/><h3 className="font-black">Record Payment</h3><label className={`${label} mt-3 block`}>Amount (Rs)<input className={input} required name="amount" inputMode="decimal"/></label><label className={`${label} mt-2 block`}>Method<select className={input} name="method"><option value="">Not specified</option><option>Bank transfer</option><option>Cash</option><option>JazzCash</option><option>Easypaisa</option><option>Other</option></select></label><label className={`${label} mt-2 block`}>Reference<input className={input} name="reference"/></label><label className={`${label} mt-2 block`}>Note<input className={input} name="note"/></label><button className="mt-3 rounded-lg bg-blue-700 px-4 py-2 font-bold text-white">Record payment</button></form>
 <form action={applyCustomerDiscountAction} className="rounded-xl border border-amber-200 bg-amber-50 p-4"><input type="hidden" name="bookingDocumentId" value={b.id}/><h3 className="font-black">Apply Customer Discount / Adjustment</h3><p className="mt-1 text-xs">Reduces final customer sale only. Vendor payout is unchanged.</p><label className={`${label} mt-3 block`}>Discount amount (Rs)<input className={input} required name="discountAmount" inputMode="decimal"/></label><label className={`${label} mt-2 block`}>Mandatory reason<input className={input} required minLength={3} name="discountReason"/></label><button className="mt-3 rounded-lg bg-amber-700 px-4 py-2 font-bold text-white">Apply discount</button></form>
 <form action={reviewPayoutAction} className="rounded-xl border p-4"><input type="hidden" name="bookingDocumentId" value={b.id}/><h3 className="font-black">Review Vendor Payout</h3><label className={`${label} mt-3 block`}>Approved payout (Rs)<input className={input} required name="vendorPayout" inputMode="decimal" defaultValue={b.internalFinancials.vendorPayoutMinor!==undefined?b.internalFinancials.vendorPayoutMinor/100:""}/></label><label className={`${label} mt-2 block`}>Internal payout notes<input className={input} name="payoutNotes" defaultValue={b.internalFinancials.payoutNotes}/></label><button className="mt-3 rounded-lg bg-green-700 px-4 py-2 font-bold text-white">Approve payout review</button></form>
 <form action={overridePaymentAction} className="rounded-xl border border-purple-200 bg-purple-50 p-4"><input type="hidden" name="bookingDocumentId" value={b.id}/><h3 className="font-black text-purple-900">Dispatch Before Payment</h3><p className="mt-1 text-xs">Does not bypass vendor payout review.</p><label className={`${label} mt-3 block`}>Mandatory exception reason<input className={input} required minLength={8} name="overrideReason"/></label><button className="mt-3 rounded-lg bg-purple-800 px-4 py-2 font-bold text-white">Approve override</button></form>
 <form action={cancelBookingAction} className="rounded-xl border border-red-200 p-4"><input type="hidden" name="bookingDocumentId" value={b.id}/><h3 className="font-black text-red-800">Stop Processing</h3><select className={input} name="cancellationType"><option value="not_proceeding">Not proceeding</option><option value="cancelled">Cancelled</option></select><label className={`${label} mt-2 block`}>Reason<input className={input} required name="cancellationReason"/></label><button className="mt-3 rounded-lg bg-red-700 px-4 py-2 font-bold text-white">Confirm stop</button></form>
 <form action={updateResponsibilitiesAction} className="lg:col-span-2 rounded-xl border p-4"><input type="hidden" name="bookingDocumentId" value={b.id}/><OperationalResponsibilities service={b.serviceType} initial={b.responsibilities as never}/><button className="mt-3 rounded-lg bg-[#0F2B46] px-4 py-2 font-bold text-white">Save Operational Responsibilities</button><p className="mt-2 text-xs text-slate-500">Does not change customer sale, payments, readiness or vendor payout.</p></form>
 </>}

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 if(!(await hasAdminSession()))redirect("/admin/pricing-calculator");const q=await searchParams;const[all,vehicles,opened]=await Promise.all([listOperationalBookings(),listDispatchVehicles(),q.open?getOperationalBooking(q.open):Promise.resolve(null)]);
 const filtered=all.filter(b=>(!q.tab||q.tab==="all"||(q.tab==="advance_recorded"?b.customerFinancials.paymentStatus==="sufficient":b.readinessStatus===q.tab))&&(!q.source||b.source.type===q.source)&&(!q.zone||b.zoneId===q.zone)&&(!q.date||b.itinerary.travelDate===q.date)&&(!q.search||`${b.bookingId} ${b.customer.name} ${b.customer.phone}`.toLowerCase().includes(q.search.toLowerCase())));
 const rows=opened&&!filtered.some(b=>b.id===opened.id)?[opened,...filtered]:filtered;
 const[events,offerPanel,assignmentPanel]=await Promise.all([q.open?listOperationalEvents(q.open):Promise.resolve([]),q.matches?getDispatchOfferPanel(q.matches):Promise.resolve(null),q.matches?getAssignmentPanel(q.matches):Promise.resolve(null)]);const matches=offerPanel?.matches??null;
 const assignmentDrivers=assignmentPanel?.availableOffers.filter((offer,index,all)=>all.findIndex(item=>item.driverId===offer.driverId)===index).map(offer=>{const driver=assignmentPanel.drivers.find(item=>item.id===offer.driverId),vendor=assignmentPanel.vendors.find(item=>item.id===offer.vendorId);return driver&&vendor?{id:driver.id,name:driver.name,vendorId:vendor.id,vendorName:vendor.name,priority:driver.priority,phone:driver.mobileNumber,whatsapp:driver.whatsappNumber,responseAt:offer.responseAt,offerId:offer.id,vehicles:assignmentPanel.matches.eligible.filter(candidate=>candidate.driver.id===driver.id).map(candidate=>{const vehicle=assignmentPanel.vehicles.find(item=>item.id===candidate.vehicle.id)!;return{id:vehicle.id,label:candidate.vehicle.label,registrationNumber:vehicle.registrationNumber,documentationState:vehicle.documentation.overallState,reasons:candidate.reasons}})}:null}).filter((item):item is NonNullable<typeof item>=>!!item)??[];
 return <main className="min-h-screen bg-slate-100 p-4 md:p-8"><div className="mx-auto max-w-7xl"><DispatchAdminNav current="dispatch"/><header className="mb-6"><p className="text-sm font-bold uppercase tracking-widest text-[#5BAE4A]">RentKA operations</p><h1 className="text-3xl font-black text-[#0F2B46]">Dispatch intake queue</h1><p className="text-slate-600">D3 finds and ranks operational resources. RentKA decides; no contact or assignment occurs.</p></header>{q.error&&<p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-red-800">{q.error}</p>}{q.message&&<p className="mb-4 rounded-lg bg-green-50 p-3 text-green-800">{q.message}</p>}
 <div className="mb-6 grid gap-5 lg:grid-cols-2"><details className="rounded-2xl bg-white p-5"><summary className="cursor-pointer text-xl font-black">+ Create Manual Booking</summary><ManualBookingForm action={createManualBookingAction} vehicles={vehicles}/></details><details className="rounded-2xl bg-white p-5"><summary className="cursor-pointer text-xl font-black">Import Existing Booking</summary><form action={importBookingAction} className="mt-4 grid gap-3"><label className={label}>Source<select className={input} name="sourceType">{OPERATIONAL_SOURCE_TYPES.filter(x=>x!=="manual").map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label className={label}>Source document ID<input className={input} required name="sourceDocumentId"/></label><button className="rounded-lg bg-[#0F2B46] px-5 py-3 font-bold text-white">Import into queue</button></form></details></div>
 <nav className="mb-3 flex flex-wrap gap-2">{tabs.map(t=><Link key={t} href={`/admin/dispatch?tab=${t}`} className={`rounded-full px-3 py-2 text-xs font-bold ${q.tab===t||(!q.tab&&t==="all")?"bg-[#0F2B46] text-white":"bg-white"}`}>{t.replaceAll("_"," ")}</Link>)}</nav><form className="mb-5 grid gap-2 rounded-xl bg-white p-3 sm:grid-cols-5"><input className={input} name="search" placeholder="ID, customer or phone" defaultValue={q.search}/><select className={input} name="source" defaultValue={q.source??""}><option value="">All sources</option>{OPERATIONAL_SOURCE_TYPES.map(x=><option key={x}>{x}</option>)}</select><select className={input} name="zone" defaultValue={q.zone??""}><option value="">All zones</option>{Object.entries(NORMAL_RENTAL_ZONES).map(([id,z])=><option key={id} value={id}>{z.label}</option>)}</select><input className={input} name="date" placeholder="YYYY-MM-DD" defaultValue={q.date}/><button className="rounded-lg bg-slate-800 px-4 py-2 text-white">Filter</button></form>
 <section className="grid gap-4">{rows.map(b=><article key={b.id} className="rounded-2xl bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-xl font-black">{b.bookingId}</h2><span className={`rounded-full px-2 py-1 text-xs font-bold ${badge(b.readinessStatus)}`}>{b.readinessStatus.replaceAll("_"," ")}</span>{b.paymentOverride?.approved&&<span className="rounded-full bg-purple-100 px-2 py-1 text-xs font-bold text-purple-800">Payment override</span>}</div><p className="text-sm">{b.source.type.replaceAll("_"," ")} · {NORMAL_RENTAL_ZONES[b.zoneId].label} · {b.serviceType}</p></div><Link href={`/admin/dispatch?open=${b.id}`} className="h-fit rounded-lg border px-4 py-2 text-sm font-bold">Open / Review</Link></div><div className="mt-4 grid gap-3 text-sm md:grid-cols-3"><div><p className="text-slate-500">Customer</p><b>{b.customer.name}</b><p>{b.customer.phone}</p></div><div><p className="text-slate-500">Trip</p><b>{formatDispatchAdminDate(b.itinerary.travelDate)} · {b.itinerary.pickupTime}</b><p>{b.itinerary.pickup} → {b.itinerary.destinationOrUsage||"Usage to confirm"}</p></div><div><p className="text-slate-500">Requested vehicle</p><b>{b.requestedVehicle.categoryOrModel}</b>{b.requestedVehicle.passengers&&<p>{b.requestedVehicle.passengers} passengers</p>}</div></div><Financials b={b}/>
 {q.open===b.id&&<div className="mt-5 grid gap-4 border-t pt-5 lg:grid-cols-2"><div className="lg:col-span-2 rounded-xl border p-4"><h3 className="font-black">Smart Matching</h3>{b.readinessStatus==="ready_for_dispatch"&&b.lifecycle==="active"?<Link href={`/admin/dispatch?open=${b.id}&matches=${b.id}`} className="mt-2 inline-block rounded-lg bg-[#0F2B46] px-4 py-2 font-bold text-white">Find Matches</Link>:<><button disabled className="mt-2 rounded-lg bg-slate-300 px-4 py-2 font-bold text-slate-600">Find Matches</button><p className="mt-2 text-sm text-amber-800">Unavailable: {b.lifecycle!=="active"?"Cancelled / Not Proceeding":b.readinessStatus.replaceAll("_"," ")}</p></>}</div>{matches&&q.matches===b.id&&<MatchPanel bookingDocumentId={b.id} projection={matches} offerProjections={offerPanel?.projections} offers={offerPanel?.offers}/>} {assignmentPanel&&q.matches===b.id&&<AssignmentPanel bookingDocumentId={b.id} bookingId={b.bookingId} payoutMinor={b.internalFinancials.vendorPayoutMinor??0} current={b.assignment} drivers={assignmentDrivers}/>}<D2Forms b={b}/><details className="lg:col-span-2 rounded-xl border p-4"><summary className="cursor-pointer font-black">Audit history ({events.length})</summary><div className="mt-3 space-y-2">{events.map(e=><div key={String(e.id)} className="rounded-lg bg-slate-50 p-2 text-sm"><b>{String(e.type).replaceAll("_"," ")}</b> · {String(e.timestamp)}<pre className="text-xs">{JSON.stringify(e.metadata??{},null,2)}</pre></div>)}</div></details></div>}</article>)}{!rows.length&&<p className="rounded-xl border border-dashed bg-white p-8 text-center">No operational bookings match these filters.</p>}</section></div></main>;
}
