import { NextResponse } from "next/server";
import { stableRouteHash,toGoogleRoutesBody,transformGoogleRoute,validateAutomaticRouteRequest } from "../../../admin/pricing-calculator/_lib/automatic-route";
import type { AutomaticRouteResponse, GoogleRoutesResponse } from "../../../admin/pricing-calculator/_lib/automatic-route";
import { hasAdminSession } from "../../../admin/_lib/session";

export const runtime="nodejs";
const CACHE_TTL_MS=10*60*1000;
const cache=new Map<string,{expires:number,value:AutomaticRouteResponse}>();
const friendlyError=(status:number)=>status===429?"Routes API quota or rate limit was reached.":status===403?"Routes API request was denied. Check billing, API enablement, and key restrictions.":"Routes API request failed. Check that Routes API and billing are enabled.";

export async function POST(request:Request){if(!(await hasAdminSession()))return NextResponse.json({success:false,error:"Unauthorized"},{status:401});let payload:unknown;try{payload=await request.json()}catch{return NextResponse.json({success:false,error:"Invalid route request."},{status:400})}if(!validateAutomaticRouteRequest(payload))return NextResponse.json({success:false,error:"Invalid route locations. Resolve every enabled route location first."},{status:400});const apiKey=process.env.GOOGLE_MAPS_SERVER_API_KEY;if(!apiKey)return NextResponse.json({success:false,code:"MISSING_SERVER_KEY",error:"Automatic route calculation is unavailable until the server Maps key is configured."},{status:503});const hash=stableRouteHash(payload);const cached=cache.get(hash);if(cached&&cached.expires>Date.now())return NextResponse.json({success:true,cached:true,route:cached.value});try{const googleResponse=await fetch("https://routes.googleapis.com/directions/v2:computeRoutes",{method:"POST",headers:{"Content-Type":"application/json","X-Goog-Api-Key":apiKey,"X-Goog-FieldMask":"routes.distanceMeters,routes.duration,routes.staticDuration,routes.legs.distanceMeters,routes.legs.duration,routes.legs.staticDuration,routes.legs.startLocation,routes.legs.endLocation"},body:JSON.stringify(toGoogleRoutesBody(payload)),cache:"no-store"});if(!googleResponse.ok)return NextResponse.json({success:false,error:friendlyError(googleResponse.status)},{status:googleResponse.status===429?429:502});const data=await googleResponse.json() as GoogleRoutesResponse;const route=transformGoogleRoute(payload,data);cache.set(hash,{expires:Date.now()+CACHE_TTL_MS,value:route});return NextResponse.json({success:true,cached:false,route})}catch(error){const noRoute=error instanceof Error&&error.message==="NO_ROUTE";return NextResponse.json({success:false,error:noRoute?"No driving route was found for the selected locations.":"Routes API request failed. Check that Routes API and billing are enabled."},{status:502})}}
