"use client";

import { useActionState, useRef, useState } from "react";
import { Autocomplete, useJsApiLoader } from "@react-google-maps/api";
import { login, logout, type LoginState } from "../actions";
import { TA_PASSENGER_CAPACITY, TA_VEHICLE_CATEGORIES, type TaVehicleCategory } from "@/lib/ta-connections/types";

const field = "w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm focus:border-[#0F2B46] focus:outline-none focus:ring-2 focus:ring-[#0F2B46]/15";
const labels = { ECONOMY_SEDAN: ["Economy Sedan", "1–4 passengers", "Toyota Corolla / Honda City / Toyota Yaris or similar"], MPV: ["MPV", "1–6 passengers", "Honda BR-V / Changan Karvaan / Suzuki APV or similar"], SUV: ["SUV", "1–6 passengers", "Toyota Prado / Toyota Fortuner or similar"], HIACE: ["Hiace", "Up to 12 passengers", "Toyota Hiace or similar"] } as const;
type AirportOption = { id: string; code: string; name: string };
type Place = { placeId: string; address: string; latitude: number; longitude: number };
type Quote = { token: string; distanceKm: number; durationMinutes: number; band: string | number; grossFare: string; currency: string; vehicleCategory: TaVehicleCategory };
type Success = { bookingId: string; taReferenceNumber: string; airport: string; serviceType: string; route: string; travelDate: string; pickupTime: string; vehicleCategory: string; passengerCount: number; contractedFare: string; status: string };

export function PortalLogin() {
  const [state, action, pending] = useActionState<LoginState, FormData>(login, {});
  return <main className="flex min-h-screen items-center justify-center bg-slate-100 px-4"><section className="w-full max-w-sm rounded-2xl border bg-white p-7 shadow-sm"><p className="text-sm font-bold uppercase tracking-widest text-green-700">TA Connections</p><h1 className="mt-2 text-2xl font-bold text-[#0F2B46]">Airport Transportation Portal</h1><form action={action} className="mt-6 space-y-4"><label className="block text-sm font-medium">Corporate password<input className={`${field} mt-1`} name="password" type="password" autoComplete="current-password" required autoFocus /></label>{state.error && <p className="text-sm text-red-700" role="alert">{state.error}</p>}<button disabled={pending} className="w-full rounded-lg bg-[#0F2B46] py-2.5 font-semibold text-white disabled:opacity-50">{pending ? "Checking…" : "Access portal"}</button></form></section></main>;
}

export function BookingPortal({ airports }: { airports: AirportOption[] }) {
  const { isLoaded } = useJsApiLoader({ id: "ta-google-places", googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY || "", libraries: ["places"] });
  const auto = useRef<google.maps.places.Autocomplete | null>(null);
  const idempotencyKey = useRef("");
  const [serviceType, setServiceType] = useState<"airport_pickup" | "airport_drop">("airport_pickup"); const [airportId, setAirportId] = useState(""); const [vehicle, setVehicle] = useState<TaVehicleCategory>("ECONOMY_SEDAN"); const [address, setAddress] = useState(""); const [place, setPlace] = useState<Place>(); const [quote, setQuote] = useState<Quote>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState<Success>(); const [whatsappUrl, setWhatsappUrl] = useState("");
  const capacity = TA_PASSENGER_CAPACITY[vehicle];
  const locationLabel = serviceType === "airport_pickup" ? "Drop-off location" : "Pickup location";
  const today = new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Karachi" });
  const invalidate = () => { setQuote(undefined); idempotencyKey.current = ""; };
  const locationInput = <input className={field} value={address} autoComplete="off" placeholder="Search a location in Pakistan" onChange={(e) => { setAddress(e.target.value); setPlace(undefined); invalidate(); }} />;
  const selectedPlace = () => { const p = auto.current?.getPlace(), loc = p?.geometry?.location; if (!p?.place_id || !loc) { setError("Select a resolved Google location from the suggestions."); return; } const resolved = { placeId: p.place_id, address: p.formatted_address || p.name || address, latitude: loc.lat(), longitude: loc.lng() }; setAddress(resolved.address); setPlace(resolved); setQuote(undefined); setError(""); };
  const calculate = async () => { if (!airportId || !place) { setError("Select an airport and a resolved Google location."); return; } setBusy(true); setError(""); try { const res = await fetch("/api/partner/ta-connections/quote", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ airportId, serviceType, vehicleCategory: vehicle, location: place }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setQuote(data); } catch (e) { setError(e instanceof Error ? e.message : "Unable to calculate route."); } finally { setBusy(false); } };
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (busy) return; if (!quote) return setError("Calculate the route and contracted fare first."); const form = new FormData(event.currentTarget); const count = Number(form.get("passengerCount")); if (count > capacity) return setError(`Select a suitable vehicle category; ${labels[vehicle][0]} supports up to ${capacity} passengers.`); const pickup = new Date(`${form.get("travelDate")}T${form.get("pickupTime")}:00+05:00`); if (pickup.getTime() - Date.now() < 4 * 60 * 60 * 1000) return setError("Bookings must be submitted at least 4 hours before the scheduled pickup time."); setBusy(true); setError(""); if (!idempotencyKey.current) idempotencyKey.current = crypto.randomUUID(); const body = Object.fromEntries(form); Object.assign(body, { quoteToken: quote.token, passengerCount: count, idempotencyKey: idempotencyKey.current }); try { const res = await fetch("/api/partner/ta-connections/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setSuccess(data.booking); setWhatsappUrl(data.whatsappUrl); } catch (e) { setError(e instanceof Error ? e.message : "Unable to submit booking."); } finally { setBusy(false); } };
  if (success) return <main className="min-h-screen bg-slate-100 p-5"><section className="mx-auto max-w-2xl rounded-2xl bg-white p-7 shadow-sm"><p className="text-sm font-bold uppercase tracking-widest text-green-700">TA Connections</p><h1 className="mt-2 text-3xl font-bold text-[#0F2B46]">Booking Request Submitted</h1><dl className="mt-6 grid gap-3 text-sm md:grid-cols-2">{Object.entries(success).map(([key, value]) => <div key={key} className="rounded-lg bg-slate-50 p-3"><dt className="text-slate-500">{key.replaceAll(/([A-Z])/g, " $1")}</dt><dd className="font-semibold">{String(value)}</dd></div>)}</dl><p className="mt-6 rounded-lg bg-amber-50 p-4 text-sm text-amber-900">This is a transport request and is awaiting RentKA confirmation. It is not yet a confirmed vehicle assignment.</p><a className="mt-4 inline-block rounded-lg bg-green-700 px-4 py-2 text-sm font-semibold text-white" href={whatsappUrl} target="_blank" rel="noreferrer">Open full WhatsApp message</a></section></main>;
  return <main className="min-h-screen bg-slate-100"><header className="bg-[#0F2B46] text-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-widest text-green-300">TA Connections</p><h1 className="text-xl font-bold">Airport Transportation Booking</h1></div><form action={logout}><button className="rounded-md border border-white/30 px-3 py-1.5 text-sm">Logout</button></form></div></header><form onSubmit={submit} className="mx-auto max-w-4xl space-y-6 px-5 py-6"><section className="grid gap-4 rounded-xl bg-white p-5 shadow-sm md:grid-cols-2"><label className="text-sm">Service type<select className={field} value={serviceType} onChange={(e) => { setServiceType(e.target.value as typeof serviceType); invalidate(); }}><option value="airport_pickup">Airport Pickup</option><option value="airport_drop">Airport Drop</option></select></label><label className="text-sm">Airport<select className={field} value={airportId} onChange={(e) => { setAirportId(e.target.value); invalidate(); }} required><option value="">Select active airport</option>{airports.map((a) => <option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label className="text-sm md:col-span-2">{locationLabel}{isLoaded ? <Autocomplete onLoad={(instance) => { auto.current = instance; }} onPlaceChanged={selectedPlace} options={{ componentRestrictions: { country: "pk" }, fields: ["formatted_address", "name", "place_id", "geometry"] }}>{locationInput}</Autocomplete> : locationInput}{place && <span className="mt-1 block text-xs text-green-700">Resolved location selected</span>}</label></section>
    <section className="rounded-xl bg-white p-5 shadow-sm"><h2 className="font-bold">Vehicle category</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{TA_VEHICLE_CATEGORIES.map((category) => <label key={category} className={`cursor-pointer rounded-lg border p-3 ${vehicle === category ? "border-[#0F2B46] bg-blue-50" : "border-slate-200"}`}><input className="mr-2" type="radio" checked={vehicle === category} onChange={() => { setVehicle(category); invalidate(); }} /><strong>{labels[category][0]}</strong><span className="block pl-6 text-sm">{labels[category][1]}</span><span className="block pl-6 text-xs text-slate-500">{labels[category][2]}</span></label>)}</div><button type="button" disabled={busy} onClick={calculate} className="mt-4 rounded-lg bg-[#0F2B46] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Calculating…" : "Calculate route and fare"}</button>{quote && <div className="mt-4 grid gap-2 rounded-lg bg-green-50 p-4 text-sm md:grid-cols-4"><p><span className="block text-slate-500">Google distance</span><strong>{quote.distanceKm.toFixed(1)} km</strong></p><p><span className="block text-slate-500">Driving time</span><strong>{quote.durationMinutes} min</strong></p><p><span className="block text-slate-500">Contract band</span><strong>{quote.band === "50_PLUS" ? "50+ km" : `Up to ${quote.band} km`}</strong></p><p><span className="block text-slate-500">Contracted fare</span><strong>{quote.currency} {quote.grossFare}</strong></p></div>}</section>
    <section className="grid gap-4 rounded-xl bg-white p-5 shadow-sm md:grid-cols-2">{[["travelDate","Travel date","date"],["pickupTime","Pickup time","time"],["requesterName","Requesting TA employee name","text"],["requesterEmail","Requesting TA employee email","email"],["airline","Airline","text"],["flightNumber","Flight number","text"],["taReferenceNumber","TA reference number","text"],["passengerOrGroupName","Passenger / group name","text"],["passengerCount",`Passenger count (max ${capacity})`,"number"],["passengerContact","Passenger contact number","tel"]].map(([name,label,type]) => <label className="text-sm" key={name}>{label}<input className={field} name={name} type={type} min={name === "travelDate" ? today : name === "passengerCount" ? "1" : undefined} max={name === "passengerCount" ? String(capacity) : undefined} required /></label>)}<label className="text-sm md:col-span-2">Special instructions<textarea className={field} name="specialInstructions" rows={4} maxLength={2000} /></label></section>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy || !quote} className="w-full rounded-lg bg-green-700 py-3 font-semibold text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit booking request"}</button></form></main>;
}
