"use client";
import { useState } from "react";
import { SAFE_DISPATCH_CATEGORIES } from "@/lib/partner-applications/onboarding-core";
import type { DuplicateCandidates } from "@/lib/partner-applications/onboarding";

type Option={id:string;label:string};type Vehicle={registrationNumber:string;registrationNormalized:string;category:string;make:string;model:string};type ApplicantDriver={name:string;mobileNormalized:string};
export default function ApprovalForm({action,applicationId,applicationType,applicantName,applicationDrivers,drivingSetup,vehicles,duplicates,vendors,drivers,dispatchVehicles}:{action:(form:FormData)=>void;applicationId:string;applicationType:"driver"|"ownerDriver"|"vendor";applicantName:string;applicationDrivers:ApplicantDriver[];drivingSetup?:"self"|"vendor_driver";vehicles:Vehicle[];duplicates:DuplicateCandidates;vendors:Option[];drivers:Option[];dispatchVehicles:Option[]}){
 const[confirmed,setConfirmed]=useState(false),input="min-h-11 rounded-lg border px-3 py-2",effectiveDrivingSetup=drivingSetup??(applicationType==="ownerDriver"?"self":applicationType==="vendor"&&applicationDrivers.length?"vendor_driver":undefined);const ambiguous=duplicates.vendors.length>1||duplicates.drivers.length>1||Object.values(duplicates.vehicleMatches).some(ids=>ids.length>1);
 function confirm(event:React.FormEvent<HTMLFormElement>){const form=new FormData(event.currentTarget),classificationLabel=(event.currentTarget.elements.namedItem("supplyClassification") as HTMLSelectElement).selectedOptions[0]?.textContent||"Needs review",vendor=form.get("vendorId")||`New vendor for ${applicantName}`,driverLines=applicationType==="vendor"&&effectiveDrivingSetup!=="self"?applicationDrivers.map(d=>`${d.name}: ${form.get(`driverId:${d.mobileNormalized}`)||"new driver"}`):[String(form.get("driverId")||`New driver ${applicantName}`)],vehicleLines=vehicles.map(v=>`${v.registrationNumber}: ${form.get(`vehicleId:${v.registrationNormalized}`)||"new vehicle"}`);if(!window.confirm(`Approve Partner?\n\nDriving setup: ${classificationLabel}\nVendor: ${vendor}\nDrivers: ${driverLines.join(", ")||"None"}\nVehicles: ${vehicleLines.join(", ")||"None"}\n\nNormal Smart Matching rules will still apply.`)){event.preventDefault();return}setConfirmed(true)}
 const classifications=effectiveDrivingSetup==="self"?[["independent_owner_driver","Drives himself"],["unknown_needs_review","Driver setup needs review"]]:effectiveDrivingSetup==="vendor_driver"?[["vendor_managed","Uses own drivers"],["unknown_needs_review","Driver setup needs review"]]:[["unknown_needs_review","Driver setup needs review"]];
 return <form action={action} onSubmit={confirm} className="mt-5 rounded-xl border-2 border-green-200 bg-green-50 p-4"><input type="hidden" name="id" value={applicationId}/><input type="hidden" name="confirmed" value={confirmed?"yes":"yes"}/><p className="text-sm font-bold text-green-900">Approve & Add to Dispatch will activate linked/created resources. Documentation remains truthful and normal Smart Matching rules still apply.</p>{ambiguous&&<p className="mt-2 rounded-lg bg-amber-100 p-3 text-sm font-bold text-amber-900">Possible existing records — explicit selection is required where multiple matches appear.</p>}<div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-black sm:col-span-2">Driving setup<select className={`${input} mt-1 w-full`} name="supplyClassification" required defaultValue=""><option value="" disabled>Choose who will drive</option>{classifications.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><span className="mt-1 block font-normal text-slate-600">Admin confirmation controls activation and safe routing.</span></label>
 <label className="text-sm font-bold">Dispatch vendor<select className={`${input} mt-1 w-full`} name="vendorId" required={applicationType==="driver"||duplicates.vendors.length>1} defaultValue={duplicates.vendors.length===1?duplicates.vendors[0]:""}><option value="">{applicationType==="driver"?"Select existing vendor":"Create new vendor"}</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.label}{duplicates.vendors.includes(v.id)?" — possible match":""}</option>)}</select></label>
 {(applicationType!=="vendor"||effectiveDrivingSetup==="self")&&<label className="text-sm font-bold">Dispatch driver<select className={`${input} mt-1 w-full`} name="driverId" required={duplicates.drivers.length>1} defaultValue={duplicates.drivers.length===1?duplicates.drivers[0]:""}><option value="">Create new driver</option>{drivers.filter(d=>duplicates.drivers.includes(d.id)).map(d=><option key={d.id} value={d.id}>{d.label} — possible match</option>)}</select></label>}
 {applicationType==="vendor"&&effectiveDrivingSetup!=="self"&&applicationDrivers.map(driver=>{const matches=duplicates.driverMatches[driver.mobileNormalized]??[];return <label key={driver.mobileNormalized} className="text-sm font-bold">Driver: {driver.name}<select className={`${input} mt-1 w-full`} name={`driverId:${driver.mobileNormalized}`} required={matches.length>1} defaultValue={matches.length===1?matches[0]:""}><option value="">Create new driver</option>{drivers.filter(d=>matches.includes(d.id)).map(d=><option key={d.id} value={d.id}>{d.label} — possible match</option>)}</select></label>})}
 {vehicles.map(v=>{const matches=duplicates.vehicleMatches[v.registrationNormalized]??[];return <div key={v.registrationNormalized} className="rounded-lg border border-green-200 bg-white p-3 sm:col-span-2"><strong>{v.make} {v.model} — {v.registrationNumber}</strong><div className="mt-2 grid gap-2 sm:grid-cols-2"><label className="text-sm font-bold">Vehicle record<select className={`${input} mt-1 w-full`} name={`vehicleId:${v.registrationNormalized}`} required={matches.length>1} defaultValue={matches.length===1?matches[0]:""}><option value="">Create new vehicle</option>{dispatchVehicles.filter(x=>matches.includes(x.id)).map(x=><option key={x.id} value={x.id}>{x.label} — possible match</option>)}</select></label>{v.category==="Other"&&<label className="text-sm font-bold">Required Dispatch category mapping<select className={`${input} mt-1 w-full`} name={`vehicleCategory:${v.registrationNormalized}`} required defaultValue=""><option value="" disabled>Select safe category</option>{SAFE_DISPATCH_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label>}</div></div>})}
 </div><button className="mt-4 min-h-12 rounded-lg bg-green-700 px-5 font-black text-white">Confirm Approve & Add to Dispatch</button></form>;
}
