"use client";
import { useMemo,useState } from "react";
import type { DocumentReviewState,PartnerDocument,PartnerDocumentHistoryEntry,PartnerDocumentOwnerType } from "@/lib/partner-applications/types";

type Row={document:PartnerDocument;ownerType:PartnerDocumentOwnerType;ownerIndex?:number;ownerLabel:string};
type ReviewValue={state:DocumentReviewState;note:string};
const states:DocumentReviewState[]=["pending","verified","rejected","needs_replacement"];
const input="min-h-11 rounded-lg border px-3 py-2";

export default function DocumentReviewPanel({applicationId,rows,history,reviewAction,saveAllAction,replaceAction}:{applicationId:string;rows:Row[];history:PartnerDocumentHistoryEntry[];reviewAction:(form:FormData)=>void;saveAllAction:(form:FormData)=>void;replaceAction:(form:FormData)=>void}){
 const initial=useMemo(()=>Object.fromEntries(rows.map(({document})=>[document.id,{state:document.reviewState,note:document.reviewNote??""}])) as Record<string,ReviewValue>,[rows]);
 const[values,setValues]=useState(initial),formId=`document-reviews-${applicationId}`;
 const dirty=rows.filter(({document})=>{const value=values[document.id];return value.state!==document.reviewState||value.note!==(document.reviewNote??"")}).map(({document})=>document.id);
 return <article className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-black">Protected documents</h3><p className="text-xs text-slate-500">Extraction suggestions are unverified and separate from review.</p></div><form id={formId} action={saveAllAction}><input type="hidden" name="id" value={applicationId}/>{dirty.map(id=><input key={id} type="hidden" name="changedDocumentId" value={id}/>)}<button disabled={!dirty.length} className="min-h-11 rounded-lg bg-[#0F2B46] px-4 font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Save All Reviews</button></form></div>
 {rows.map(({document,ownerType,ownerIndex,ownerLabel})=>{const value=values[document.id],versions=history.filter(item=>item.kind===document.kind&&item.ownerType===ownerType&&item.ownerIndex===ownerIndex);return <section key={document.id} className="mt-3 rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong>{document.kind.replaceAll("_"," ")}</strong><p className="text-xs">{ownerLabel} · {document.originalName} · {document.reviewState} · extraction {document.extraction?.status||"not attempted"}</p></div><div className="flex flex-wrap gap-2"><a target="_blank" rel="noreferrer" className="rounded-lg border px-3 py-2 text-sm font-bold" href={`/api/admin/partner-applications/documents?application=${applicationId}&document=${document.id}`}>View securely</a></div></div>
 <div className="mt-3 grid gap-3 lg:grid-cols-2"><div className="flex flex-wrap gap-2"><select form={formId} className={input} name={`state:${document.id}`} value={value.state} onChange={event=>setValues(current=>({...current,[document.id]:{...current[document.id],state:event.target.value as DocumentReviewState}}))}>{states.map(state=><option key={state}>{state}</option>)}</select><input form={formId} className={`${input} min-w-56 flex-1`} name={`note:${document.id}`} value={value.note} onChange={event=>setValues(current=>({...current,[document.id]:{...current[document.id],note:event.target.value}}))} placeholder="Review note"/><button form={formId} formAction={reviewAction} name="documentId" value={document.id} className="rounded-lg bg-slate-800 px-3 text-white">Save Review</button>{dirty.includes(document.id)&&<span className="self-center text-xs font-bold text-amber-700">Unsaved</span>}</div>
 <form action={replaceAction} className="rounded-lg bg-slate-50 p-3"><input type="hidden" name="id" value={applicationId}/><input type="hidden" name="documentId" value={document.id}/><input type="hidden" name="ownerType" value={ownerType}/><input type="hidden" name="ownerIndex" value={ownerIndex??""}/><label className="block text-xs font-bold">Replace / Upload<input required name="file" type="file" accept="image/jpeg,image/png,application/pdf" className="mt-1 block w-full text-sm"/></label><input name="reason" className={`${input} mt-2 w-full`} placeholder="Reason for replacement (optional)"/><button className="mt-2 min-h-10 rounded-lg border bg-white px-3 text-sm font-bold">Replace Document</button></form></div>
 <div className="mt-3 border-t pt-3"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Document history</p><p className="mt-1 text-xs"><strong>Current</strong> — uploaded {document.uploadedAt}</p>{[...versions].reverse().map(version=><p key={version.id} className="mt-1 text-xs"><a target="_blank" rel="noreferrer" className="font-bold underline" href={`/api/admin/partner-applications/documents?application=${applicationId}&document=${version.id}`}>Previous — view securely</a> · replaced {version.replacedAt}{version.replacementReason?` · ${version.replacementReason}`:""}</p>)}</div></section>})}
 {!rows.length&&<p className="mt-2 text-sm text-slate-500">No documents uploaded.</p>}</article>;
}
