"use client";
import { useState } from "react";
import { CATEGORIES, MARKETING_STATUSES, SOURCES, type Contact, type ContactInput, type FileAudienceView, type Source } from "@/lib/whatsapp-campaigns/types";
import { contactsForAudience } from "@/lib/whatsapp-campaigns/core";
import { addContact, setContactReview } from "../actions";
import CsvImport from "./CsvImport";
import FileAudiences from "../FileAudiences";
const control = "rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm";
const button = "rounded-lg bg-[#0F2B46] px-4 py-2 text-sm font-bold text-white disabled:opacity-50";
const blank: ContactInput = { displayName: "", phoneOriginal: "", source: "manual", sourceReferenceId: "", category: "unknown", notes: "" };
export default function Contacts({ contacts, audiences, initialAudienceId = "" }: { contacts: Contact[]; audiences: FileAudienceView[]; initialAudienceId?: string }) {
  const [manual, setManual] = useState(blank), [pending, setPending] = useState(false), [message, setMessage] = useState("");
  const [filters, setFilters] = useState({ search: "", source: "", category: "", status: "", optOut: "", sent: "", audience: initialAudienceId });
  const [page, setPage] = useState(0);
  const selectedAudience = audiences.find(a => a.audienceId === filters.audience);
  const fileContacts = filters.audience ? contactsForAudience(contacts, selectedAudience?.members ?? []) : contacts;
  const filtered = fileContacts.filter(c => (!filters.search || `${c.displayName} ${c.phoneE164} ${c.phoneOriginal}`.toLowerCase().includes(filters.search.toLowerCase())) && (!filters.source || (c.sources ?? [c.source]).includes(filters.source as Source)) && (!filters.category || c.category === filters.category) && (!filters.status || c.marketingStatus === filters.status) && (!filters.optOut || c.optOut === (filters.optOut === "yes")) && (!filters.sent || !!c.lastSentAt === (filters.sent === "yes")));
  const names = new Map<string, string[]>();
  for (const audience of audiences) for (const member of audience.members) names.set(member.contactId, [...(names.get(member.contactId) ?? []), audience.audienceName]);
  async function run(work: () => Promise<void>) { setPending(true); setMessage(""); try { await work(); } catch { setMessage("Action could not complete. Check your input and admin session. Opt-outs cannot be reversed here."); } finally { setPending(false); } }
  function filter(key: keyof typeof filters, value: string) { setFilters({ ...filters, [key]: value }); setPage(0); }
  return <><h1 className="text-3xl font-black text-[#0F2B46]">File-based campaign contacts</h1><p className="mt-2 text-slate-600">Contacts uploaded through this campaign importer are considered eligible after Confirm Import. Opt-outs, invalid numbers and excluded contacts remain suppressed. Original contact source and file audience membership are kept separately.</p><p role="status" className="my-4 font-semibold">{message}</p>
    <div className="grid gap-5 lg:grid-cols-2"><CsvImport /><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Add one campaign contact</h2><p className="mt-2 text-sm">New manual contacts are eligible by default. Existing suppression states are preserved.</p><form className="mt-4 grid gap-3" onSubmit={e => { e.preventDefault(); void run(async () => { const result = await addContact(manual); setMessage(result.created ? "Contact added as eligible." : "Existing contact preserved; missing metadata merged."); setManual(blank); }); }}>
      <label>Name<input className={`${control} block w-full`} value={manual.displayName} maxLength={160} onChange={e => setManual({ ...manual, displayName: e.target.value })} /></label><label>Phone<input className={`${control} block w-full`} required maxLength={80} placeholder="03020589999 or +447911123456" value={manual.phoneOriginal} onChange={e => setManual({ ...manual, phoneOriginal: e.target.value })} /></label>
      <label>Source<select className={`${control} block w-full`} value={manual.source} onChange={e => setManual({ ...manual, source: e.target.value as Source })}>{SOURCES.map(v => <option key={v}>{v}</option>)}</select></label><label>Category<select className={`${control} block w-full`} value={manual.category} onChange={e => setManual({ ...manual, category: e.target.value as ContactInput["category"] })}>{CATEGORIES.map(v => <option key={v}>{v}</option>)}</select></label><label>Notes<textarea className={`${control} block w-full`} maxLength={1000} value={manual.notes} onChange={e => setManual({ ...manual, notes: e.target.value })} /></label><button className={button} disabled={pending}>Save contact</button>
    </form></section></div>
    <FileAudiences audiences={audiences} contacts={contacts} />
    <section className="my-6 rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-3 text-xl font-bold">{selectedAudience ? `${selectedAudience.audienceName} contacts` : "All campaign contacts"}</h2><div className="flex flex-wrap gap-2"><select aria-label="Import / File" className={control} value={filters.audience} onChange={e => filter("audience", e.target.value)}><option value="">All files</option>{audiences.map(a => <option key={a.audienceId} value={a.audienceId}>{a.audienceName}</option>)}</select><input aria-label="Search name or phone" className={control} placeholder="Search name or phone" value={filters.search} onChange={e => filter("search", e.target.value)} />{([["source", SOURCES], ["category", CATEGORIES], ["status", MARKETING_STATUSES]] as const).map(([key, options]) => <select key={key} aria-label={key} className={control} value={filters[key]} onChange={e => filter(key, e.target.value)}><option value="">All {key}</option>{options.map(v => <option key={v}>{v}</option>)}</select>)}<select aria-label="Opt-out filter" className={control} value={filters.optOut} onChange={e => filter("optOut", e.target.value)}><option value="">All opt-out states</option><option value="yes">Opted out</option><option value="no">Not opted out</option></select><select aria-label="Send history filter" className={control} value={filters.sent} onChange={e => filter("sent", e.target.value)}><option value="">All send histories</option><option value="no">Never sent</option><option value="yes">Previously sent</option></select></div>
    <p className="my-4 text-sm">{filtered.length} matching contacts. File eligibility is shown in Import History; global contact status may predate a file approval.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Name", "Phone", "Source", "Import / File", "Category", "Global status", "Opt-out", "Last sent", "Created / imported"].map(v => <th className="p-2" key={v}>{v}</th>)}</tr></thead><tbody>{filtered.slice(page * 50, page * 50 + 50).map(c => <tr key={c.id} className="border-t"><td className="p-2">{c.displayName || "—"}</td><td className="p-2 whitespace-nowrap">{c.phoneE164}</td><td className="p-2">{(c.sources ?? [c.source]).join(", ")}</td><td className="p-2">{names.get(c.id)?.join(", ") || "No file association"}</td><td className="p-2">{c.category}</td><td className="p-2"><span className="block">{c.marketingStatus}</span><select aria-label={`Update ${c.displayName || c.phoneE164}`} className={control} disabled={pending || c.optOut || c.marketingStatus === "opted_out"} value="" onChange={e => { const status = e.target.value as "eligible" | "excluded" | "unreviewed" | "opted_out"; if (status) void run(async () => { await setContactReview(c.id, status); setMessage("Status saved."); }); }}><option value="">Update…</option><option value="eligible">Mark eligible</option><option value="excluded">Exclude</option><option value="unreviewed">Needs review</option><option value="opted_out">Record opt-out</option></select></td><td className="p-2">{c.optOut ? "Yes" : "No"}</td><td className="p-2">{c.lastSentAt?.slice(0, 10) || "Never"}</td><td className="p-2">{c.createdAt?.slice(0, 10)}<br />{c.importedAt?.slice(0, 10)}</td></tr>)}</tbody></table>{!filtered.length && <p className="p-6 text-center text-slate-500">No contacts match these filters.</p>}</div><div className="mt-4 flex items-center gap-3"><button className={control} disabled={!page} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page + 1}</span><button className={control} disabled={(page + 1) * 50 >= filtered.length} onClick={() => setPage(page + 1)}>Next</button></div></section>
  </>;
}