import "server-only";
import { FieldValue,Timestamp } from "firebase-admin/firestore";
import { getAdminDb } from "../firebaseAdmin";
import type { MetaStatusEvent } from "./meta-whatsapp-webhook";
import { reconcileWhatsAppDeliveryStatus } from "./whatsapp-delivery-reconciliation";

const EVENTS="metaWhatsAppWebhookEvents",MESSAGES="metaWhatsAppMessages";
export type MetaWebhookPersistResult={received:number;created:number;duplicates:number};
export async function persistMetaWhatsAppStatusEvents(events:MetaStatusEvent[]):Promise<MetaWebhookPersistResult>{const db=getAdminDb();let created=0,duplicates=0;for(const event of events){const eventRef=db.collection(EVENTS).doc(event.eventId),messageRef=db.collection(MESSAGES).doc(event.messageId);await db.runTransaction(async tx=>{const[eventSnap,messageSnap]=await Promise.all([tx.get(eventRef),tx.get(messageRef)]);if(eventSnap.exists){duplicates++;return}const occurredAt=Timestamp.fromMillis(Number(event.timestamp)*1000),now=FieldValue.serverTimestamp(),minimal={metaMessageId:event.messageId,status:event.status,occurredAt,receivedAt:now,...(event.phoneNumberId?{phoneNumberId:event.phoneNumberId}:{}),...(event.wabaId?{wabaId:event.wabaId}:{}),...(event.recipientId?{recipientId:event.recipientId}:{}),...(event.errorCode?{errorCode:event.errorCode}:{}),...(event.errorTitle?{errorTitle:event.errorTitle}:{})};tx.create(eventRef,minimal);const previous=messageSnap.data(),previousMillis=previous?.statusTimestamp&&typeof previous.statusTimestamp.toMillis==="function"?previous.statusTimestamp.toMillis():0;if(!messageSnap.exists||occurredAt.toMillis()>=previousMillis)tx.set(messageRef,{metaMessageId:event.messageId,status:event.status,statusTimestamp:occurredAt,updatedAt:now,...(event.phoneNumberId?{phoneNumberId:event.phoneNumberId}:{}),...(event.wabaId?{wabaId:event.wabaId}:{})},{merge:true});created++});try{await reconcileWhatsAppDeliveryStatus({messageId:event.messageId,status:event.status,...(event.errorCode?{errorCode:event.errorCode}:{})})}catch{console.error("WhatsApp delivery reconciliation failed; durable webhook event was preserved.")}}return{received:events.length,created,duplicates}}
