import { createHash,createHmac,timingSafeEqual } from "node:crypto";

export const META_MESSAGE_STATUSES=["sent","delivered","read","failed"] as const;
export type MetaMessageStatus=typeof META_MESSAGE_STATUSES[number];
export type MetaStatusEvent={eventId:string;messageId:string;status:MetaMessageStatus;timestamp:string;recipientId?:string;phoneNumberId?:string;wabaId?:string;errorCode?:string;errorTitle?:string};

export function verifyMetaWebhookChallenge(input:{mode:string|null;token:string|null;challenge:string|null;expectedToken:string|undefined}){return!!input.expectedToken&&input.mode==="subscribe"&&input.token===input.expectedToken&&input.challenge!==null}
export function verifyMetaWebhookSignature(rawBody:string,signature:string|null,appSecret:string|undefined){if(!appSecret||!signature?.startsWith("sha256="))return false;const received=signature.slice(7);if(!/^[a-f0-9]{64}$/i.test(received))return false;const expected=createHmac("sha256",appSecret).update(rawBody,"utf8").digest("hex");return timingSafeEqual(Buffer.from(received,"hex"),Buffer.from(expected,"hex"))}
const text=(value:unknown)=>typeof value==="string"?value:"";
const status=(value:unknown):MetaMessageStatus|undefined=>META_MESSAGE_STATUSES.includes(value as MetaMessageStatus)?value as MetaMessageStatus:undefined;
export function parseMetaWhatsAppStatusEvents(payload:unknown):MetaStatusEvent[]{if(!payload||typeof payload!=="object")return[];const root=payload as Record<string,unknown>;if(root.object!=="whatsapp_business_account"||!Array.isArray(root.entry))return[];const events:MetaStatusEvent[]=[];for(const rawEntry of root.entry){if(!rawEntry||typeof rawEntry!=="object")continue;const entry=rawEntry as Record<string,unknown>,wabaId=text(entry.id);if(!Array.isArray(entry.changes))continue;for(const rawChange of entry.changes){if(!rawChange||typeof rawChange!=="object")continue;const change=rawChange as Record<string,unknown>;if(change.field!=="messages"||!change.value||typeof change.value!=="object")continue;const value=change.value as Record<string,unknown>,metadata=value.metadata&&typeof value.metadata==="object"?value.metadata as Record<string,unknown>:undefined,phoneNumberId=text(metadata?.phone_number_id);if(!Array.isArray(value.statuses))continue;for(const rawStatus of value.statuses){if(!rawStatus||typeof rawStatus!=="object")continue;const item=rawStatus as Record<string,unknown>,messageId=text(item.id),current=status(item.status),timestamp=text(item.timestamp);if(!messageId||!current||!/^\d{1,16}$/.test(timestamp))continue;const error=Array.isArray(item.errors)&&item.errors[0]&&typeof item.errors[0]==="object"?item.errors[0] as Record<string,unknown>:undefined,eventId=createHash("sha256").update(`${messageId}:${current}:${timestamp}`).digest("hex");events.push({eventId,messageId,status:current,timestamp,recipientId:text(item.recipient_id)||undefined,phoneNumberId:phoneNumberId||undefined,wabaId:wabaId||undefined,errorCode:error?.code!==undefined?String(error.code):undefined,errorTitle:text(error?.title)||undefined})}}}return[...new Map(events.map(event=>[event.eventId,event])).values()]}
