import type { DistanceKey, ResolvedPlace, TripType } from "./types";

export interface AutomaticRouteRequest { origin: ResolvedPlace; pickup: ResolvedPlace; stops: ResolvedPlace[]; finalDrop: ResolvedPlace; returnDestination?: ResolvedPlace; includeReturn: boolean; tripType: TripType; }
export interface GoogleRouteLeg { distanceMeters?: number; duration?: string; staticDuration?: string; }
export interface GoogleRoutesResponse { routes?: Array<{ distanceMeters?: number; duration?: string; staticDuration?: string; legs?: GoogleRouteLeg[] }>; }
export interface AutomaticRouteResponse { requestHash: string; distanceMeters: number; durationSeconds: number; legCount: number; distances: Record<Exclude<DistanceKey,"buffer">,number>; }

const validCoordinate=(value:number,min:number,max:number)=>Number.isFinite(value)&&value>=min&&value<=max;
const validPlace=(value:unknown):value is ResolvedPlace=>{if(!value||typeof value!=="object")return false;const place=value as Partial<ResolvedPlace>;return typeof place.placeId==="string"&&place.placeId.length>0&&place.placeId.length<=256&&typeof place.displayName==="string"&&place.displayName.length<=500&&typeof place.formattedAddress==="string"&&place.formattedAddress.length<=1000&&typeof place.lat==="number"&&typeof place.lng==="number"&&validCoordinate(place.lat,23,38.5)&&validCoordinate(place.lng,60,78.5)};
export function validateAutomaticRouteRequest(value:unknown):value is AutomaticRouteRequest{if(!value||typeof value!=="object")return false;const request=value as Partial<AutomaticRouteRequest>;return validPlace(request.origin)&&validPlace(request.pickup)&&Array.isArray(request.stops)&&request.stops.length<=20&&request.stops.every(validPlace)&&validPlace(request.finalDrop)&&typeof request.includeReturn==="boolean"&&(!request.includeReturn||validPlace(request.returnDestination))&&["Within city","Outstation","One-way customer drop","Round trip","Custom multi-stop trip"].includes(request.tripType??"")}
const coordinates=(place:ResolvedPlace)=>({location:{latLng:{latitude:place.lat,longitude:place.lng}}});
export function toGoogleRoutesBody(request:AutomaticRouteRequest){const intermediates=[request.pickup,...request.stops];if(request.includeReturn)intermediates.push(request.finalDrop);return{origin:coordinates(request.origin),destination:coordinates(request.includeReturn?request.returnDestination!:request.finalDrop),intermediates:intermediates.map(coordinates),travelMode:"DRIVE",routingPreference:"TRAFFIC_AWARE"}}
export function stableRouteHash(request:AutomaticRouteRequest){const compact={origin:[request.origin.placeId,request.origin.lat,request.origin.lng],pickup:[request.pickup.placeId,request.pickup.lat,request.pickup.lng],stops:request.stops.map((place)=>[place.placeId,place.lat,place.lng]),finalDrop:[request.finalDrop.placeId,request.finalDrop.lat,request.finalDrop.lng],returnDestination:request.includeReturn&&request.returnDestination?[request.returnDestination.placeId,request.returnDestination.lat,request.returnDestination.lng]:null,includeReturn:request.includeReturn,tripType:request.tripType};const text=JSON.stringify(compact);let hash=2166136261;for(let index=0;index<text.length;index++){hash^=text.charCodeAt(index);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(36)}
const seconds=(duration?:string)=>{const parsed=Number(duration?.replace(/s$/,""));return Number.isFinite(parsed)&&parsed>=0?parsed:0};
export function transformGoogleRoute(request:AutomaticRouteRequest,response:GoogleRoutesResponse):AutomaticRouteResponse{const route=response.routes?.[0];if(!route||!Array.isArray(route.legs)||route.legs.length===0)throw new Error("NO_ROUTE");const legs=route.legs;const distances={pickupOperational:0,customerTrip:0,outstation:0,driverReturn:0};const outstation=request.tripType!=="Within city";legs.forEach((leg,index)=>{const km=Math.max(0,Number(leg.distanceMeters)||0)/1000;if(index===0)distances.pickupOperational+=km;else if(request.includeReturn&&index===legs.length-1)distances.driverReturn+=km;else if(outstation&&index===legs.length-(request.includeReturn?2:1))distances.outstation+=km;else distances.customerTrip+=km});return{requestHash:stableRouteHash(request),distanceMeters:Math.max(0,Number(route.distanceMeters)||legs.reduce((sum,leg)=>sum+(Number(leg.distanceMeters)||0),0)),durationSeconds:seconds(route.duration)||legs.reduce((sum,leg)=>sum+seconds(leg.duration),0),legCount:legs.length,distances}}
