import type { CalculatorState, Expenses, PricingStrategy, StopType, TripPackage, TripStop, VehicleCategory, VehiclePreset } from "./types";
const uid=()=>Math.random().toString(36).slice(2,10);
const categoryDefaults:Record<VehicleCategory,{fuel:number;customerExtra:number}>={Hatchback:{fuel:16,customerExtra:500},Sedan:{fuel:10,customerExtra:500},SUV:{fuel:8,customerExtra:1000},Van:{fuel:7,customerExtra:800},"Coaster or bus":{fuel:5.5,customerExtra:1000}};
const vehicle=(name:string,category:VehicleCategory,vendorRent:number,customerReferenceRent:number,fuelAverage?:number):VehiclePreset=>({id:name.toLowerCase().replaceAll(" ","-"),name,category,includedHours:12,vendorRent,customerReferenceRent,fuelAverage:fuelAverage??categoryDefaults[category].fuel,vendorExtraHour:0,customerExtraHour:categoryDefaults[category].customerExtra,defaultDriverFood:0,defaultDriverAccommodation:0});
export const VEHICLES:VehiclePreset[]=[vehicle("Suzuki Alto","Hatchback",5500,7000),vehicle("Wagon R","Hatchback",6000,7500),vehicle("Honda City","Sedan",7500,9500),vehicle("Toyota Corolla","Sedan",7000,9000),vehicle("Honda Civic","Sedan",10000,12500),vehicle("Honda BR-V","SUV",11000,14000,8),vehicle("Fortuner","SUV",22000,28000,7),vehicle("Prado","SUV",26000,33000,6.5),vehicle("Hiace","Van",15000,19000,7),vehicle("Coaster","Coaster or bus",22000,28000,5.5)];
export const ORIGINS=["RentKA Office – Sohan","Vendor G-10","Vendor Rawalpindi","Vendor Bahria","Vendor Bhara Kahu"].map((name,index)=>({id:`origin-${index}`,name}));
export const STOP_TYPES:StopType[]=["Sightseeing","Museum","Mosque","Restaurant","Tea stop","Park","Hotel","Airport","Meeting","Custom"];
export const WAITING_DEFAULTS:Record<StopType,number>={Sightseeing:45,Museum:60,Mosque:40,Restaurant:60,"Tea stop":25,Park:45,Hotel:15,Airport:45,Meeting:60,Custom:30};
const inferType=(name:string):StopType=>STOP_TYPES.find((type)=>name.toLowerCase().includes(type.toLowerCase()))??(name.toLowerCase().includes("monument")?"Sightseeing":"Custom");
export function newStop(name=""):TripStop{const type=inferType(name);return{id:uid(),name,type,waitingMinutes:WAITING_DEFAULTS[type],notes:"",enabled:true}}
export const createExpenses=():Expenses=>({toll:400,parking:0,driverFood:0,driverAccommodation:0,outstationSurcharge:0,miscellaneous:0,operationalContingency:0,discount:0});
export const createPricing=():PricingStrategy=>({mode:"target",targetProfitPercent:35,minimumProfitPercent:15,fixedProfit:3000,manualPrice:0,marketAdjustment:0});
const distances={pickupOperational:0,customerTrip:0,outstation:0,driverReturn:0,buffer:0};
const pkg=(name:string,names:string[]):TripPackage=>({id:uid(),name,enabled:true,stops:names.map(newStop),distances:{...distances},drivingMinutes:0,timeBufferMinutes:30,expenses:createExpenses(),pricing:createPricing(),routeStatus:"manual"});
export function createState():CalculatorState{const packages=[pkg("Package A",["Museum","Pakistan Monument","Faisal Mosque"]),pkg("Package B",["Museum","Pakistan Monument","Faisal Mosque","Lake View Park"]),pkg("Package C",["Museum","Pakistan Monument","Faisal Mosque","Lake View Park","Daman-e-Koh"])];return{trip:{date:"",pickupTime:"",tripType:"Custom multi-stop trip",vehiclePresetId:"toyota-corolla",vehicleName:"Toyota Corolla",originPresetId:"origin-0",origin:ORIGINS[0].name,pickup:"",finalDrop:"",driverReturn:ORIGINS[0].name,includeDriverReturn:true,notes:""},vehiclePresets:VEHICLES,originPresets:ORIGINS,packages,activePackageId:packages[0].id,fuelPrice:336.03,fuelBufferPercent:0}}
