import { nonNegative,summarizeManualRoute } from "./route";
import type { CalculatorState,DistanceKey,FuelLine,PricingResult,TripPackage,VehiclePreset } from "./types";
export const roundUp=(value:number,unit=500)=>Math.ceil(value/unit)*unit;
const fuelLabels:Record<DistanceKey,string>={pickupOperational:"Vendor/office to pickup fuel",customerTrip:"Customer trip fuel",outstation:"Outstation fuel",driverReturn:"Driver return fuel",buffer:"Buffer fuel"};
export function calculatePricing(state:CalculatorState,pkg:TripPackage,vehicle:VehiclePreset):PricingResult{
 const routePackage=state.trip.includeDriverReturn?pkg:{...pkg,distances:{...pkg.distances,driverReturn:0}};const route=summarizeManualRoute(routePackage,vehicle.includedHours);const average=nonNegative(vehicle.fuelAverage);const petrol=nonNegative(state.fuelPrice);const fuelBufferRate=nonNegative(state.fuelBufferPercent)/100;
 const fuelLines=(Object.entries(pkg.distances) as [DistanceKey,number][]).map(([key,value]):FuelLine=>{const kilometres=key==="driverReturn"&&!state.trip.includeDriverReturn?0:nonNegative(value);const litres=average>0?kilometres/average:0;return{key,label:fuelLabels[key],kilometres,litres,cost:litres*petrol}});
 const fuelLitres=fuelLines.reduce((sum,line)=>sum+line.litres,0);const rawFuelCost=fuelLines.reduce((sum,line)=>sum+line.cost,0);const fuelBufferAmount=rawFuelCost*fuelBufferRate;const fuelCost=rawFuelCost+fuelBufferAmount;
 const vehicleCost=nonNegative(vehicle.vendorRent);const vendorExtraHourCost=route.extraHours*nonNegative(vehicle.vendorExtraHour);const customerExtraHourReference=route.extraHours*nonNegative(vehicle.customerExtraHour);const e=pkg.expenses;
 const internalLines=[{label:"Vendor base vehicle rent",amount:vehicleCost},{label:"Vendor extra hours",amount:vendorExtraHourCost},{label:"Complete route fuel",amount:fuelCost},{label:"Toll",amount:e.toll},{label:"Parking",amount:e.parking},{label:"Driver food",amount:e.driverFood},{label:"Driver accommodation",amount:e.driverAccommodation},{label:"Outstation vehicle surcharge",amount:e.outstationSurcharge},{label:"Miscellaneous",amount:e.miscellaneous},{label:"Operational contingency",amount:e.operationalContingency}];
 const internalCost=internalLines.reduce((sum,line)=>sum+nonNegative(line.amount),0);const target=nonNegative(pkg.pricing.targetProfitPercent)/100;const minimum=nonNegative(pkg.pricing.minimumProfitPercent)/100;const minimumPrice=internalCost*(1+minimum);
 const unroundedSuggestedPrice=pkg.pricing.mode==="target"?internalCost*(1+target):pkg.pricing.mode==="fixed"?internalCost+nonNegative(pkg.pricing.fixedProfit):nonNegative(pkg.pricing.manualPrice);const baseSuggestedPrice=pkg.pricing.mode==="manual"?unroundedSuggestedPrice:roundUp(unroundedSuggestedPrice);const adjustmentImpact=Number.isFinite(Number(pkg.pricing.marketAdjustment))?Number(pkg.pricing.marketAdjustment):0;const suggestedPrice=Math.max(0,baseSuggestedPrice+adjustmentImpact);const finalPrice=Math.max(0,suggestedPrice-nonNegative(e.discount));
 const grossProfit=finalPrice-internalCost;const margin=finalPrice>0?grossProfit/finalPrice*100:0;const markup=internalCost>0?grossProfit/internalCost*100:0;const indicator=finalPrice<internalCost||markup<nonNegative(pkg.pricing.minimumProfitPercent)?"below-minimum":markup>=nonNegative(pkg.pricing.targetProfitPercent)?"excellent":"acceptable";
 const warnings:string[]=[];const outstation=pkg.distances.outstation>0||["Outstation","One-way customer drop","Round trip"].includes(state.trip.tripType);
 if(!state.trip.origin.trim())warnings.push("Vendor/office origin is missing.");if(!state.trip.pickup.trim())warnings.push("Customer pickup is missing.");if(!state.trip.finalDrop.trim())warnings.push("Final customer drop is missing.");if(outstation&&state.trip.includeDriverReturn&&!state.trip.driverReturn.trim())warnings.push("Return destination is required for this trip type.");if(route.totalKm===0)warnings.push("Total kilometres are zero.");if(average===0)warnings.push("Fuel average is zero.");if(petrol===0)warnings.push("Petrol price is zero.");if(outstation&&state.trip.includeDriverReturn&&nonNegative(pkg.distances.driverReturn)===0)warnings.push("Outstation trip has zero driver return kilometres.");if(route.extraHours>0)warnings.push(`Booking exceeds included duration by ${route.extraHours} billable hour(s).`);if(finalPrice<internalCost)warnings.push("Final price is below internal cost.");if(markup<nonNegative(pkg.pricing.minimumProfitPercent))warnings.push("Profit is below the minimum acceptable level.");if(outstation&&nonNegative(e.toll)===0)warnings.push("Toll is zero for a route where toll may apply.");if(route.totalKm>0&&fuelCost===0)warnings.push("Quotation would include fuel, but calculated fuel cost is zero.");
 return{route,fuelLines,fuelLitres,rawFuelCost,fuelBufferAmount,fuelCost,vehicleCost,vendorExtraHourCost,customerExtraHourReference,internalLines,internalCost,minimumPrice,unroundedSuggestedPrice,baseSuggestedPrice,suggestedPrice,finalPrice,adjustmentImpact,grossProfit,margin,markup,indicator,warnings};
}
export const money=(value:number)=>`Rs. ${Number.isFinite(value)?value.toLocaleString("en-PK",{minimumFractionDigits:0,maximumFractionDigits:2}):"0"}`;
export const duration=(minutes:number)=>`${Math.floor(minutes/60)}h ${Math.round(minutes%60)}m`;
export const percent=(value:number)=>`${(Number.isFinite(value)?value:0).toFixed(1)}%`;
