import type { Metadata } from "next";
import Link from "next/link";
import { hasAdminSession } from "../_lib/session";
import { listTaAirports, listTaBookings, listTaRateSets } from "@/lib/ta-connections/repository";
import { minorToPkr } from "@/lib/ta-connections/validation";
import { AirportForm, RateSetForm, TaAdminLogin } from "./_components/SettingsForms";
import { GooglePlacesProvider } from "../pricing-calculator/_components/GooglePlacesProvider";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "TA Connections Admin", description: "Private TA Connections contract administration.", robots: { index: false, follow: false, noarchive: true, nosnippet: true } };

export default async function TaConnectionsAdminPage() {
  if (!(await hasAdminSession())) return <TaAdminLogin />;
  const [airports, rateSets, bookings] = await Promise.all([listTaAirports(), listTaRateSets(), listTaBookings()]);
  const airportNames = new Map(airports.map((airport) => [airport.id, `${airport.code} — ${airport.name}`]));
  return <main className="min-h-screen bg-slate-100 text-slate-900">
    <header className="border-b border-slate-200 bg-[#0F2B46] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-widest text-green-300">RentKA Internal</p><h1 className="text-xl font-bold">TA Connections</h1></div><Link className="text-sm underline" href="/admin/pricing-calculator">Pricing calculator</Link></div></header>
    <div className="mx-auto max-w-7xl space-y-8 px-5 py-6">
      <nav className="flex flex-wrap gap-2 text-sm"><a className="rounded-full bg-[#0F2B46] px-3 py-1.5 text-white" href="#bookings">Bookings</a><a className="rounded-full bg-[#0F2B46] px-3 py-1.5 text-white" href="#airports">Airports</a><a className="rounded-full bg-[#0F2B46] px-3 py-1.5 text-white" href="#rates">Contract Rates</a>{["Invoices", "Monthly Statements"].map((label) => <span key={label} aria-disabled="true" className="rounded-full bg-slate-200 px-3 py-1.5 text-slate-500">{label} — later stage</span>)}</nav>
      <section id="bookings" className="space-y-4"><div><h2 className="text-xl font-bold">Bookings</h2><p className="text-sm text-slate-600">Latest submitted TA transport requests. Status operations belong to a later stage.</p></div>{bookings.length === 0 ? <p className="rounded-xl border border-dashed border-slate-300 p-5 text-sm text-slate-600">No TA booking requests yet.</p> : <div className="space-y-3">{bookings.map((booking) => <details key={booking.bookingId} className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer list-none"><div className="grid gap-2 text-sm md:grid-cols-4"><strong>{booking.bookingId}</strong><span>{booking.airportCode} · {booking.airline}</span><span>{booking.taReferenceNumber} · {booking.vehicleCategory}</span><span className="md:text-right">{booking.pricing.currency} {minorToPkr(booking.pricing.grossContractRateMinor)} · {booking.bookingStatus}</span></div><p className="mt-1 text-xs text-slate-500">{booking.createdAt} · {booking.pickupLocation.address} → {booking.dropoffLocation.address}</p></summary><dl className="mt-4 grid gap-3 border-t pt-4 text-sm md:grid-cols-2">{[["Requester", `${booking.createdBy?.displayName ?? "—"} / ${booking.requesterEmail ?? "—"}`],["Passenger", `${booking.passengerOrGroupName} / ${booking.passengerContact} / ${booking.passengerCount}`],["Flight", `${booking.airline} ${booking.flightNumber}`],["Travel", `${booking.travelDate} ${booking.pickupTime} PKT`],["Airport", `${booking.airportCode} — ${booking.airportName}`],["Service", booking.serviceType],["Pickup", booking.pickupLocation.address],["Drop-off", booking.dropoffLocation.address],["Route", `${booking.pricing.routeDistanceKm.toFixed(1)} km / ${booking.pricing.routeDurationMinutes} min / ${booking.pricing.contractDistanceBand}`],["Rate version", booking.pricing.rateVersion],["Commission / Net", `${booking.pricing.commissionPercent}% / ${booking.pricing.currency} ${minorToPkr(booking.pricing.netRentkaAmountMinor)}`],["Email status", `${booking.notificationStatus?.rentkaEmail ?? "—"} / requester ${booking.notificationStatus?.requesterEmail ?? "—"}`],["Instructions", booking.specialInstructions || "None"]].map(([label, value]) => <div key={label}><dt className="text-slate-500">{label}</dt><dd className="font-medium">{value}</dd></div>)}</dl></details>)}</div>}</section>
      <section id="airports" className="space-y-4"><div><h2 className="text-xl font-bold">Airports</h2><p className="text-sm text-slate-600">Search and select a verified Google airport, then enter its IATA code and review the populated details.</p></div><GooglePlacesProvider><AirportForm />{airports.map((airport) => <AirportForm key={airport.id} airport={airport} />)}</GooglePlacesProvider></section>
      <section id="rates" className="space-y-4"><div><h2 className="text-xl font-bold">Contract Rates</h2><p className="text-sm text-slate-600">Saving creates a new immutable version and supersedes the prior active contract for that airport.</p></div><RateSetForm airports={airports} hasActiveContract={rateSets.some((rate) => rate.active)} />
        <div className="space-y-3">{rateSets.length === 0 ? <p className="rounded-xl border border-dashed border-slate-300 p-5 text-sm text-slate-600">No contract versions configured. No commercial rates have been seeded.</p> : rateSets.map((rate) => <article key={rate.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><span className={`rounded-full px-2 py-1 text-xs font-bold ${rate.active ? "bg-green-100 text-green-800" : "bg-slate-200 text-slate-600"}`}>{rate.active ? "ACTIVE CONTRACT" : "HISTORICAL / SUPERSEDED"}</span><h3 className="mt-2 font-bold">{airportNames.get(rate.airportId) ?? rate.airportId}</h3></div><div className="text-right text-sm"><p>Effective {rate.effectiveFrom}{rate.effectiveTo ? ` to ${rate.effectiveTo.slice(0, 10)}` : ""}</p><p>{rate.commissionPercent}% commission · Version {rate.version}</p></div></div><details className="mt-3 text-sm"><summary className="cursor-pointer font-semibold">View stored rates and policies</summary><div className="mt-3 grid gap-3 md:grid-cols-2">{rate.vehicleRates.map((vehicle) => <div key={vehicle.vehicleCategory} className="rounded-lg bg-slate-50 p-3"><strong>{vehicle.vehicleCategory}</strong><p>{Object.entries(vehicle.bandRatesMinor).map(([band, amount]) => `${band} km: PKR ${minorToPkr(amount)}`).join(" · ")}</p><p>Over 50: PKR {minorToPkr(vehicle.additionalPerKmMinor)}/km</p></div>)}<div className="md:col-span-2"><p><strong>Waiting:</strong> {rate.policies.waitingPolicy}</p><p><strong>Cancellation:</strong> {rate.policies.cancellationPolicy}</p><p><strong>No-show:</strong> {rate.policies.noShowPolicy}</p></div></div></details></article>)}</div>
      </section>
    </div>
  </main>;
}
