import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { hasAdminSession } from "../_lib/session";
import DispatchAdminNav from "../_components/DispatchAdminNav";
import { Active, checkOptions, driverStatusOptions, input, label, priorityOptions, Select, textarea, Zones } from "../_components/DispatchFormFields";
import { getDispatchDriver,listDispatchDrivers } from "@/lib/dispatch/drivers";
import { listDispatchVendors } from "@/lib/dispatch/vendors";
import { listDispatchVehicles } from "@/lib/dispatch/vehicles";
import { NORMAL_RENTAL_ZONES } from "@/lib/normal-rental/zones";
import { DISPATCH_CREATION_DEFAULTS, operationalStatusPresentation } from "@/lib/dispatch/admin-presentation";
import { formatDispatchAdminDate } from "@/lib/dispatch/validation";
import { saveDriver } from "./actions";
import DriverVehicleEligibility from "./DriverVehicleEligibility";

export const metadata:Metadata={title:"Dispatch Drivers | RentKA Admin",robots:{index:false,follow:false,noarchive:true,nosnippet:true}};
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 if(!(await hasAdminSession()))redirect("/admin/pricing-calculator");const q=await searchParams;const[all,vendors,vehicles,editing]=await Promise.all([listDispatchDrivers(),listDispatchVendors(),listDispatchVehicles(),q.edit?getDispatchDriver(q.edit):null]);const vendorName=new Map(vendors.map(v=>[v.id,v.name])),rows=all.filter(d=>(!q.zone||d.zoneIds.includes(q.zone as never))&&(!q.vendor||d.vendorId===q.vendor)&&(!q.status||d.status===q.status)&&(!q.priority||d.priority===q.priority)),doc=editing?.documentation;
 return <main className="min-h-screen bg-slate-100 p-4 md:p-8"><div className="mx-auto max-w-7xl"><DispatchAdminNav current="drivers"/><header className="mb-6"><p className="text-sm font-bold uppercase tracking-widest text-[#5BAE4A]">Dispatch operations</p><h1 className="text-3xl font-black text-[#0F2B46]">Drivers</h1><p className="text-slate-600">Drivers belong to vendors and zones; optional eligibility limits pairing without permanent vehicle assignment.</p></header>{q.error&&<p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{q.error}</p>}{q.saved&&<p className="mb-4 rounded-lg bg-green-50 p-3 text-sm text-green-800">{q.saved}</p>}
 <section className="mb-6 rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black text-[#0F2B46]">{editing?"Edit driver":"Add driver"}</h2>{!vendors.length?<p className="mt-3 rounded-lg bg-amber-50 p-3">Create a dispatch vendor first.</p>:<form action={saveDriver} className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><input type="hidden" name="id" value={editing?.id??""}/><label className={label}>Driver name<input className={input} name="name" required defaultValue={editing?.name}/></label><label className={label}>Mobile number<input className={input} name="mobileNumber" required placeholder="03020589999" defaultValue={editing?.mobileNumber}/></label><label className={label}>WhatsApp number<input className={input} name="whatsappNumber" required placeholder="923020589999" defaultValue={editing?.whatsappNumber}/></label><DriverVehicleEligibility vendors={vendors} vehicles={vehicles} driver={editing} defaultVendorId={q.vendor}/><Zones selected={editing?.zoneIds}/><label className={label}>Priority<Select name="priority" value={editing?.priority??DISPATCH_CREATION_DEFAULTS.driver.priority} options={priorityOptions}/></label><label className={label}>Current status<Select name="status" value={editing?.status??DISPATCH_CREATION_DEFAULTS.driver.status} options={driverStatusOptions}/></label><div><Active value={editing?.active??DISPATCH_CREATION_DEFAULTS.driver.active}/></div><label className={`${label} lg:col-span-3`}>Internal notes<textarea className={textarea} name="notes" defaultValue={editing?.notes}/></label><details className="lg:col-span-3 rounded-xl border p-4"><summary className="cursor-pointer font-black text-[#0F2B46]">Optional documentation</summary><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3"><label className={label}>CNIC verification<Select name="cnicVerificationState" value={doc?.cnicVerificationState??"unknown"} options={checkOptions}/></label><label className={label}>Driving licence<Select name="licenceState" value={doc?.licenceState??"unknown"} options={checkOptions}/></label><label className={label}>Licence expiry (DD/MM/YYYY)<input className={input} type="text" inputMode="numeric" placeholder="25/08/2027" name="licenceExpiry" defaultValue={formatDispatchAdminDate(doc?.licenceExpiry)}/></label><label className={label}>Verification date (DD/MM/YYYY)<input className={input} type="text" inputMode="numeric" placeholder="25/08/2027" name="documentationVerifiedAt" defaultValue={formatDispatchAdminDate(doc?.verifiedAt)}/></label><label className={`${label} md:col-span-2`}>Documentation notes<textarea className={textarea} name="documentationNotes" defaultValue={doc?.notes}/></label></div></details><div className="lg:col-span-3 flex gap-2"><button className="rounded-lg bg-[#0F2B46] px-5 py-2.5 font-bold text-white">Save driver</button>{editing&&<Link href="/admin/drivers" className="rounded-lg border px-5 py-2.5">Cancel</Link>}</div></form>}</section>
 <form className="mb-4 grid gap-2 rounded-xl bg-white p-3 sm:grid-cols-3 lg:grid-cols-5"><select className={input} name="zone" defaultValue={q.zone??""}><option value="">All zones</option>{Object.entries(NORMAL_RENTAL_ZONES).map(([id,z])=><option key={id} value={id}>{z.label}</option>)}</select><select className={input} name="vendor" defaultValue={q.vendor??""}><option value="">All vendors</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select className={input} name="status" defaultValue={q.status??""}><option value="">All statuses</option>{driverStatusOptions.map(x=><option key={x}>{x}</option>)}</select><select className={input} name="priority" defaultValue={q.priority??""}><option value="">All priorities</option>{priorityOptions.map(x=><option key={x}>{x}</option>)}</select><button className="rounded-lg bg-slate-800 px-4 py-2 text-white">Filter</button></form>
 <section className="grid gap-4 md:grid-cols-2">{rows.map(d=>{const state=operationalStatusPresentation(d.active,d.status),eligibility=d.vehicleEligibility;return <article key={d.id} className={`rounded-2xl bg-white p-5 shadow-sm ${state.inactive?"opacity-75":""}`}><div className="flex justify-between gap-3"><div><h2 className="text-lg font-black text-[#0F2B46]">{d.name}</h2><p className="mt-1 text-sm font-semibold">{d.mobileNumber} · WhatsApp {d.whatsappNumber}</p></div><Link href={`/admin/drivers?edit=${d.id}`} className="h-fit rounded-lg border px-3 py-2 text-sm font-bold">Edit</Link></div><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-blue-50 px-2 py-1 font-bold">{state.label}</span><span className="rounded-full bg-violet-50 px-2 py-1">{d.priority}</span></div><p className="mt-3 text-sm">{vendorName.get(d.vendorId)||"Unknown vendor"}</p><p className="mt-1 text-xs text-slate-500">{d.zoneIds.map(z=>NORMAL_RENTAL_ZONES[z].label).join(" · ")}</p><p className="mt-2 text-xs font-semibold text-slate-600">Vehicle eligibility: {!eligibility||eligibility.mode==="any_vendor_vehicle"?"Any vendor vehicle":eligibility.mode==="specific_vehicles"?`${eligibility.vehicleIds?.length??0} selected vehicle(s)`:(eligibility.allowedModelsOrCategories??[]).map(x=>x.replace(/^(model|category):/,"")).join(", ")}</p></article>})}{!rows.length&&<p className="rounded-xl border border-dashed bg-white p-6 text-center text-slate-500">No drivers match these filters.</p>}</section></div></main>;
}
